INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q589612', N'myxoma', N'myxoid tumor of primitive connective tissue', N''),
( N'Q5898279', N'hyperphenylalaninemia', N'', N''),
( N'Q5898315', N'hypersensitivity reaction type III disease', N'human disease', N''),
( N'Q591256', N'MALT lymphoma', N'non-Hodgkin lymphoma that has material basis in mucosal tissue involved in antibody production', N''),
( N'Q5921848', N'Howel–Evans syndrome', N'Tylosis with oesophageal cancer', N''),
( N'Q5922406', N'inflammatory breast cancer', N'aggressive types of breast cancer', N''),
( N'Q592804', N'Ludwigs angina', N'human disease', N''),
( N'Q593277', N'Chemotherapy-induced acral erythema', N'chemotherapy-induced dermal side effects tassociated with the use of cytostatic agents', N''),
( N'Q593958', N'transient cerebral isolation', N'neurological dysfunction by transiently  ischemia', N''),
( N'Q594013', N'Prader–Willi syndrome', N'genetic disorder on chromosome 15, causing weak muscles, slow development, obesity, intellectual impairment, narrow forehead, small hands/feet, short height, light skin/hair, and infertility', N''),
( N'Q594841', N'idiopathy', N'disease with unknown pathogenesis or apparently spontaneous origin', N''),
( N'Q59484501', N'Anemia in pregnancy', N'disease of anemia during pregnancy in humans', N''),
( N'Q595010', N'hypertrichosis', N'hair disease characterized by hair growth that is abnormal in quantity or location', N''),
( N'Q595083', N'Anterior compartment syndrome', N'disease', N''),
( N'Q5952492', N'Hyalinizing clear cell carcinoma', N'', N''),
( N'Q5954614', N'hydroa vacciniforme', N'A rare skin disorder of unknown etiology affecting children. It is a photodermatitis, characterized by the formation of vesicles and scarring on sun exposed areas.', N''),
( N'Q5955105', N'hydrolethalus syndrome', N'Human disease', N''),
( N'Q59554760', N'Functional hypothalamic amenorrhea', N'form of amenorrhea caused by hypogonadism related to defective functioning of the hypothalamus', N''),
( N'Q5957516', N'Hyper-IgM syndrome type 2', N'Human disease', N''),
( N'Q5957519', N'CD40 deficiency', N'Human disease', N''),
( N'Q5957524', N'Hyper-IgM syndrome type 4', N'hyperimmunoglobulin syndrome characterized by normal or increased serum IgM concentrations associated with low or absent serum IgG, IgA, and IgE concentrations, indicating a defect in the class-switch recombination (CSR) process', N''),
( N'Q5957527', N'Hyper-IgM syndrome type 5', N'Human disease', N''),
( N'Q5957980', N'estrogen excess', N'Human disease', N''),
( N'Q5958205', N'Hyperkeratotic cutaneous capillary-venous malformation', N'', N''),
( N'Q5958530', N'Hyperproinsulinemia', N'human disease', N''),
( N'Q5958533', N'Hyperprothrombinemia', N'', N''),
( N'Q5958740', N'hyperthyroxinemia', N'thyroid disease', N''),
( N'Q5958765', N'hypersensitivity', N'An inflammatory response to an exogenous environmental antigen or an endogenous antigen initiated by the adaptive immune system.', N''),
( N'Q5958826', N'Hypervitaminosis E', N'', N''),
( N'Q5959159', N'Hypoandrogenism', N'medical condition', N''),
( N'Q5959167', N'Hypoalphalipoproteinemia', N'metabolic disorder characterized by deficiency of high density (alpha) lipoprotein in the blood', N''),
( N'Q5959327', N'hypochondrogenesis', N'human disease', N''),
( N'Q5959600', N'Hypoestrogenism', N'Medical condition', N''),
( N'Q5959625', N'hypoglossia', N'congenital disorder of digestive system', N''),
( N'Q5959735', N'hypolipoproteinemia', N'Human disease', N''),
( N'Q5961220', N'Hypothalamic disease', N'Human disease', N''),
( N'Q5961451', N'hypotrichosis–lymphedema–telangiectasia syndrome', N'human disease', N''),
( N'Q5962435', N'Hystrix-like ichthyosis–deafness syndrome', N'', N''),
( N'Q596474', N'conduct disorder', N'specific developmental disorder marked by a pattern of repetitive behavior wherein the rights of others or social norms are violated', N''),
( N'Q5965479', N'uterine sarcoma', N'uterine corpus cancer that is located in the muscles of the uterus or located in other tissues that support the uterus', N''),
( N'Q5973974', N'Precursor B-cell lymphoblastic leukemia', N'Subtype of acute lymphoblastic leukemia (ALL)', N''),
( N'Q5986438', N'ichthyosis bullosa of Siemens', N'Superficial epidermolytic ichthyosis (SEI) is a rare keratinopathic ichthyosis (KI; see this term) characterized by the presence of superficial blisters and erosions at birth', N''),
( N'Q5986440', N'Ichthyosis follicularis with alopecia and photophobia syndrome', N'Ichthyosis follicularis - alopecia - photophobia (IFAP) is a rare genetic disorder characterized by the triad of ichthyosis follicularis, alopecia, and photophobia from birth', N''),
( N'Q5986443', N'Ichthyosis linearis circumflexa', N'', N''),
( N'Q5986448', N'Ichthyosis hystrix', N'group of rare skin disorders in the ichthyosis family of skin', N''),
( N'Q5986449', N'Ichthyosis with confetti', N'human disease', N''),
( N'Q5986451', N'Ichthyosis prematurity syndrome', N'', N''),
( N'Q5988889', N'Idiopathic orbital inflammatory disease', N'Human disease', N''),
( N'Q5988903', N'Idiopathic pure sudomotor failure', N'', N''),
( N'Q599683', N'Brugada syndrome', N'heart conduction disease characterized by abnormal ECG findings', N''),
( N'Q6004750', N'Immature teratoma', N'Human disease', N''),
( N'Q6005412', N'immune-mediated inflammatory diseases', N'', N''),
( N'Q6005429', N'Immune dysregulation', N'', N''),
( N'Q6007089', N'impetigo herpetiformis', N'impetigo that is characterized as a form of severe pustular psoriasis occurring in pregnancy', N''),
( N'Q6007505', N'impossible syndrome', N'complex combination of human congenital malformations (birth defects)', N''),
( N'Q6013981', N'carbohydrate metabolic disorder', N'inherited metabolic disorder that affect the catabolism and anabolism of carbohydrates', N''),
( N'Q6013986', N'renal tubular transport disease', N'Human disease', N''),
( N'Q60195073', N'intrahepatic cholestasis of pregnancy', N'intrahepatic cholestasis characterized by reversible cholestasis typically occurring in the second or third trimester of pregnancy, elevated serum aminotransferases and bile acid level and resolution of symptoms by 2 to 3 weeks after delivery', N''),
( N'Q6025119', N'Indirect inguinal hernia', N'', N''),
( N'Q6029036', N'Infantile convulsions and choreoathetosis', N'', N''),
( N'Q6029048', N'infantile myofibromatosis', N'connective tissue benign neoplasm that is characterized by the development of benign tumors in the skin, striated muscles, bones, and in exceptional cases, visceral organs', N''),
( N'Q6029060', N'Infantile neuroaxonal dystrophy', N'describes several similar diseases', N''),
( N'Q6029067', N'Infantile systemic hyalinosis', N'', N''),
( N'Q6030096', N'Inflammatory myeloblastic tumor', N'', N''),
( N'Q6030100', N'Inflammatory myofibroblastic tumour', N'mesenchymal cell neoplasm that has material basis in myofibroblastic cells admixed with inflammatory cells', N''),
( N'Q6033800', N'Inherited disorders of trafficking', N'', N''),
( N'Q603644', N'cholangitis', N'bile duct disease that is an inflammation of the bile duct', N''),
( N'Q604075', N'multiple endocrine neoplasia type 2A', N'autosomal dominant disease characterized by medullary carcinoma of the thyroid, pheochromocytoma, hyperparathyroidism, and occasionally cutaneous lichen amyloidosis', N''),
( N'Q6043263', N'integrative agnosia', N'agnosia that is a loss of the ability to integrate these elements together into comprehensible perceptual wholes while recognizing elements of the whole', N''),
( N'Q6046092', N'interdigitating dendritic cell sarcoma', N'histiocytic and dendritic cell cancer that effect dendritic cells', N''),
( N'Q60464424', N'Frozen pelvis', N'', N''),
( N'Q6047923', N'Internal resorption', N'Human disease', N''),
( N'Q605006', N'glomerulonephritis', N'nephritis that causes inflammation of the glomeruli located in kidney', N''),
( N'Q605576', N'May–Thurner syndrome', N'a mechanical problem where the left iliac vein is compressed by the right iliac artery', N''),
( N'Q6057159', N'Interstitial granulomatous drug reaction', N'', N''),
( N'Q6057162', N'interstitial keratitis', N'human disease', N''),
( N'Q6057394', N'Intervertebral disc disorder', N'human disease', N''),
( N'Q6057481', N'neuronal intestinal dysplasia', N'Human disease', N''),
( N'Q6058359', N'intracranial berry aneurysm', N'intracranial aneurysm with a characteristic rounded shape; the most common form of cerebral aneurysm', N''),
( N'Q6058392', N'Intraepidermal neutrophilic IgA dermatosis', N'', N''),
( N'Q6058395', N'intraductal papilloma', N'human disease', N''),
( N'Q6058489', N'Intranodal palisaded myofibroblastoma', N'', N''),
( N'Q6058506', N'Intraocular lymphoma', N'Human disease', N''),
( N'Q6058862', N'fatty liver disease', N'lipid storage disease characterized by the accumulation of large vacuoles of triglyceride fat in liver cells via the process of steatosis', N''),
( N'Q6060418', N'Inverse psoriasis', N'', N''),
( N'Q6066379', N'bladder disease', N'urinary system disease that is located in the bladder', N''),
( N'Q6072985', N'iron metabolism disease', N'Human disease', N''),
( N'Q6072988', N'Iron metallic discoloration', N'', N''),
( N'Q6073877', N'Irritant folliculitis', N'', N''),
( N'Q6073879', N'inflamed seborrheic keratosis', N'Human disease', N''),
( N'Q60786772', N'LPS-responsive beige-like anchor protein deficiency', N'', N''),
( N'Q60791934', N'mucinous cystic  neoplasm of the liver', N'', N''),
( N'Q6079234', N'Ischial bursitis', N'', N''),
( N'Q608085', N'photodermatitis', N'photosensitivity disorder in which an agent or allergen is activated by light to sensitize the allergic response', N''),
( N'Q608259', N'trichotillomania', N'impulse control disorder that involves the uncontrollable plucking of ones hair', N''),
( N'Q6084258', N'Islet cell carcinoma', N'islet cell tumor that has material basis in epithelial cells', N''),
( N'Q6085391', N'Isobutyryl-coenzyme A dehydrogenase deficiency', N'gene (11q25)', N''),
( N'Q6085903', N'selective IgM deficiency disease', N'selective immunoglobulin deficiency disease thatis a dysgammaglobulinemia resulting from decreased levels of immunoglobulin M (IgM) production to roduction of other antibodies', N''),
( N'Q6088851', N'isthmicoma', N'Human disease', N''),
( N'Q609066', N'avolition', N'inability to initiate and persist in goal-directed activities (negative symptom)', N''),
( N'Q609165', N'juvenile polyposis syndrome', N'autosomal dominant disease that is characterized by predisposition to hamartomatous benign polyps in the gastrointestinal tract, specifically in the stomach, small intestine, colon, and rectum', N''),
( N'Q609503', N'gliosarcoma', N'Human disease', N''),
( N'Q609675', N'Hughes-Stovin syndrome', N'disease', N''),
( N'Q610075', N'Wolf-Hirschhorn syndrome', N'chromosome abnormality with a distinct craniofacial phenotype and intellectual disability', N''),
( N'Q611458', N'neuromyelitis optica', N'inflammatory demyelinating diseases of the central nervous system characterized mainly by attacks of uni- or bilateral optic neuritis and acute myelitis', N''),
( N'Q611571', N'hemorrhagic disease', N'human disease', N''),
( N'Q6118062', N'Jackson–Weiss syndrome', N'', N''),
( N'Q611984', N'keratoconus', N'corneal disease characterized by structural changes within the cornea causing it to thin and change, leading to a protruding conical shape', N''),
( N'Q612093', N'granulosa cell tumour', N'Human disease', N''),
( N'Q612108', N'acute promyelocytic leukemia', N'acute myeloid leukemia characterized by accumulation of promyelocytes in the bone marrow and by a translocation between chromosomes 15 and 17', N''),
( N'Q612681', N'anuria', N'lack of urine', N''),
( N'Q6126829', N'Jalili syndrome', N'Jalili syndrome is characterized by the association of amelogenesis imperfecta (AI; see this term) and cone-rod retinal dystrophy (CORD; see this term)', N''),
( N'Q612693', N'xeroderma pigmentosum', N'autosomal recessive disease that is characterized by a deficiency in the ability to repair ultraviolet damage that has material basis in autosomal recessive inheritance of DNA repair', N''),
( N'Q6132707', N'thrombocytopenic purpura', N'human disease', N''),
( N'Q6137239', N'hantavirus pulmonary syndrome', N'human disease', N''),
( N'Q613809', N'Kleine-Levin syndrome', N'recurrent hypersomnia that is characterized by recurring periods of excessive amounts of sleep and altered behavior', N''),
( N'Q6139748', N'progeroid syndrome', N'range of genetic disorders which cause a person to appear to grow older faster', N''),
( N'Q614279', N'louping ill', N'animal disease', N''),
( N'Q614750', N'bronchiolitis obliterans', N'lung disease involving obstruction of the bronchioles', N''),
( N'Q6150957', N'Gastric dilatation volvulus', N'a medical condition in dogs', N''),
( N'Q6152510', N'cervical dystonia', N'human disease', N''),
( N'Q615363', N'Torticollis', N'dystonic condition defined by an abnormal, asymmetrical head or neck position, which may be due to a variety of causes', N''),
( N'Q6155971', N'janus kinase-3 deficiency', N'Human disease', N''),
( N'Q615645', N'Fabry disease', N'rare human genetic lysosomal storage disorder', N''),
( N'Q6159042', N'Japanese spotted fever', N'Human disease', N''),
( N'Q616003', N'aortic aneurysm', N'aorta to greater than 1.5 times normal size.', N''),
( N'Q6160183', N'Jargon aphasia', N'type of aphasia involving noun selection difficulty', N''),
( N'Q616087', N'aortic valve insufficiency', N'aortic valve disease that is characterized by leaking of the aortic valve of the heart causes blood to flow in the reverse direction during ventricular diastole, from the aorta into the left ventricle', N''),
( N'Q616088', N'aortitis', N'inflammation of the aortic wall', N''),
( N'Q616667', N'temporal lobe epilepsy', N'Human disease', N''),
( N'Q617079', N'calculus', N'concretion of material, usually mineral salts, that forms in an organ or duct of the body', N''),
( N'Q618246', N'Apert syndrome', N'congenital disorder of digestive system', N''),
( N'Q618622', N'periapical periodontitis', N'Human disease', N''),
( N'Q619428', N'Roberts syndrome', N'Human disease', N''),
( N'Q620760', N'Postural orthostatic tachycardia syndrome', N'condition in which a change from lying to standing causes an abnormally large increase in heart rate', N''),
( N'Q620918', N'lagophthalmos', N'Human disease', N''),
( N'Q621053', N'taijin kyofusho', N'Japanese culture-bound syndrome', N''),
( N'Q622427', N'ptosis', N'eye disease characterized by the drooping or falling of the upper eyelid', N''),
( N'Q622437', N'alpha-1-antitrypsin deficiency', N'genetic disorder that may result in lung disease or liver disease', N''),
( N'Q622604', N'pyromania', N'impulse control disorder', N''),
( N'Q622828', N'hypokalemic periodic paralysis', N'Human disease', N''),
( N'Q622901', N'Korsakoffs syndrome', N'mental illness caused by a lack of thiamine in the brain', N''),
( N'Q622969', N'orbital cellulitis', N'Human disease', N''),
( N'Q623031', N'liver cancer', N'human disease', N''),
( N'Q623668', N'choroid plexus papilloma', N'Human disease', N''),
( N'Q624398', N'Blounts disease', N'osteochondrodysplasia that results in inward turning of lower leg, located in tibia, which fails to develop normally', N''),
( N'Q624590', N'Arachnoid cyst', N'human disease', N''),
( N'Q624748', N'multiple endocrine neoplasia type 2B', N'autosomal dominant disease characterized by medullary thyroid carcinoma, pheochromocytoma, multiple mucosal neuromas and intestinal ganglioneuromas, and often a marfanoid habitus and other skeletal abnormalities', N''),
( N'Q625506', N'preterm birth', N'birth at less than a specified gestational age', N''),
( N'Q625935', N'hip dysplasia', N'human disease', N''),
( N'Q627291', N'cicatricial pemphigoid', N'autoimmune blistering disease', N''),
( N'Q627368', N'blastomycosis', N'primary systemic mycosis that results in a systemic fungal infection, has material basis in Blastomyces dermatitidis, transmitted by airborne spores and has symptom skin lesions, has symptom lung lesions and has symptom pleural thickening', N''),
( N'Q627373', N'Pleomorphic xanthoastrocytoma', N'Human disease', N''),
( N'Q627625', N'histoplasmosis', N'human disease', N''),
( N'Q6279182', N'epileptic seizure', N'disease, disturbance of cortical function due to a sudden, abnormal, excessive, and disorganized discharge of brain cells', N''),
( N'Q628648', N'Eagle syndrome', N'human disease', N''),
( N'Q629515', N'stimulant psychosis', N'psychotic disorder that appears in some people who abuse stimulant drugs', N''),
( N'Q630090', N'glycogen storage disease I', N'rare disease', N''),
( N'Q630552', N'retinitis', N'Human disease', N''),
( N'Q6311294', N'Jumping Frenchmen of Maine', N'human disease', N''),
( N'Q6311812', N'Junctional epidermolysis bullosa with pyloric atresia', N'Human disease', N''),
( N'Q6311816', N'Junctional tachycardia', N'type of heart arrhythmia', N''),
( N'Q631361', N'diabetic retinopathy', N'Human disease', N''),
( N'Q6318950', N'childhood type dermatomyositis', N'Human disease', N''),
( N'Q6318953', N'hemochromatosis type 2', N'hemochromatosis characterized by autosomal recessive inheritance of early onset of severe iron loading with symptoms including; hypogonadotropic hypogonadism, cardiomyopathy, arthropathy, and liver fibrosis or cirrhosis', N''),
( N'Q6318955', N'Juvenile hyaline fibromatosis', N'', N''),
( N'Q6318965', N'idiopathic juvenile osteoporosis', N'osteoporosis with no known cause that is characterized by pain in the back and extremities, walking difficulties, multiple fractures, and radiological evidence of osteoporosis', N''),
( N'Q6318969', N'Juvenile primary lateral sclerosis', N'', N''),
( N'Q631904', N'atypical teratoid rhabdoid tumor', N'brain cancer that is usually located in the brain, but can occur anywhere in the central nervous system', N''),
( N'Q6319133', N'juxtaglomerular cell tumor', N'', N''),
( N'Q632228', N'Hajdu-Cheney syndrome', N'rare disease', N''),
( N'Q632522', N'bacteriuria', N'medical term denoting the presence of bacteria in urine', N''),
( N'Q633859', N'Poland syndrome', N'Human disease', N''),
( N'Q6348271', N'Kairo cancer', N'', N''),
( N'Q635339', N'Conorhyland', N'Human disease', N''),
( N'Q6362361', N'Kang cancer', N'', N''),
( N'Q63677197', N'Airport malaria', N'occurs when a malaria infected female Anopheles mosquito travels by aircraft from a country where malaria is common', N''),
( N'Q6368059', N'Karak syndrome', N'', N''),
( N'Q637816', N'occupational disease', N'chronic ailment that occurs as a result of work or occupational activity; aspect of occupational safety and health', N''),
( N'Q6378573', N'Katz syndrome', N'', N''),
( N'Q6378691', N'Kaufman oculocerebrofacial syndrome', N'. An autosomal recessive mode of inheritance seems most likely.', N''),
( N'Q638729', N'autoimmune thrombocytopenic purpura', N'primary thrombocytopenia that involves relatively few platelets in blood as a result of autoantibodies', N''),
( N'Q638975', N'central core myopathy', N'Human disease', N''),
( N'Q639203', N'Menkes disease', N'Human disease', N''),
( N'Q6393653', N'Keratosis follicularis spinulosa decalvans', N'human disease', N''),
( N'Q6393657', N'Keratosis linearis with ichthyosis congenital and sclerosing keratoderma syndrome', N'', N''),
( N'Q63943905', N'Limbic-predominant age-related TDP-43 encephalopathy', N'form of dementia', N''),
( N'Q6395632', N'Keutel syndrome', N'Keutel syndrome is characterised by diffuse cartilage calcification, brachytelephalangism, peripheral pulmonary artery stenoses and facial dysmorphism', N''),
( N'Q639776', N'cat-scratch disease', N'human disease', N''),
( N'Q640836', N'Lujan–Fryns syndrome', N'rare genetic condition in humans', N''),
( N'Q641605', N'exocrine pancreatic insufficiency', N'Human disease', N''),
( N'Q6422092', N'Kniest dysplasia', N'Human disease', N''),
( N'Q6426064', N'Kohlschütter-Tönz syndrome', N'rare inherited human disease', N''),
( N'Q64348505', N'calcium pyrophosphate dihydrate crystal deposition disease', N'disease', N''),
( N'Q64403009', N'Tertiary peritonitis', N'', N''),
( N'Q6441908', N'Kufor-Rakeb syndrome', N'Kufor-Rakeb syndrome (KRS) is a rare genetic neurodegenerative disorder characterized by juvenile Parkinsonism, pyramidal degeneration (dystonia), supranuclear palsy, and cognitive impairment', N''),
( N'Q644318', N'vasculitis', N'vascular disease that is characterized by inflammation of the blood vessels', N''),
( N'Q644364', N'median rhomboid glossitis', N'Human disease', N''),
( N'Q64485022', N'Paternal depression', N'a psychological disorder derived from parental depression', N''),
( N'Q645363', N'bursitis', N'human disease', N''),
( N'Q6458655', N'DNA ligase IV deficiency', N'Human disease', N''),
( N'Q6468402', N'Lachiewicz–Sibley syndrome', N'', N''),
( N'Q6468835', N'Lacquer dermatitis', N'', N''),
( N'Q64698726', N'embryo loss', N'early pregnancy loss during the mammalian embryos development: in humans, loss in the second through eighth week after fertilization', N''),
( N'Q6470994', N'alcoholic liver cirrhosis', N'Human disease', N''),
( N'Q647630', N'premature ovarian failure', N'ovarian disease where ovaries do not produce estrogen despite high levels of circulating gonadotropins in women under 40', N''),
( N'Q64869872', N'Perimyositis', N'myopathy characterized by inflammation near muscle', N''),
( N'Q6488975', N'large-cell lung carcinoma', N'Disease', N''),
( N'Q6488977', N'Large-cell lymphoma', N'Human disease', N''),
( N'Q6489116', N'Large cell neuroendocrine carcinoma of the lung', N'Human disease', N''),
( N'Q6489151', N'T-cell large granular lymphocyte leukemia', N'chronic lymphocytic leukemia that exhibits an unexplained, chronic (> 6 months) elevation in large granular lymphocytes (LGLs) in the peripheral blood', N''),
( N'Q648982', N'argyria', N'medical condition', N''),
( N'Q6491971', N'Laryngoonychocutaneous syndrome', N'', N''),
( N'Q649558', N'Chagas disease', N'human disease', N''),
( N'Q6495941', N'Lathosterolosis', N'Lathosterolosis is an extremely rare inborn error of sterol biosynthesis characterized by facial dysmorphism, congenital anomalies (including limb and kidney anomalies), failure to thrive, developmental delay and liver disease', N''),
( N'Q649602', N'Ohtahara syndrome', N'neonatoal period electroclinical syndrome that is characterized by tonic spasms and partial seizures', N''),
( N'Q6498240', N'Laugier–Hunziker syndrome', N'human disease', N''),
( N'Q650026', N'ectrodactyly', N'deficiency or absence of one or more central digits of the hand or foot', N''),
( N'Q650766', N'tinea capitis vale', N'Human disease', N''),
( N'Q65081603', N'Plane-form enamel hypoplasia', N'', N''),
( N'Q651223', N'pneumoconiosis', N'interstitial lung disease that is caused by the inhalation of dust', N''),
( N'Q651680', N'alkaptonuria', N'amino acid metabolic disorder that involves phenylalanine and tyrosine metabolism with the accumulation of homogentisic acid, a toxic tyrosine byproduct', N''),
( N'Q6516936', N'left atrial enlargement', N'', N''),
( N'Q6523346', N'Lentigo maligna melanoma', N'', N''),
( N'Q6523439', N'Lenz microphthalmia syndrome', N'human disease', N''),
( N'Q6523462', N'Lenz–Majewski syndrome', N'Lenz-Majewski hyperostotic dwarfism is an extremely rare syndrome associating dwarfism, characteristic facial appearance, cutis laxa and progressive bone sclerosis', N''),
( N'Q652568', N'Argyll Robertson pupil', N'symptom of human disease', N''),
( N'Q652744', N'hand, foot and mouth disease', N'human disease', N''),
( N'Q6527832', N'lepromatous leprosy', N'Human disease', N''),
( N'Q653078', N'Whipple disease', N'Human disease', N''),
( N'Q653200', N'flat feet problems', N'human foot arch that is very low', N''),
( N'Q653318', N'silicosis', N'pneumoconiosis that is an inflammation and scarring of the upper lobes of the lungs causing nodular lesions resulting from inhalation of silica, quartz or slate particles', N''),
( N'Q6533258', N'Lethal acantholytic epidermolysis bullosa', N'Lethal acantholytic epidermolysis bullosa is a suprabasal subtype of epidermolysis bullosa simplex (EBS, see this term) characterized by generalized oozing erosions, usually in the absence of blisters', N''),
( N'Q6533262', N'lethal congenital contracture syndrome 1', N'lethal congenital contracture syndrome that has material basis in homozygous or compound heterozygous mutation in the mRNA export mediator GLE1 on chromosome 9q34', N''),
( N'Q6533263', N'lethal midline granuloma', N'Human disease', N''),
( N'Q653383', N'mallet finger', N'an extensor tendon injury at the farthest away finger joint', N''),
( N'Q6534510', N'Leukocyte adhesion deficiency-1', N'', N''),
( N'Q6534539', N'Leukotriene C4 synthase deficiency', N'Leukotriene C4 synthase deficiency is an extremely rare fatal neurometabolic developmental disorder characterized clinically by muscular hypotonia, psychomotor retardation, failure to thrive, and microcephaly', N''),
( N'Q6534949', N'Levator ani syndrome', N'', N''),
( N'Q653924', N'long QT syndrome', N'condition involving delayed repolarization of the heart during the heartbeat cycle', N''),
( N'Q653971', N'indigestion', N'Human disease', N''),
( N'Q6543199', N'lichen myxedematosus', N'Human disease', N''),
( N'Q6543200', N'lichen nitidus', N'Human disease', N''),
( N'Q6543217', N'lichen striatus', N'rare skin condition, seen primarily in children, characterized by self-limiting eruption of small, scaly papules.', N''),
( N'Q6543864', N'Liebenberg syndrome', N'human disease', N''),
( N'Q654425', N'Waterhouse-Friderichsen syndrome', N'adrenal gland disease that is characterized by failure of the adrenal gland due to bleeding into the gland', N''),
( N'Q654485', N'malignant peripheral nerve sheath tumor', N'Human disease', N''),
( N'Q6546687', N'Ligneous conjunctivitis', N'', N''),
( N'Q6549091', N'Limb–mammary syndrome', N'human disease', N''),
( N'Q6556681', N'lipoatrophic diabetes', N'type 2 diabetes that involves severe lipodystrophy in addition to the traditional signs of diabetes', N''),
( N'Q6556693', N'lipodermatosclerosis', N'disease', N''),
( N'Q655982', N'eosinophilic granuloma', N'', N''),
( N'Q656199', N'Torsion dystonia', N'a hereditary disease characterized by involuntary painful muscle contractions resulting in uncontrollable distortions', N''),
( N'Q657193', N'metabolic syndrome', N'clustering of medical conditions (giving a total of 16 possible combinations giving the syndrome)', N''),
( N'Q657516', N'hereditary spastic paraplegia', N'genetically and clinically heterogeneous group of neurodegenerative disorders characterized by progressive spasticity and hyperreflexia of the lower limbs', N''),
( N'Q6579320', N'The great imitator', N'', N''),
( N'Q6583504', N'Ribose-5-phosphate isomerase deficiency', N'human disease', N''),
( N'Q6587253', N'Queensland tick typhus', N'Human disease', N''),
( N'Q658873', N'radiation burn', N'damage to the skin or other biological tissue caused by exposure to radiation', N''),
( N'Q659033', N'biliary atresia', N'congenital disorder of digestive system investigation of choice of the disease is  MRCP', N''),
( N'Q659584', N'molluscum contagiosum', N'viral infection of the skin', N''),
( N'Q660330', N'TAR syndrome', N'genetic disorder', N''),
( N'Q661015', N'achalasia', N'esophageal disease characterized by an inability of the esophagus to move food toward the stomach resulting from the lower esophogeal sphincter not fully relaxing during swallowing', N''),
( N'Q662185', N'choanal atresia', N'congenital disorder of respiratory system', N''),
( N'Q662272', N'short bowel syndrome', N'Human disease', N''),
( N'Q662298', N'ectropion', N'human disease', N''),
( N'Q663041', N'maturity-onset diabetes of the young', N'genetic disease that has material basis in mutations in the MODY genes disrupting insulin production', N''),
( N'Q664174', N'asbestosis', N'pneumoconiosis caused by inhalation and retention of asbestos fibers', N''),
( N'Q665207', N'Thoracic Outlet Syndrome', N'vascular disease that is characterized by compression at the superior thoracic outlet resulting from excess pressure placed on a neurovascular bundle passing between the anterior scalene and middle scalene muscles', N''),
( N'Q6663796', N'lobomycosis', N'dermatomycosis that results in infection located in skin or located in subcutaneous tissue, has material basis in Lacazia loboi and has symptom crusty plaques, has symptom tumors and results in formation of nodular lesions', N''),
( N'Q6664621', N'Localized disease', N'', N''),
( N'Q6664623', N'Localized epidermolysis bullosa simplex', N'epidermolysis bullosa simplex that is characterized by skin blistering that begins anytime between childhood and adulthood and is usually limited to the hands and feet', N''),
( N'Q6664633', N'Localized lichen myxedematosus', N'', N''),
( N'Q6668132', N'Loin pain hematuria syndrome', N'disease', N''),
( N'Q666980', N'Rubinstein-Taybi syndrome', N'rare disease', N''),
( N'Q6673122', N'thyroid gland disease', N'type of endocrine disease', N''),
( N'Q667681', N'Neu-Laxova syndrome', N'', N''),
( N'Q6692756', N'Low-grade fibromyxoid sarcoma', N'', N''),
( N'Q6694174', N'Lowry–MacLean syndrome', N'Lowry-MacLean syndrome is a very rare syndrome characterized by microcephaly, craniosynostosis, glaucoma, growth failure and visceral malformations', N''),
( N'Q669435', N'renal agenesis', N'congenital disorder of urinary system', N''),
( N'Q669822', N'Laron syndrome', N'congenital disorder characterized by marked short stature associated with normal or high serum growth hormone (GH) and low serum insulin-like growth factor-1 (IGF-I) levels which fail to rise after exogenous GH administration', N''),
( N'Q6705425', N'Lutembachers syndrome', N'Human disease', N''),
( N'Q6708237', N'lymphatic system disease', N'immune system disease that is located in the lymphatic system', N''),
( N'Q6708247', N'Lymphoblastic lymphoma', N'lymphoma that has material basis in immature malignant lymphocytes (lymphoblasts) committed to the B-cell or T-cell lineage and located in primarily lymph nodes or located in extranodal sites', N''),
( N'Q6708258', N'lymphocytic colitis', N'colitis characterized by an accumulation of lymphocytes in the colonic epithelium and connective tissue (lamina propria)', N''),
( N'Q6708260', N'lymphoepithelial lesion', N'', N''),
( N'Q6708266', N'Lymphoepithelioma-like carcinoma', N'carcinoma that is a malignant epithelial neoplasm densely infiltrated by lymphoid cells', N''),
( N'Q6708277', N'lymphoid leukemia', N'A malignant lymphocytic neoplasm of B-cell or T-cell lineage involving primarily the bone marrow and the peripheral blood.  This category includes precursor or acute lymphoblastic leukemias and chronic leukemias.', N''),
( N'Q6710283', N'Wolman disease', N'autosomal recessive inborn error of metabolism that results in the body not producing enough active lysosomal acid lipase (LAL) enzyme', N''),
( N'Q6714500', N'MASA syndrome', N'hereditary spastic paraplegia that is characterized by hydrocephalus, spasticity of the lower limbs, adducted thumbs, aphasia, seizures, agenesis of the corpus callosum and intellectual disability in the mild to moderate range', N''),
( N'Q6717006', N'MODY 5', N'', N''),
( N'Q6717008', N'MODY 6', N'', N''),
( N'Q6717114', N'MORM syndrome', N'', N''),
( N'Q671776', N'mutism', N'inability to speak, often caused by a speech disorder or mental disorder', N''),
( N'Q6725504', N'macrophage activation syndrome', N'complication of several chronic rheumatic diseases of childhood', N''),
( N'Q6725785', N'retinal telangiectasia', N'condition of the retina', N''),
( N'Q673083', N'gingivitis', N'Human disease', N''),
( N'Q6737984', N'Majocchis disease', N'', N''),
( N'Q6742919', N'male breast cancer', N'Human disease', N''),
( N'Q6742925', N'male reproductive system disease', N'reproductive system disease that affects male reproductive organs.', N''),
( N'Q6743502', N'malignant acrospiroma', N'Human disease', N''),
( N'Q6743507', N'malignant fibrous histiocytoma', N'human disease', N''),
( N'Q6743510', N'malignant mixed tumor', N'cell type cancer that has material basis in cells  from two tissues', N''),
( N'Q6743513', N'skin pilomatrix carcinoma', N'Human disease', N''),
( N'Q6743514', N'malignant pleural effusion', N'human disease', N''),
( N'Q6743515', N'rhabdoid tumor', N'childhood kidney neoplasm that is located in the in the kidney as well as other locations outside the kidneys such as the liver, muscle, heart, lung, soft tissues, skin, the central nervous system', N''),
( N'Q6743517', N'Malignant triton tumor', N'Human disease', N''),
( N'Q6744557', N'Malouf syndrome', N'This syndrome is characterized by the association of dilated cardiomyopathy and hypergonadotropic hypogonadism (DCM-HH)', N''),
( N'Q6744609', N'3MC syndrome 3', N'3MC congenital syndrome associated with the COLEC10 gene on chromosome 8q24', N''),
( N'Q674461', N'multiple chemical sensitivity', N'chronic medical condition of disputed cause', N''),
( N'Q6745785', N'mammary myofibroblastoma', N'rare, benign tumor of the breast', N''),
( N'Q675010', N'lysosomal storage disease', N'inherited metabolic disorder that involve an abnormal accumulation of substances inside the lysosome resulting from defects in lysosomal function', N''),
( N'Q675311', N'autoimmune polyendocrine syndrome', N'autoimmune disease of endocrine system with auto-reactivity against endocrine organs', N''),
( N'Q6758201', N'Marcus Gunn pupil', N'medical sign observed during an eye test', N''),
( N'Q6758640', N'Marden–Walker syndrome', N'', N''),
( N'Q676191', N'vaginitis', N'Human disease', N''),
( N'Q6773846', N'Marshall syndrome', N'', N''),
( N'Q677449', N'aspiration pneumonia', N'bronchopneumonia that develops due to the entrance of foreign materials into the lungs', N''),
( N'Q677803', N'nephrogenic systemic fibrosis', N'', N''),
( N'Q6784873', N'Mast cell leukemia', N'rare leukemia (blood cancer) involving mast cells', N''),
( N'Q6785569', N'mast cell neoplasm', N'hematologic cancer that has material basis in mast cells', N''),
( N'Q6806121', N'Median nerve palsy', N'', N''),
( N'Q6806161', N'mediastinal large B cell lymphoma', N'', N''),
( N'Q6806655', N'Medication-induced hyperlipoproteinemia', N'', N''),
( N'Q6807316', N'Medullary carcinoma', N'Human disease', N''),
( N'Q6807330', N'medulloepithelioma', N'Human disease', N''),
( N'Q680873', N'otitis externa', N'inflammation of the outer ear and ear canal.', N''),
( N'Q6811406', N'melanoacanthoma', N'Human disease', N''),
( N'Q6811448', N'Melanocytic oral lesion', N'', N''),
( N'Q6811491', N'Melanoma with features of a Spitz nevus', N'skin melanoma that is characterized by asymmetric shape, diameter greater than 1 cm, a lesion with a deep invasive component, and a high degree of cytologic atypia', N''),
( N'Q6811539', N'Melanosis', N'', N''),
( N'Q681160', N'dermatomyositis', N'myositis that results in inflammation located in muscle or located in skin where a skin rash is often seen prior to the onset of muscle weakness', N''),
( N'Q681817', N'squamous cell carcinoma', N'carcinoma that derives from squamous epithelial cells', N''),
( N'Q681970', N'contagious pustular dermatitis', N'Human disease', N''),
( N'Q6821200', N'mesenchymal chondrosarcoma', N'Human disease', N''),
( N'Q6821415', N'mesoblastic nephroma', N'kidney cancer that is found in the kidney and is usually found before birth by ultrasound or within the first 3 months of life', N''),
( N'Q6822340', N'metabolic bone disease', N'', N''),
( N'Q6822414', N'Metachondromatosis', N'Metachondromatosis (MC) is a rare disorder characterized by the presence of both multiple enchondromas and osteochondroma-like lesions', N''),
( N'Q6823071', N'metanephric adenoma', N'Human disease', N''),
( N'Q6824028', N'methylmalonyl-CoA mutase deficiency', N'A methylmalonic acidemia characterized by accumulation of methylmalonic acid in the blood that is unresponsive to vitamn B12 therapy and that has material basis in mutation in the MUT gene on chromosome 6p12.3.', N''),
( N'Q682798', N'bejel', N'Human disease', N''),
( N'Q6836884', N'Michelin tire baby syndrome', N'human disease', N''),
( N'Q6837320', N'3MC syndrome 1', N'3MC syndrome associated with the MASP1 gene on chromosome 3q27', N''),
( N'Q6838869', N'Mickleson syndrome', N'', N''),
( N'Q6839205', N'Warburg micro syndrome', N'autosomal recessive disease characterized by severe intellectual disability, microcephaly, congenital cataract, microcornea, microphthalmia, agenesis or hypoplasia of the corpus callosum and hypogenitalism', N''),
( N'Q6839323', N'microcephalic osteodysplastic primordial dwarfism type II', N'Human disease', N''),
( N'Q6839330', N'Microcephaly lymphoedema chorioretinal dysplasia', N'syndrome characterized byvariable expression of microcephaly, ocular disorders including chorioretinopathy, congenital lymphedema of the lower limbs, and mild to moderate intellectual disability', N''),
( N'Q6839796', N'microorchidism', N'Human disease', N''),
( N'Q6839894', N'microphthalmia–dermal aplasia–sclerocornea syndrome', N'', N''),
( N'Q6840462', N'microvascular occlusion', N'', N''),
( N'Q6840464', N'Microvasculature remodeling', N'alterations of vascular wall structures, often leading to elevated vascular resistance', N''),
( N'Q684383', N'exophthalmos', N'human disease', N''),
( N'Q6844287', N'migraine-associated vertigo', N'vertigo associated with a migraine', N''),
( N'Q684810', N'berylliosis', N'pneumoconiosis that involves allergic response located in lungs caused by inhalation of beryllium compounds', N''),
( N'Q684840', N'Sneddon syndrome', N'form of arteriopathy', N''),
( N'Q684924', N'rheumatism', N'Human disease', N''),
( N'Q685200', N'Superior canal dehiscence', N'inner ear disease characterized by dehiscence in the bone overlying the superior semicircular canal experience with symptoms of pressure or sound-induced vertigo, bone conduction hyperacusis, and pulsatile tinnitus', N''),
( N'Q685594', N'second-degree atrioventricular block', N'disease of the electrical conduction system of the heart. It is a conduction block between the atria and ventricles.', N''),
( N'Q686131', N'lactocele', N'retention cyst containing milk or a milky substance that is usually located in the mammary glands', N''),
( N'Q6865354', N'Minimally differentiated acute myeloblastic leukemia', N'', N''),
( N'Q686574', N'endometrial hyperplasia', N'uterine benign neoplasm that is characterized by excessive proliferation of the cells of the endometrium', N''),
( N'Q6874652', N'Mirror movement disorder', N'movement disease characterized by involuntary movements of one side of the body that mirror intentional movements on the opposite side primarily involving the upper limbs', N''),
( N'Q6879590', N'Missouri Lyme disease', N'', N''),
( N'Q6881782', N'Mitis junctional epidermolysis bullosa', N'Human disease', N''),
( N'Q6881866', N'mitochondrial encephalomyopathy', N'human disease', N''),
( N'Q6881876', N'mitochondrial DNA depletion syndrome 1', N'Human disease', N''),
( N'Q6881881', N'mitochondrial myopathy', N'myopathy characterized by mitochondrial dysfunction', N''),
( N'Q6881883', N'Mitochondrial trifunctional protein deficiency', N'', N''),
( N'Q6883839', N'Mixed-cell lymphoma', N'', N''),
( N'Q6883955', N'Mixed anxiety-depressive disorder', N'', N''),
( N'Q6883972', N'Mixed gonadal dysgenesis  X0/XY', N'Human disease', N''),
( N'Q6884011', N'mixed receptive-expressive language disorder', N'neurodevelopmental condition', N''),
( N'Q68854', N'snakebite', N'injury caused by a bite from a snake', N''),
( N'Q688890', N'pulmonary sequestration', N'congenital disorder of respiratory system', N''),
( N'Q688949', N'fibromuscular dysplasia', N'human arterial disease', N''),
( N'Q6896359', N'Mollarets meningitis', N'Human disease', N''),
( N'Q689777', N'Dopamine-responsive dystonia', N'genetic movement disorder', N''),
( N'Q6899222', N'money disorder', N'', N''),
( N'Q689985', N'lipoma', N'benign tumor made of fat tissue', N''),
( N'Q690032', N'relapsing fever borreliosis', N'primary bacterial infectious disease that results in infection, has material basis in Borrelia, which is transmitted by tick or transmitted by body louse', N''),
( N'Q6901244', N'MonoMAC', N'disease', N''),
( N'Q6901575', N'monofixation syndrome', N'Human disease', N''),
( N'Q6901736', N'Monomelic amyotrophy', N'disease of the lower motor neurons', N''),
( N'Q6901967', N'Monosomy 14', N'', N''),
( N'Q690210', N'dysosmia', N'qualitative alteration or distortion of the perception of smell', N''),
( N'Q691112', N'Muselmann', N'term used among captives of World War II Nazi concentration camps', N''),
( N'Q692536', N'muscular disease', N'disease in which the muscle fibers do not function, resulting in muscular weakness', N''),
( N'Q6931137', N'Mucinous carcinoma', N'', N''),
( N'Q6931138', N'mucinosis', N'human disease', N''),
( N'Q6931140', N'mucinous cystadenocarcinoma', N'cystadenocarcinoma that derives from epithelial cells originating in glandular tissue, with a capsulated structure and mucus-producing cells', N''),
( N'Q6931143', N'mucinous cystadenoma', N'Human disease', N''),
( N'Q6931254', N'mucormycosis', N'Human disease', N''),
( N'Q6931266', N'mucosal melanoma', N'melanoma that has material basis in melanocytes located in mucosal membranes lining the respiratory, gastrointestinal and urogenital tract', N''),
( N'Q6931269', N'mucositis', N'gastrointestinal system disease that is characterized by painful inflammation and ulceration of the mucous membranes lining the digestive tract', N''),
( N'Q693442', N'subarachnoid hemorrhage', N'bleeding into the subarachnoid space', N''),
( N'Q6934690', N'Multifocal motor neuropathy', N'Multifocal motor neuropathy (MMN) is a rare acquired immune-mediatedneuropathy characterized clinically by a purely motor deficit with conduction block and asymmetric multifocal weakness, fasciculations, and cramping', N''),
( N'Q6934693', N'multifocal stenosing ulceration of the small intestine', N'', N''),
( N'Q6934914', N'multiple carboxylase deficiency', N'human disease', N''),
( N'Q693519', N'essential tremor', N'movement disorder causing involuntary tremors, especially in the hands. It occurs alone without other neurological signs and symptoms.', N''),
( N'Q693578', N'pseudoachondroplasia', N'osteochondrodysplasia that has material basis in mutations in the COMP gene which results in short limb dwarfism', N''),
( N'Q693872', N'Meige syndrome', N'cranio-facial dystonia that is accompanied by blepharospasm', N''),
( N'Q6939061', N'Murrain', N'Umbrella term for deadly disease, especially of livestock', N''),
( N'Q694552', N'lymphogranuloma venereum', N'sexually transmitted disease caused by the invasive serovars L1, L2, L2a or L3 of Chlamydia trachomatis.', N''),
( N'Q6946984', N'Mycobacterium avium-intracellulare infection', N'Human disease', N''),
( N'Q6947340', N'Myeloperoxidase deficiency', N'human disease', N''),
( N'Q6947906', N'myocardial ischemia', N'disease', N''),
( N'Q6947909', N'myoclonic astatic epilepsy', N'generalised idiopathic epilepsy', N''),
( N'Q6947913', N'myoepithelioma of the head and neck', N'neoplasm composed of outgrowths of myoepithelial cells from a sweat gland', N''),
( N'Q6949365', N'myxoid liposarcoma', N'human disease', N''),
( N'Q6949370', N'myxosarcoma', N'human disease', N''),
( N'Q6951345', N'N-Acetylglutamate synthase deficiency', N'N-acetylglutamate synthase (NAGS) deficiency is a urea cycle disorder leading to hyperammonaemia', N''),
( N'Q6955667', N'NUT midline carcinoma', N'Human disease', N''),
( N'Q695954', N'psychogenic pain', N'Type of pain', N''),
( N'Q6960193', N'Nakajo syndrome', N'', N''),
( N'Q69642903', N'Congenital heart defects, dysmorphic facial features, and intellectual developmental disorder', N'rare genetic disorder', N''),
( N'Q696490', N'panic attack', N'period of intense fear or apprehension of sudden onset', N''),
( N'Q6965688', N'Narcotic dermopathy', N'', N''),
( N'Q697117', N'spinal disc herniation', N'disease', N''),
( N'Q6972442', N'fasciolosis', N'parasitic worm infection caused by the common liver fluke Fasciola hepatica as well as by Fasciola gigantica', N''),
( N'Q6985741', N'necrotizing sialometaplasia', N'Human disease', N''),
( N'Q6991009', N'Nematode dermatitis', N'', N''),
( N'Q6993484', N'Neonatal ichthyosis–sclerosing cholangitis syndrome', N'', N''),
( N'Q6993491', N'Neonatal lupus erythematosus', N'', N''),
( N'Q6993502', N'neonatal abstinence syndrome', N'Medical condition in newborn babies caused by drugs taken by the mother before birth', N''),
( N'Q6995207', N'nephrosis', N'non-inflammatory kidney disease', N''),
( N'Q6996973', N'nervous system disease', N'human disease', N''),
( N'Q7002244', N'neurogenic inflammation', N'inflammation arising from the local release by afferent neurons of inflammatory mediators such as Substance P, Calcitonin Gene-Related Peptide (CGRP), neurokinin A (NKA), and endothelin-3 (ET-3)', N''),
( N'Q7002430', N'neuromuscular junction disease', N'neuromuscular disease that is characterized by the disfunction of conduction through the neuromuscular junction', N''),
( N'Q7002720', N'Neurothekeoma', N'A benign neoplasm arising from nerve sheaths. It is characterized by the presence of a myxoid stroma.', N''),
( N'Q7003001', N'neutral lipid storage disease', N'lipid storage disease that is characterized by accumulation of triglycerides in the cytoplasm of leukocytes, muscle, liver, fibroblasts, and other tissues', N''),
( N'Q7003142', N'Neutrophil immunodeficiency syndrome', N'', N''),
( N'Q7003148', N'Neutrophilic eccrine hidradenitis', N'', N''),
( N'Q7004538', N'Nevi and melanomas', N'', N''),
( N'Q7005032', N'Nevus comedonicus', N'Human disease', N''),
( N'Q7005033', N'Nevus comedonicus syndrome', N'', N''),
( N'Q7005035', N'Nevus depigmentosus', N'Human disease', N''),
( N'Q7005037', N'Nevus of Ito', N'', N''),
( N'Q7005041', N'Nevus psiloliparus', N'', N''),
( N'Q703961', N'transmissible spongiform encephalopathy', N'group of brain diseases induced by prion proteins', N''),
( N'Q7042475', N'Njolstad syndrome', N'cutaneous condition', N''),
( N'Q7045267', N'No reflow phenomenon', N'', N''),
( N'Q7046751', N'Nodular melanoma', N'melanoma that is characterized as highly aggressive and manifests as a uniform blue-black, blue-red, or amelanotic nodule', N''),
( N'Q7048905', N'non-epileptic seizure', N'medical condition', N''),
( N'Q704930', N'progressive multifocal leukoencephalopathy', N'viral disease affecting human brains', N''),
( N'Q7049641', N'nonunion', N'permanent failure of healing following a broken bone', N''),
( N'Q7053148', N'Normophosphatemic familial tumoral calcinosis', N'calcinosis that is characterized by massive periarticular, and seldom visceral, deposition of calcified tumors', N''),
( N'Q7053975', N'Siberian tick typhus', N'Human disease', N''),
( N'Q705906', N'paratyphoid fever', N'bacterial infection caused by one of the three types of Salmonella enterica', N''),
( N'Q7059204', N'neuronal ceroid lipofuscinosis 8 northern epilepsy variant', N'human disease', N''),
( N'Q7068152', N'nuclear moulding', N'', N''),
( N'Q706845', N'Lassa fever', N'viral disease', N''),
( N'Q706952', N'anterior spinal artery syndrome', N'Human disease', N''),
( N'Q7070519', N'deficiency anemia', N'Human disease', N''),
( N'Q7077142', N'Ocular neurosis', N'', N''),
( N'Q707774', N'coronary thrombosis', N'Human disease', N''),
( N'Q7077950', N'odontogenic cyst', N'cyst in the jaw that arises from tissues of tooth development', N''),
( N'Q707816', N'Giant cell arteritis', N'Human disease', N''),
( N'Q707837', N'arteriovenous fistula', N'abnormal, epithelial-lined connection between an artery and vein that is present at the time of birth', N''),
( N'Q7080278', N'Oguchi disease-1', N'human disease', N''),
( N'Q708165', N'neurogenic arthrogryposis multiplex congenita', N'congenital joint contracture in two or more areas of the body', N''),
( N'Q708176', N'arthropathy', N'disease of a joint', N''),
( N'Q7087988', N'Oliver–McFarlane syndrome', N'An autosomal recessive disease characterized by trichomegaly, severe chorioretinal atrophy and multiple pituitary hormone deficiencies that has material basis in homozygous or compound heterozygous mutation in PNPLA6 on 19p13.2.', N''),
( N'Q7088441', N'Olmsted syndrome', N'', N''),
( N'Q709360', N'von Willebrands disease', N'blood-clotting disorder', N''),
( N'Q7098081', N'ophthalmia nodosa', N'Human disease', N''),
( N'Q7098730', N'Opsismodysplasia', N'Opsismodysplasia is a skeletal dysplasia characterized by congenital dwarfism and facial dysmorphism', N''),
( N'Q7098792', N'optic disk drusen', N'Human disease', N''),
( N'Q7098795', N'crater-like holes of optic disc', N'Human disease', N''),
( N'Q7098796', N'optic nerve glioma', N'human disease', N''),
( N'Q7098797', N'Optic nerve hypoplasia', N'human disease', N''),
( N'Q7098798', N'Optic nerve tumor', N'Human disease', N''),
( N'Q7098799', N'optic nerve sheath meningioma', N'Human disease', N''),
( N'Q7098800', N'Optic papillitis', N'Human disease', N''),
( N'Q7099389', N'Oral florid papillomatosis', N'Oral mucosal pathology', N''),
( N'Q7099404', N'oral submucous fibrosis', N'human disease', N''),
( N'Q7100071', N'Orbital apex syndrome', N'', N''),
( N'Q7100076', N'Orbital lymphoma', N'Human disease', N''),
( N'Q7103627', N'ornithine translocase deficiency', N'amino acid metabolic disorder that has material basis in deficiency of ornithine translocase resulting in the accumulation of ammonia in the blood', N''),
( N'Q7106993', N'Oslers sign', N'', N''),
( N'Q7107436', N'tongue disease', N'disease involving the tongue', N''),
( N'Q7107512', N'Ossifying fibromyxoid tumour', N'Human disease', N''),
( N'Q7107615', N'ossifying fibroma', N'bone benign neoplasm that is located in the mouth and results in an overgrowth of gingival tissue due to irritation or trauma', N''),
( N'Q7107617', N'Osteolathyrism', N'collagen cross-linking deficiency brought on by dietary over-reliance on the seeds of Lathyrus sativus', N''),
( N'Q7107618', N'Osteolipochondroma', N'', N''),
( N'Q7107643', N'Osteoporotic bone marrow defect', N'', N''),
( N'Q7108724', N'otic polyp', N'Human disease', N''),
( N'Q7109017', N'otospondylomegaepiphyseal dysplasia', N'osteochondrodysplasia that results from mutations in the COL11A2 gene which results in enlargement of the located in epiphysis in located in hand and located in foot, distinct facial features, platyspondyly and hearing loss', N''),
( N'Q7113244', N'ovarian disease', N'Human disease', N''),
( N'Q7113247', N'Ovarian fibroma', N'A benign neoplasm arising from soft tissue of the ovary. It is characterized by the presence of spindle-shaped fibroblasts.', N''),
( N'Q7113254', N'ovarian serous cystadenoma', N'ovary serous adenoma that has material basis in glandular epithelium, in which cystic accumulations of retained secretions are formed', N''),
( N'Q7118181', N'PAPA syndrome', N'Pyogenic arthritis-pyoderma gangrenosum-acne syndrome is a rare pleiotropic autoinflammatory disorder of childhood, primarily affecting the joints and skin', N''),
( N'Q7118906', N'perivascular epithelioid cell neoplasm', N'Human disease', N''),
( N'Q7123066', N'Pacman dysplasia', N'', N''),
( N'Q712320', N'arthus reaction', N'Human disease', N''),
( N'Q7128425', N'Palmoplantar ectodermal dysplasia', N'', N''),
( N'Q7128426', N'palmoplantar keratosis', N'keratosis characterized by abnormal thickening of the palms and the soles', N''),
( N'Q7130407', N'pancreas disease', N'endocrine system disease that is located in the pancreas', N''),
( N'Q7130412', N'pancreatic neoplasm', N'undifferentiated growth detected in the pancreas', N''),
( N'Q7130420', N'Pancreatic serous cystadenoma', N'human disease', N''),
( N'Q7130423', N'pancreatoblastoma', N'Human disease', N'')
GO