INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q50349818', N'multicentric Castleman disease', N'Castleman disease characterized by systemic inflammatory symptoms, polyclonal lymphoproliferation, cytopenias, and multiple organ system dysfunction caused by a cytokine storm often including interleukin-6', N''),
( N'Q503629', N'osteonecrosis', N'bone death caused when the bone no longer receives blood supply', N''),
( N'Q5037834', N'carbamoyl phosphate synthetase I deficiency disease', N'amino acid metabolic disorder that involves accumulation of ammonia in the blood', N''),
( N'Q5037996', N'Carbon stain', N'', N''),
( N'Q5038165', N'Carcinoma ex-pleomorphic adenoma', N'', N''),
( N'Q5038170', N'carcinosarcoma', N'mixed cell type cancer that has material basis in carcinomatous (epithelial tissue) and sarcomatous (connective tissue) components', N''),
( N'Q5044061', N'carnitine-acylcarnitine translocase deficiency', N'', N''),
( N'Q5044163', N'carnosity', N'abnormal fleshy excrescence or tuberosity', N''),
( N'Q5045550', N'carotidynia', N'', N''),
( N'Q5047506', N'Carvajal syndrome', N'autosomal recessive disease characterized by autosomal recessive inheritance of dilated cardiomyopathy, woolly hair, and keratoderma that has material basis in  homozygous mutation in the DSP gene on chromosome 6p24', N''),
( N'Q504775', N'bladder cancer', N'urinary system cancer that results in malignant growth located in the urinary bladder', N''),
( N'Q504790', N'nephrotic syndrome', N'Human disease', N''),
( N'Q5051442', N'cataphylaxis', N'deterioration of the natural defense system of the body due to an infection', N''),
( N'Q5051575', N'catastrophic illness', N'severe illness requiring prolonged hospitalization or recovery', N''),
( N'Q5051580', N'catastrophic antiphospholipid syndrome', N'human disease', N''),
( N'Q5051865', N'Catel–Manzke syndrome', N'Catel-Manzke syndrome is a rare bone disease characterized by bilateral hyperphalangy and clinodactyly of the index finger typically in association with Pierre Robin sequence (see this term) comprising micrognathia, cleft palate and glossoptosis', N''),
( N'Q5055067', N'Cavernous venous malformation', N'', N''),
( N'Q5062120', N'central nervous system depression', N'medical condition', N''),
( N'Q5062122', N'central nervous system disease', N'nervous system disease that affects either the spinal cord (myelopathy) or brain (encephalopathy) of the central nervous system', N''),
( N'Q5062123', N'Central neurocytoma', N'Human disease', N''),
( N'Q5064098', N'CEDNIK syndrome', N'human disease', N''),
( N'Q5064103', N'intracranial vasospasm', N'Human disease', N''),
( N'Q5064108', N'cerebritis', N'Human disease', N''),
( N'Q5064109', N'Cerebroretinal microangiopathy with calcifications and cysts', N'', N''),
( N'Q5064113', N'cerebrospinal fluid leak', N'injury', N''),
( N'Q5064568', N'Cernunnos deﬁciency', N'Cernunnos-XLF deficiency is a rare form of combined immunodeficiency characterized by microcephaly, growth retardation, and T and B cell lymphopenia', N''),
( N'Q5065301', N'ceruminoma', N'Human disease', N''),
( N'Q5065302', N'ceruminous carcinoma', N'Human disease', N''),
( N'Q5065349', N'cervical polyp', N'cervix disease characterized by a benign polyp on the surface of the cervical canal', N''),
( N'Q506652', N'pyelonephritis', N'Human disease', N''),
( N'Q506659', N'prostatic hypertrophy', N'noncancerous increase in size of the prostate', N''),
( N'Q506680', N'endemic disease', N'epidemiological term describing a disease which is constantly present in a specific area', N''),
( N'Q5073466', N'squamous cell thyroid carcinoma', N'A rapidly growing primary carcinoma of the thyroid gland composed of malignant squamous cells. The clinical course is usually aggressive.', N''),
( N'Q5075435', N'alopecia areata', N'condition in which hair is lost from some or all areas of the body', N''),
( N'Q5090449', N'chemical colitis', N'colitis caused by introduction of various chemicals', N''),
( N'Q5090456', N'chemical eye injury', N'medical condition', N''),
( N'Q5090486', N'Chemical pneumonitis', N'inflammation of the lung caused by aspirating or inhaling irritants', N''),
( N'Q509122', N'avoidant personality disorder', N'personality disorder that is characterized by a pervasive pattern of social inhibition, feelings of inadequacy, extreme sensitivity to negative evaluation, and avoidance of social interaction', N''),
( N'Q5092514', N'senile angioma', N'Human disease', N''),
( N'Q50936730', N'Soemmering ring', N'', N''),
( N'Q509389', N'mastoiditis', N'middle ear disease characterized by an inflammation of the mucosal lining of the mastoid antrum and the mastoid air cell system inside the mastoid process', N''),
( N'Q5097618', N'Chilblain lupus', N'Human disease', N''),
( N'Q5097982', N'childhood leukemia', N'leukemia that occurs in children', N''),
( N'Q510236', N'neurasthenia', N'psychopathological term to denote a condition with symptoms of fatigue, anxiety, headache, heart palpitations, high blood pressure, neuralgia, and depressed mood. also known as effort syndrome', N''),
( N'Q5104520', N'chondrodysplasia Blomstrand type', N'Human disease', N''),
( N'Q5104526', N'chondroid lipoma', N'lipoma that is a deep-seated, firm, yellow tumors that characteristically occur on the legs of women', N''),
( N'Q5104958', N'Chorangiosis', N'', N''),
( N'Q5104959', N'chorioangioma', N'Human disease', N''),
( N'Q5105007', N'chorea gravidarum', N'Human disease', N''),
( N'Q5105211', N'choroid plexus neoplasm', N'cerebral ventricle neoplasm that is located in the plexus located in the ventricles of the brain', N''),
( N'Q511000', N'scleritis', N'Disease of human eye', N''),
( N'Q511097', N'psoriatic arthritis', N'syndrome that occurs in humans with psoriasis who also experience symptoms similar to arthritis', N''),
( N'Q511372', N'Krabbe disease', N'Krabbe disease is a lysosomal disorder that affects the white matter of the central and peripheral nervous systems. It includes infantile, late-infantile/juvenile and adult forms.', N''),
( N'Q5113735', N'Chromatin bridge', N'', N''),
( N'Q5113903', N'chromosomal fragile site', N'', N''),
( N'Q5113966', N'Chronic deciduitis', N'', N''),
( N'Q5113970', N'Chronic diarrhea of infancy', N'functional diarrhea of childhood', N''),
( N'Q5113976', N'Chronic eosinophilic leukemia', N'human disease', N''),
( N'Q5113979', N'chronic leukemia', N'broad type of leukemia; disjoint with acute leukemia', N''),
( N'Q5113985', N'Chronic lymphangitis', N'', N''),
( N'Q5113990', N'Chronic phase chronic myelogenous leukemia', N'initial phase of chronic myeloid leukemia consisting of an relatively indolent period lasting from 4 to 7 years', N''),
( N'Q5113997', N'Chronic progressive lymphedema', N'', N''),
( N'Q5114004', N'chronic traumatic encephalopathy', N'neurodegenerative disease caused by repeated head injuries', N''),
( N'Q511818', N'tetany', N'medical sign consisting of the involuntary contraction of muscles', N''),
( N'Q5118576', N'Chyloderma', N'', N''),
( N'Q512313', N'androgen insensitivity syndrome', N'sex differentiation condition', N''),
( N'Q51250082', N'Zellweger spectrum disorder', N'group of rare autosomal recessive genetic disorders', N''),
( N'Q512942', N'paraphasia', N'language output error commonly associated with aphasia, and characterized by the production of unintended syllables, words, or phrases during the effort to speak', N''),
( N'Q5129816', N'clay-shoveler fracture', N'fracture through the spinous process of a vertebra', N''),
( N'Q51302742', N'caffeinism', N'caffeine overdose', N''),
( N'Q5130609', N'Clear-cell ovarian carcinoma', N'ovarian carcinoma that has material basis in cells with clear cytoplasm and glycogen secreting hob nail cells', N''),
( N'Q5130614', N'kidney clear cell sarcoma', N'kidney sarcoma that has material basis in clear cells that are characterized as cells that look clear when viewed under a microscope', N''),
( N'Q5130798', N'clear cell acanthoma', N'Human disease', N''),
( N'Q5130800', N'clear cell adenocarcinoma', N'adenocarcinoma that derives from epithelial cells which have clear cytoplasm', N''),
( N'Q5130802', N'Clear cell papillary renal cell carcinoma', N'', N''),
( N'Q5134392', N'clipping', N'surgical procedure performed to treat an aneurysm', N''),
( N'Q5134736', N'cloacal exstrophy', N'bladder exstrophy-epispadias-cloacal exstrophy complex that is characterized by a defect in the urethra, bladder and bowel', N''),
( N'Q5135822', N'Clouston syndrome', N'Human disease', N''),
( N'Q5136452', N'clubbed thumb', N'genetic trait', N''),
( N'Q5140809', N'coenzyme Q10 deficiency disease', N'mitochondrial metabolism disease that is characterized by a deficiency of CoQ10 resulting from reduced biosynthesis', N''),
( N'Q5142470', N'Raynaud syndrome', N'medical condition in which spasm of arteries cause episodes of reduced blood flow', N''),
( N'Q5145912', N'collagenopathy, types II and XI', N'', N''),
( N'Q5145914', N'Collagenous spherulosis', N'', N''),
( N'Q5149292', N'Colpocephaly', N'A cephalic disorder involving the disproportionate enlargement of the occipital horns of the lateral ventricles', N''),
( N'Q5150905', N'mixed hyperlipidemia', N'', N''),
( N'Q5150906', N'combined immunodeficiency', N'primary immunodeficiency disease that involves multiple components of the immune system, including both humoral immunity and cell-mediated immunity', N''),
( N'Q515376', N'renal artery obstruction', N'narrowing of one of the renal arteries, most often caused by atherosclerosis or fibromuscular dysplasia', N''),
( N'Q5156399', N'Complement 2 deficiency', N'Human disease', N''),
( N'Q5156400', N'Complement 3 deficiency', N'Human disease', N''),
( N'Q5156409', N'complement deficiency', N'primary immunodeficiency disease that is the result in a mutation of a gene encoding one of the thirty complement system proteins, produced predominantly in liver, which function to defend against infection and produce inflammation', N''),
( N'Q5156568', N'complex and mixed tumor', N'neoplasm composed of at least two distinct cellular populations', N''),
( N'Q5156653', N'Complicated grief disorder', N'pathological (and lasting) reaction to loss', N''),
( N'Q5159188', N'Condensing osteitis', N'Human disease', N''),
( N'Q5160405', N'congenital amegakaryocytic thrombocytopenia', N'thrombocytopenia characterized by a severe reduction in megakaryocyte and platelet numbers that has material basis in homozygous or compound heterozygous mutation in the MPL gene on chromosome 1p34', N''),
( N'Q5160407', N'congenital afibrinogenemia', N'Human disease', N''),
( N'Q5160413', N'congenital secretory chloride diarrhea 1', N'secretory diarrhea that has material basis in mutation in the SLC26A3 gene', N''),
( N'Q5160416', N'congenital cytomegalovirus infection', N'mother-to-child transmission of cytomegalovirus occurring in the prenatal period', N''),
( N'Q5160418', N'congenital disorder of glycosylation type IIc', N'genetic disease', N''),
( N'Q5160420', N'Congenital distal spinal muscular atrophy', N'hereditary condition characterized by muscle wasting', N''),
( N'Q5160422', N'congenital dyserythropoietic anemia', N'congenital hemolytic anemia characterized by ineffective erythropoiesis, and resulting from a decrease in the number of red blood cells (RBCs) in the body and a less than normal quantity of hemoglobin in the blood', N''),
( N'Q5160426', N'congenital dyserythropoietic anemia type IV', N'', N''),
( N'Q5160427', N'congenital epulis', N'Human disease', N''),
( N'Q5160431', N'Congenital fourth nerve palsy', N'human disease', N''),
( N'Q5160434', N'Congenital hearing loss', N'', N''),
( N'Q5160435', N'congenital hemolytic anemia', N'Human disease', N''),
( N'Q5160440', N'congenital hypoplastic anemia', N'Human disease', N''),
( N'Q5160441', N'congenital limb deformities', N'human disease', N''),
( N'Q5160446', N'nonsyndromic congenital nail disorder 7', N'Human disease', N''),
( N'Q5160447', N'congenital melanocytic nevus', N'Human disease', N''),
( N'Q5160450', N'Congenital self-healing reticulohistiocytosis', N'Hashimoto-Pritzker histiocytosis (HPH) is a variant of Langerhans cell histiocytosis (see this term) characterized by multiple disseminated skin lesions (firm, red-brown, painless papulo-nodules)', N''),
( N'Q5160453', N'congenital diarrhea 5 with tufting enteropathy', N'Congenital Tufting Enteropathy is a rare congenital enteropathy presenting with early-onset severe and intractable diarrhea that leads to irreversible intestinal failure', N''),
( N'Q5160454', N'congenital syphilis', N'syphilis that results in a multisystem infection in the fetus via the placenta', N''),
( N'Q5161045', N'conidiobolomycosis', N'Human disease', N''),
( N'Q5161171', N'conjunctival concretion', N'Human disease', N''),
( N'Q5161181', N'conjunctivochalasis', N'Human disease', N''),
( N'Q5162309', N'short-rib thoracic dysplasia 9 with or without polydactyly', N'asphyxiating thoracic dystrophy that has material basis in homozygous or compound heterozygous mutation in the IFT140 gene on chromosome 16p13', N''),
( N'Q5164851', N'Contact stomatitis', N'', N''),
( N'Q516562', N'Mikulicz disease', N'Human disease', N''),
( N'Q5166383', N'Convergence insufficiency', N'Human disease', N''),
( N'Q5168503', N'Copenhagen disease', N'Progressive non-infectious anterior vertebral fusion (PAVF) is an early childhood spinal disorder characterized by the gradual onset of thoracic and/or lumbar spine ankylosis often in conjunction with kyphosis with distinctive radiological features', N''),
( N'Q5169379', N'Cor bovinum', N'massive hypertrophy of the left ventricle of the heart due to volume overload', N''),
( N'Q5169382', N'Cor triatriatum', N'congenital heart defect where the left atrium (cor triatriatum sinistrum) or right atrium (cor triatriatum dextrum) is subdivided by a thin membrane, resulting in three atrial chambers', N''),
( N'Q5171107', N'Cornea plana 1', N'congenital hereditary deformity of the eye surface', N''),
( N'Q5171111', N'corneal perforation', N'', N''),
( N'Q517202', N'de Quervain syndrome', N'inflammation of two tendons that control movement of the thumb and their tendon sheath', N''),
( N'Q5172183', N'coronary aneurysm', N'Human disease', N''),
( N'Q5172184', N'coronary artery anomaly', N'Human disease', N''),
( N'Q5172192', N'coronary occlusion', N'partial or complete obstruction of blood flow in a coronary artery', N''),
( N'Q5172199', N'coronary artery vasospasm', N'Human disease', N''),
( N'Q5173263', N'cortical deafness', N'agnosia that is a loss of the ability to perceive any auditory information but whose hearing is intact', N''),
( N'Q5175170', N'costochondritis', N'Human disease', N''),
( N'Q517782', N'Dactylitis', N'inflammation of an entire digit (a finger or toe)', N''),
( N'Q517856', N'placenta accreta', N'placenta disease that is characterized by an abnormally deep attachment of the placenta, through the endometrium and into the myometrium', N''),
( N'Q5178867', N'Couvelaire uterus', N'Blood from detached placental sitewhich enter into uterine musculature and peritoneal cavity', N''),
( N'Q5181860', N'Cramp fasciculation syndrome', N'', N''),
( N'Q5182126', N'cranial nerve disease', N'neuropathy that is located in one of the twelve cranial nerves', N''),
( N'Q5182134', N'craniofacial disease', N'human disease', N''),
( N'Q5182138', N'craniodiaphyseal dysplasia', N'osteosclerosis that results in increased calcium concentration located in skull which decreases the size of cranium foramina and cervical spinal canal', N''),
( N'Q5182141', N'Craniofrontonasal dysplasia', N'Human disease', N''),
( N'Q5182143', N'craniopagus twins', N'conjoined twins who are fused at the cranium', N''),
( N'Q5182155', N'Craniotabes', N'softening or thinning of the skull in infants and children', N''),
( N'Q5182157', N'Cranio–lenticulo–sutural dysplasia', N'Craniolenticulosutural dysplasia (CLSD), also known as Boyadjiev-Jabs syndrome, is characterized by the specific association of large and late-closing fontanels, hypertelorism, early-onset cataract and mild generalized skeletal dysplasia', N''),
( N'Q5185088', N'cricopharyngeal spasm', N'disease', N''),
( N'Q51881374', N'postvaccinal encephalitis', N'', N''),
( N'Q5189052', N'Crouzonodermoskeletal syndrome', N'autosomal dominant disease characterized by Crouzon-like features, premature synostosis of cranial sutures, and acanthosis nigricans that has material basis in heterozygous missense mutation in the FGFR3 gene on chromosome 4p16', N''),
( N'Q5191403', N'crystal arthropathy', N'Human disease', N''),
( N'Q5194974', N'Currarino syndrome', N'', N''),
( N'Q5196200', N'Cushing ulcer', N'', N''),
( N'Q5196687', N'cutaneous T cell lymphoma', N'non-Hodgkins lymphoma that has material basis in a mutation of T cells', N''),
( N'Q5196693', N'cutaneous diphtheria', N'pyoderma that is a milder form of diphtheria restricted to the skin producing shallow skin ulcers is caused by direct physical contact of individuals infected with Corynebacterium diphtheriae as the bacteria releases the diphtheria toxin', N''),
( N'Q5196694', N'Cutaneous endometriosis', N'Human disease', N''),
( N'Q5196696', N'Cutaneous group B streptococcal infection', N'', N''),
( N'Q5196703', N'cutaneous meningioma', N'Human disease', N''),
( N'Q5198214', N'cyclic hematopoiesis', N'Human disease', N''),
( N'Q5201177', N'cystadenocarcinoma', N'adenocarcinoma that derives from epithelial cells originating in glandular tissue, in which cystic accumulations of retained secretions are formed', N''),
( N'Q5201186', N'cystathioninuria', N'amino acid metabolic disorder characterized by elevated plasma and urinary cystathionine levels that has material basis in homozygous or compound heterozygous mutation in the CTH gene on chromosome 1p31', N''),
( N'Q5201211', N'cystic kidney disease', N'congenital or acquired kidney disorder characterized by the presence of renal cysts', N''),
( N'Q5201212', N'cystic nephroma', N'Human disease', N''),
( N'Q5201216', N'cysticercosis cutis', N'', N''),
( N'Q5201263', N'glandular cystitis', N'A reactive inflammatory disorder affecting the bladder. It is characterized by the development of small cysts in the bladder wall. The cysts are lined by metaplastic glandular cells.', N''),
( N'Q520127', N'periodontitis', N'human disease of the tissues surrounding the teeth', N''),
( N'Q5203266', N'D-glyceric acidemia', N'gene has been mapped to 3p21', N''),
( N'Q5203306', N'D-bifunctional protein deficiency', N'human disease', N''),
( N'Q521863', N'Beckwith-Wiedemann syndrome', N'syndrome characterized by overgrowth (macrosomia), an increased risk of childhood cancer and congenital malformations', N''),
( N'Q5220984', N'Danon disease', N'Human disease', N''),
( N'Q523893', N'ichthyosis', N'skin disease in which dry, scaly skin accumulates', N''),
( N'Q524353', N'erythromelalgia', N'Human disease', N''),
( N'Q525075', N'hamartoma', N'non-cancerous growth, made up of an abnormal mixture of cells and tissues normally found in the area of the body', N''),
( N'Q5251081', N'Defatting', N'medical condition', N''),
( N'Q5251124', N'Defective interfering particle', N'', N''),
( N'Q5254539', N'delta thalassemia', N'type of thalassemia', N''),
( N'Q525642', N'DiGeorge syndrome', N'T cell deficiency disease that is the result of a large deletion of chromosome 22, which includes the DGS gene needed for development of the thymus and related glands with subsequent lack of T-cell production', N''),
( N'Q5259438', N'Dental subluxation', N'', N''),
( N'Q5259533', N'dentin dysplasia', N'teeth hard tissue disease characterized by presence of normal enamel but atypical dentin with abnormal pulpal morphology', N''),
( N'Q5259573', N'Dentomandibular sensorimotor dysfunction', N'', N''),
( N'Q5259645', N'denture stomatitis', N'lip disease', N''),
( N'Q52601023', N'vulvar neoplasm', N'neoplasm of the vulva', N''),
( N'Q5261301', N'derailment', N'thought disorder in psychiatry', N''),
( N'Q5262702', N'dermatopathia pigmentosa reticularis', N'human disease', N''),
( N'Q5262715', N'dermatosis papulosa nigra', N'Human disease', N''),
( N'Q5264831', N'desmoplastic small-round-cell tumor', N'aggressive, rare cancer', N''),
( N'Q5264836', N'Desmosterolosis', N'Desmosterolosis is a very rare sterol biosynthesis disorder characterized by multiple congenital anomalies, failure to thrive, and intellectual disability, with elevated levels of desmosterol', N''),
( N'Q5265029', N'desquamative interstitial pneumonia', N'idiopathic interstitial pneumonia that is characterized by the accumulation of bronchiolocentric alveolar macrophages in alveolar spaces and interstitial inflammation and involves mild bronchiolar fibrosis and chronic inflammation', N''),
( N'Q5272095', N'Diastasis symphysis pubis', N'separation of normally joined pubic bones', N''),
( N'Q5272105', N'diastolic heart failure', N'heart failure caused by abnormal myocardial relaxation during diastole', N''),
( N'Q5274956', N'dientamoebiasis', N'A parasitic protozoa infectious disease that involves infection of the large intestine by a protozoan parasite Dientamoeba fragilis. The symptoms include diarrhea, stomach pain and cramping, loss of appetite and weight, nausea, and fatigue.', N''),
( N'Q5275410', N'diffuse cutaneous mastocytosis', N'Human disease', N''),
( N'Q5275412', N'Diffuse epidermolytic palmoplantar keratoderma', N'human disease', N''),
( N'Q5275415', N'Diffuse infiltrative lymphocytosis syndrome', N'Human disease', N''),
( N'Q5275417', N'Diffuse leprosy of Lucio and Latapí', N'clinical variety of lepromatous leprosy', N''),
( N'Q5276448', N'dihydropyrimidine dehydrogenase deficiency', N'purine-pyrimidine metabolic disorder that is an autosomal recessive metabolic disorder in which there is absent or significantly decreased activity of dihydropyrimidine dehydrogenase, an enzyme involved in the metabolism of uracil and thymine', N''),
( N'Q5280135', N'Dipygus', N'severe congenital deformity where the body axis forks left and right partway along the torso with the pelvis and legs duplicated', N''),
( N'Q5282160', N'Disequilibrium', N'', N''),
( N'Q5282510', N'writing disorder', N'human disease', N''),
( N'Q5282519', N'calcium metabolism disease', N'Disorders in the processing of calcium in the body: its absorption, transport, storage, and utilization', N''),
( N'Q5282748', N'Disseminated disease', N'', N''),
( N'Q5282749', N'disseminated superficial actinic porokeratosis', N'Human disease', N''),
( N'Q5282840', N'Distal hereditary motor neuropathies', N'Human disease', N''),
( N'Q5282843', N'distal muscular dystrophy', N'group of genetic disorders characterized by progressive muscular atrophy and muscle weakness beginning in the hands, the legs, or the feet', N''),
( N'Q5282845', N'autosomal recessive distal spinal muscular atrophy 1', N'human disease', N''),
( N'Q5283757', N'diurnal enuresis', N'functional daytime urinary incontinence', N''),
( N'Q5283947', N'diversion colitis', N'colitis caused by diversion of the fecal stream due to complication of ileostomy or colostomy', N''),
( N'Q5289050', N'Dolichol kinase deficiency', N'human disease', N''),
( N'Q5289085', N'dolichostenomelia', N'', N''),
( N'Q5290299', N'Dominant dystrophic epidermolysis bullosa', N'human disease', N''),
( N'Q529292', N'anencephaly', N'absence of a major portion of the brain, skull, and scalp that occurs during embryonic development', N''),
( N'Q530142', N'FG syndrome', N'disease', N''),
( N'Q5309747', N'dryness', N'medical condition in which there is a decrease in normal lubrication of the skin or mucous membranes', N''),
( N'Q531012', N'congenital hypothyroidism', N'hypothyroidism that is present at birth', N''),
( N'Q531019', N'aortic valve stenosis', N'aortic valve disease that has physical basis in incomplete opening of the aortic valve', N''),
( N'Q5315596', N'Dunnigan familial partial lipodystrophy', N'', N''),
( N'Q5319350', N'dysbaric osteonecrosis', N'ischemic bone disease caused by decompression bubbles in bone', N''),
( N'Q5319366', N'dyschromatosis symmetrica hereditaria', N'pigmentation disease characterized by progressively pigmented and depigmented macules, often mixed in a reticulate pattern, concentrated on the dorsal extremities', N''),
( N'Q5319369', N'dyschromatosis universalis hereditaria', N'pigmentation disease characterized by reticulate hyper- and hypo-pigmentated macules in a generalized distribution', N''),
( N'Q5319554', N'dysplastic nevus syndrome', N'Human skin disease', N''),
( N'Q532158', N'Pediculus humanus capitis infestation', N'Human disease', N''),
( N'Q5322531', N'EAST syndrome', N'SeSAME syndrome is characterized by seizures, sensorineural deafness, ataxia, intellectual deficit, and electrolyte imbalance (hypokalemia, metabolic alkalosis, and hypomagnesemia)', N''),
( N'Q5322931', N'EEM syndrome', N'', N''),
( N'Q5325633', N'ear disease', N'human disease', N''),
( N'Q5326887', N'early myoclonic encephalopathy', N'Human disease', N''),
( N'Q5334252', N'ectomesenchymoma', N'human disease', N''),
( N'Q5334259', N'ectoparasitism', N'parasitic disease caused by organisms that live primarily on the surface of the host', N''),
( N'Q5334295', N'ectopic thymus', N'Human disease', N''),
( N'Q5334319', N'Ectrodactyly–ectodermal dysplasia–cleft syndrome', N'autosomal dominant disease characterized by ectrodactyly, ectodermal dysplasia, and orofacial clefts (cleft lip-palate)', N''),
( N'Q5340515', N'systemic scleroderma', N'scleroderma that is characterized by fibrosis (or hardening) of the skin and major organs, as well as vascular alterations, and autoantibodies', N''),
( N'Q535364', N'Angelman syndrome', N'Genetic condition in humans', N''),
( N'Q5358728', N'Griscelli syndrome type 1', N'A Griscelli syndrome characterized by silvery gray sheen of the hair, hypopigmentation of the skin and neurological impairment without immunodeficiency that has material basis in mutations in the MYO5A gene on chromosome 15q21.2.', N''),
( N'Q535876', N'Sheehans syndrome', N'human disease', N''),
( N'Q5359413', N'elephantiasis nostras', N'', N''),
( N'Q5360758', N'Micromastia', N'human disease', N''),
( N'Q536269', N'phaeochromocytoma', N'type of neuroendocrine tumor', N''),
( N'Q53660452', N'primary mediastinal B-cell lymphoma', N'diffuse large B-cell lymphoma that is is characterized by a diffuse proliferation of medium to large B-cells associated with sclerosis', N''),
( N'Q53660493', N'Alwadei syndrome', N'autosomal recessive non-syndromic intellectual disability that has material basis in an autosomal recessive mutation of the RUSC2 gene on chromosome 9p13', N''),
( N'Q5370230', N'embryoma', N'carcinosarcoma and embryonal cancer that is located in embryonic tissue and results in a mass of rapidly growing cells', N''),
( N'Q5370233', N'embryonal rhabdomyosarcoma', N'rhabdomyosarcoma with mesenchymally-derived malignant cells resembling the developing skeletal muscle of the embryo', N''),
( N'Q5375191', N'dental enamel hypoplasia', N'Human disease', N''),
( N'Q5375429', N'enchondromatosis', N'human disease', N''),
( N'Q5376225', N'endocardial fibroelastosis', N'endocardium disease that is characterized by endocardium becoming massively fibrosed and thickened wih elastic tissue resulting in a restrictive cardiomyopathy.', N''),
( N'Q5376307', N'Endocrine bone disease', N'', N''),
( N'Q5376333', N'endogenous depression', N'mental depression that is characterized by a dysregulation of the endogenous opioid system and not of the monaminergic system', N''),
( N'Q5376362', N'Endometrial intraepithelial neoplasia', N'', N''),
( N'Q5376363', N'endometrial stromal sarcoma', N'human disease', N''),
( N'Q5376366', N'Endometrioid tumor', N'Human disease', N''),
( N'Q5376367', N'endometriosis of ovary', N'Human disease', N''),
( N'Q5376410', N'endosalpingiosis', N'Human disease', N''),
( N'Q5376444', N'endothrix infectious disease', N'tinea capitis that results in fungal infection located in hair, has material basis in Ascomycota fungi that belong to a group called dermatophytes, which produce arthroconidia within the hair shaft only', N''),
( N'Q5376565', N'Endovascular papillary hemangioendothelioma', N'An intermediate, rarely metastasizing blood vessel neoplasm. It is characterized by the presence of lymphatic-like vascular channels and papillary endothelial proliferation.', N''),
( N'Q5380222', N'enterocele', N'Human disease', N''),
( N'Q5381904', N'Eosinophilic folliculitis', N'', N''),
( N'Q5382100', N'Ependymal tumor', N'malignant glioma that is derived from ependymal cells, a type of glial cell, located in ventricle lining within the central part of the brain', N''),
( N'Q5382842', N'Epidermal nevus syndrome', N'a rare neurocutaneous syndrome', N''),
( N'Q5382846', N'epidermolysis bullosa herpetiformis', N'Human disease', N''),
( N'Q5382847', N'Epidermolysis bullosa simplex of Ogna', N'Human disease', N''),
( N'Q5382848', N'Epidermolysis bullosa simplex with mottled pigmentation', N'Epidermolysis bullosa simplex with mottled pigmentation (EBS-MP) is a basal subtype of epidermolysis bullosa simplex (EBS, see this term) characterized by generalized blistering with mottled or reticulate brown pigmentation', N''),
( N'Q5382849', N'epidermolysis bullosa simplex with muscular dystrophy', N'autosomal recessive disease characterized early childhood onset of progressive muscular dystrophy and blistering skin changes and that has material basis in homozygous or compound heterozygous mutation in the PLEC gene on chromosome 8q24', N''),
( N'Q5383691', N'Epithelial-myoepithelial carcinoma', N'Human disease', N''),
( N'Q5383708', N'epithelioid sarcoma', N'human disease', N''),
( N'Q5383711', N'Epithelioma cuniculatum', N'Human disease', N''),
( N'Q538432', N'synovitis', N'connective tissue disease that results in inflammation located in synovial membrane that lines a synovial joint which causes pain and swelling', N''),
( N'Q53926008', N'Nipah Virus Infection', N'disease caused by Nipah virus', N''),
( N'Q539465', N'necrotizing ulcerative gingivitis', N'Human disease', N''),
( N'Q539491', N'angiodysplasia', N'vascular disease that is characterized as a small vascular malformation of the gut', N''),
( N'Q53951449', N'infantile parkinsonism-dystonia', N'Infantile dystonia-parkinsonism (IPD) is an extremely rare inherited neurological syndrome that presents in early infancy with hypokinetic parkinsonism and dystonia and that can be fatal', N''),
( N'Q5396391', N'erythema elevatum diutinum', N'vasculitis characterised by red, purple, brown or yellow papules (raised spot), plaques, or nodules, found on the backs of the hands, other extensor surfaces overlying joints, and on the buttocks', N''),
( N'Q5396477', N'spinocerebellar ataxia type 34', N'Human disease', N''),
( N'Q5396513', N'Erythrotelangiectatic rosacea', N'', N''),
( N'Q539681', N'angiomyolipoma', N'cell type benign neoplasm that from perivascular epithelioid cells', N''),
( N'Q5398631', N'esophageal candidiasis', N'candidiasis that involves fungal infection of the esophagus by Candida albicans in immunocompromised people, resulting in lesions, bleeding, painful swallowing and substernal pain', N''),
( N'Q5401847', N'Estrogen insensitivity syndrome', N'', N''),
( N'Q5405504', N'linear IgA bullous dermatosis', N'Human disease', N''),
( N'Q540571', N'fibromyalgia', N'chronic disorder of unknown etiology characterized by pain, stiffness, and tenderness', N''),
( N'Q540850', N'orchitis', N'inflammation of the testes', N''),
( N'Q5409708', N'phacolytic glaucoma', N'Human disease', N''),
( N'Q541244', N'hereditary spherocytosis', N'congenital hemolytic anemia characterized by the production of red blood cells with a sphere shape, rather than the normal biconcave disk shape', N''),
( N'Q541852', N'uncombable hair syndrome', N'rare scalp hair shaft dysplasia', N''),
( N'Q5419654', N'Excited delirium', N'', N''),
( N'Q5420699', N'ectothrix infectious disease', N'Human disease', N''),
( N'Q5422046', N'External resorption', N'Human disease', N''),
( N'Q5422194', N'extracutaneous mastocytoma', N'Human disease', N''),
( N'Q5422284', N'Extravasation of urine', N'', N''),
( N'Q5432926', N'Familial British dementia', N'', N''),
( N'Q5432930', N'Familial aortic dissection', N'', N''),
( N'Q5432932', N'familial atrial fibrillation', N'atrial fibrillation that has material basis in autosomal dominant inheritance of the familial atrial fibrillation (ATFB) genes', N''),
( N'Q5432934', N'familial dysalbuminemic hyperthyroxinemia', N'', N''),
( N'Q5432935', N'familial encephalopathy with neuroserpin inclusion bodies', N'human disease', N''),
( N'Q5432936', N'exudative vitreoretinopathy', N'retinal vascular disease characterized by the prevention of blood vessel formation at the edges of the retina and the hemorrhage of the blood vessels in the retina', N''),
( N'Q5432945', N'Familial partial lipodystrophy', N'lipodystrophy characterized by abnormal subcutaneous adipose tissue distribution beginning in late childhood or early adult life', N''),
( N'Q5432946', N'familial progressive hyperpigmentation', N'The rare congenital Disease', N''),
( N'Q5432947', N'Familial male-limited precocious puberty', N'rare disease', N''),
( N'Q543517', N'juvenile myoclonic epilepsy', N'adolescence-adult electroclinical syndrome that is characterized by brief, involuntary twitching of a muscle or a group of muscles (myoclonus) early in the morning with onset between 12 and 18 years', N''),
( N'Q5437240', N'fat necrosis', N'form of necrosis characterized by the action upon fat by digestive enzymes', N''),
( N'Q5437988', N'Fatty-acid metabolism disorder', N'', N''),
( N'Q544006', N'anxiety disorder', N'cognitive disorder with an excessive, irrational dread of everyday situations', N''),
( N'Q5441566', N'Feingold syndrome', N'autosomal dominant disease characterized by variable combinations of microcephaly, limb malformations, esophageal and duodenal atresias, and learning disability/mental retardation', N''),
( N'Q5442760', N'female reproductive system disease', N'reproductive system disease that impairs the ability to reproduce and is located in the uterus, vagina, cervix, ovaries or fallopian tubes', N''),
( N'Q5445898', N'fetal disease', N'human disease', N''),
( N'Q5445915', N'Fetal thrombotic vasculopathy', N'', N''),
( N'Q5446449', N'Fibrinolysis syndrome', N'', N''),
( N'Q5446459', N'Fibrocartilaginous mesenchymoma of bone', N'', N''),
( N'Q5446462', N'fibroepithelial neoplasms', N'Human disease', N''),
( N'Q5446465', N'Fibrofolliculoma', N'', N''),
( N'Q5446468', N'Fibrolamellar hepatocellular carcinoma', N'A hepatocellular carcinoma characterized microscopically by laminated fibrous layers interspersed between the tumour cells. The polygonal, deeply eosinophilic tumor cells arise in non-cirrhotic livers.', N''),
( N'Q5446477', N'fibrosclerosis of breast', N'Human disease', N''),
( N'Q545403', N'hh blood group', N'rare blood type', N''),
( N'Q545408', N'anhidrosis', N'Human disease', N''),
( N'Q5454124', N'first arch syndrome', N'', N''),
( N'Q54553070', N'mixed phenotype acute leukemia', N'An acute leukemia in which the blasts lack sufficient evidence to classify as myeloid or lymphoid or they have morphologic and/or immunophenotypic characteristics of both myeloid and lymphoid cells. (WHO, 2001)', N''),
( N'Q5458521', N'Fleischers syndrome', N'Mammo-renal syndrome', N''),
( N'Q5459411', N'Flinders Island spotted fever', N'A spotted fever that has material basis in Rickettsia honei, which is transmitted by cayenne ticks (Amblyomma cajennense). The infection has symptom mild spotted fever, has symptom eschar and has symptom adenopathy.', N''),
( N'Q5459852', N'Floating-Harbor syndrome', N'Floating-Harbor syndrome is a genetic developmental disorder characterized by facial dysmorphism, short stature with delayed bone age, and expressive language delay', N''),
( N'Q5463653', N'Flynn–Aird syndrome', N'', N''),
( N'Q5463847', N'focal dermal hypoplasia', N'form of ectodermal dysplasia', N''),
( N'Q5463849', N'focal facial dermal dysplasia', N'', N''),
( N'Q5464172', N'Foix–Alajouanine syndrome', N'', N''),
( N'Q5464647', N'follicle-stimulating hormone insensitivity', N'', N''),
( N'Q5464657', N'follicular dendritic cell sarcoma', N'dendritic cell sarcoma cancer that effects the follicular dendritic cells', N''),
( N'Q5464661', N'Follicular large-cell lymphoma', N'', N''),
( N'Q5464665', N'follicular thyroid cancer', N'thyroid carcinoma that has material basis in follicular cells', N''),
( N'Q5473408', N'mucopolysaccharidosis IX', N'mucopolysaccharidosis characterized by a deficiency in hyaluronidase', N''),
( N'Q5474322', N'sex cord-gonadal stromal tumor', N'reproductive organ cancer that is located in the sex cord-derived tissues of the ovary and testis', N''),
( N'Q548213', N'neural tube defect', N'congenital disorder of the nervous system', N''),
( N'Q548719', N'aniridia', N'Human disease', N''),
( N'Q54875151', N'knee dislocation', N'Disruption of the joint between the tibia and the femur', N''),
( N'Q548913', N'aniseikonia', N'Human disease', N''),
( N'Q548984', N'dentinogenesis imperfecta', N'Human disease', N''),
( N'Q549229', N'varicocele', N'abnormal enlargement of the pampiniform venous plexus in the scrotum', N''),
( N'Q5492304', N'Frank–ter Haar syndrome', N'', N''),
( N'Q5493754', N'Frasier syndrome', N'Human disease', N''),
( N'Q549534', N'osteosarcoma', N'bone cancer that is located in bone that has material basis in cells of mesenchymal origin', N''),
( N'Q550061', N'Endothelial dysfunction', N'systemic pathological state of the endothelium', N''),
( N'Q550455', N'retinal disease', N'eye disease that is located in the retina', N''),
( N'Q5506384', N'fruit allergy', N'type of food allergy caused by fruit', N''),
( N'Q5509166', N'Fungal folliculitis', N'fungal infection', N''),
( N'Q5509169', N'fungal meningitis', N'meningitis that has material basis in a fungal infection', N''),
( N'Q5509198', N'funisitis', N'connective tissue disease that is an inflammation of the connective tissue of the umbilical cord', N''),
( N'Q551085', N'myelitis', N'spinal cord disease that is characterized by inflammation of the white matter or gray matter of the spinal cord', N''),
( N'Q5512866', N'GAPO syndrome', N'GAPO syndrome is a multiple congenital anomalies (MCA) syndrome involving connective tissue characterized by Growth retardation, Alopecia, Pseudoanodontia and Ocular manifestations', N''),
( N'Q5513688', N'Tay-Sachs disease AB variant', N'GM2 gangliosidosis, AB variant is an extremely rare, severe genetic disorder characterized by progressive neurological decline due to ganglioside activator deficiency', N''),
( N'Q5513690', N'gangliosidosis GM1', N'lysosomal storage disease', N''),
( N'Q5513691', N'GM2 gangliosidosis', N'human disease', N''),
( N'Q5514398', N'GRACILE syndrome', N'inherited metabolic disease', N''),
( N'Q5517825', N'galactokinase deficiency', N'galactosemia that involves an accumulation of galactose and galactitol secondary to the decreased conversion of galactose to galactose-1-phosphate by galactokinase', N''),
( N'Q5518905', N'gallbladder disease', N'gastrointestinal system disease that is located in the gallbladder', N''),
( N'Q5521142', N'Gangliocytic paraganglioma', N'', N''),
( N'Q5521151', N'ganglioneuroblastoma', N'Human disease', N''),
( N'Q552348', N'eclampsia', N'pre-eclampsia characterized by the presence of seizures', N''),
( N'Q5524075', N'Garrods tetrad', N'', N''),
( N'Q5524429', N'Gartners duct cyst', N'', N''),
( N'Q5526789', N'gastric outlet obstruction', N'Human disease', N''),
( N'Q5526827', N'Gastrocutaneous syndrome', N'human disease', N''),
( N'Q5526839', N'gastrointestinal system cancer', N'organ system cancer located in gastrointestinal tract that is manifested in organs of the gastrointestinal system', N''),
( N'Q5526844', N'Gastrojejunocolic fistula', N'', N''),
( N'Q5530367', N'Gelastic seizure', N'rare type of seizure that involves a sudden burst of energy, usually in the form of laughing or crying', N''),
( N'Q5532415', N'generalized epilepsy', N'epilepsy syndrome that is characterised by generalised seizures with no apparent cause which arise from independent foci or epileptic circuits that involve the whole brain', N''),
( N'Q5532463', N'Generalized atrophic benign epidermolysis bullosa', N'', N''),
( N'Q5532470', N'Generalized epidermolysis bullosa simplex', N'epidermolysis bullosa simplex that is characterized by widespread blisters that appear at birth or in early infancy', N''),
( N'Q5532491', N'Generalized lymphadenopathy', N'generalised lymphadenites', N''),
( N'Q5532501', N'Generalized pustular psoriasis', N'human disease', N''),
( N'Q5533166', N'geniculate ganglionitis', N'Human disease', N''),
( N'Q5533230', N'Genital leiomyoma', N'Human disease', N''),
( N'Q5533246', N'Genitopatellar syndrome', N'', N''),
( N'Q5533828', N'genuphobia', N'fear of ones own knees or someone elses knees or the act of kneeling', N''),
( N'Q55345705', N'deafness-enamel hypoplasia-nail defects syndrome', N'', N''),
( N'Q5548621', N'geotrichosis', N'opportunistic mycosis that has material basis in Galactomyces geotrichum, results in systemic infection in immunocompromised people', N''),
( N'Q5552374', N'Gerodermia osteodysplastica', N'human disease', N''),
( N'Q5556985', N'Ghosal hematodiaphyseal dysplasia', N'Ghosal hematodiaphyseal dysplasia syndrome (GHDD) is a rare disorder characterized by increased bone density (predominantly diaphyseal) and aregenerative corticosteroid-sensitive anemia', N''),
( N'Q5558010', N'Nicolaides–Baraitser syndrome', N'', N''),
( N'Q5558337', N'Giant-cell carcinoma of the lung', N'lung carcinoma that is located in large undifferentiated cells', N''),
( N'Q5558486', N'Giant platelet disorder', N'', N''),
( N'Q555868', N'olecranon bursitis', N'Human disease', N''),
( N'Q5560212', N'Gigantiform cementoma', N'instance of ossifying fibroma (disease) that is caused by an inherited modification of the individuals genome', N''),
( N'Q5560415', N'pulmonary alveolar microlithiasis', N'human disease', N''),
( N'Q55607503', N'Cholesterol crystal', N'', N''),
( N'Q55610804', N'Emberger syndrome', N'Deafness - lymphedema - leukemia is a very rare, serious syndromic genetic disorder characterized by primary lymphedema, immunodeficiency, and hematological disorders', N''),
( N'Q55624965', N'Neotenic complex syndrome', N'Congenital extreme form of developmental delay and neoteny', N''),
( N'Q556281', N'uterine fibroid', N'uterine benign neoplasm derived from the smooth muscle layer of the uterus', N''),
( N'Q55629168', N'Pascual-Castroviejo syndrome', N'Cerebro-facio-thoracic dysplasia or Pascual-Castroviejo syndrome type 1 is a rare syndrome characterized by facial dysmorphism, intellectual deficit and costovertebral abnormalities', N''),
( N'Q5563106', N'gingival disease', N'human disease', N''),
( N'Q55647711', N'Chronic airway-digestive inflammatory disease', N'', N''),
( N'Q5566617', N'glandular rosacea', N'', N''),
( N'Q5567200', N'Glassy cell carcinoma of the cervix', N'', N''),
( N'Q5571213', N'glomangiosarcoma', N'Human disease', N''),
( N'Q5571234', N'glomeruloid hemangioma', N'Human disease', N''),
( N'Q5571239', N'glomerulosclerosis', N'glomerulonephritis that is characterized by hardening of the glomerulus in the kidney', N''),
( N'Q5572316', N'Glucocorticoid deficiency 1', N'human disease', N''),
( N'Q5572341', N'Glucose-galactose malabsorption', N'Glucose-galactose malabsorption (GGM) is a very rare, potentially lethal, genetic metabolic disease characterized by impaired glucose-galactose absorption resulting in severe watery diarrhea and dehydration with onset inthe neonatal period', N''),
( N'Q5572467', N'Glutathione synthetase deficiency', N'human disease', N''),
( N'Q5572555', N'glycerol kinase deficiency', N'Human disease', N''),
( N'Q5572606', N'Glycogen storage disease type 0', N'human disease', N''),
( N'Q5572613', N'Glycogen storage disease type XI', N'Fanconi-Bickel glycogenosis (FBG) is a rare glycogen storage disease characterized by hepatorenal glycogen accumulation, severe renal tubular dysfunction and impaired glucose and galactose metabolism', N''),
( N'Q557429', N'acute disease', N'disease with a rapid onset and/or a short course', N''),
( N'Q557552', N'ankyloglossia', N'congenital disorder of digestive system', N''),
( N'Q5575547', N'Goblet cell carcinoid', N'', N''),
( N'Q55780373', N'diaphyseal medullary stenosis-bone malignancy syndrome', N'', N''),
( N'Q55784046', N'multisystemic smooth muscle dysfunction syndrome', N'', N''),
( N'Q55784868', N'progeroid features-hepatocellular carcinoma predisposition syndrome', N'human disease', N''),
( N'Q55784997', N'Lamb-Shaffer syndrome', N'human disease', N''),
( N'Q558070', N'pelvic inflammatory diseases', N'infection of uterus, fallopian tubes, ovaries or the inner surface of pelvis', N''),
( N'Q558077', N'Williams-Beuren syndrome', N'neurodevelopmental disorder', N''),
( N'Q5581314', N'gonadal tissue neoplasms', N'human disease', N''),
( N'Q5581320', N'gonadoblastoma', N'cell type benign neoplasm that is composed of a mixture of gonadal elements', N''),
( N'Q5581327', N'Gonadotropin-resistant ovary syndrome', N'primary or secondary amenorrhea and is resistant to exogenous gonadotropin stimulation', N''),
( N'Q5582043', N'Gonococcemia', N'', N''),
( N'Q558230', N'cholesteatoma', N'keratosis characterized by keratinizing squamous epithelium located in middle ear and/or mastoid, subepithelial connective tissue and by the progressive accumulation of keratin debris with or without surrounding inflammatory reaction', N''),
( N'Q558404', N'alcoholic liver disease', N'', N''),
( N'Q558623', N'Aphakia', N'disorder of lens', N''),
( N'Q559082', N'chondrocalcinosis', N'arthritis that has material basis in the accumulation of salt crystals located in joint', N''),
( N'Q5592612', N'Graham-Little syndrome', N'', N''),
( N'Q5593572', N'Gram-negative rosacea', N'', N''),
( N'Q5596720', N'corneal granular dystrophy', N'Human disease', N''),
( N'Q5596833', N'Granulomatous prostatitis', N'', N''),
( N'Q5596834', N'granulomatous amebic encephalitis', N'Human disease', N''),
( N'Q5596838', N'Granulomatous mastitis', N'', N''),
( N'Q5598270', N'gray matter heterotopia', N'neuronal migration disorder characterised by clumps of ectopic neurones in the gray matter', N''),
( N'Q5598273', N'Gray platelet syndrome', N'rare congenital autosomal recessive bleeding disorder caused by a reduction or absence of alpha-granules in blood platelets', N''),
( N'Q5598281', N'gray zone lymphoma', N'lymphoma that is characterized by having cellular features of both classic Hodgkins lymphomas and large B-cell Lymphomas', N''),
( N'Q56014413', N'congenital dyserythropoietic anemia type I', N'Congenital dyserythropoietic anemiatype I (CDA I) is a hematologic disorder of erythropoiesis characterized by moderate to severe macrocytic anemia occasionally associated with limb or nail deformities and scoliosis', N''),
( N'Q5603286', N'Green Tobacco Sickness', N'type of nicotine poisoning', N''),
( N'Q560337', N'Tay-Sachs disease', N'disease marked by accumulation of G2 gangliosides due to hexosaminidase A deficiency', N''),
( N'Q560456', N'otomycosis', N'human disease', N''),
( N'Q5609501', N'Grinker myelinopathy', N'', N''),
( N'Q5609615', N'Griscelli syndrome type 2', N'A Griscelli syndrome characterized by silvery gray sheen of the hair, hypopigmentation of the skin and immunodeficiency with or without neurologic impairment that has material basis in mutation in the RAB27A gene on chromosome 15q21.3.', N''),
( N'Q5609617', N'Griscelli syndrome type 3', N'Griscelli syndrome characterized by isolated silvery gray sheen of the hair and hypopigmentation of the skin that has material basis in mutation in the MLPH or MYO5A genes', N''),
( N'Q5609817', N'tinea pedis', N'Foot disease', N''),
( N'Q5610516', N'gross pathology', N'', N''),
( N'Q5613758', N'guanidinoacetate methyltransferase deficiency', N'Human disease', N''),
( N'Q5629424', N'HEC syndrome', N'', N''),
( N'Q56297474', N'Multicentric carpotarsal osteolysis syndrome', N'', N''),
( N'Q5629813', N'HIV-associated lipodystrophy', N'Human disease', N''),
( N'Q5639341', N'Haim–Munk syndrome', N'Haim-Munk syndrome (HMS) is characterized by palmoplantar hyperkeratosis, severe early-onset periodontitis, onychogryposis, pes planus, arachnodactyly and acroosteolysis', N''),
( N'Q5639509', N'Hair follicle nevus', N'', N''),
( N'Q5643382', N'Halogenoderma', N'', N''),
( N'Q5643617', N'Haltlose personality disorder', N'proposed personality disorder', N''),
( N'Q567576', N'nominal aphasia', N'type of aphasia that causes problems with recalling words or names', N''),
( N'Q567694', N'anorchia', N'human disease', N''),
( N'Q567820', N'Alexander disease', N'congenital disorder of nervous system', N''),
( N'Q567869', N'anosognosia', N'Unawareness of ones own illness, symptoms or impairments', N''),
( N'Q56792371', N'Repeated Implantation Failure', N'term that refers to the failure of the embryo to implant onto the side of the uterus wall following IVF treatment', N''),
( N'Q568321', N'anoxia', N'medical condition', N''),
( N'Q5685180', N'hawkinsinuria', N'disease', N''),
( N'Q568865', N'cherubism', N'Human disease', N''),
( N'Q5692507', N'Heart valve dysplasia', N'human disease', N''),
( N'Q5696358', N'focal epithelial hyperplasia', N'viral infectious disease that results in infection located in mouth, has material basis in human papillomavirus (types 13 or 32)', N''),
( N'Q570875', N'in situ pulmonary adenocarcinoma', N'lung cancer that derives from the distal bronchioles or alveoli that initially exhibit a specific non-invasive growth pattern', N''),
( N'Q5710984', N'hemangioendothelioma', N'group of vascular neoplasms', N''),
( N'Q5711181', N'Hematopoietic ulcer', N'', N''),
( N'Q5711647', N'Hemihyperplasia–multiple lipomatosis syndrome', N'human disease', N''),
( N'Q5712491', N'Hemoglobin Lepore syndrome', N'', N''),
( N'Q5712565', N'hemorrhagic cystitis', N'Inflammation of the bladder resulting in bloody urine', N''),
( N'Q5714797', N'Hennekam syndrome', N'human disease', N''),
( N'Q57157864', N'Early pregnancy bleeding', N'', N''),
( N'Q572111', N'anterograde amnesia', N'loss of the ability to create new memories after the onset of amnesia', N''),
( N'Q572169', N'Seckel syndrome', N'autosomal recessive disease characterized by intrauterine growth retardation and postnatal dwarfism with microcephaly and intellectual disability', N''),
( N'Q572695', N'Eisenmengers syndrome', N'fetal heart defect', N''),
( N'Q5731687', N'hepatic veno-occlusive disease', N'hepatic vascular disease that is characterized by obstruction of some of the small veins of the liver', N''),
( N'Q5731794', N'Hepatosplenic T-cell lymphoma', N'', N''),
( N'Q5737835', N'Hereditary diffuse leukoencephalopathy with spheroids', N'', N''),
( N'Q5737853', N'Hereditary inclusion body myopathy', N'', N''),
( N'Q5737872', N'hereditary pyropoikilocytosis', N'An autosomal recessive inherited severe hemolytic anemia. It is a subtype of hereditary elliptocytosis and is characterized by partial spectrin deficiency.', N''),
( N'Q574329', N'anthracosis', N'human disease', N''),
( N'Q5743696', N'herpetic whitlow', N'painful blister of the periungual skin that is caused by herpes simplex virus type 1 or 2', N''),
( N'Q574406', N'Bartholins duct cyst', N'cyst in a blocked Bartholins gland', N''),
( N'Q574694', N'pseudomyxoma peritonei', N'appendix cancer that is characterized by progressive accumulation of mucus-secreting tumor cells within the abdomen and pelvis', N''),
( N'Q574741', N'Dubowitz syndrome', N'genetic disorder', N''),
( N'Q5749018', N'skin squamous cell carcinoma', N'skin carcinoma that has material basis in squamous cells', N''),
( N'Q5749020', N'squamous cell carcinoma of the lung', N'lung cancer', N''),
( N'Q574905', N'Clostridium difficile colitis', N'colitis characterized by an overgrowth of Clostridium difficile bacteria', N''),
( N'Q576109', N'mucopolysaccharidosis VI', N'Lysosomal storage disease', N''),
( N'Q576179', N'egg allergy', N'food allergy that is an allergy or hypersensitivity to dietary substances from the yolk or whites of eggs, causing an overreaction of the immune system which may lead to severe physical symptoms', N''),
( N'Q576349', N'brain diseases', N'central nervous system diseases located in the brain', N''),
( N'Q5763722', N'rhinoscleroma', N'Human disease', N''),
( N'Q5773034', N'histiocytic sarcoma', N'', N''),
( N'Q5773040', N'histiocytoma', N'Human disease', N''),
( N'Q578257', N'Kohlers disease', N'osteochondrosis that results in death and collapse located in navicular bone of foot', N''),
( N'Q578994', N'parasitic helminthiasis infectious disease', N'macroparasitic disease in which a part of the body is infected with parasitic worms', N''),
( N'Q579527', N'pulmonary valve stenosis', N'Human disease', N''),
( N'Q579665', N'dextrocardia', N'rare congenital defect in which the apex of the heart is located on the right side of the body', N''),
( N'Q5797309', N'lacrimal duct obstruction', N'Human disease', N''),
( N'Q580285', N'Morquio Syndrome', N'Rare Disease', N''),
( N'Q580290', N'spinal muscular atrophy', N'rare congenital neuromuscular disorder', N''),
( N'Q580506', N'keratosis follicularis', N'Human disease', N''),
( N'Q580754', N'self-defeating personality disorder', N'proposed personality disorder', N''),
( N'Q581592', N'paraganglioma', N'Human disease', N''),
( N'Q582189', N'chronic mountain sickness', N'disease in which the proportion of blood volume that is occupied by red blood cells increases and there is an abnormally low level of oxygen in the blood', N''),
( N'Q582207', N'antiphospholipid syndrome', N'Human disease', N''),
( N'Q582904', N'marasmus', N'form of severe malnutrition characterized by energy deficiency', N''),
( N'Q5832339', N'Neonatal encephalopathy', N'Neurological dysfunction shortly after birth', N''),
( N'Q583908', N'vascular dementia', N'dementia that involves impairments in cognitive function caused by problems in blood vessels that feed the brain', N''),
( N'Q584211', N'hydrocele', N'Human disease', N''),
( N'Q584265', N'nervous system malformations', N'congenital conditions that stem from damage to, or abnormal development of, the budding nervous system', N''),
( N'Q584560', N'dysgraphia', N'neurological condition, developmental or acquired', N''),
( N'Q585011', N'Antley-Bixler syndrome', N'autosomal recessive disease that is characterized at birth or prenatally by malformations and deformities affecting the majority of the skeleton and other areas of the body with autosomal recessive inheritance of the FGFR2 gene', N''),
( N'Q585285', N'thrombocytopenia', N'blood platelet disease characterized by a low platelet count', N''),
( N'Q585911', N'tropical sprue', N'Human disease', N''),
( N'Q586009', N'malignant Sertoli-Leydig cell tumor', N'Human disease', N''),
( N'Q586878', N'omphalitis of newborn', N'inflammation of the umbilical cord stump', N''),
( N'Q587420', N'myotonia congenita', N'muscle tissue disease that is characterised by slow muscle relaxation associated with hyperexcitation of the muscle fibres', N''),
( N'Q5880534', N'Holiday heart syndrome', N'', N''),
( N'Q588321', N'toxic megacolon', N'Human disease', N''),
( N'Q5883885', N'holocarboxylase synthetase deficiency', N'human disease', N'')
GO