INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q2879095', N'optic nerve disease', N'cranial nerve disease that is located in the optic nerve', N''),
( N'Q2881413', N'lateral sclerosis', N'motor neuron disease characterized by painless but progressive weakness and stiffness of the muscles of the legs', N''),
( N'Q28823477', N'passive–aggressive personality disorder', N'', N''),
( N'Q2886899', N'oral candidiasis', N'candidiasis that involves fungal infection of the mucous membrane of the mouth by Candida species, which is characterized by thick white or cream-colored deposits on inflamed mucosal membranes', N''),
( N'Q288714', N'alpha thalassemia', N'Alpha thalassemia is a thalassemia involving the genes HBA1and HBA2 hemoglobin genes', N''),
( N'Q2888275', N'Sakati-Nyhan syndrome', N'An acrocephalosyndactylia characterized by abnormalities in the bones of the legs, congenital heart defects and craniofacial defects and craniosynostosis. The patients suffer from cyanosis and other respiratory and breathing infections.', N''),
( N'Q2892779', N'nephrogenic diabetes insipidus', N'impaired renal function disease characterized by a complete or partial resistance of the kidneys to vasopressin (ADH)', N''),
( N'Q28936239', N'Al-Raqad syndrome', N'congenital autosomal recessive syndrome discovered by Jordanian physician Mohammad Al-Raqad', N''),
( N'Q2894827', N'childhood absence epilepsy', N'A childhood electroclinical syndrome characterized by the occurrence of typical absence seizures starting between the age of four and ten years.', N''),
( N'Q2895302', N'complex partial seizure', N'human disease', N''),
( N'Q2895354', N'reflex epilepsy', N'Human disease', N''),
( N'Q2896802', N'Distal renal tubular acidosis', N'', N''),
( N'Q2897350', N'gastric lymphoma', N'Human disease', N''),
( N'Q2898645', N'neonatal diabetes mellitus', N'Human disease', N''),
( N'Q290213', N'Purtschers retinopathy', N'', N''),
( N'Q2906693', N'baritosis', N'benign type of pneumoconiosis, which is caused by long-term exposure to barium dus', N''),
( N'Q2912193', N'esophageal disease', N'gastrointestinal system disease that is located in the esophagus', N''),
( N'Q2915477', N'folate deficiency', N'Human disease', N''),
( N'Q291617', N'beta-mannosidosis.', N'lysosomal storage disease that has material basis in deficiency of the beta-A-manosidase enzyme resulting in the disruption of N-linked glycoprotein oligosaccharide catabolism.', N''),
( N'Q2919083', N'primary hyperparathyroidism', N'Human disease', N''),
( N'Q2923350', N'brachymetatarsia', N'condition in which there is one or more abnormally short or overlapping toes metatarsals', N''),
( N'Q2933021', N'health effects of caffeine', N'', N''),
( N'Q2936142', N'channelopathy', N'diseases caused by disturbed function of ion channel subunits or the proteins that regulate them', N''),
( N'Q2937283', N'Capillaritis', N'', N''),
( N'Q2938089', N'peripartum cardiomyopathy', N'Human disease', N''),
( N'Q296104', N'Activated protein C resistance', N'hemostatic disorder', N''),
( N'Q2964433', N'Jansens metaphyseal chondrodysplasia', N'metaphyseal dysplasia that has material basis in mutation in PTH receptor which results in short-limbed dwarfism', N''),
( N'Q2964434', N'Schmid metaphyseal chondrodysplasia', N'metaphyseal dysplasia that results in dwarfism and bowed legs', N''),
( N'Q2964437', N'Conradi–Hünermann syndrome', N'Rare X-linked form of chondrodysplasia punctata', N''),
( N'Q2964438', N'McKusick type metaphyseal dysplasia', N'metaphyseal dysplasia that results in short-limbed dwarfism and fine sparse hair', N''),
( N'Q2966706', N'chromhidrosis', N'a rare condition characterized by the secretion of colored sweat, caused by the deposition of lipofuscin in the sweat glands. Usually chromhidrosis affects the apocrine glands, mainly on the face and underarms.', N''),
( N'Q2966733', N'Ring chromosome 20 syndrome', N'', N''),
( N'Q2970970', N'intestinal infectious disease', N'intestinal disease that involves intestinal infection that has material basis in viruses, bacteria, fungi and parasites', N''),
( N'Q2973381', N'reduced affect display', N'condition of reduced emotional reactivity in an individual', N''),
( N'Q2977746', N'Toxic multinodular goitre', N'Human diseasexdr dildar', N''),
( N'Q2979344', N'Aspiration pneumonitis', N'chemical pneumonitis or aspiration pneumonitis caused by aspiration during anaesthesia, especially during pregnancy', N''),
( N'Q298230', N'esophagitis', N'inflammation of the esophagus', N''),
( N'Q298233', N'esophageal atresia', N'congenital disorder of digestive system', N''),
( N'Q298278', N'esophageal varix', N'Human disease', N''),
( N'Q2986781', N'Purgas pneumonic plague', N'plague that results in infection located in lung, which results from direct inhalation of the bacillus and has symptom fever, has symptom chills, has symptom cough and has symptom difficulty breathing', N''),
( N'Q2986815', N'photodermatosis', N'photoszematose', N''),
( N'Q2989168', N'hair diseases', N'integumentary system disease that is located in hair', N''),
( N'Q2991265', N'polymicrogyria', N'A condition that affects the development of the human brain by multiple small gyri (microgyri) creating excessive folding of the brain leading to an abnormally thick cortex.', N''),
( N'Q2995419', N'contagious disease', N'subset category of transmissible diseases, which are transmitted to other persons', N''),
( N'Q300121', N'atrioventricular block', N'heart conduction disease that is characterized by the impairment of the conduction between the atria and ventricles of the heart', N''),
( N'Q3002709', N'Cholinergic crisis', N'over-stimulation at a neuromuscular junction due to an excess of acetylcholine', N''),
( N'Q300801', N'Aagenaes syndrome', N'syndrome that is characterized by congenital hypoplasia of lymph vessels, which causes lymphedema of the legs and recurrent cholestasis in infancy, and slow progress to hepatic cirrhosis and giant cell hepatitis with fibrosis of the portal tracts', N''),
( N'Q3008595', N'cyclosporiasis', N'infection caused by Cyclospora cayetanensis', N''),
( N'Q3010352', N'cerebrovascular disease', N'artery disease that is characterized by dysfunction of the blood vessels supplying the brain', N''),
( N'Q3011658', N'dacryocystocele', N'Human disease', N''),
( N'Q3020720', N'total anomalous pulmonary venous connection', N'', N''),
( N'Q3025883', N'type-2 diabetes', N'type of diabetes mellitus with high blood sugar and insulin resistance', N''),
( N'Q3026420', N'Diastematomyelia', N'A rare congenital abnormality in which the spinal cord is split in half by fibrous or bony tissue. It may present as an isolated phenomenon or in association with spina bifida.', N''),
( N'Q3026441', N'Machado-Joseph disease', N'autosomal dominant cerebellar ataxia that is characterized by slow degeneration of the hindbrain and has material basis in expansion of CAG triplet repeats (glutamine) in the ATXN3 gene', N''),
( N'Q3029045', N'spastic diplegia', N'type of cerebral palsy characterized by spasticity and hypertonia of the lower extremities bilaterally, particularly the legs, hips, and pelvis; this is the most common (70%) form of cerebral palsy', N''),
( N'Q3030636', N'carotid artery dissection', N'Human disease', N''),
( N'Q3030745', N'distomatosis', N'group of parasitoses', N''),
( N'Q303123', N'Aarskog syndrome', N'monogenic disease affects a persons height, muscles, skeleton, genitals, and appearance of the face', N''),
( N'Q30314000', N'physical disorder', N'', N''),
( N'Q30314084', N'running injury', N'', N''),
( N'Q30314087', N'hypertension and brachydactyly syndrome', N'human disease', N''),
( N'Q30314091', N'HUPRA syndrome', N'human disease', N''),
( N'Q30314095', N'Sorsbys fundus dystrophy', N'human disease', N''),
( N'Q30314097', N'Functional somatic syndrome', N'', N''),
( N'Q30314162', N'Hemoglobin Hopkins-2', N'', N''),
( N'Q30314231', N'Adenoacanthoma', N'', N''),
( N'Q30314291', N'Childhood granulomatous periorificial dermatitis', N'', N''),
( N'Q30314380', N'Pork-Cat Syndrome', N'', N''),
( N'Q30314692', N'Lymphocyte-variant hypereosinophilia', N'human disease', N''),
( N'Q30314949', N'Isodisomy', N'', N''),
( N'Q30315051', N'Quadriga phenomenon', N'', N''),
( N'Q30315066', N'marfanoid–progeroid–lipodystrophy syndrome', N'human disease', N''),
( N'Q30325669', N'cat bite', N'The bite of the domestic cat', N''),
( N'Q303555', N'hypoactive sexual desire disorder', N'sexual dysfunction', N''),
( N'Q3041498', N'eye disease', N'health condition negatively affecting the eye', N''),
( N'Q3042104', N'dysferlinopathy', N'human disease', N''),
( N'Q3042106', N'dysgammaglobulinemia', N'selective immunoglobulin deficiency disease that is caused by a reduction in some types of gamma globulins', N''),
( N'Q3042113', N'episodic kinesigenic dyskinesia 1', N'dystonia characterized by autosomal dominant inheritance of recurrent brief involuntary hyperkinesias triggered by sudden movements that has material basis in heterozygous mutation in the PRRT2 gene on chromosome 16p11', N''),
( N'Q3042114', N'paroxysmal nonkinesigenic dyskinesia 2', N'human disease', N''),
( N'Q3042144', N'Autosomal recessive multiple epiphyseal dysplasia', N'', N''),
( N'Q3042159', N'X-linked dystonia-parkinsonism', N'A focal dystonia characterized by parkinsonism that is frequently accompanied by focal dystonia and progresses to generalized dystonia that has material basis in an SVA retrotransposon insertion in the intron of the TAF1 gene on chromosome Xq13.1.', N''),
( N'Q3042171', N'oculopharyngeal muscular dystrophy', N'Oculopharyngeal muscular dystrophy (OPMD) is an adult-onset progressive myopathy characterized by progressive eyelid ptosis, dysphagia, dysarthria and proximal limb weakness', N''),
( N'Q3043143', N'carnitine palmitoyltransferase I deficiency', N'human disease', N''),
( N'Q3043147', N'fructose-1,6-bisphosphatase deficiency', N'carbohydrate metabolic disorder that has material basis in a deficiency of fructose-1,6-bisphosphatase resulting in hypoglycemia and metabolic acidosis on fasting due to insufficient fructose bisphosphatase for gluconeogenesis', N''),
( N'Q3043149', N'Pyruvate kinase deficiency', N'congenital nonspherocytic hemolytic anemia that has material basis in homozygous or compound heterozygous mutation in the PKLR gene on chromosome 1q22', N''),
( N'Q3043153', N'protein S deficiency', N'disorder associated with increased risk of venous thrombosis', N''),
( N'Q3043155', N'purine nucleoside phosphorylase deficiency', N'combined T cell and B cell immunodeficiency that is a rare autosomal recessive metabolic disorder that has material basis in mutation in the PNP gene and characterized mainly by decreased T-cell function', N''),
( N'Q3043158', N'mevalonic aciduria', N'Human disease', N''),
( N'Q3043160', N'primary immunodeficiency disease', N'immune system disease that results when one or more essential parts of the immune system is missing or not working properly at birth due to a genetic mutation', N''),
( N'Q3043161', N'ornithine carbamoyltransferase deficiency', N'urea cycle disorder that involves a mutated and ineffective form of the enzyme ornithine transcarbamylase', N''),
( N'Q304497', N'hemiplegia', N'paralysis of the arm, leg, and trunk on the same side of the body', N''),
( N'Q3045238', N'Congenital insensitivity to pain', N'Not feeling pain', N''),
( N'Q304601', N'myiasis', N'parasitic ectoparasitic infectious disease that is caused by parasitic dipterous fly larvae (maggots) feeding on the hosts necrotic or living tissue', N''),
( N'Q3046374', N'zygomycosis', N'infections caused by fungi in the class Zygomycetes', N''),
( N'Q3047124', N'Ectopic testis', N'', N''),
( N'Q3049292', N'constrictive pericarditis', N'heart disorder in which the pericardial sac becomes thickened and fibrotic, tightening the myocardium and impeding the normal myocardial function', N''),
( N'Q3049302', N'human monocytic ehrlichiosis', N'human disease', N''),
( N'Q3052614', N'nosophobia', N'specific phobia that involves an irrational fear of contracting a disease', N''),
( N'Q3053945', N'glycine encephalopathy', N'amino acid metabolic disorder that involves abnormally high levels of the amino acid glycine in bodily fluids and tissues', N''),
( N'Q3053951', N'viral encephalitis', N'encephalitis that involves inflammation of the brain caused by viral infection', N''),
( N'Q3055079', N'Enthesitis', N'Inflammation at the site of insertion of ligaments, tendons, and other fibrous structures into bone', N''),
( N'Q3055156', N'persistent truncus arteriosus', N'Human disease', N''),
( N'Q3055380', N'intestinal disease', N'gastrointestinal system disease that is located in the intestine', N''),
( N'Q305641', N'abasia', N'disease', N''),
( N'Q30643222', N'methylenetetrahydrofolate reductase deficiency', N'', N''),
( N'Q30645673', N'Thymoma-associated multiorgan autoimmunity', N'', N''),
( N'Q3065932', N'cognitive disorder', N'disease of mental health that affects cognitive functions including memory processing, perception and problem solving', N''),
( N'Q3071315', N'fibrochondrogenesis', N'Human disease', N''),
( N'Q3073142', N'Pontiac fever', N'legionellosis that involves a milder respiratory illness without pneumonia. Symptoms include fever, headache and muscle aches which last for 2 to 5 days', N''),
( N'Q3074499', N'fluoride toxicity', N'condition in which there are elevated levels of the fluoride ion in the body', N''),
( N'Q30753528', N'platypnea-orthodeoxia syndrome', N'', N''),
( N'Q3080319', N'penicilliosis', N'Human disease', N''),
( N'Q3084532', N'endemic typhus', N'typhus transmitted by fleas (Xenopsylla cheopis), usually on rats', N''),
( N'Q3085434', N'Pallister-Hall syndrome', N'Human disease', N''),
( N'Q3087172', N'developmental disorder', N'disease of mental health that occur during a childs developmental period between birth and age 18 resulting in retarding of the childs psychological or physical development', N''),
( N'Q3089469', N'sequelae', N'pathological condition resulting from a disease, injury, therapy, or other trauma', N''),
( N'Q308978', N'pressure ulcer', N'chronic ulcer of skin where the ulcer is an ulceration of tissue deprived of adequate blood supply by prolonged pressure', N''),
( N'Q309067', N'motion sickness', N'condition in which a disagreement exists between visually perceived movement and the vestibular systems sense of movement', N''),
( N'Q30989182', N'RIDDLE syndrome', N'human disease', N''),
( N'Q30989658', N'aromatic L-amino acid decarboxylase deficiency', N'human disease', N''),
( N'Q30989792', N'familial cold autoinflammatory syndrome 3', N'human disease', N''),
( N'Q3099702', N'Athletic pubalgia', N'', N''),
( N'Q3100117', N'septicemic plague', N'Human disease', N''),
( N'Q3100515', N'hypervitaminosis A', N'Human disease', N''),
( N'Q310335', N'Schindler disease', N'Rare congenital metabolic disorder in humans.', N''),
( N'Q3108582', N'primary congenital glaucoma', N'Human disease', N''),
( N'Q3108583', N'anterior segment mesenchymal dysgenesis', N'Human disease', N''),
( N'Q3109873', N'Evans syndrome', N'Human disease', N''),
( N'Q3124960', N'epidermolysis bullosa simplex', N'disorder resulting from mutations in the genes encoding keratin 5 or keratin 14', N''),
( N'Q3128789', N'Spontaneous bacterial peritonitis', N'development of a bacterial infection in the peritoneum, despite the absence of an obvious source for the infection', N''),
( N'Q3130277', N'pretibial myxedema', N'Human disease', N''),
( N'Q3134276', N'femoral hernia', N'protrusion of a viscus through a weakness in the containing wall', N''),
( N'Q3136516', N'benign cephalic histiocytosis', N'human disease', N''),
( N'Q3136521', N'non-Langerhans-cell histiocytosis', N'Human disease', N''),
( N'Q3136522', N'generalized eruptive histiocytoma', N'human disease', N''),
( N'Q3137154', N'non-communicable disease', N'medical condition or disease not transmissible directly from person to person', N''),
( N'Q3143800', N'water retention', N'', N''),
( N'Q3144117', N'Hyperchlorhydria', N'', N''),
( N'Q3144186', N'Hyperphosphatasia with mental retardation syndrome type 1', N'human disease', N''),
( N'Q3144201', N'Excessive daytime sleepiness', N'Symptom characterized by persistent sleepiness during daytime', N''),
( N'Q3144217', N'myostatin-related muscle hypertrophy', N'A muscle tissue disease characterized by increased muscle bulk and strength that has material basis in homozygous mutation in the MSTN gene on chromosome 2q32.2.', N''),
( N'Q3144300', N'X-linked adrenal hypoplasia congenita', N'adrenal cortical hypofunction that is characterized by a reduction in adrenal gland function resulting from incomplete development of the adrenal cortex and has material basis in the nuclear receptor NR0B1 (DAX1) gene', N''),
( N'Q3144913', N'hemangiopericytoma', N'soft tissue cancer that is a soft tissue sarcoma and originates in the pericytes in the walls of capillaries', N''),
( N'Q3144934', N'HFE hereditary haemochromatosis', N'metal metabolism disorder characterized by the accumulation of iron in various organs of the body', N''),
( N'Q3144936', N'hemochromatosis type 3', N'hemochromatosis that has material basis in homozygous or compound heterozygous mutation in the TFR2 gene on chromosome 7q22', N''),
( N'Q3144945', N'hemoglobin H disease', N'alpha thalassemia that has material basis in contiguous gene deletion of the hemoglobin alpha-1 (HBA1) and alpha-2 (HBA2) genes on one chromosome 16, and a defect, deletional or nondeletional, in either HBA1 or HBA2 on the other', N''),
( N'Q3144949', N'hemopericardium', N'pericardial effusion that results from blood in the pericardial sac', N''),
( N'Q3144986', N'alcoholic hepatitis', N'hepatitis (inflammation of the liver) due to excessive intake of alcohol', N''),
( N'Q3145111', N'Heterophoria', N'vision abnormality', N''),
( N'Q3153671', N'lysinuric protein intolerance', N'Human disease', N''),
( N'Q3153686', N'Toluene toxicity', N'hazardous chemical exposure', N''),
( N'Q3155162', N'parasitic twin', N'', N''),
( N'Q317158', N'adjustment disorder', N'human disease', N''),
( N'Q3179593', N'skin tag', N'', N''),
( N'Q317977', N'abducens nerve palsy', N'non-neoplastic or neoplastic disorder affecting the abducens nerve (sixth cranial nerve)', N''),
( N'Q318005', N'nocturnal enuresis', N'disease', N''),
( N'Q3184856', N'substance abuse', N'a patterned use of a drug in which the user consumes the psychoactive/chemical substance substances in amounts or with methods which are harmful to themselves or others', N''),
( N'Q319312', N'premature ejaculation', N'Human disease', N''),
( N'Q319595', N'presbyopia', N'medical condition associated with aging of the eye', N''),
( N'Q319763', N'inferiority complex', N'An intense feeling of inferiority', N''),
( N'Q3197774', N'klebsiellosis', N'infection by Klebsiella bacteria', N''),
( N'Q319812', N'abetalipoproteinemia', N'Human disease', N''),
( N'Q3199902', N'urethral cancer', N'urinary tract cancer that derives from the tissues of the urethra', N''),
( N'Q3204645', N'frontal lobe epilepsy', N'common form of epilepsy that may appear to be related to a psychiatric problem or a sleep disorder', N''),
( N'Q320719', N'dependent personality disorder', N'personality disorder that is characterized by a pervasive psychological dependence on other people', N''),
( N'Q3208285', N'post-schizophrenic depression', N'depressive episode, arising in the aftermath of a schizophrenic psychosis', N''),
( N'Q32136782', N'transient myeloproliferative syndrome', N'myeloproliferative neoplasm characterized by leukocytosis in newborns with Down syndrome and rarely in non-Downs infants', N''),
( N'Q32147145', N'maturity-onset diabetes of the young type 2', N'maturity-onset diabetes of the young that has material basis in heterozygous mutation in the GCK gene on chromosome 7p13', N''),
( N'Q3221083', N'motor neuron disease', N'neurological disorder that selectively affect motor neurons', N''),
( N'Q3234995', N'vitamin B12 deficiency', N'vitamin metabolic disorder that results from low blood levels of vitamin B12', N''),
( N'Q3237080', N'Megalencephalic leukoencephalopathy with subcortical cysts', N'hereditary CNS demyelinating disease', N''),
( N'Q3237081', N'leukoencephalopathy', N'human disease', N''),
( N'Q3237103', N'leukostasis', N'human disease', N''),
( N'Q3241451', N'childhood obesity', N'condition where excess body fat negatively affects a childs health or well-being', N''),
( N'Q3242224', N'congenital generalized lipodystrophy', N'Human disease', N''),
( N'Q3242950', N'kidney cancer', N'urinary system cancer that is located in the kidney', N''),
( N'Q324464', N'testicular cancer', N'male sex reproductive system cancer that is located in the testicles', N''),
( N'Q3251367', N'osteochondrodysplasia', N'bone development disease that results in defective development of cartilage or bone', N''),
( N'Q3257123', N'Livedoid vasculitis', N'vasculitis with purpuric ulcers', N''),
( N'Q326071', N'giardiasis', N'parasitic disease of humans and other mammals', N''),
( N'Q3264425', N'loxoscelism', N'condition occasionally produced by the bite of the recluse spiders', N''),
( N'Q326643', N'hepatitis E', N'Human disease', N''),
( N'Q326648', N'salmonellosis', N'infection caused by Salmonella bacteria', N''),
( N'Q326663', N'tick-borne encephalitis', N'viral infectious disease involving the central nervous system', N''),
( N'Q3267714', N'Tumid lupus erythematosus', N'', N''),
( N'Q3269843', N'hyperkalemic periodic paralysis', N'Human disease', N''),
( N'Q327005', N'glanders', N'horse disease that can be transmitted to humans', N''),
( N'Q3270160', N'actinobacillosis', N'Human disease', N''),
( N'Q3270174', N'Balanoposthitis', N'Human disease', N''),
( N'Q3270312', N'hereditary leiomyomatosis and renal cell cancer syndrome', N'Hereditary leiomyomatosis and renal cell cancer (HLRCC) is a hereditary cancer syndrome characterized by a predisposition to cutaneous and uterine leiomyomas and, in some families, to renal cell cancer', N''),
( N'Q327281', N'hepatitis D', N'Human disease', N''),
( N'Q327298', N'shigellosis', N'human disease', N''),
( N'Q3273331', N'acatalasia', N'Human disease', N''),
( N'Q3276506', N'orotic aciduria', N'pyrimidine metabolic disorder that is characterized by an excessive secretion of orotic acid in urine', N''),
( N'Q3278042', N'isovaleric acidemia', N'organic acidemia that disrupts or prevents normal metabolism of the branched-chain amino acid leucine', N''),
( N'Q3281227', N'mucosulfatidosis', N'Lysosomal storage disease', N''),
( N'Q3281266', N'Cruveilhier–Baumgarten disease', N'', N''),
( N'Q3281274', N'Griscelli syndrome', N'autosomal recessive disease characterized by silvery gray sheen of the hair and hypopigmentation of the skin', N''),
( N'Q3281285', N'Niemann–Pick disease, SMPD1-associated', N'', N''),
( N'Q3281293', N'Roussy–Lévy syndrome', N'human disease', N''),
( N'Q3281296', N'Schamberg disease', N'', N''),
( N'Q3281299', N'Scheie syndrome', N'mucopolysaccharidosis characterized by corneal clouding, facial dysmorphism and normal lifespan', N''),
( N'Q3281322', N'peroxisomal disease', N'inherited metabolic disorder that involves peroxisome malfunction', N''),
( N'Q3281328', N'heavy chain disease', N'hypersensitivity reaction type IV disease that results from a proliferation of cells producing immunoglobulin heavy chains', N''),
( N'Q3281373', N'metal metabolism disorder', N'inherited metabolic disorder that involves metabolic disturbances in the processing or distribution of dietary minerals', N''),
( N'Q3281375', N'inborn errors of purine–pyrimidine metabolism', N'inherited metabolic disorder involving dysfunction of purine and pyrimidine metabolism', N''),
( N'Q3281380', N'X-linked lymphoproliferative disease', N'lymphoproliferative disorder', N''),
( N'Q3286546', N'respiratory disease', N'disease of the respiratory system', N''),
( N'Q3288122', N'pervasive developmental disorder not otherwise specified', N'neurodevelopmental condition', N''),
( N'Q3296793', N'renovascular hypertension', N'Human disease', N''),
( N'Q3297002', N'smut', N'reproductive structure of fungi', N''),
( N'Q3297012', N'rubeosis iridis', N'Human disease', N''),
( N'Q3297103', N'chromosome 1p36 deletion syndrome', N'Human disease', N''),
( N'Q3297888', N'pain disorder', N'somatoform disorder that involves chronic pain in one or more areas, and is thought to be caused by psychological stress.', N''),
( N'Q3298999', N'microcytic anemia', N'Human disease', N''),
( N'Q3299714', N'normocytic anemia', N'Human disease', N''),
( N'Q3301664', N'viral meningitis', N'human disease', N''),
( N'Q3304152', N'Jervell-Lange Nielsen syndrome', N'Human disease', N''),
( N'Q3311537', N'hereditary disorder', N'', N''),
( N'Q331181', N'abrasion', N'loss of tooth substance by mechanical contact with objects other than tooth-tooth contact', N''),
( N'Q331283', N'leishmaniasis', N'disease caused by parasites of the Leishmania type', N''),
( N'Q3312899', N'familial hemiplegic migraine', N'migraine with aura that is characterized by temporary numbness or weakness, often affecting one side of the body', N''),
( N'Q3317827', N'disability affecting intellectual abilities', N'subnormal intellectual functioning (cognitive disorder)', N''),
( N'Q3321253', N'chromosome 9p deletion syndrome', N'Human disease', N''),
( N'Q332293', N'carpal tunnel syndrome', N'medical condition due to compression of the median nerve as it travels through the wrist at the carpal tunnel', N''),
( N'Q3324389', N'localized scleroderma', N'human disease', N''),
( N'Q332768', N'survivor guilt', N'Mental condition', N''),
( N'Q3331452', N'myofibrillar myopathy 1', N'Human disease', N''),
( N'Q3331454', N'X-linked myotubular myopathy', N'', N''),
( N'Q3331923', N'myelophthisic anemia', N'aplastic anemia that is characterized by displacement of hemopoietic bone-marrow tissue either by fibrosis, tumors or granulomas', N''),
( N'Q3333223', N'Menometrorrhagia', N'', N''),
( N'Q3335660', N'3-M syndrome', N'autosomal recessive disease characterized by dwarfism, facial dysmorphia and skeletal abnormalities', N''),
( N'Q3335662', N'Hydrops-ectopic calcification-moth-eaten skeletal dysplasia', N'lethality and affected fetuses are considered as nonviable', N''),
( N'Q3335666', N'diastrophic dysplasia', N'osteochondrodysplasia that has material basis in abnormal cartilage development due to mutations in the SLC26A2 gene which results in short limb dwarfism', N''),
( N'Q3335671', N'mulibrey nanism', N'Human disease', N''),
( N'Q3338656', N'chorea-acanthocytosis', N'Human disease', N''),
( N'Q3338664', N'Adult-onset basal ganglia disease', N'Neuroferritinopathy is a late-onset type of neurodegeneration with brain iron accumulation (NBIA; see this term) characterized by progressive chorea or dystonia and subtle cognitive deficits', N''),
( N'Q3338677', N'familial amyloid neuropathy', N'human disease', N''),
( N'Q3338681', N'Hereditary sensory and autonomic neuropathy type I', N'', N''),
( N'Q3338682', N'giant axonal neuropathy 1', N'human disease', N''),
( N'Q3339235', N'neurological disorder', N'disease of anatomical entity that is located in the central nervous system or located in the peripheral nervous system', N''),
( N'Q334655', N'amenorrhea', N'absence of a menstrual period in a woman of reproductive age', N''),
( N'Q3347154', N'multiple endocrine neoplasia type 1', N'autosomal dominant disease that has material basis in a mutation in the MEN1 tumor suppressor gene and is characterized by over active endocrine glands frequently involving tumors of the parathyroid glands, the pituitary gland, and the pancreas', N''),
( N'Q3348620', N'central retinal artery occlusion', N'retinal artery occlusion characterized by blockage of blood flow through the central retinal artery', N''),
( N'Q335555', N'Sjögrens syndrome', N'hypersensitivity reaction type II disease affecting the exocrine glands', N''),
( N'Q3357479', N'osteoradionecrosis', N'disease', N''),
( N'Q3357668', N'agnathia-otocephaly complex', N'Human disease', N''),
( N'Q3358135', N'Systemic primary carnitine deficiency', N'amino acid metabolic disorder that involves defective proteins called carnitine transporters, which bring carnitine into cells and prevent its escape from the body preventing the body cannot utilize fats for energy', N''),
( N'Q3358864', N'Southeast Asian ovalocytosis', N'', N''),
( N'Q335941', N'aboulia', N'absence of willpower or decisiveness, especially as a symptom of mental disorder', N''),
( N'Q3360152', N'pachyonychia congenita', N'rare group of autosomal dominant skin disorders that are caused by a mutation in one of five different keratin genes', N''),
( N'Q3368713', N'Léri–Weill dyschondrosteosis', N'human disease', N''),
( N'Q337585', N'intraductal carcinoma', N'Human disease', N''),
( N'Q337604', N'aceruloplasminemia', N'Aceruloplasminemia is an adult-onset disorder of neurodegeneration with brain iron accumulation (NBIA; see this term) characterized by anemia, retinal degeneration, diabetes and various neurological symptoms', N''),
( N'Q3377653', N'scapular fracture', N'injury of the shoulder blade', N''),
( N'Q3377927', N'PHACE association', N'cutaneous condition characterized by multiple congenital abnormalities. ("PHACES"=Posterior fossa malformations–hemangiomas–arterial anomalies–cardiac defects–eye abnormalities–sternal cleft and supraumbilical raphe syndrome)', N''),
( N'Q3378593', N'substance dependence', N'need for a drug that develops from repeated drug administration, whose discontinuation results in withdrawal symptoms', N''),
( N'Q337998', N'acariasis', N'parasitic ectoparasitic infectious disease caused by mites', N''),
( N'Q3381802', N'Pthirus pubis infestation', N'disease caused by the pubic louse, Pthirus pubis, a parasitic insect notorious for infesting human pubic hair', N''),
( N'Q3384899', N'sebaceous adenoma', N'Human disease', N''),
( N'Q339221', N'gynecomastia', N'Human disorder, which causes the appearance of breasts in males', N''),
( N'Q3392956', N'pouchitis', N'Acute inflammation in the intestinal mucosa of the continent ileal reservoir (or pouch) in patients who have undergone ileostomy and restorative proctocolectomy (proctocolectomy, restorative)', N''),
( N'Q339547', N'carcinoid syndrome', N'Human disease', N''),
( N'Q3395618', N'autosomal recessive polycystic kidney', N'recessive form of polycystic kidney disease', N''),
( N'Q3395796', N'polyradiculoneuropathy', N'condition in which polyneuropathy and polyradiculopathy occur together', N''),
( N'Q3399863', N'postterm pregnancy', N'', N''),
( N'Q340594', N'achondroplasia', N'osteochondrodysplasia that results in dwarfism from abnormal ossification of cartilage in long bones', N''),
( N'Q3408668', N'prurigo', N'', N''),
( N'Q3410750', N'pulicosis', N'skin condition caused by several species of fleas', N''),
( N'Q3410985', N'purpura fulminans', N'A purpura characterized by blood spots, bruising and discolouration of the skin', N''),
( N'Q3411230', N'Pemphigus vegetans of Hallopeau', N'', N''),
( N'Q341999', N'hidradenitis suppurativa', N'Human disease', N''),
( N'Q3433884', N'gestational trophoblastic disease', N'No lo sé bro', N''),
( N'Q3435504', N'AIDS dementia complex', N'Human disease', N''),
( N'Q3441028', N'Norum disease', N'Human disease', N''),
( N'Q3444851', N'hypobetalipoproteinemia', N'hypolipoproteinemia characterized by permanently low levels of apolipoprotein B and LDL cholesterol resulting from an impaired ability to absorb and transport fats', N''),
( N'Q3445377', N'regressive autism', N'', N''),
( N'Q344873', N'acute respiratory distress syndrome', N'human disease', N''),
( N'Q3449191', N'organic personality disorder', N'mental disorder', N''),
( N'Q3454355', N'Shwartzman phenomenon', N'Human disease', N''),
( N'Q3456637', N'X-linked myopathy with excessive autophagy', N'Human disease', N''),
( N'Q3473544', N'clear-cell sarcoma', N'', N''),
( N'Q3475955', N'sclerosteosis', N'hyperostosis characterized by excessive bone formation most prominent in the skull, mandible, clavicle, ribs and diaphyses of long bones; bone formation occurs throughout life', N''),
( N'Q3493538', N'thyroid medullary carcinoma', N'malignant thyroid neoplasm originating from C-cells', N''),
( N'Q3495854', N'palindromic rheumatism', N'human disease', N''),
( N'Q3497004', N'laryngeal papillomatosis', N'', N''),
( N'Q3500973', N'lipoatrophy', N'', N''),
( N'Q3501154', N'Larsen syndrome', N'autosomal dominant disease that is characterized by large-joint dislocations and characteristic craniofacial abnormalities', N''),
( N'Q3501283', N'dextro-transposition of the great arteries', N'congenital heart disease characterized by complete inversion of the great vessels where the aorta incorrectly arises from the right ventricle and the pulmonary artery incorrectly arises from the left ventricle', N''),
( N'Q3501498', N'congenital aortic stenosis', N'human disease', N''),
( N'Q3505189', N'verbal auditory agnosia', N'human disease', N''),
( N'Q3508561', N'ATR-16 syndrome', N'alpha thalassemia that has material basis in a deletion in chromosome 16p that involves the alpha-1 (HBA1) and alpha-2 (HBA2) genes, among others', N''),
( N'Q3508563', N'leukoencephalopathy with vanishing white matter', N'human disease', N''),
( N'Q3508565', N'ABCD syndrome', N'autosomal recessive disease that is characterized by albinism, black lock, cell migration disorder of the neurocytes of the gut and sensorineural deafness and has material basis in a mutation in the endothelin B receptor gene (EDNRB)', N''),
( N'Q3508566', N'immune dysregulation-polyendocrinopathy-enteropathy-X-linked syndrome', N'hypersensitivity reaction type II disease characterized by onset in infancy of refractory diarrhea, endocrinopathies, type 1 diabetes mellitus, and dermatitis that has material basis in mutation in the FOXP3 gene on chromosome Xp11', N''),
( N'Q3508568', N'CHILD syndrome', N'CHILD syndrome (Congenital Hemidysplasia with Ichthyosiform nevus and Limb Defects, CS) is an X-linked dominant genodermatosis characterized by unilateral inflammatory and scaling skin lesions with ipsilateral visceral and limb anomalies', N''),
( N'Q3508570', N'MASS syndrome', N'', N''),
( N'Q3508572', N'muscle-eye-brain disease', N'disease', N''),
( N'Q3508578', N'rapadilino syndrome', N'Human disease', N''),
( N'Q3508585', N'ablepharon macrostomia syndrome', N'Human disease', N''),
( N'Q3508595', N'hereditary motor and sensory neuropathy with agenesis of the corpus callosum', N'Human disease', N''),
( N'Q3508605', N'autosomal dominant type IV Ehlers-Danlos syndrome', N'Human disease', N''),
( N'Q3508611', N'X-linked hyper IgM syndrome', N'human disease', N''),
( N'Q3508614', N'hyperinsulinism-hyperammonemia syndrome', N'', N''),
( N'Q3508616', N'Baller-Gerold syndrome', N'synostosis characterized by coronal craniosynostosis, short stature, and aplasia or hypoplasia of the radial bone', N''),
( N'Q3508618', N'Congenital contractural arachnodactyly', N'', N''),
( N'Q3508623', N'Bruck syndrome', N'syndrome characterized by a combination of multiple joint contractures and osteogenesis imperfecta', N''),
( N'Q3508625', N'Carey Fineman Ziter syndrome', N'human disease', N''),
( N'Q3508634', N'Donnai-Barrow syndrome', N'human disease', N''),
( N'Q3508635', N'Fryns syndrome', N'disease', N''),
( N'Q3508639', N'Goldberg-Shprintzen syndrome', N'A syndrome characterized by intellectual disability, specific facial gestalt and Hirschsprungs disease (HSCR). It has material basis in homozygous mutation in the KIAA1279 gene on chromosome 10q21.1.', N''),
( N'Q3508649', N'Greig cephalopolysyndactyly syndrome', N'acrocephalosyndactylia that has material basis in mutation in the GLI3 gene which results in abnormal development located in limb, located in head, located in face', N''),
( N'Q3508650', N'Grisels syndrome', N'non-traumatic subluxation of the atlanto-axial joint caused by inflammation of the adjacent tissues. This is a rare disease that usually affects children.', N''),
( N'Q3508651', N'Thymoma with immunodeficiency', N'', N''),
( N'Q3508653', N'Lytico-bodig disease', N'human disease', N''),
( N'Q3508654', N'congenital disorder of glycosylation type Ia', N'human disease', N''),
( N'Q3508669', N'Loeys-Dietz syndrome', N'Human disease', N''),
( N'Q3508673', N'Melnick–Needles syndrome', N'congenital disorder that affects primarily bone development.', N''),
( N'Q3508674', N'McKusick–Kaufman syndrome', N'McKusick-Kaufman syndrome is a very rare, genetic developmental disorder presenting in the neonatal period characterized by genitourinary malformations, polydactyly, and more rarely, congenital heart disease or gastrointestinal malformations', N''),
( N'Q3508677', N'deafness dystonia syndrome', N'mitochondrial metabolism disease that is characterized by hearing loss that begins early in life, problems with movement, impaired vision, and behavior problems', N''),
( N'Q3508679', N'Muenke syndrome', N'Human disease', N''),
( N'Q3508681', N'Nezelof syndrome', N'Human disease', N''),
( N'Q3508686', N'Saethre-Chotzen syndrome', N'acrocephalosyndactylia that has material basis in a genetic mutation in the TWIST1 gene which results in premature fusion located in skull', N''),
( N'Q3508705', N'Timothy syndrome', N'An autosomal dominant disease that is characterized by cardiac, hand/foot, facial, and neurodevelopmental features. The two forms are type 1 (classic) and type 2, a rare form that has material basis in mutations in a transcript variant of CACNA1C.', N''),
( N'Q3508714', N'Testicular dysgenesis syndrome', N'', N''),
( N'Q3508729', N'Occipital horn syndrome', N'Occipital horn syndrome (OHS) is a mild form of Menkes disease (MD, see this term), a syndrome characterized by progressive neurodegeneration and connective tissue disorders due to a copper transport defect', N''),
( N'Q3508735', N'Bare lymphocyte syndrome', N'', N''),
( N'Q3508737', N'multiple hamartoma syndrome', N'syndrome characterized as a spectrum of disorders (Cowden syndrome, Bannayan-Riley-Ruvalcaba syndrome, PTEN-related Proteus syndrome, and Proteus-like syndrome) caused by germline mutations of the PTEN gene', N''),
( N'Q3508750', N'Opitz-GBBB syndrome', N'A monogenic disease that is characterized by hypertelorism, hypospadias, and additional midline defects resulting from mutations to the MID1 gene in the X-linked form or from a deletion on chromosome 22q11.2 in the autosomal dominant form.', N''),
( N'Q3508764', N'hand-foot-genital syndrome', N'autosomal dominant human genetic disease characterized by limb malformations (e.g. bilateral shortening of thumbs/big toes) and urogenital defects (e.g. abnormalities of ureters/urethra; incomplete Müllerian fusion in females; hypospadias in males)', N''),
( N'Q3508768', N'Lymphedema–distichiasis syndrome', N'people with this hereditary condition have a double row of eyelashes,', N''),
( N'Q3508774', N'Wiedemann-Rautenstrauch syndrome', N'Wiedemann-Rautenstrauch syndrome is a very rare disorder with features of premature aging recognizable at birth, decreased subcutaneous fat, hypotrichosis, relative macrocephaly and dysmorphism', N''),
( N'Q3508783', N'oral-facial-digital syndrome', N'genetic disease that is characterized by malformations of the face, oral cavity, and digits with polycystic kidney disease and variable involvement of the central nervous system and has material basis in X-linked inheritance of an OFD gene', N''),
( N'Q3508786', N'orofaciodigital syndrome I', N'An orofaciodigital syndrome characterized_by polycystic kidney disease and variable involvement of the central nervous system and has_material_basis_in X-linked inheritance of the OFD1 gene.', N''),
( N'Q3508787', N'postencephalitic Parkinson disease', N'A disease believed to be caused by a viral illness that triggers degeneration of the nerve cells in the substantia nigra. Overall, this degeneration leads to clinical parkinsonism.', N''),
( N'Q3508794', N'Tricho–rhino–phalangeal syndrome', N'human disease', N''),
( N'Q3508795', N'trichorhinophalangeal syndrome type II', N'Human disease', N''),
( N'Q3508797', N'Obstructive lung disease', N'category of respiratory disease characterized by airway obstruction', N''),
( N'Q3508800', N'congenital myasthenic syndrome', N'Human disease', N''),
( N'Q3508804', N'paraneoplastic neurologic syndrome', N'paraneoplastic syndrome that involves the nervous system', N''),
( N'Q3508806', N'eosinophilia-myalgia syndrome', N'Human disease', N''),
( N'Q3512243', N'autosomal dominant familial periodic fever', N'human disease', N''),
( N'Q3513620', N'Junctional ectopic tachycardia', N'rare syndrome of the heart that manifests in patients recovering from heart surgery: cardiac arrhythmia, or irregular beating of the heart, caused by abnormal conduction from or through the atrioventricular node', N''),
( N'Q351708', N'Adams-Oliver syndrome', N'syndrome characterized by defects of the scalp (aplasia cutis congenita), abnormalities of the fingers, toes, arms and legs', N''),
( N'Q3518022', N'rotator cuff tear', N'injury to the rotator cuff of the shoulder joint', N''),
( N'Q3525980', N'Paris-Trousseau syndrome', N'Paris-Trousseau thrombocytopenia (TCPT) is a contiguous gene syndrome characterized by mild bleeding tendency, variable thrombocytopenia (THC), dysmorphic facies, abnormal giant alpha-granules in platelets and dysmegakaryopoiesis', N''),
( N'Q353172', N'parasitic protozoa infectious disease', N'parasitic disease caused by a protozoan', N''),
( N'Q3539030', N'trichothiodystrophy syndromes', N'human disease', N''),
( N'Q3540280', N'trombiculiasis', N'mite infestation that involves rash caused by Leptotrombidium deliense', N''),
( N'Q3540864', N'balance disorder', N'disturbance that causes an individual to feel unsteady', N''),
( N'Q3540887', N'sensory processing disorder', N'neurodevelopmental condition involving heightened and/or muted responses to sensory input', N''),
( N'Q3540902', N'lipid storage disease', N'lysosomal storage disease that involves the accumulation of harmful amounts of lipids (fats) in some of the bodys cells and tissues', N''),
( N'Q3542012', N'connective tissue neoplasm', N'musculoskeletal system cancer that is located in connective tissue', N''),
( N'Q3542016', N'neuroectodermal tumor', N'Human disease', N''),
( N'Q3542021', N'endodermal sinus tumor', N'germ cell cancer that has material basis in cells that line the yolk sac of the embryo', N''),
( N'Q3542024', N'melanocytic tumor', N'human disease', N''),
( N'Q3542027', N'epithelioma', N'', N''),
( N'Q3554941', N'vasoplegia', N'', N''),
( N'Q3556400', N'color agnosia', N'agnosia that is a loss of the ability to recognize a color, while being able to perceive or distinguish it', N''),
( N'Q356005', N'adenoid cystic carcinoma', N'type of cancer', N''),
( N'Q356033', N'adenocarcinoma', N'carcinoma that has material basis in abnormally proliferating cells, derives from epithelial cells, which originate in glandular tissue', N''),
( N'Q356058', N'adenomatoid tumor', N'type of tumor', N''),
( N'Q356372', N'uveal melanoma', N'uveal cancer that has material basis in uvea pigment cells', N''),
( N'Q356410', N'Adermatoglyphia', N'rare genetic disorder causing lack of fingerprints', N''),
( N'Q356713', N'aspergilloma', N'infection of the respiratory tract with fungi of the genus Aspergillus', N''),
( N'Q3567797', N'hereditary mucosal leukokeratosis', N'skin disease characterized by a defect in the normal process of keratinization of the mucosa', N''),
( N'Q3570558', N'juvenile xanthogranuloma', N'Human disease', N''),
( N'Q357067', N'Adie syndrome', N'neurological disorder characterized by a tonically dilated pupil', N''),
( N'Q357522', N'Adipsia', N'Clinically significant lack of expression of thirst', N''),
( N'Q3589130', N'Junctional epidermolysis bullosa, Herlitz type', N'', N''),
( N'Q3589131', N'epidermolysis bullosa dystrophica', N'inherited disease affecting the skin and other organs', N''),
( N'Q3589157', N'Autosomal dominant nocturnal frontal lobe epilepsy', N'frontal lobe epilepsy that is characterized by autosomal dominant inheritance with childhood onset of clusters of brief nocturnal motor seizures with hyperkinetic or tonic manifestations', N''),
( N'Q3591490', N'erythroblastopenia', N'human desease', N''),
( N'Q3591492', N'Leiners disease', N'disease', N''),
( N'Q3591493', N'erythrokeratodermia variabilis', N'Human disease', N''),
( N'Q3598794', N'3-methylglutaconic aciduria', N'organic acidemia that is characterized by elevated levels of 3-methylglutaconic acid and 3-methylglutaric acid in the urine', N''),
( N'Q359892', N'salpingitis', N'infection and inflammation in the fallopian tubes', N''),
( N'Q360035', N'dhat syndrome', N'culture-bound syndrome', N''),
( N'Q360341', N'organic brain syndrome', N'syndrome or disorder of mental function whose cause is alleged to be known as organic (physiologic) rather than purely of the mind', N''),
( N'Q3604584', N'Acne keloidalis nuchae', N'Sindrome de vello africano', N''),
( N'Q3607819', N'Alastrim', N'milder form of smallpox', N''),
( N'Q3612627', N'allomnesia', N'deformation of actual memories', N''),
( N'Q361648', N'double outlet right ventricle', N'Human disease, Congenital Heart Disease', N''),
( N'Q3616632', N'beta thalassemia', N'thalassemia characterized by the reduced or absent synthesis of the beta globin chains of hemoglobin', N''),
( N'Q3616643', N'Anetoderma', N'Primary anetoderma is a rare skin disease characterized by loss of elastin tissue resulting in localized areas of flaccid skin in the absence of a secondary cause', N''),
( N'Q3616648', N'thoracic aortic aneurysm', N'aortic aneurysm that is located in the thoracic aorta', N''),
( N'Q3617579', N'anisopoikilocytosis', N'blood disorder often caused by some type of anemia', N''),
( N'Q3620651', N'central sleep apnea', N'sleep apnea that is characterized by a malfunction of the basic neurological controls for breathing rate and the failure to give the signal to inhale, causing the individual to miss one or more cycles of breathing', N''),
( N'Q3622611', N'secondary hyperparathyroidism', N'Human disease', N''),
( N'Q3624834', N'periapical abscess', N'localized collection of pus associated with a tooth', N''),
( N'Q362719', N'anterior ischemic optic neuropathy', N'Human disease', N''),
( N'Q3629047', N'Gyrate atrophy of the choroid', N'Human disease', N''),
( N'Q3629075', N'Drop attack', N'sudden fall without loss of consciousness', N''),
( N'Q3640920', N'blepharochalasis', N'eyelid disease that is characterized by exacerbations and remissions of eyelid edema, which results in a stretching and subsequent atrophy of the eyelid tissue, leading to the formation of redundant folds over the lid margins', N''),
( N'Q3640984', N'third-degree atrioventricular block', N'medical condition in which the impulse generated in the sinoatrial node (SA node) in the atrium of the heart does not propagate to the ventricles', N''),
( N'Q3640986', N'first-degree atrioventricular block', N'disease of the electrical conduction system of the heart in which the PR interval is lengthened beyond 0.20 seconds', N''),
( N'Q3642764', N'achilles bursitis', N'bursitis (inflammation of synovial sac) of bursa situated above the insertion of tendon to calcaneus', N''),
( N'Q365589', N'XX male syndrome', N'rare congenital condition where an individual with a female genotype has phenotypically male characteristics that can vary between cases', N''),
( N'Q3656132', N'Sandifer syndrome', N'A childhood disorder characterised by gastrointestinal symptoms and associated neurological features.', N''),
( N'Q3658376', N'typical pulmonary carcinoid tumour', N'Disease', N''),
( N'Q3658380', N'adenosquamous carcinoma', N'squamous cell carcinoma that contains squamous cells and gland-like cells', N''),
( N'Q3658562', N'non-small-cell lung carcinoma', N'type of tumour', N''),
( N'Q3667186', N'keratosis', N'skin disease characterized by growth of keratin on the skin or mucous membranes', N''),
( N'Q366868', N'congenital adrenal hyperplasia', N'steroid inherited metabolic disorder that is characterized by adrenal insufficiency and variable degrees of hyper or hypo androgeny manifestations resulting from steroidogenic enzyme deficiency', N''),
( N'Q366964', N'X-linked adrenoleukodystrophy', N'X-linked adrenoleukodystrophy (X-ALD) is a peroxisomal disorder resulting in cerebral demyelination, axonal dysfunction in the spinal cord leading to spastic paraplegia, adrenal insufficiency and in some cases testicular insufficiency', N''),
( N'Q3676446', N'Fuchs heterochromic uveitis', N'syndrome that is a chronic unilateral (or rarely bilateral) iridocyclitis appearing with the triad of heterochromia, predisposition to cataracts and glaucoma, and keratitic percipitates on the posterior corneal surface', N''),
( N'Q367756', N'angiomatosis', N'benign vascular malformation involving skin, subcutaneous tissue, skeletal muscle and occasionally bone', N''),
( N'Q3678252', N'trigonitis', N'Inflammation of the trigone of the urinary bladder', N''),
( N'Q367929', N'Klüver–Bucy syndrome', N'syndrome resulting from bilateral lesions of the medial temporal lobe', N''),
( N'Q3680952', N'myeloid sarcoma', N'solid tumor composed of immature white blood cells[2] called myeloblasts.', N''),
( N'Q368562', N'hemopneumothorax', N'medical term describing the combination of two conditions: pneumothorax, or air in the chest cavity, and hemothorax (also called hæmothorax), or blood in the chest cavity', N''),
( N'Q3686833', N'vernal conjunctivitis', N'Human disease', N''),
( N'Q369148', N'neurilemmoma', N'Human disease', N''),
( N'Q369157', N'meningioma', N'Tumor forms from meninges', N''),
( N'Q369262', N'growth hormone deficiency', N'Human disease', N''),
( N'Q370066', N'tolosa-hunt syndrome', N'Human disease', N''),
( N'Q3702898', N'hereditary sensory and autonomic neuropathy', N'congenital disorder of nervous system', N''),
( N'Q3704730', N'adrenocorticotropic hormone deficiency', N'hypopituitarrium that is characterized by a decreased or absent production of adrenocorticotropic hormone by the pituitary gland', N''),
( N'Q3704732', N'antithrombin III deficiency', N'inherited blood coagulation disease characterized by the tendency to form clots in the veins', N''),
( N'Q3705799', N'chronic mucocutaneous candidiasis', N'human disease', N''),
( N'Q3705876', N'dermatomycosis', N'cutaneous mycosis that results in fungal infection located in skin or of its appendages, has material basis in Ascomycota fungi other than the dermatophytes', N''),
( N'Q37062409', N'Pain management in children', N'This is a description of the medical condition of pain in children, its assessment, treatment and prevention', N''),
( N'Q3709312', N'dyskeratosis congenita', N'rare progressive congenital disorder with a highly variable phenotype', N''),
( N'Q3710164', N'X-linked reticulate pigmentary disorder', N'Rare X-linked genetic condition', N''),
( N'Q3710440', N'myoclonic dystonia', N'dystonia characterized by myoclonic jerks affecting mostly proximal muscles and dystonia, usually torticollis or writers cramp, that typically responds to alcohol and has onset in the first of second decade of life', N''),
( N'Q3711812', N'Ullrich congenital muscular dystrophy', N'Ullrich congenital muscular dystrophy (UCMD) is characterized by early-onset, generalized and slowly progressive muscle weakness, multiple proximal joint contractures, marked hypermobility of the distal joints and normal intelligence', N''),
( N'Q371520', N'polydactyly', N'physical anomaly resulting in supernumerary fingers and/or toes', N''),
( N'Q3718816', N'eczema herpeticum', N'Human disease', N''),
( N'Q3724806', N'subdural empyema', N'form of empyema in the subdural space', N''),
( N'Q3725646', N'midface dysplasia', N'Human disease', N''),
( N'Q3726816', N'epiblepharon', N'human disease', N''),
( N'Q3726860', N'epidermolysis bullosa acquisita', N'chronic subepidermal blistering disease associated with autoimmunity to type VII collagen', N''),
( N'Q3726862', N'junctional epidermolysis bullosa', N'skin condition characterized by blister formation within the lamina lucida of the basement membrane zone', N''),
( N'Q372701', N'esophageal cancer', N'gastrointestinal system cancer that is located in the esophagus', N''),
( N'Q372752', N'prostatitis', N'Human disease', N''),
( N'Q3731836', N'congenital ichthyosiform erythroderma', N'rare type of the ichthyosis family of skin diseases', N''),
( N'Q373822', N'eating disorder', N'specific developmental disorder that is characterized by abnormal eating habits that may involve either insufficient or excessive food intake to the detriment of an individuals physical and emotional health', N''),
( N'Q374036', N'Langerhans-cell histiocytosis', N'disease involving clonal proliferation of Langerhans cells', N''),
( N'Q3743188', N'cocaine dependence', N'drug dependence that is a psychological dependency on the regular use of cocaine', N''),
( N'Q3743620', N'cannabis dependence', N'drug dependence that involves the continued use of cannabis despite problems related to use of the substance', N''),
( N'Q3751709', N'environmental disease', N'class of non-hereditary diseases', N''),
( N'Q3765145', N'ichthyosis vulgaris', N'skin disorder causing dry, scaly skin. It is the most common form of ichthyosis', N''),
( N'Q376666', N'cholecystitis', N'cholangitis that is characterized by an inflammation that is located in the gallbladder', N''),
( N'Q3768153', N'pigmented villonodular synovitis', N'human disease', N''),
( N'Q3772406', N'mesangial proliferative glomerulonephritis', N'glomerulonephritis associated primarily with the mesangium', N''),
( N'Q3774229', N'Transient acantholytic dermatosis', N'acantholytic', N''),
( N'Q3774304', N'sycosis', N'', N''),
( N'Q377493', N'selective mutism', N'anxiety disorder causing inability to speak under certain circumstances', N''),
( N'Q3775782', N'apical granuloma', N'tooth disease', N''),
( N'Q3775784', N'Lymphomatoid granulomatosis', N'', N''),
( N'Q3776920', N'bacterial pneumonia', N'pneumonia involving inflammation of the lungs caused by bacteria', N''),
( N'Q377978', N'thrombophlebitis', N'phlebitis that results from a blood clot in the vessel', N''),
( N'Q378681', N'peripheral artery disease', N'artery disease characterized by build up of plaque in the arteries that carry blood to your head, organs, and limbs', N''),
( N'Q379038', N'adult polyglucosan body disease', N'Adult polyglucosan body disease (APBD) is a glycogen storage disease of adults characterized by progressive upper and lower motor neuron dysfunction, progressive neurogenic bladder and cognitive difficulties that can lead to dementia', N''),
( N'Q379054', N'Adult T-cell leukemia/lymphoma', N'Human disease', N''),
( N'Q3791936', N'papillary hidradenoma', N'Human disease', N''),
( N'Q3792460', N'Subdural hygroma', N'collection of cerebrospinal fluid (CSF), without blood, located under the dural membrane', N''),
( N'Q379299', N'vitreous detachment', N'condition of the eye in which the vitreous membrane separates from the retina', N''),
( N'Q379418', N'keratomalacia', N'Human disease', N''),
( N'Q3796380', N'ileitis', N'inflammatory bowel disease characterized by inflammation located in ileum, has symptom diarrhea, has symptom abdominal pain, often in the right lower quadrant, has symptom weight loss', N''),
( N'Q3798547', N'Haverhill fever', N'Human disease', N''),
( N'Q3799243', N'pulmonary valve insufficiency', N'disease that occurs when the pulmonary valve is not strong enough to prevent backflow into the right ventricle', N''),
( N'Q3801491', N'epidermolytic hyperkeratosis', N'rare and severe form of ichthyosis', N''),
( N'Q3801522', N'Caffey disease', N'A bone inflammation disease that causes bone changes, soft tissue swelling and irritability in infants. The disease has been associated with COL1A1 gene. It has symptom soft-tissue swelling, has symptom bone lesions, and has symptom irritability.', N''),
( N'Q3801524', N'hyperpituitarism', N'endocrine disease', N''),
( N'Q3801559', N'Hyperthecosis', N'hyperplasia of the theca interna of the ovary', N''),
( N'Q3801600', N'transient hypogammaglobulinemia of infancy', N'form of hypogammaglobulinemia appearing after birth, leading to a reduction in the level of IgG, and also sometimes IgA and IgM', N''),
( N'Q3801629', N'Hypoprothrombinemia', N'Human disease', N''),
( N'Q3804555', N'X-linked ichthyosis', N'skin condition caused by the hereditary deficiency of the steroid sulfatase (STS) enzyme that affects 1 in 2000 to 1 in 6000 males', N''),
( N'Q3804556', N'lamellar ichthyosis', N'disease', N''),
( N'Q3813599', N'oxycephaly', N'A cephalic disorder where the top of the skull is pointed or conical due to premature closure of the coronal suture plus any other suture.', N''),
( N'Q3813663', N'early infantile epileptic encephalopathy 9', N'infantile epileptic encephalopathy that has material basis in the gene encoding protocadherin-19 (PCDH19) on chromosome Xq22', N''),
( N'Q3820071', N'cholinergic urticaria', N'urticaria induced by sweating', N''),
( N'Q382091', N'post-thrombotic syndrome', N'venous insufficiency that is characterized by aching pain, heaviness, swelling, cramps, itching, or tingling in the affected limb and is a chronic complication of deep venous thrombosis', N''),
( N'Q382370', N'monkeypox', N'viral disease', N''),
( N'Q3824458', N'lipid pneumonia', N'Human disease', N''),
( N'Q3824795', N'exfoliation syndrome', N'Human disease', N''),
( N'Q3825881', N'bladder calculus', N'stone found in the urinary bladder', N''),
( N'Q382641', N'phimosis', N'condition in which the foreskin cannot be pulled back past the glans of the penis', N''),
( N'Q3831227', N'Leukoedema', N'blue, grey or white appearance of mucosae, particularly the buccal mucosa', N''),
( N'Q383126', N'chronic condition', N'human health condition or disease that is persistent or otherwise long-lasting in its effects', N''),
( N'Q383228', N'Gerstmann-Straussler-Scheinker syndrome', N'prion disease characterized by adult onset of memory loss, dementia, ataxia, and pathologic deposition of amyloid-like plaques in the brain', N''),
( N'Q3832889', N'Lymphangiectasia', N'pathologic dilation of lymph vessels', N''),
( N'Q3832896', N'Nodal marginal zone B cell lymphoma', N'marginal zone B-cell lymphoma  which morphologically resembles lymph nodes involved by marginal zone lymphomas of extranodal or splenic types, but without evidence of extranodal or splenic disease', N''),
( N'Q3832897', N'thyroid lymphoma', N'lymphoma primarily involving the thyroid gland', N''),
( N'Q3832899', N'primary effusion lymphoma', N'Primary effusion lymphoma (PEL) is a large B-cell lymphoma located in the body cavities, characterized by pleural, peritoneal, and pericardial fluid lymphomatous effusions and that is always associated with human herpes virus-8 (HHV-8)', N''),
( N'Q3832900', N'splenic marginal zone lymphoma', N'marginal zone B-cell lymphocyte located in the spleen comprised of B-cells in place of white pulp', N''),
( N'Q3840916', N'luteoma', N'ovarian benign neoplasm characterized by solid proliferations of luteinized cells, resulting in a tumor-like ovarian enlargement that regresses during the puerperium', N''),
( N'Q3843800', N'chronic congestive splenomegaly', N'chronic congestive enlargement of the spleen[2] resulting in premature destruction of the red blood cells by the spleen.', N''),
( N'Q3843801', N'DeSanctis–Cacchione syndrome', N'A rare autosomal recessive inherited syndrome. It is characterized by xeroderma pigmentosum, mental retardation, dwarfism, hypogonadism, and neurologic abnormalities.', N''),
( N'Q3843802', N'Hurler–Scheie syndrome', N'MPS - I H/S:  cutaneous condition, also characterized by mild mental retardation and corneal clouding', N''),
( N'Q3843804', N'Acute erythroid leukemia', N'rare form of acute myeloid leukemia (less than 5% of AML cases) where the myeloproliferation is of erythroblastic precursors.', N''),
( N'Q3843807', N'Salla disease', N'autosomal recessive lysosomal storage disease', N''),
( N'Q3843811', N'immune disorder', N'', N''),
( N'Q3854684', N'syphilitic meningitis', N'Human disease', N''),
( N'Q385532', N'spermatocele', N'retention cyst of a tubule of the rete testis or the head of the epididymis distended with barely watery fluid that contains spermatozoa.', N''),
( N'Q3857010', N'Microspherophakia', N'disorder of lens', N''),
( N'Q385774', N'Townes-Brocks syndrome', N'Genetic Disorder', N''),
( N'Q3858675', N'myositis ossificans', N'myositis that is accompanied by ossification of muscle tissue or bony deposits in the muscles', N''),
( N'Q386346', N'tethered spinal cord syndrome', N'human disease', N'')
GO