INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q816422', N'dysmenorrhea', N'pain during menstruation', N''),
( N'Q816798', N'amyloidosis', N'metabolic disease involving abnormal deposited amyloid proteins', N''),
( N'Q816912', N'Benedikt syndrome', N'', N''),
( N'Q817310', N'benign paroxysmal positional nystagmus', N'human disease', N''),
( N'Q81867', N'albinism', N'congenital disorder causing skin to lack pigmentation', N''),
( N'Q819207', N'pseudohypoparathyroidism', N'human disease', N''),
( N'Q81923010', N'Cohen-Gibson syndrome', N'Human disease', N''),
( N'Q8205487', N'Hyaline arteriolosclerosis', N'', N''),
( N'Q820818', N'Phlegmasia cerulea dolens', N'', N''),
( N'Q822228', N'Bernard-Soulier syndrome', N'Human disease', N''),
( N'Q822598', N'renal osteodystrophy', N'Human disease', N''),
( N'Q823027', N'disseminated intravascular coagulation', N'pathological process characterized by the widespread activation of the clotting cascade that results in the formation of blood clots in the small blood vessels throughout the body', N''),
( N'Q823140', N'hereditary coproporphyria', N'Human disease', N''),
( N'Q824292', N'hyponatremia', N'low blood sodium level', N''),
( N'Q824595', N'dysembryoplastic neuroepithelial tumour', N'type of brain tumour', N''),
( N'Q82504', N'endocarditis', N'endocardium disease characterized by inflammation of the endocardium of the heart chambers and valves', N''),
( N'Q825923', N'signet ring cell adenocarcinoma', N'adenocarcinoma that derives from epithelial cells originating in glandular tissue, which have signet ring appearance', N''),
( N'Q826103', N'Reye syndrome', N'syndrome characterized by acute brain damage and liver function problems', N''),
( N'Q826522', N'thyroid cancer', N'endocrine gland cancer located in the thryoid gland located in the neck below the thyroid cartilage', N''),
( N'Q826759', N'status asthmaticus', N'type of asthma', N''),
( N'Q82684153', N'Megavitamin-B6 syndrome', N'', N''),
( N'Q826918', N'bone cyst', N'pseudocystics cavity formations of fibermixoid content in bones', N''),
( N'Q827017', N'gait abnormality', N'deviation from normal walking (gait)', N''),
( N'Q827216', N'Nasal septal hematoma', N'', N''),
( N'Q827497', N'Muir-Torre syndrome', N'Human disease', N''),
( N'Q829150', N'glycogen storage disease IV', N'human disease', N''),
( N'Q8294850', N'physiological plant disorders', N'', N''),
( N'Q829876', N'photokeratitis', N'Eyes with no protection to the UV rays', N''),
( N'Q830265', N'vitelliform macular dystrophy', N'A macular degeneration that can cause progressive vision loss, it is characterized by the disruption of cells in a small area near the center of the retina, the macula.', N''),
( N'Q83030', N'dementia', N'long-term brain disorders causing personality changes and impaired memory, reasoning, and normal function', N''),
( N'Q831363', N'Bethlem myopathy', N'human disease', N''),
( N'Q831530', N'rosacea', N'long-term human skin disease characterized by ruddy reddening of the skin', N''),
( N'Q83319', N'typhoid fever', N'A bacterial infectious disorder contracted by consumption of food or drink contaminated with Salmonella typhi. This disorder is common in developing countries and can be treated with antibiotics.', N''),
( N'Q834047', N'schizoaffective disorder', N'psychotic disorder that is characterized by recurring episodes of mood fluctuations and a loss of contact with reality', N''),
( N'Q835051', N'hyperplasia', N'increase in the amount of organic tissue that results from cell proliferation', N''),
( N'Q835061', N'mastitis', N'inflammation of the breast', N''),
( N'Q835718', N'opportunistic infection', N'infection caused by pathogens that take advantage of an opportunity not normally available', N''),
( N'Q836356', N'croup', N'respiratory condition that is usually triggered by an acute viral infection of the upper airway', N''),
( N'Q837054', N'obsolete adenovirus infectious disease', N'human disease', N''),
( N'Q838018', N'Capgras syndrome', N'psychiatric disorder (syndrome) in which a person holds a delusion that a family member has been replaced by an identical impostor', N''),
( N'Q838139', N'ventricular septal defect', N'heart septal defect characterized by an opening in the interventricular septum, causing a shunt between ventricles', N''),
( N'Q838145', N'leukoplakia', N'condition of the mucous membranes', N''),
( N'Q838966', N'irritable bowel syndrome', N'syndrome that is a functional bowel disorder characterized by chronic abdominal pain, discomfort, bloating, and alteration of bowel habits in the absence of any detectable organic cause', N''),
( N'Q840004', N'cholesterol embolism', N'vascular disease with blood vessel obstruction resulting from the release of cholesterol', N''),
( N'Q840646', N'premature heart beat', N'', N''),
( N'Q840910', N'metritis', N'', N''),
( N'Q841989', N'epulis', N'Human disease', N''),
( N'Q842169', N'sparganosis', N'Helminthiasis', N''),
( N'Q842428', N'ascariasis', N'Human disease', N''),
( N'Q843799', N'adenocarcinoma of the lung', N'non-small cell lung carcinoma that derives from epithelial cells of glandular origin', N''),
( N'Q844590', N'body dysmorphic disorder', N'Mental disorder', N''),
( N'Q844717', N'spina bifida', N'congenital disorder of nervous system', N''),
( N'Q844935', N'coronary artery disease', N'Artery disease characterized by plaque building up along the inner walls of the arteries of the heart resulting in a narrowing of the arteries and a reduced blood supply to the cardiac muscles', N''),
( N'Q845224', N'generalized anxiety disorder', N'anxiety disorder that is characterized by long-lasting anxiety that is not focused on any one object or situation', N''),
( N'Q845698', N'blepharitis', N'eyelid disease that is characterized by often chronic inflammation of the eyelid, generally the part where eyelashes grow', N''),
( N'Q845787', N'histrionic personality disorder', N'personality disorder characterized by excessive emotionality and attention-seeking', N''),
( N'Q846316', N'aplastic anemia', N'anemia that is characterized by a deficiency of red blood cells, white blood cells and platelets produced by bone marrow', N''),
( N'Q847057', N'retinitis pigmentosa', N'retinal degeneration characterized by the gradual deterioration of the photoreceptors or the retinal pigment epithelium of the retina leading to progressive sight loss', N''),
( N'Q847583', N'cardiomyopathy', N'heart disease and a myopathy that is characterised by deterioration of the function of the heart muscle', N''),
( N'Q847605', N'neurofibromatoses', N'human diseases', N''),
( N'Q848343', N'glucose-6-phosphate dehydrogenase deficiency', N'carbohydrate metabolic disorder that is characterised by abnormally low levels of glucose-6-phosphate dehydrogenase (abbreviated G6PD or G6PDH)', N''),
( N'Q848371', N'lichen planus', N'chronic disease of skin, tongue or oral mucosa', N''),
( N'Q848662', N'ventricular fibrillation', N'disorganized electrical activity in the ventricles. It is a type of cardiac arrhythmia Ventricular fibrillation results in cardiac arrest', N''),
( N'Q84955701', N'Anaplastic oligodendroglioma', N'Human disease', N''),
( N'Q8511208', N'intermediate uveitis', N'Human disease', N''),
( N'Q851693', N'chondropathy', N'human disease', N''),
( N'Q852094', N'Couvade syndrome', N'', N''),
( N'Q852423', N'laryngeal cancer', N'respiratory system cancer that is located in the larynx', N''),
( N'Q854573', N'acute pancreatitis', N'Human disease', N''),
( N'Q856736', N'Foreign accent syndrome', N'medical condition', N''),
( N'Q857667', N'pulmonary edema', N'fluid accumulation in the air spaces and parenchyma of the lungs', N''),
( N'Q858426', N'5-alpha-reductase deficiency', N'', N''),
( N'Q859142', N'citrullinemia', N'urea cycle disorder that involves the accumulation of ammonia in the blood.', N''),
( N'Q860167', N'bicuspid aortic valve', N'human disease', N''),
( N'Q860395', N'osteomalacia', N'bone remodeling disease that has material basis in a vitamin D deficiency which results in softening located in bone', N''),
( N'Q860740', N'learning disability', N'range of neurodevelopmental conditions', N''),
( N'Q861028', N'hemangioma', N'cell type benign neoplasm that has physical basis in endothelial cells that line blood vessels and is characterised by increased number of normal or abnormal vessels filled with blood', N''),
( N'Q861224', N'juvenile rheumatoid arthritis', N'rheumatoid arthritis that involves an autoimmune disease onset in children under 16 which attacks the healthy cells and tissue of located in joint', N''),
( N'Q861560', N'schizotypal personality disorder', N'personality disorder that involves a need for social isolation, anxiety in social situations, odd behavior and thinking, and often unconventional beliefs', N''),
( N'Q861645', N'Gauchers disease', N'human disease characterized by deficiency of the enzyme glucocerebrosidase which results in the accumulation of harmful quantities of the glycolipid glucocerebroside throughout the body', N''),
( N'Q861814', N'Biloma', N'', N''),
( N'Q861845', N'kernicterus', N'congenital disorder of nervous system', N''),
( N'Q862872', N'fatal familial insomnia', N'rare form of prion disease characterized by subacute onset of insomnia showing as a reduced overall sleep time, autonomic dysfunction, and motor disturbances', N''),
( N'Q863710', N'condylomata lata', N'', N''),
( N'Q863725', N'Bing–Neel syndrome', N'', N''),
( N'Q863861', N'Hailey-Hailey disease', N'Human disease', N''),
( N'Q864296', N'pituitary adenoma', N'Human disease', N''),
( N'Q864868', N'bone marrow suppression', N'disease', N''),
( N'Q866602', N'multidrug-resistant tuberculosis', N'tuberculosis that is resistant to isoniazid and rifampicin, the two most powerful first-line anti-TB drugs', N''),
( N'Q866622', N'Bisphosphonate-associated osteonecrosis of the jaw', N'disease', N''),
( N'Q868137', N'coccidioidomycosis', N'fungal infection', N''),
( N'Q870891', N'linitis plastica', N'Human disease', N''),
( N'Q874586', N'Peyronies disease', N'Human disease', N''),
( N'Q874632', N'low compliance bladder', N'human disease', N''),
( N'Q876887', N'cellulitis', N'Human disease', N''),
( N'Q8775887', N'hypertensive heart disease', N'heart disease that is caused by high blood pressure', N''),
( N'Q877827', N'diabetic ketoacidosis', N'potentially life-threatening complication in people with diabetes mellitus', N''),
( N'Q88058672', N'COVID-19 disease in pregnancy', N'medical consequences of COVID-19 for pregnant women and foetuses', N''),
( N'Q881480', N'anomalous left coronary artery from the pulmonary artery', N'coronary artery anomaly in which the left coronary artery (LCA) branches off the pulmonary artery instead of the aortic sinus', N''),
( N'Q881811', N'pemphigoid', N'autoimmune blistering diseases', N''),
( N'Q881855', N'gestational trophoblastic neoplasm', N'Human disease', N''),
( N'Q882077', N'blastoma', N'A cell type cancer that has material basis in abnormally proliferating cells derived from precursor cells called blast cells.', N''),
( N'Q883850', N'blepharophimosis', N'Human disease', N''),
( N'Q883863', N'blepharospasm', N'focal dystonia that is characterized by the involuntary, forcible contraction of the muscles controlling eye blinks', N''),
( N'Q884023', N'conjugate gaze palsy', N'Human disease', N''),
( N'Q884590', N'Bloch-Sulzberger syndrome', N'genetic disorder that affects the skin, hair, teeth, nails, and central nervous system.', N''),
( N'Q885574', N'Blue rubber bleb nevus syndrome', N'Blue rubber bleb nevus (BRBNS) is a rare vascular malformation disorder with cutaneous and visceral lesions frequently associated with serious, potentially fatal bleeding and anemia', N''),
( N'Q886261', N'cauliflower ear', N'A permanent deformity caused by physical trauma to the ear', N''),
( N'Q890167', N'giant condyloma acuminatum', N'exophytic tumor of the anogenital region associated with HPV infections', N''),
( N'Q890200', N'blood coagulation disease', N'condition in which the blood’s ability to coagulate (form clots) is impaired', N''),
( N'Q890367', N'argininemia', N'urea cycle disorder that involves arginase deficiency resulting in elevated levels of plasma arginine', N''),
( N'Q890470', N'Legius syndrome', N'rare genetic skin pigmentation disorder characterized by multiple cafe-au-lait macules', N''),
( N'Q892776', N'Bonnet–Dechaume–Blanc syndrome', N'disease', N''),
( N'Q895297', N'boutonneuse fever', N'Human disease', N''),
( N'Q895414', N'Bowenoid papulosis', N'Human disease', N''),
( N'Q895871', N'cortical blindness', N'human disease', N''),
( N'Q895930', N'nodding disease', N'', N''),
( N'Q896643', N'brachydactyly', N'bone development disease characterized by short fingers and toes', N''),
( N'Q899726', N'spinocerebellar ataxia', N'group of dominantly inherited, predominately late-onset, cerebellar ataxias. Neuro-developmental outcome and brain-derived neurotrophic factor level in relation to feeding practice in early infancy.', N''),
( N'Q9002005', N'hemorrhagic fever with renal syndrome', N'Group of clinically similar illnesses caused by species of hantaviruses', N''),
( N'Q905389', N'dichromatopsia', N'human illness, a type of color blindness', N''),
( N'Q905619', N'necrobiosis lipoidica', N'Human disease', N''),
( N'Q906264', N'Phthisis bulbi', N'Human disease', N''),
( N'Q906492', N'dystonia', N'human disease', N''),
( N'Q9079046', N'nonsyndromic deafness', N'auditory system disease that is associated with permanent hearing loss caused by damage to structures in the inner ear and/or the middle ear, which is not associated with other signs and symptoms', N''),
( N'Q907921', N'incontinentia pigmenti achromians', N'Human disease', N''),
( N'Q9081107', N'Pearson syndrome', N'mitochondrial metabolism disease', N''),
( N'Q910455', N'tracheomalacia', N'tracheal disease', N''),
( N'Q911386', N'stomatitis', N'inflammation of the mouth and lips', N''),
( N'Q911427', N'Behçets disease', N'rare immune-mediated small-vessel systemic vasculitis in humans', N''),
( N'Q912344', N'ego-dystonic sexual orientation', N'Human disease', N''),
( N'Q912766', N'postcholecystectomy syndrome', N'Human disease', N''),
( N'Q912796', N'papilloma', N'cell type benign neoplasm that is composed of epithelial tissue on papillae of vascularized connective tissue', N''),
( N'Q913856', N'Friedreich ataxia', N'Human disease', N''),
( N'Q914389', N'Cockayne syndrome', N'rare and fatal autosomal recessive neurodegenerative disorder', N''),
( N'Q915322', N'Coats disease', N'Human disease', N''),
( N'Q9161215', N'MURCS association', N'', N''),
( N'Q916280', N'restless legs syndrome', N'central nervous system disease characterized by throbbing, pulling creeping or other unpleasant sensations in the legs and the irresistible urge to move them', N''),
( N'Q9162871', N'atypical autism', N'autism spectrum disorder that involves some autistic symptoms occuring after age 3 with an abscence of all the traits necessary for a diagnosis of autism', N''),
( N'Q916398', N'lymphedema', N'Human disease', N''),
( N'Q917069', N'rhabdomyolysis', N'Disease', N''),
( N'Q917227', N'Sandhoff disease', N'Sandhoff disease is a lysosomal storage disorder from the GM2 gangliosidosis family and is characterised by central nervous system degeneration', N''),
( N'Q917357', N'Rett syndrome', N'Genetic brain disorder', N''),
( N'Q917399', N'Usher syndrome', N'syndrome characterized by a combination of hearing loss and visual impairment', N''),
( N'Q917447', N'inflammatory bowel diseases', N'intestinal disease characterized by inflammation located in all parts of digestive tract', N''),
( N'Q917620', N'onychomycosis', N'fungal infection of the nail', N''),
( N'Q9177591', N'Kufs disease', N'Neuronal ceroid lipofuscinosis', N''),
( N'Q918285', N'adrenocortical carcinoma', N'adrenal cortex cancer that forms in the outer layer of tissue of the adrenal gland and that has material basis in abnormally proliferating cells derives from epithelial cells', N''),
( N'Q9190356', N'nodular nonsuppurative panniculitis', N'cutaneous condition characterized by recurrent subcutaneous nodules that heal with depression of the overlying skin', N''),
( N'Q9190385', N'Vibroacoustic disease', N'', N''),
( N'Q920766', N'sweating sickness', N'contagious disease of humans that struck England and Europe between 1485 and 1551', N''),
( N'Q921907', N'Charles Bonnet syndrome', N'visual disturbances and the experience of complex visual hallucinations in a blind person', N''),
( N'Q922029', N'pinta disease', N'Human disease', N''),
( N'Q922215', N'insulitis', N'illness', N''),
( N'Q922411', N'hypopituitarism', N'pituitary gland disease characterized by the decreased secretion of one or more of the eight hormones normally produced by the pituitary gland', N''),
( N'Q922640', N'bronchopulmonary dysplasia', N'Human disease', N''),
( N'Q922927', N'primary amebic meningoencephalitis', N'fatal parasitic protozoa infectious disease that involves infection of the central nervous system caused by Naegleria fowleri; symptoms include headache, nausea, rigidity of the neck muscles, vomiting, delirium, seizures and coma.', N''),
( N'Q922971', N'Acanthamoeba keratitis', N'Human disease', N''),
( N'Q923020', N'epidermolysis bullosa', N'human disease', N''),
( N'Q923164', N'expressive aphasia', N'type of aphasia characterized by partial loss of the ability to produce language', N''),
( N'Q923339', N'osteophyte', N'a bone projection formed on the margins of a joint, caused by stress and damage to the surfaces', N''),
( N'Q924002', N'hypertrophy of breast', N'Human disease', N''),
( N'Q924421', N'septic arthritis', N'arthritis that involves infection by a pathogen located in joint syaptic', N''),
( N'Q925092', N'Wolff-Parkinson-White syndrome', N'disorder due to a specific type of problem with the electrical system of the heart which has resulted in symptoms', N''),
( N'Q926462', N'pityriasis versicolor', N'condition characterized by a rash on the trunk and proximal extremities', N''),
( N'Q9274700', N'spotted fever', N'Human disease', N''),
( N'Q928424', N'Barth syndrome', N'lipid metabolism disorder that has material basis in X-linked inheritance of the tafazzin gene and is characterized by decreased production of an enzyme required to produce cardiolipin', N''),
( N'Q928697', N'sensorineural hearing loss', N'type of Hearing Loss', N''),
( N'Q928767', N'Multiple familial trichoepithelioma', N'human disease', N''),
( N'Q9290860', N'choledocholithiasis', N'Human disease', N''),
( N'Q929221', N'invasive lobular carcinoma', N'Human disease', N''),
( N'Q929313', N'cardiac tamponade', N'Compression of the heart due to excessive accumulation of fluid in the pericardium (sac in which the heart is enclosed)', N''),
( N'Q9294051', N'ocular hypertension', N'eye disease that is characterized by elevated intraocular pressure in the absence of optic nerve damage or visual field loss', N''),
( N'Q929737', N'liver disease', N'disorder of the human liver', N''),
( N'Q929833', N'rare disease', N'disease that affects a small percentage of the population', N''),
( N'Q929963', N'primary polydipsia', N'dry mouth and excessive fluid consumption in the absence of physiological stimuli to drink', N''),
( N'Q931323', N'nephropathia epidemica', N'human disease', N''),
( N'Q931538', N'mucolipidosis type IV', N'Lysosomal storage disease', N''),
( N'Q932843', N'pulpitis', N'Human disease', N''),
( N'Q932899', N'Kocher–Debre–Semelaigne syndrome', N'Muscular pseudohypertropy - hypothyroidism, also known as Kocher-Debre-Semelaigne syndrome is a rare disorder characterized by pseudohypertrophy of muscles due to longstanding hypothyroidism (see this term)', N''),
( N'Q933716', N'polycythemia', N'Human disease', N''),
( N'Q934034', N'Chediak-Higashi syndrome', N'autosomal recessive disease characterized by oculocutaneous albinism, immune deficiency, coagulation deficiency and neuropathy; it is that has material basis in mutations in the CHS1 gene', N''),
( N'Q935129', N'postpartum depression', N'endogenous depression that involves intense, sustained and sometimes disabling depression experienced by women after giving birth', N''),
( N'Q935293', N'purpura', N'human disease', N''),
( N'Q935710', N'mitochondrial disease', N'spontaneously occuring or inherited disorder that involves mitochondrial dysfunction', N''),
( N'Q9358981', N'Neuropsychiatric systemic lupus erythematosus', N'', N''),
( N'Q936382', N'hypocalcaemia', N'low calcium levels in blood serum', N''),
( N'Q9363854', N'aneurysm of heart', N'Human disease', N''),
( N'Q936417', N'paraneoplastic syndrome', N'', N''),
( N'Q936549', N'somatoform disorder', N'category of mental disorder', N''),
( N'Q9366868', N'arterial calcification of infancy', N'vascular disease that is characterized by generalized calcification of the arterial internal elastic lamina, leading to rupture of the lamina and occlusive changes in the tunica intima with stenosis and decreased elasticity of the vessel wall', N''),
( N'Q937353', N'echolalia', N'speech disorder that involves the automatic repetition of vocalizations made by another person', N''),
( N'Q9376235', N'endolymphatic hydrops', N'human disease', N''),
( N'Q937818', N'acrodermatitis enteropathica', N'Human disease', N''),
( N'Q938107', N'hypogonadism', N'endocrine disease', N''),
( N'Q938205', N'neuroblastoma', N'An autonomic nervous system neoplasm that is derived from immature nerve cells.', N''),
( N'Q938329', N'Richters syndrome', N'Human disease', N''),
( N'Q9385429', N'Overactive disorder associated with mental retardation and stereotyped movements', N'', N''),
( N'Q9386039', N'perinatal infectious disease', N'human disease', N''),
( N'Q9386865', N'olivopontocerebellar atrophy', N'group of sporadic and inherited neurodegenerative disorders affecting the cerebellum, pons, and inferior olives', N''),
( N'Q938793', N'articular cartilage disease', N'disease involving the articular cartilage of joint', N''),
( N'Q938983', N'osteomyelitis', N'bone inflammation disease that has material basis in infection located in bone or located in bone marrow', N''),
( N'Q938991', N'Monckeberg arteriosclerosis', N'Humans arterial pathology', N''),
( N'Q9390205', N'ADULT syndrome', N'human disease', N''),
( N'Q9390211', N'branchiooculofacial syndrome', N'autosomal dominant disease that is characterized by low birth weight and growth retardation, bilateral branchial clefts', N''),
( N'Q9390252', N'Hoyeraal-Hreidarsson syndrome', N'a rare multisystem disease characterized by intrauterine growth retardation, microcephaly, cerebellar hypoplasia, progressive combined immune deficiency and aplastic anemia.', N''),
( N'Q9390256', N'Jaccouds syndrome', N'Human disease', N''),
( N'Q9390284', N'Netherton syndrome', N'Human disease', N''),
( N'Q9390341', N'Schwartz-Jampel syndrome 1', N'autosomal recessive disease characterized by neuromyotonia and chondrodysplasia that has material basis in hypomorphic mutations in the HSPG2 gene on chromosome 1p36', N''),
( N'Q9390457', N'Hanhart syndrome', N'human disease', N''),
( N'Q9390465', N'Limb body wall complex', N'Limb body wall complex (LBWC) is characterized by severe multiple congenital anomalies in the fetus with exencephaly/encephalocele, thoraco- and/or abdominoschisis (anterior body wall defects) and limb defects, with or without facial clefts', N''),
( N'Q9390597', N'hypogonadotropic hypogonadism 23 with or without anosmia', N'A hypogonadotropic hypogonadism that has_material_basis_in homozygous or compound heterozygous mutation in the LHB gene on chromosome 19q13.', N''),
( N'Q9390614', N'Otodental syndrome', N'congenital disorder of digestive system', N''),
( N'Q939261', N'erythrasma', N'Human disease', N''),
( N'Q939364', N'congenital heart disease', N'cardiovascular disease', N''),
( N'Q940210', N'ankyloblepharon-ectodermal defects-cleft lip/palate syndrome', N'human disease', N''),
( N'Q940874', N'granular cell tumor', N'Human disease', N''),
( N'Q941770', N'proctitis', N'human disease; inflammation of the anus', N''),
( N'Q942755', N'folliculitis', N'Human disease', N''),
( N'Q942926', N'immunoglobulin A deficiency', N'dysgammaglobulinemia characterized by a deficiency of immunoglobulin A', N''),
( N'Q9430213', N'Borna disease', N'horse disease', N''),
( N'Q943897', N'gastroparesis', N'Human disease', N''),
( N'Q944108', N'animal phobia', N'specific phobia that involves a fear caused by the presence or thought of a specific animal that poses little or no danger at all', N''),
( N'Q944758', N'tetraplegia', N'paralysis of all four limbs and torso', N''),
( N'Q944777', N'endometrial cancer', N'uterine cancer that is located in tissues lining the uterus', N''),
( N'Q945238', N'peripheral neuropathy', N'nervous system disease located in nerves or nerve cells', N''),
( N'Q945930', N'progressive supranuclear palsy', N'Progressive supranuclear palsy (PSP) is a rare late-onset neurodegenerative disease characterized by supranuclear gaze palsy, postural instability, progressive rigidity, and mild dementia', N''),
( N'Q946278', N'tracheitis', N'inflammation of the trachea', N''),
( N'Q946882', N'pericoronitis', N'human disease', N''),
( N'Q947813', N'encephalomalacia', N'Human disease', N''),
( N'Q948056', N'dentine hypersensitivity', N'Human disease', N''),
( N'Q948318', N'polycythemia vera', N'human disease', N''),
( N'Q949302', N'skin disease', N'class of disorder that affects skin, hair or nails', N''),
( N'Q949694', N'amebiasis', N'human protozoa disease', N''),
( N'Q950591', N'scotoma', N'Human disease', N''),
( N'Q950838', N'germinoma', N'germ cell cancer that lacks histologic differentiation. It usually refers to a tumor in the brain', N''),
( N'Q953049', N'Papilledema', N'Human disease', N''),
( N'Q953330', N'fibrillary astrocytoma', N'astrocytoma that is characterized as a low grade astrocytoma and has material basis in neoplastic astrocytes', N''),
( N'Q953638', N'Wiskott-Aldrich syndrome', N'rare disease', N''),
( N'Q954625', N'myelodysplastic syndrome', N'diverse collection of blood-related medical conditions with ineffective production of the myeloid class of blood cells', N''),
( N'Q954674', N'iron deficiency anemia', N'anemia caused by a lack of iron', N''),
( N'Q954831', N'prolactinoma', N'adenoma of the pituitary gland producing prolactin', N''),
( N'Q955454', N'Coxa valga', N'', N''),
( N'Q955638', N'high pressure neurological syndrome', N'neurological and physiological disorder experienced by divers', N''),
( N'Q957751', N'XY gonadal dysgenesis', N'gonadal dysgenesis that is characterized by a normal 46,XY karyotype along with a progressive loss of germ cells on the developing gonads of an embryo', N''),
( N'Q958797', N'scleroderma', N'rheumatic disease and collagen disease that involves the abnormal growth of connective tissue, which supports the skin and internal organs', N''),
( N'Q959211', N'chylomicron retention disease', N'Human disease', N''),
( N'Q959457', N'inappropriate ADH syndrome', N'endocrine disease', N''),
( N'Q959922', N'carbuncle', N'human disease', N''),
( N'Q961331', N'pilonidal cyst', N'hair-containing cyst or sinus, occurring chiefly in the coccygeal region', N''),
( N'Q96185025', N'Colonic ulcer', N'', N''),
( N'Q963944', N'melioidosis', N'Human disease', N''),
( N'Q964920', N'gingival recession', N'human disease', N''),
( N'Q966052', N'cryptorchidism', N'defective mammal development', N''),
( N'Q966149', N'McLeod syndrome', N'', N''),
( N'Q966229', N'myxedema', N'Human disease', N''),
( N'Q970203', N'milk allergy', N'type of food allergy caused by milk', N''),
( N'Q970208', N'liver failure', N'Inability of the liver to perform its normal functions', N''),
( N'Q970826', N'Gulf War syndrome', N'syndrome affecting returning military veterans and civilian workers of the Gulf War', N''),
( N'Q97194759', N'Segmental colitis associated with diverticulosis', N'', N''),
( N'Q972514', N'optic neuritis', N'optic nerve disease that results in inflammation located in optic nerve which may cause a complete or partial loss of vision', N''),
( N'Q973524', N'spondylolisthesis', N'bone structure disease that has material basis in displacement located in set of vertebrae', N''),
( N'Q97366919', N'Prefibrotic primary myelofibrosis', N'', N''),
( N'Q97403851', N'Sickle cell retinopathy', N'', N''),
( N'Q974691', N'epidermodysplasia verruciformis', N'Human disease', N''),
( N'Q974869', N'leukocytosis', N'condition in which the white cell count in blood is above the normal range', N''),
( N'Q974928', N'pycnodysostosis', N'osteochondrodysplasia that has material basis in a mutation in the CTSK gene which results in dwarfism, brittle bones, osteopetrosis, shortening of the distal phalanges', N''),
( N'Q97495320', N'Exposure keratopathy', N'', N''),
( N'Q975182', N'Pelger-Huet anomaly', N'Human disease', N''),
( N'Q975705', N'gastric mucosal hypertrophy', N'Human disease', N''),
( N'Q976163', N'polyhydramnios', N'placenta disease that is characterized by an excess of amniotic fluid in the amniotic sac', N''),
( N'Q976388', N'acute leukemia', N'Human disease', N''),
( N'Q977090', N'vulvovaginal candidiasis', N'excessive growth of yeast in the vagina that results in irritation', N''),
( N'Q977787', N'gallbladder cancer', N'biliary tract cancer that is located in the gallbladder', N''),
( N'Q979049', N'erythema marginatum', N'', N''),
( N'Q979129', N'congenital central hypoventilation syndrome', N'Human disease', N''),
( N'Q979168', N'cerebral edema', N'human disease', N''),
( N'Q980709', N'status epilepticus', N'human disease', N''),
( N'Q980926', N'polymyositis', N'rare idiopathic inflammatory myopathy characterized by symmetric proximal muscle weakness and elevated muscle enzymes', N''),
( N'Q98266891', N'Shrunken pore syndrome', N'', N''),
( N'Q987319', N'secondary hypertension', N'human disease', N''),
( N'Q988405', N'essential hypertension', N'hypertension with no known cause, the most common type of hypertension', N''),
( N'Q991023', N'Browns tendon sheath syndrome', N'Human disease', N''),
( N'Q991037', N'Brown-Séquard syndrome', N'Human disease', N''),
( N'Q991538', N'pituitary apoplexy', N'Human disease', N''),
( N'Q992139', N'human granulocytic anaplasmosis', N'human disease', N''),
( N'Q994794', N'noma', N'human disease', N''),
( N'Q994859', N'homocystinuria', N'amino acid metabolic disorder that involves an accumulation of homocysteine in the serum and an increased excretion of homocysteine in the urine', N''),
( N'Q994942', N'bruxism', N'disorder that involves involuntarily grinding or clenching of the teeth', N''),
( N'Q998273', N'Smith-Lemli-Opitz syndrome', N'an inborn error of cholesterol synthesis. It is an autosomal recessive, multiple malformation syndrome caused by a mutation in the enzyme 7-Dehydrocholesterol reductase, or DHCR7.', N''),
( N'Q10874', N'blindness', N'complete or nearly complete lack of vision', N''),
( N'Q11072', N'amnesia', N'cognitive disorder where the memory is disturbed or lost and involves the loss of memories previously established, loss of the ability to create new memories, continuous high blood pressure and severe shock may also caused amnesia', N''),
( N'Q11081', N'Alzheimers disease', N'progressive, neurodegenerative disease characterized by memory loss', N''),
( N'Q11085', N'Parkinsons disease', N'long-term degenerative neurological disorder that mainly affects movement', N''),
( N'Q11088', N'coeliac disease', N'long term autoimmune disorder caused by a reaction to gluten', N''),
( N'Q12078', N'cancer', N'group of diseases', N''),
( N'Q12090', N'cholera', N'bacterial infection of the small intestine', N''),
( N'Q12135', N'mental disorder', N'behavioral or mental pattern that causes significant distress or impairment of personal functioning', N''),
( N'Q12152', N'myocardial infarction', N'interruption of blood supply to a part of the heart', N''),
( N'Q12156', N'malaria', N'Mosquito-borne infectious disease', N''),
( N'Q12174', N'obesito', N'medical condition in which excess body fat harms health', N''),
( N'Q12192', N'pneumonia', N'inflammatory condition of the lung', N''),
( N'Q12195', N'poliomyelitis', N'human disease', N''),
( N'Q12199', N'HIV/AIDS', N'human disease resulting from HIV II', N''),
( N'Q12202', N'stroke', N'problem with the arteries supplying blood to the brain', N''),
( N'Q12204', N'tuberculosis', N'infectious disease caused by the bacterium Mycobacterium tuberculosis', N''),
( N'Q12206', N'diabetes mellitus', N'group of metabolic disorders characterized by high blood sugar levels over a prolonged period', N''),
( N'Q12214', N'smallpox', N'eradicated human disease', N''),
( N'Q1472', N'Crohns disease', N'type of inflammatory bowel disease', N''),
( N'Q1477', N'ulcerative colitis', N'inflammatory bowel disease that causes ulcers in the colon', N''),
( N'Q1485', N'systemic lupus erythematosus', N'inflammation of connective tissue marked by skin rashes, joint pain and swelling, inflammation of the kidneys and inflammation of the tissue surrounding the heart.', N''),
( N'Q16483', N'toxic diffuse goiter', N'endocrine disease', N''),
( N'Q16485', N'De Quervains thyroiditis', N'Thyroid disease', N''),
( N'Q16488', N'postpartum thyroiditis', N'thyroid disease', N''),
( N'Q16495', N'Riedels fibrosing thyroiditis', N'thyroid disease', N''),
( N'Q16499', N'hyperthyroidism', N'thyroid gland disease that involves an over Production of thyroid hormone.', N''),
( N'Q16501', N'hypothyroidism', N'human disease', N''),
( N'Q17583', N'miliary tuberculosis', N'extrapulmonary tuberculosis that results in formation of tiny lesions in all the organs', N''),
( N'Q18576', N'Pick disease', N'rare neurodegenerative disorder, characterized by formation of Pick bodies', N''),
( N'Q18579', N'frontotemporal lobar degeneration', N'group of disorders', N''),
( N'Q18583', N'progressive nonfluent aphasia', N'neurological disorder', N''),
( N'Q18592', N'frontotemporal dementia', N'medical condition', N''),
( N'Q18654', N'dissociative amnesia', N'Human disease', N''),
( N'Q18657', N'dissociative identity disorder', N'mental disorder, characterized by multiple personality states and amnesia', N''),
( N'Q18671', N'intermittent explosive disorder', N'impulse control disorder that involves the episodic inability to control violent impulses with a disproportionate degree of aggressiveness', N''),
( N'Q18740', N'transient global amnesia', N'amnestic disorder that is characterized by temporary but almost total disruption of short-term memory with a range of problems accessing older memories.', N''),
( N'Q18742', N'visual agnosia', N'impairment in recognition of visually presented objects', N''),
( N'Q25556', N'anovulation', N'human disease', N''),
( N'Q25787', N'recurrent miscarriage', N'Human disease', N''),
( N'Q26967', N'telogen effluvium', N'Human disease', N''),
( N'Q2836', N'aphasia', N'inability to use spoken language', N''),
( N'Q28693', N'miscarriage', N'natural death of an embryo or fetus before it is able to survive independently', N''),
( N'Q28814', N'autoimmune hemolytic anemia', N'autoimmune disease of blood that is characterized by deficient red blood cells caused by auto-antibodies.', N''),
( N'Q29496', N'leukemia', N'group of cancers that usually begin in the bone marrow', N''),
( N'Q30953', N'dengue fever', N'tropical disease caused by the dengue virus, transmitted by mosquito', N''),
( N'Q31798', N'chancroid', N'sexually transmitted bacterial infection in humans', N''),
( N'Q32446', N'pulmonary fibrosis', N'human disease', N''),
( N'Q32540', N'eosinophilic pneumonia', N'disease in which an eosinophil, a type of white blood cell, accumulates in the lung', N''),
( N'Q32552', N'Loeffler syndrome', N'Human disease', N''),
( N'Q32778', N'bronchiectasis', N'disorder of respiratory system', N''),
( N'Q32811', N'Churg-Strauss syndrome', N'vasculitits that is systemic vasculitis realized as blood vessel inflammation and has_symptom asthma along with hay fever, rash and gastrointestinal bleeding.', N''),
( N'Q33121', N'serum sickness', N'negative reaction against proteins which are contained in a specific serum', N''),
( N'Q33525', N'carcinoma', N'cell type cancer that has material basis in abnormally proliferating cells derives from epithelial cells', N''),
( N'Q35869', N'asthma', N'long-term disease involving inflamed airways', N''),
( N'Q35890', N'extrinsic allergic alveolitis', N'Human disease', N''),
( N'Q36855', N'swine influenza', N'infection caused by any one of several types of swine influenza viruses', N''),
( N'Q36956', N'leprosy', N'Chronic infection caused by bacteria Mycobacteria lepræ and lepromatosis', N''),
( N'Q39222', N'rabies', N'viral disease', N''),
( N'Q40301', N'parathyroid carcinoma', N'endocrine disease', N''),
( N'Q40878', N'diarrhea', N'loose or liquid bowel movements', N''),
( N'Q41083', N'syphilis', N'sexually transmitted infection', N''),
( N'Q41091', N'anal stricture', N'human disease', N''),
( N'Q41112', N'schizophrenia', N'psychotic disorder characterized by emotional responsiveness and disintegration of thought process', N''),
( N'Q41478', N'hemorrhoid', N'vascular structures in the anal canal', N''),
( N'Q41571', N'epilepsy', N'human neurological disease causing seizures', N''),
( N'Q41861', N'arterial hypertension', N'Long term medical condition with elevated arterial blood pressure (for pulmonary hypertension use Q1128595, for intracranial hypertension use Q18558125)', N''),
( N'Q42844', N'major depressive disorders', N'all-encompassing low mood accompanied by low self-esteem, and by loss of interest or pleasure in normally enjoyable activities.', N''),
( N'Q42982', N'allergy', N'immune system response to a substance that most people tolerate well', N''),
( N'Q43405', N'exhibitionism', N'act of exposing in a public or semi-public context those parts of ones body that are not normally exposed', N''),
( N'Q43898', N'Epiploic appendagitis', N'', N''),
( N'Q43987', N'avian influenza', N'influenza caused by viruses adapted to birds', N''),
( N'Q47715', N'Down syndrome', N'chromosomal condition characterized by flat-looking facial features and weak muscle tone (hypotonia) in infancy and is caused by trisomy of all or a critical portion of chromosome 21 and is associated with intellectual disability', N''),
( N'Q47790', N'tetanus', N'bacterial infection characterized by muscle spasms', N''),
( N'Q47912', N'lung cancer', N'cancer in the lung', N''),
( N'Q48143', N'meningitis', N'inflammation of membranes around the brain and spinal cord', N''),
( N'Q49970', N'hyperuricemia', N'acquired metabolic disease that has material basis in an abnormally high level of uric acid in the blood.', N''),
( N'Q49989', N'Creutzfeldt-Jakob disease', N'degenerative neurological disorder', N''),
( N'Q52844', N'enthesopathy', N'human disease: a disorder involving the attachment of a tendon or ligament to a bone', N''),
( N'Q52848', N'spondyloarthropathy', N'joint disease of the vertebral column', N''),
( N'Q52849', N'ankylosing spondylitis', N'a type of arthritis in which there is long term inflammation of the joints of the spine', N''),
( N'Q52851', N'plantar fasciitis', N'Human disease', N''),
( N'Q52854', N'frozen shoulder', N'painful human disease of uncertain origin affecting the shoulder capsule', N''),
( N'Q52856', N'diabetic foot', N'foot that exhibits any pathology that results directly from diabetes mellitus or any long-term complication of diabetes mellitus', N''),
( N'Q52859', N'diabetic foot ulcer', N'major complication of diabetes mellitus', N''),
( N'Q53829', N'thyroid nodule', N'human disease', N''),
( N'Q5445', N'anemia', N'decrease in number of red blood cells', N''),
( N'Q55998', N'pleurisy', N'inflammation of the membranes that surround the lungs', N''),
( N'Q56002', N'ventricular tachycardia', N'fast heart rhythm that originates in one of the ventricles of the heart', N''),
( N'Q61335', N'pre-eclampsia', N'hypertension occurring during pregnancy', N''),
( N'Q62736', N'osteoarthritis', N'form of arthritis caused by degeneration of joints', N''),
( N'Q6853', N'hepatitis B', N'human viral infection', N''),
( N'Q8277', N'multiple sclerosis', N'disease that damages the myelin sheaths around nerve axons', N''),
( N'Q8280', N'herpes gestationis', N'dermatosis of pregnancy', N''),
( N'Q8282', N'Addisons disease', N'adrenal cortical hypofunction that is characterized by insufficient steroid hormone production by the adrenal glands', N''),
( N'Q8285', N'myasthenia gravis', N'human disease', N''),
( N'Q8388', N'pedophilia', N'paraphilia characterized by a sexual attraction to prepubescent children', N''),
( N'Q8392', N'zoophilia', N'paraphilia involving a sexual fixation on non-human animal', N'')
GO