INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q1416773', N'granuloma inguinale', N'sexually transmitted bacterial disease', N''),
( N'Q1417240', N'benign neoplasm', N'disease of cellular proliferation that results in abnormal growths in the body which lack the ability to metastasize', N''),
( N'Q1418152', N'Mobius syndrome', N'rare disease', N''),
( N'Q1418225', N'autoimmune polyendocrine syndrome type 2', N'An autoimmune polyendocrine syndrome that is characterized by abnormal functioning of the immune system that causes auto-reactivity against endocrine organs. It is more heterogeneous and has not been linked to one gene.', N''),
( N'Q1418735', N'neurofibroma', N'Human disease', N''),
( N'Q1419261', N'Maffucci syndrome', N'syndrome characterized by the presence of multiple enchondromas (benign growths of cartilage) associated with multiple cavernous hemangiomas and phleboliths', N''),
( N'Q1419862', N'stork bite', N'Human disease', N''),
( N'Q1419931', N'Niemann-Pick disease', N'severe metabolic disorders in which sphingomyelin accumulates in lysosomes in cells', N''),
( N'Q1421738', N'glycogen storage disease', N'glycogen metabolism disorder that has material basis in enzymes deficiencies necessary in the processing of glycogen synthesis or breakdown within muscles, liver, and other cell types', N''),
( N'Q1422034', N'Cronkhite-Canada syndrome', N'syndrome characterized by multiple polyps of the digestive tract', N''),
( N'Q1422574', N'Gradenigos syndrome', N'complication of otitis media and mastoiditis involving the apex of the petrous temporal bone', N''),
( N'Q1423087', N'retinopathy of prematurity', N'disease of the eye affecting prematurely born babies generally having received intensive neonatal care, in which oxygen therapy is used on them due to the premature development of their lungs', N''),
( N'Q1423167', N'phlebitis', N'vein disease that is characterized by inflammation of a vein', N''),
( N'Q1423177', N'breast fibrocystic disease', N'Human disease', N''),
( N'Q1423538', N'gamma chain deficiency', N'immunodeficiency disorder in which the body produces very few T cells and NK cells', N''),
( N'Q1424106', N'interstitial nephritis', N'type of nephritis affecting the interstitium of the kidneys surrounding the tubules', N''),
( N'Q1424488', N'dacryoadenitis', N'human disease', N''),
( N'Q1424491', N'Aplasia cutis congenita', N'', N''),
( N'Q1424509', N'plantar fascial fibromatosis', N'non-malignant thickening of the feets deep connective tissue', N''),
( N'Q1424612', N'intussusception', N'Human disease', N''),
( N'Q1424956', N'neuroleptic malignant syndrome', N'nervous system disease that is characterized by hyperthermia, muscular rigidity, autonomic dysfunction and altered consciousness and is associated with administration of antipsychotic and other central dopaminergic blockers', N''),
( N'Q1425185', N'oral hairy leukoplakia', N'mouth disease characterized by a white patch on the lateral sides of the tongue with a corrugated or hairy appearance; caused by Epstein-Barr virus', N''),
( N'Q1425208', N'hallux rigidus', N'disease', N''),
( N'Q1425572', N'Fraser syndrome', N'autosomal recessive congenital disorder', N''),
( N'Q1426491', N'thrombotic thrombocytopenic purpura', N'human disease', N''),
( N'Q1427032', N'macular hole', N'Human disease', N''),
( N'Q1427959', N'dental fluorosis', N'human disease', N''),
( N'Q142807', N'floater', N'deposits of various size, shape, consistency, refractive index, and motility within the eyes vitreous humour, which is normally transparent', N''),
( N'Q1428132', N'Cerebral venous sinus thrombosis', N'presence of acute thrombosis (a blood clot) in the dural venous sinuses, which drain blood from the brain.', N''),
( N'Q1428695', N'focal dystonia', N'dystonia that is localized to a specific part of the body', N''),
( N'Q1429863', N'thymoma', N'thymus cancer that derives from epithelial cells', N''),
( N'Q1430844', N'allergic bronchopulmonary aspergillosis', N'aspergillosis that involves an allergic reaction due to the spores of Aspergillus moulds (A. fumigatus), which colonizes the mucus in the airways causing inflammation', N''),
( N'Q1431371', N'Frey syndrome', N'Human disease', N''),
( N'Q1431933', N'Aortoiliac occlusive disease', N'', N''),
( N'Q1433212', N'myositis', N'myopathy characterized by muscle inflammation', N''),
( N'Q1433936', N'hyperprolactinemia', N'acquired metabolic disease that has material basis in the presence of abnormally-high levels of prolactin in the blood', N''),
( N'Q1434446', N'nephrosclerosis', N'medical condition referring to damage to the kidney due to chronic high blood pressure', N''),
( N'Q1434575', N'spermatic cord torsion', N'spermatic cord (from which the testicle is suspended) twists, cutting off the testicles blood supply', N''),
( N'Q1435202', N'Foix–Chavany–Marie syndrome', N'Illness', N''),
( N'Q1435219', N'focal nodular hyperplasia', N'benign hepatic vascular tumors', N''),
( N'Q1435223', N'focal segmental glomerulosclerosis', N'kidney disease', N''),
( N'Q1435822', N'neutropenia', N'abnormally low concentration of neutrophils in the blood', N''),
( N'Q1436099', N'nymphomania', N'', N''),
( N'Q1436162', N'pantothenate kinase-associated neurodegeneration', N'A neurodegeneration with brain iron accumulation that has_material_basis_in autosomal recessive inheritance of mutation in the PANK2 gene on chromosome 20p13.', N''),
( N'Q1436558', N'adenoid hypertrophy', N'upper respiratory tract disease characterized by the unusual growth of the adenoid tonsil; has symptom snoring, has symptom hyponasality, has symptom otitis media with effusion, has symptom mouth breathing', N''),
( N'Q1437103', N'angiokeratoma of Fordyce', N'sebaceous glands that are present in most individuals', N''),
( N'Q1437472', N'atransferrinemia', N'Human disease', N''),
( N'Q14375936', N'hyperinsulinemia', N'condition in which there are excess levels of insulin circulating in the blood relative to the level of glucose', N''),
( N'Q143790', N'Alien hand syndrome', N'neuropsychiatric disorder', N''),
( N'Q143925', N'toothache', N'medical condition of the teeth', N''),
( N'Q1440436', N'fragile X-associated tremor/ataxia syndrome', N'Fragile X-associated tremor/ataxia syndrome (FXTAS) is a rare neurodegenerative disorder characterized by adult-onset progressive intention tremor and gait ataxia', N''),
( N'Q144119', N'hysteria', N'former diagnostic category', N''),
( N'Q1442621', N'Tangier disease', N'extremely rare inherited human disorder', N''),
( N'Q1444550', N'ischaemic heart disease', N'', N''),
( N'Q1446169', N'collagen disease', N'systemic autoimmune diseases (e.g., rheumatoid arthritis, systemic lupus erythematosus, and systemic sclerosis), but now is thought to be more appropriate for diseases associated with defects in collagen, which is a component of the connective tissue', N''),
( N'Q14509067', N'exanthem', N'Human disease', N''),
( N'Q1451877', N'embryonal carcinoma', N'embryonal cancer that is a type of germ cell tumour, located in the ovaries or testes', N''),
( N'Q1452604', N'multiple epiphyseal dysplasia', N'An osteochondrodysplasia that has material basis in defective cartilage mineralization into bone which results in irregular ossification centers of the located in hip or located in knee. The disease has symptom fatigue, has symptom joint pain.', N''),
( N'Q1453590', N'freemartinism', N'genetic condition of female mammals', N''),
( N'Q1453767', N'Fregoli delusion', N'psychopathological syndrome', N''),
( N'Q1455531', N'endemic goiter', N'human disease', N''),
( N'Q1456383', N'situs inversus', N'congenital condition in which the major visceral organs are reversed from their normal positions', N''),
( N'Q1456403', N'Legg-Calve-Perthes disease', N'osteochondrosis that results in death and fracture located in hip joint', N''),
( N'Q1456558', N'angular cheilitis', N'cheilitis characterized by inflammation of one or both of the corners of the mouth', N''),
( N'Q1456924', N'Madelungs deformity', N'Madelung disease, or deformity (MD) is a predominantly bilateral wrist anomaly characterized by shortened and bowed radii and long ulnae leading to dorsal dislocation of the distal ulna and limited mobility of the wrist and elbow', N''),
( N'Q1457267', N'schizencephaly', N'rare birth defect characterized by abnormal clefts lined with grey matter that form the ependyma of the cerebral ventricles to the pia mater.', N''),
( N'Q14594748', N'Webbed penis', N'', N''),
( N'Q1459798', N'Keratoglobus', N'degenerative non-inflammatory disorder of the eye in which structural changes within the cornea cause it to become extremely thin and change to a more globular shape than its normal gradual curve', N''),
( N'Q1459821', N'holoprosencephaly', N'congenital disorder of the nervous system', N''),
( N'Q1459851', N'Hallermann-Streiff syndrome', N'congenital disorder', N''),
( N'Q1462309', N'coloboma', N'eye disease characterized by missing pieces of tissue in structures that form the eye, such as the iris, retina, choroid or optic disc', N''),
( N'Q1464888', N'Fuchs endothelial dystrophy', N'corneal dystrophy characterized by accumulation of focal outgrowths (guttae) and thickening of Descemets membrane, leading to corneal edema and loss of vision', N''),
( N'Q1467170', N'Chronic Somogyi rebound', N'', N''),
( N'Q1467339', N'hypertriglyceridemia', N'elevated levels of triglycerides in the blood', N''),
( N'Q1469637', N'Prinzmetals angina', N'cardiac chest pain at rest that occurs in cycles', N''),
( N'Q1469646', N'Bloom syndrome', N'rare genetic disorder with short strature and predisposition to cancer', N''),
( N'Q1470140', N'cryptococcosis', N'Potentially fatal disease', N''),
( N'Q1470530', N'delayed sleep phase disorder', N'chronic mismatch between a persons normal daily rhythm, compared to other people and societal norms', N''),
( N'Q1471410', N'placenta praevia', N'placenta disease that is characterized by placenta attachment to the uterine wall close to or covering the cervix', N''),
( N'Q1471642', N'micropenis', N'unusually small penis', N''),
( N'Q1472019', N'apparent life-threatening event syndrome', N'', N''),
( N'Q147270', N'cone dystrophy', N'inherited ocular disorder characterized by the loss of cone cells', N''),
( N'Q1472818', N'common variable immunodeficiency', N'immune disorder characterized by recurrent infections and low antibody levels, specifically in immunoglobulin', N''),
( N'Q147362', N'ovarian cyst', N'fluid-filled sac in the ovary', N''),
( N'Q1473749', N'Müllerian agenesis', N'congenital malformation of female reproductive organs', N''),
( N'Q1473802', N'osteoid osteoma', N'benign bone tumor that arises from osteoblasts and was originally thought to be a smaller version of an osteoblastoma', N''),
( N'Q1474598', N'functional disorder', N'medical condition that impairs normal functioning of bodily processes', N''),
( N'Q1474877', N'hypercalcemia', N'high calcium (Ca2+) level in the blood serum', N''),
( N'Q1475667', N'taeniasis', N'parasitic disease due to infection with tapeworms belonging to the genus Taenia', N''),
( N'Q1475743', N'Robinow syndrome', N'syndrome characterized by mild to moderate short stature due to growth delays after birth, distinctive craniofacial abnormalities, skeletal malformations and genital abnormalities', N''),
( N'Q1476361', N'HAM', N'human disease', N''),
( N'Q1476525', N'lipid metabolism disorder', N'An inherited acute metabolic disorder that involves the creation and degradation of lipids.', N''),
( N'Q1476789', N'jaw-winking syndrome', N'autosomal dominant condition with incomplete penetrance, in which nursing infants will have rhythmic upward jerking of their upper eyelid', N''),
( N'Q1476965', N'xanthinuria', N'purine-pyrimidine metabolic disorder characterized by deficiency of xanthine oxidase, resulting in excretion of large amounts of xanthine in the urine and the formation of xanthine stones', N''),
( N'Q1477265', N'pseudopseudohypoparathyroidism', N'a rare genetic disorder in the human body', N''),
( N'Q1477777', N'osteopoikilosis', N'osteosclerosis that results in numerous bone islands located in skeleton', N''),
( N'Q147778', N'liver cirrhosis', N'long-term disease of the liver', N''),
( N'Q1478321', N'spinal stenosis', N'bone deterioration disease that has material basis in bony spurs, disc degeneration, or thickened ligaments which results in narrowing located in spinal cord', N''),
( N'Q1479494', N'paroxysmal nocturnal hemoglobinuria', N'disease of the blood characterized by destruction of red blood cells by the complement system, a part of the bodys innate immune system', N''),
( N'Q1479497', N'porphyria cutanea tarda', N'acute porphyria characterized by painful, blistering skin lesions that develop on sun-exposed skin', N''),
( N'Q1479681', N'mucopolysaccharidosis', N'lysosomal storage disease that involves the accumulation of glycosaminoglycans in the tissues and their excretion in the urine', N''),
( N'Q1480377', N'periostitis', N'medical condition caused by inflammation of the periosteum, a layer of connective tissue that surrounds bone', N''),
( N'Q1482034', N'combat disorder', N'acute stress disorder that involves neurotic reactions to unusual, severe, or overwhelming military stress', N''),
( N'Q1483214', N'pemphigus', N'rare group of blistering autoimmune diseases that affect the skin and mucous membranes', N''),
( N'Q1484058', N'short QT syndrome', N'heart conduction disease that is characterized by heart arrhythmia defined as a short QT interval on an EKG (less than 300 ms) that does not significantly change with heart rate, tall and peaked T waves, and a structurally normal heart', N''),
( N'Q1484679', N'gastric antral vascular ectasia', N'Human disease', N''),
( N'Q1485893', N'encephalopathy due to GLUT1 deficiency', N'disease', N''),
( N'Q14870002', N'Hot tub folliculitis', N'', N''),
( N'Q14917216', N'myrmecia', N'virus-related cutaneous foot disease', N''),
( N'Q1492283', N'Biliary sludge', N'disease', N''),
( N'Q1493513', N'gangliosidosis', N'Human disease', N''),
( N'Q1494009', N'pulmonary cyst', N'', N''),
( N'Q14942021', N'auto-brewery syndrome', N'medical condition in which intoxicating quantities of ethanol are produced within the digestive system', N''),
( N'Q1495085', N'gas gangrene', N'Human disease', N''),
( N'Q1495661', N'gastrointestinal stromal tumor', N'Human disease', N''),
( N'Q1495674', N'gastroschisis', N'birth defect in which the babys intestines extend outside of the body through a hole next to the belly button.', N''),
( N'Q1499629', N'joint effusion', N'effusion of watery liquid into the cavity of a joint', N''),
( N'Q1500373', N'lactic acidosis', N'acquired metabolic condition that has material basis in low pH in body tissues and blood accompanied by the buildup of lactate especially D-lactate', N''),
( N'Q1501239', N'insulinoma', N'adenoma that is located in the pancreas and is characterized by overproduction of insulin', N''),
( N'Q1502312', N'polyneuropathy', N'peripheral system disease that is characterized by damage affecting peripheral nerves (peripheral neuropathy) in roughly the same areas on both sides of the body, featuring weakness, numbness, pins-and-needles, and burning pain', N''),
( N'Q15043325', N'benzodiazepine abuse', N'the use of benzodiazepines without a prescription, often for recreational purposes, which poses risks of dependence, withdrawal and other long-term effects', N''),
( N'Q15043641', N'Frontotemporal dementia and parkinsonism linked to chromosome 17', N'', N''),
( N'Q1504570', N'protein C deficiency', N'rare genetic trait that predisposes to thrombotic disease', N''),
( N'Q1504713', N'leiomyosarcoma', N'malignant smooth muscle cancer that can arise almost anywhere in the body, but is most common in the uterus, abdomen, or pelvis', N''),
( N'Q15051314', N'steroid inherited metabolic disorder', N'lipid metabolism disorder that involves defects in steroid metabolism', N''),
( N'Q15051322', N'inborn error of lipid metabolism', N'', N''),
( N'Q1505689', N'tenosynovitis', N'inflammation of the fluid-filled sheath (called the synovium) that surrounds a tendon, typically leading to joint pain, swelling, and stiffness', N''),
( N'Q15057288', N'Anotia', N'', N''),
( N'Q1506216', N'Hermansky-Pudlak syndrome', N'rare disease', N''),
( N'Q1506572', N'atrial flutter', N'abnormal heart rhythm that starts in the atrial chambers of the heart', N''),
( N'Q1507379', N'nemaline myopathy', N'congenital structural myopathy characterized by generally non-progressive muscle weakness of varying severity', N''),
( N'Q1507609', N'ochronosis', N'syndrome caused by the accumulation of homogentisic acid in connective tissues', N''),
( N'Q1509367', N'rapidly progressive glomerulonephritis', N'human disease', N''),
( N'Q1511436', N'auditory agnosia', N'agnosia that is a loss of the ability to distinguishing environmental and non-verbal auditory cues including difficulty distinguishing speech from non-speech sounds even though hearing is usually normal', N''),
( N'Q15124212', N'lung neoplasm', N'disease', N''),
( N'Q1515038', N'thyroid hormone resistance syndrome', N'Human disease', N''),
( N'Q1515119', N'Gerstmann syndrome', N'nervous system disease that results from damage located in left parietal lobe, has symptom agraphia, has symptom acalculia, has symptom finger agnosia', N''),
( N'Q1515163', N'SAPHO syndrome', N'variety of inflammatory bone disorders that may be associated with skin changes', N''),
( N'Q1516083', N'piebaldism', N'Human disease', N''),
( N'Q1516211', N'renal tubular acidosis', N'renal tubular transport disease characterized by excess levels of acid in the blood, due to a failure of the kidneys', N''),
( N'Q1516888', N'inclusion-cell disease', N'Human disease', N''),
( N'Q1518637', N'VIPoma', N'rare endocrine tumor that overproduces vasoactive intestinal peptide', N''),
( N'Q1519657', N'parakeratosis', N'keratinization characterized by the retention of nuclei in the stratum corneum', N''),
( N'Q1521567', N'omphalocele', N'physical disorder characterized by a defect in the development of the abdominal wall muscles, resulting in the intestines, liver and other organs to remain outside of the abdomen in a sac', N''),
( N'Q15218681', N'seasickness', N'', N''),
( N'Q1522871', N'calcific tendinitis', N'disorder characterized by deposits of hydroxyapatite (a crystalline calcium phosphate) in any tendon of the body', N''),
( N'Q1524166', N'pigeon toe', N'condition which causes the toes to point inward when walking', N''),
( N'Q1524940', N'choroid plexus carcinoma', N'choroid plexus cancer that has material basis in epithelial cells of the choroid plexus', N''),
( N'Q1526459', N'pyoderma gangrenosum', N'condition that causes tissue to become necrotic, causing deep ulcers that usually occur on the legs', N''),
( N'Q15270307', N'hereditary motor and sensory neuropathy', N'congenital disorder of nervous system', N''),
( N'Q1527711', N'nephrocalcinosis', N'Human disease', N''),
( N'Q1527888', N'pancreatitis', N'human disease involving the inflammation of the pancreas', N''),
( N'Q1529258', N'Glanzmanns thrombasthenia', N'human disease', N''),
( N'Q1529650', N'Vitreous hemorrhage', N'', N''),
( N'Q1529983', N'mucopolysaccharidosis II', N'mucopolysaccharidosis characterized by a deficiency of the lysosomal enzyme iduronate sulfatase', N''),
( N'Q1530812', N'Oculo-facial-cardio-dental syndrome', N'Very rare genetic disease involving ocular abnormalities and cardiac abnormalities.', N''),
( N'Q1531322', N'limb-girdle muscular dystrophy', N'muscular dystrophy characterized by weakening of the muscles of the hip and shoulders which comprise the limb girdle muscles', N''),
( N'Q1531482', N'gliomatosis cerebri', N'rare primary brain tumor', N''),
( N'Q1531991', N'parkinsonian syndrome', N'symptoms that resemble Parkinsons disease', N''),
( N'Q1532338', N'ischemic colitis', N'colitis caused by inadequate blood supply to the colon', N''),
( N'Q1532790', N'Scheuermanns disease', N'osteochondrosis that results in abnormal bone growth and curvature located in thoracic vertebral column', N''),
( N'Q153356', N'chlamydia infection', N'sexually transmitted infection caused by the bacterium Chlamydia trachomatis.', N''),
( N'Q1534492', N'microhematuria', N'medical condition', N''),
( N'Q1535394', N'Nesidioblastosis', N'carbohydrate metabolic disorder that involves low blood glucose resulting from an excess of insulin', N''),
( N'Q1536273', N'Host tropism', N'', N''),
( N'Q1536513', N'Focal infection theory', N'', N''),
( N'Q1536720', N'nevoid basal cell carcinoma syndrome', N'an autosomal dominant condition that can cause unusual facial appearances and a predisposition for basal-cell carcinoma', N''),
( N'Q1538213', N'lipodystrophy', N'group of genetic or acquired disorders in which the body is unable to produce and maintain healthy fat tissue', N''),
( N'Q1538218', N'Muckle-Wells syndrome', N'Human disease', N''),
( N'Q1538227', N'Kabuki syndrome', N'rare disease', N''),
( N'Q1538277', N'Gorhams disease', N'A syndrome that is characterized by bone loss (osteolysis) which is often associated with swelling or abnormal blood vessel growth (angiomatous proliferation). Bone loss can occur in just one bone or spread to soft tissue and adjacent bones.', N''),
( N'Q1538490', N'acute proliferative glomerulonephritis', N'Human disease', N''),
( N'Q153861', N'tularemia', N'primary bacterial infectious disease that has material basis in Francisella tularensis, which is transmitted by dog tick bite (Dermacentor variabilis), transmitted by deer flies (Chrysops sp) or transmitted by contact with infected animal tissues.', N''),
( N'Q15401586', N'pneumocystis pneumonia', N'pneumonia caused by Pneumocystis jirovecii, common among AIDS patients', N''),
( N'Q15401621', N'Trousseaus syndrome', N'', N''),
( N'Q1541975', N'multiple system atrophy', N'Multiple system atrophy (MSA) is a neurodegenerative disorder characterized by autonomic failure (cardiovascular and/or urinary), parkinsonism, cerebellar impairment and corticospinal signs with a median survival of 6-9 years', N''),
( N'Q1542410', N'thrombogavitis', N'blood platelet disease that is characterized by the presence of high platelet counts in the blood', N''),
( N'Q1542466', N'vulvitis', N'vulva disease', N''),
( N'Q15428809', N'2q37 deletion syndrome', N'', N''),
( N'Q15431667', N'metallosis', N'', N''),
( N'Q1543446', N'Noonan syndrome', N'human disease', N''),
( N'Q15443105', N'autosomal dominant polycystic kidney disease', N'congenital disorder of urinary system', N''),
( N'Q1544408', N'Alagille syndrome', N'congenital disorder of digestive system', N''),
( N'Q1544416', N'lissencephaly', N'congenital disorder of nervous system', N''),
( N'Q1544517', N'oneiroid syndrome', N'dream-like fantastic delusional state (psychopathological syndrome)', N''),
( N'Q1544884', N'Lennox-Gastaut syndrome', N'rare but severe childhood-onset epilepsy', N''),
( N'Q1544989', N'Peutz-Jeghers syndrome', N'autosomal dominant genetic disorder characterized by the development of benign hamartomatous polyps in the gastrointestinal tract and hyperpigmented macules on the lips and oral mucosa (melanosis)', N''),
( N'Q1545572', N'splenic infarction', N'condition in which oxygen supply to the spleen is interrupted', N''),
( N'Q1545750', N'lymphangioma', N'malformations of the lymphatic system characterized by lesions that are thin-walled cysts', N''),
( N'Q15460254', N'amoebic dysentery', N'Human disease', N''),
( N'Q1546498', N'non-alcoholic fatty liver disease', N'storing of excess fat in liver cells, not caused by heavy alcohol use', N''),
( N'Q154666', N'bovine sponginess encephalitic', N'bovine counterpart to variant Creutzfeldt-Jakob disease', N''),
( N'Q1547640', N'organic acidemia', N'amino acid metabolic disorder that disrupts normal amino acid metabolism causing a building up of branched-chain amino acids', N''),
( N'Q154865', N'botulism', N'human and animal disease', N''),
( N'Q154869', N'hepatitis C', N'human viral infection', N''),
( N'Q154874', N'yellow fever', N'viral disease', N''),
( N'Q154878', N'toxoplasmosis', N'parasitic disease', N''),
( N'Q154882', N'legionnaires disease', N'legionellosis that is characterized by severe form of infection producing pneumonia.', N''),
( N'Q1549421', N'tooth agenesis', N'human disease', N''),
( N'Q1549428', N'steatorrhea', N'Human disease', N''),
( N'Q1550521', N'vesicoureteral reflux', N'ureteral disease characterized by backward flow of urine from the urinary bladder into the ureter', N''),
( N'Q1550742', N'genu varum', N'O-knees', N''),
( N'Q155098', N'leptospirosis', N'human and animal infectious disease', N''),
( N'Q1553018', N'multiple endocrine neoplasia', N'human disease', N''),
( N'Q1553850', N'hemoglobinuria', N'condition in which the oxygen transport protein hemoglobin is found in abnormally high concentrations in the urine', N''),
( N'Q1557239', N'microphthalmia', N'eye disease where one or both eyeballs are abnormally small', N''),
( N'Q1558317', N'focal hand dystonia', N'focal dystonia that affects a single muscle or small group of muscles in the hand resulting from involuntary muscular contractions', N''),
( N'Q155857', N'rubella', N'human viral disease', N''),
( N'Q1559250', N'Peters plus syndrome', N'syndrome that is characterized by anterior chamber eye anomalies, short limbs with broad distal extremities, characteristic facial features, cleft lip/palate, and variable developmental delay/intellectual disability', N''),
( N'Q156050', N'brucellosis', N'Human and animal disease', N''),
( N'Q156103', N'gastroenteritis', N'medical condition characterized by inflammation of the stomach and/or small intestine', N''),
( N'Q1561430', N'Developmental verbal dyspraxia', N'neurodevelopmental condition', N''),
( N'Q1561647', N'congenital aplasia of the vas deferens', N'', N''),
( N'Q15630404', N'Asymptomatic inflammatory prostatitis', N'', N''),
( N'Q1563513', N'HELLP syndrome', N'severe pre-eclampsia characterized by hemolysis, elevated liver enzyme and low platelet count', N''),
( N'Q15646785', N'calcaneal spur', N'exostosis that results in an abnomal growth located in calcaneus', N''),
( N'Q156590', N'priapism', N'peripheral vascular disease characterized by blood trapped in the penis that is unable to drain.', N''),
( N'Q15666414', N'tarsal coalition', N'human disease', N''),
( N'Q1569573', N'hepatopulmonary syndrome', N'Human disease', N''),
( N'Q1569702', N'osteitis pubis', N'noninfectious inflammation of the pubis symphysis (also known as the pubic symphysis, symphysis pubis, or symphysis pubica), causing varying degrees of lower abdominal and pelvic pain', N''),
( N'Q1570013', N'thrombophilia', N'abnormality of blood coagulation that increases the risk of thrombosis (blood clots in blood vessels)', N''),
( N'Q1571741', N'Hemoglobin Barts', N'abnormal type of hemoglobin that consists of four gamma globins', N''),
( N'Q1572384', N'mammary Pagets disease', N'type of cancer that may have the appearance of eczema, involving the nipple', N''),
( N'Q1572538', N'nephroptosis', N'abnormal condition in which the kidney drops down into the pelvis when the patient stands up', N''),
( N'Q15730674', N'Sessile serrated adenoma', N'', N''),
( N'Q15731388', N'High-grade prostatic intraepithelial neoplasia', N'', N''),
( N'Q15731494', N'multicentric reticulohistiocytosis', N'syndrome that is characterized by papulonodular skin lesions containing a proliferation of true macrophages associated with arthritis', N''),
( N'Q1573307', N'Wernicke encephalopathy', N'presence of neurological symptoms caused by biochemical lesions of the central nervous system after exhaustion of B-vitamin reserves,', N''),
( N'Q15734064', N'Pancreatic mucinous cystadenoma', N'Human disease', N''),
( N'Q15734066', N'Ovarian cystadenoma', N'Human disease', N''),
( N'Q1573613', N'venous ulcer', N'', N''),
( N'Q1576205', N'carotid artery stenosis', N'narrowing or constriction of the inner surface (lumen) of the carotid artery, usually caused by atherosclerosis', N''),
( N'Q157661', N'hepatitis A', N'acute infectious disease of the liver', N''),
( N'Q1578799', N'trichophagia', N'', N''),
( N'Q15802235', N'endometrial stromal tumour', N'human disease', N''),
( N'Q1581308', N'conductive hearing loss', N'', N''),
( N'Q1581845', N'mediastinitis', N'inflammatory process affecting the mediastinum', N''),
( N'Q1583485', N'Rothmund-Thomson syndrome', N'human disease', N''),
( N'Q1584110', N'arteriovenous malformation', N'vascular anomaly', N''),
( N'Q1585081', N'malignant hyperthermia', N'genetic disease that is characterized by a drastic and uncontrolled increase in skeletal muscle oxidative metabolism, which overwhelms the bodys capacity to supply oxygen, remove carbon dioxide, and regulate body temperature', N''),
( N'Q1585753', N'urethral stricture', N'narrowing of the urethra caused by injury, instrumentation, infection and certain non-infectious forms of urethritis', N''),
( N'Q1585769', N'urolithiasis', N'kidney stone disease', N''),
( N'Q1586088', N'hypoparathyroidism', N'Endocrine disease', N''),
( N'Q1587881', N'popliteal pterygium syndrome', N'Human disease', N''),
( N'Q1592207', N'pseudolymphoma', N'benign nepolasm that resembles a malignant lymphoma', N''),
( N'Q1593114', N'Spermaturia', N'', N''),
( N'Q1593600', N'Reflux nephropathy', N'Human disease', N''),
( N'Q1593605', N'uveoparotid fever', N'Human disease', N''),
( N'Q1594599', N'Post-transplant lymphoproliferative disorder', N'Human disease', N''),
( N'Q159701', N'glaucoma', N'eye disease that is characterized by an unstable or a sustained increase in the intraocular pressure which the eye cannot withstand without damage to its structure or impairment of its function', N''),
( N'Q1597484', N'Ear mite', N'common name', N''),
( N'Q15975183', N'benign neonatal seizures', N'Human disease', N''),
( N'Q1597571', N'Cutaneous larva migrans', N'', N''),
( N'Q1598200', N'metabolic acidosis', N'lactic acidosis that has material basis in high levels of acid', N''),
( N'Q1598365', N'heparin-induced thrombocytopenia', N'development of thrombocytopenia (a low platelet count), due to the administration of various forms of heparin, an anticoagulant', N''),
( N'Q16001403', N'aberrations of the eye', N'asymmetries in the topography and refractive index of the corneal surface that affect visual acuity', N''),
( N'Q16002876', N'ametropic amblyopia', N'Human disease', N''),
( N'Q16002898', N'Amphistomiasis', N'parasitic disease of livestock animals and humans', N''),
( N'Q160105', N'cervical cancer', N'cancer arising from the cervix, caused by a sexually transmitted virus', N''),
( N'Q1601794', N'parasitic infectious diseases', N'infectious disease caused or transmitted by a parasite', N''),
( N'Q1601921', N'annular pancreas', N'pancreas disease characterized by autosomal dominant inheritance of the annular pancreas (head of the pancreas forming a ring around the second portion of the duodenum) and duodenal stenosis', N''),
( N'Q160649', N'typhus', N'group of infectious diseases', N''),
( N'Q1607658', N'hepatoblastoma', N'uncommon malignant liver cancer occurring in infants and children', N''),
( N'Q160796', N'delirium', N'severe confusion that develops quickly, and often fluctuates in intensity, neurocognitive disorder', N''),
( N'Q1607983', N'erysipeloid', N'infections most commonly present in a mild cutaneous', N''),
( N'Q1609733', N'hereditary folate malabsorption', N'', N''),
( N'Q1609737', N'hereditary neuropathy with liability to pressure palsies', N'peripheral neuropathy', N''),
( N'Q1609755', N'hereditary fructose intolerance syndrome', N'inborn error of fructose metabolism caused by a deficiency of the enzyme aldolase B', N''),
( N'Q1613670', N'cutaneous small-vessel vasculitis', N'hypersensitivity vasculitis that results in inflammation of small blood vessels, characterized clinically by palpable purpura, which is a slightly elevated purpuric rash over one or more areas of the skin', N''),
( N'Q1613885', N'herpesviral encephalitis', N'encephalitis associated with herpes simplex virus', N''),
( N'Q1614115', N'hypervolemia', N'disease', N''),
( N'Q16154200', N'Androgen deprivation-induced senescence', N'', N''),
( N'Q1615557', N'adiposis dolorosa', N'rare condition characterized by generalized obesity and fatty tumors in the adipose tissue.', N''),
( N'Q1617386', N'hidrocystoma', N'Human disease', N''),
( N'Q1617658', N'Hyper IgM syndrome', N'primary immune deficiency disorders characterized by defective CD40 signaling', N''),
( N'Q161790', N'Asperger syndrome', N'neurodevelopmental condition', N''),
( N'Q161801', N'sudden infant death syndrome', N'syndrome that is characterized by the sudden death of an infant that is not predicted by medical history and remains unexplained after a thorough forensic autopsy and detailed death scene investigation.', N''),
( N'Q1618019', N'Fox-Fordyce disease', N'chronic blockage of the sweat gland ducts with a secondary, non-bacterial inflammatory response to the secretions and cellular debris in the cysts', N''),
( N'Q161964', N'capillary leak syndrome', N'Human disease', N''),
( N'Q1620193', N'cerebral degeneration', N'human disease', N''),
( N'Q1620444', N'hematocele of tunica vaginalis testis', N'Human disease', N''),
( N'Q1620594', N'hirsutism', N'hair growth on a woman, generally causing a full beard to grow (see bearded lady)', N''),
( N'Q1621463', N'Molybdenum cofactor deficiency', N'metal metabolism disease characterized by encephalopathy that worsens over time resulting from the absence of molybdenum cofactor which leads to accumulation of toxic levels of sulphite and neurological damage', N''),
( N'Q1621830', N'lupus nephritis', N'inflammation of the kidneys caused by lupus', N''),
( N'Q1622407', N'mixed connective tissue disease', N'collagen disease that is considered an overlap of three diseases, systemic lupus erythematosus, scleroderma, and polymyositis with very high titers of circulating antinuclear antibody to a ribonucleoprotein antigen', N''),
( N'Q162266', N'hemolytic-uremic syndrome', N'Human disease', N''),
( N'Q1623006', N'keratoconjunctivitis', N'inflammation ("-itis") of the cornea and conjunctiva.', N''),
( N'Q16240919', N'Blastic NK cell lymphoma', N'', N''),
( N'Q16242752', N'allergic contact dermatitis', N'medical condition', N''),
( N'Q16242812', N'Amalgam tattoo', N'common discoloration of tissue in the mouth', N''),
( N'Q16244733', N'bowel obstruction', N'Human disease', N''),
( N'Q16252204', N'dicarboxylic aminoaciduria', N'Human disease', N''),
( N'Q16254348', N'cervical neuroendocrine carcinoma', N'', N''),
( N'Q16254825', N'Postmenopausal confusion', N'', N''),
( N'Q16256637', N'emphysematous cystitis', N'Hip fracture right', N''),
( N'Q16257070', N'Hypertensive leukoencephalopathy', N'', N''),
( N'Q16257164', N'Inflammatory fibroid polyp', N'', N''),
( N'Q16257997', N'Nevus anemicus', N'', N''),
( N'Q16258700', N'Transitional cell carcinoma of the ovary', N'Human disease', N''),
( N'Q16258703', N'Transplant glomerulopathy', N'', N''),
( N'Q16258730', N'Twin Anemia-Polycythemia Sequence', N'', N''),
( N'Q1627324', N'Neonatal hemochromatosis', N'', N''),
( N'Q1627831', N'sialolithiasis', N'condition where a calcified mass or sialolith forms within a salivary gland, usually in the duct of the submandibular gland', N''),
( N'Q1628473', N'corneal ulcer', N'area of epithelial tissue loss from corneal surface; associated with inflammatory cells in the cornea and anterior chamber', N''),
( N'Q1629483', N'Walker–Warburg syndrome', N'rare form of autosomal recessive congenital muscular dystrophy', N''),
( N'Q1632552', N'hyperostosis', N'human disease', N''),
( N'Q1632678', N'Mallory–Weiss syndrome', N'bleeding from a laceration in the mucosa at the junction of the stomach and esophagus', N''),
( N'Q163469', N'pneumoperitoneum', N'pneumatosis (abnormal presence of air or other gas) in the peritoneal cavity, a potential space within the abdominal cavity.', N''),
( N'Q1634800', N'telangiectasia', N'condition caused by small dilated blood vessels near the surface of the skin or mucous membranes', N''),
( N'Q1634879', N'encephalomyelitis', N'inflammation of the brain and spinal cord', N''),
( N'Q1636310', N'Landau–Kleffner syndrome', N'a rare childhood neurological syndrome characterized by seizures and progressive loss of speech typically in a child with previous age-appropriate development', N''),
( N'Q1637035', N'Keratosis pilaris', N'skin condition characterized by small bumps', N''),
( N'Q1638140', N'hypopyon', N'Human disease', N''),
( N'Q1638637', N'polycoria', N'', N''),
( N'Q163865', N'scurvy', N'human disease', N''),
( N'Q163905', N'Lafora disease', N'Lafora disease (LD) is a rare, inherited, severe, progressive myoclonic epilepsy characterized by myoclonus and/or generalized seizures, visual hallucinations (partial occipital seizures), and progressive neurological decline', N''),
( N'Q1639178', N'opioid use disorder', N'substance abuse disorder that involves the recurring use of opioid drugs despite negative consequences', N''),
( N'Q1640292', N'adenoiditis', N'inflammation of the adenoid tissue', N''),
( N'Q1640324', N'hydrophthalmos', N'Human disease', N''),
( N'Q1640632', N'Labial fusion', N'human disease', N''),
( N'Q1640810', N'Hyper-IgD syndrome', N'', N''),
( N'Q1640860', N'hyperaldosteronism', N'adrenal gland hyperfunction disease that results in the overproduction of aldosterone by the adrenal glands', N''),
( N'Q1640998', N'hyperkeratosis', N'thickening of the stratum corneum (the outermost layer of the epidermis), often associated with the presence of an abnormal quantity of keratin', N''),
( N'Q1641042', N'hypermobility syndrome', N'human disease:  joints that stretch farther than normal', N''),
( N'Q1641062', N'hyperphosphatemia', N'electrolyte disorder in which there is an elevated level of phosphate in the blood.', N''),
( N'Q1641132', N'malignant hypertension', N'condition of markedly elevated blood pressure with diastolic pressure typically greater than 120 mm Hg', N''),
( N'Q1641153', N'secondary hypertrophic osteoarthropathy', N'medical condition combining clubbing and periostitis of the small hand joints', N''),
( N'Q1641171', N'hypervitaminosis D', N'Human disease', N''),
( N'Q1641332', N'hypogonadotropism', N'endocrine disease', N''),
( N'Q1641384', N'hypophosphatemia', N'electrolyte disorder in which there is a low level of phosphate in the blood', N''),
( N'Q1641399', N'hypoplastic left heart syndrome', N'congenital heart disease characterized by abnormal development of the left-sided structures of the heart', N''),
( N'Q1641483', N'hypotrichosis', N'hair disease that is characterized by sparse hair on the scalp resulting from abnormal hair follicle development and has material basis in mutations in proteins involved in hair growth, division or proliferation of cells within hair follicles', N''),
( N'Q1641486', N'Marie Unna hereditary hypotrichosis', N'disease', N''),
( N'Q1642040', N'hemarthrosis', N'bleeding into joint spaces', N''),
( N'Q1642094', N'hematidrosis', N'sweating of blood', N''),
( N'Q1642147', N'hemoglobinopathy', N'genetic defect causing abnormal hemoglobin structure', N''),
( N'Q1642170', N'hemophagocytic lymphohistiocytosis', N'uncommon hematologic disorder seen more often in children than in adults', N''),
( N'Q1642206', N'superior mesenteric artery syndrome', N'gastro-vascular disorder in which the third and final portion of the duodenum is compressed between the abdominal aorta (AA) and the overlying superior mesenteric artery', N''),
( N'Q1642307', N'Suspension trauma', N'type of medical trauma', N''),
( N'Q164727', N'ornithosis', N'disease', N''),
( N'Q1647794', N'breast cyst', N'Human disease', N''),
( N'Q1648128', N'geniculate herpes zoster', N'disorder that is caused by the reactivation of varicella zoster virus in the geniculate ganglion, a nerve cell bundle of the facial nerve', N''),
( N'Q164818', N'Q fever', N'disease caused by infection with Coxiella burnetii', N''),
( N'Q1648484', N'Duchenne muscular dystrophy', N'Duchenne muscular dystrophy (DMD) is a neuromuscular disease characterized by rapidly progressive muscle weakness and wasting due to degeneration of skeletal, smooth and cardiac muscle', N''),
( N'Q164952', N'malignant histiocytosis', N'Human disease', N''),
( N'Q1649897', N'catecholaminergic polymorphic ventricular tachycardia', N'disorder characterized by an abnormal heart rhythm (arrhythmia)', N''),
( N'Q165135', N'goiter', N'swelling of the thyroid gland', N''),
( N'Q165328', N'osteoporosis', N'bone resorption disease characterized by the thinning of bone tissue and decreased mechanical strength', N''),
( N'Q16543725', N'Undifferentiated connective tissue disease', N'', N''),
( N'Q16545548', N'Cervicogenic headache', N'', N''),
( N'Q1654860', N'argininosuccinic aciduria', N'amino acid metabolic disorder that involves the accumulation of argininosuccinic acid (ASA) in the blood and urine', N''),
( N'Q16550087', N'Langer mesomelic dysplasia', N'Langer mesomelic dysplasia (LMD) is characterized by severe disproportionate short stature with mesomelic and rhizomelic shortening of the upper and lower limbs', N''),
( N'Q1656793', N'ideomotor apraxia', N'Human disease', N''),
( N'Q1658731', N'postoperative nausea and vomiting', N'', N''),
( N'Q1660341', N'shoulder impingement syndrome', N'syndrome which occurs when the tendons of the rotator cuff muscles become irritated and inflamed as they pass through the subacromial space, the passage beneath the acromion', N''),
( N'Q16606544', N'nickel allergic contact dermatitis', N'allergic contact dermatitis that has allergic trigger nickel atom', N''),
( N'Q16606552', N'obstructive sleep apnea', N'obstruction of the upper airway during sleep', N''),
( N'Q166102', N'prolapse of female genital organ', N'portion of the vaginal canal protruding from the opening of the vagina', N''),
( N'Q16642630', N'atypical adenomatous hyperplasia', N'', N''),
( N'Q1668089', N'neurocytoma', N'type of nervous system benign tumor', N''),
( N'Q166907', N'cluster headache', N'neurological disorder', N''),
( N'Q167050', N'Sertoli cell-only syndrome', N'Human disease', N''),
( N'Q1670952', N'oculomotor nerve paralysis', N'Human disease', N''),
( N'Q1671412', N'interstitial cystitis', N'chronic inflammatory condition of the submucosal and muscular layers of the bladder', N''),
( N'Q1671489', N'fructose malabsorption', N'disorder', N''),
( N'Q1671598', N'intrauterine growth restriction', N'poor growth of fetus in mothers womb during pregnancy', N''),
( N'Q1671685', N'invasive ductal carcinoma', N'human disease', N''),
( N'Q167178', N'scabies', N'human disease', N''),
( N'Q167264', N'Marburg virus disease', N'Human disease', N''),
( N'Q16775468', N'elephantiasis', N'Human disease', N''),
( N'Q1678281', N'Bardet-Biedl syndrome', N'ciliopathic human genetic disorder that produces many effects and affects many body systems', N''),
( N'Q167844', N'conjunctivitis', N'inflammation of the outermost layer of the eye and the inner surface of the eyelids', N''),
( N'Q16802188', N'Multilocular cystic clear cell renal cell carcinoma', N'Human disease', N''),
( N'Q16815740', N'glycogen storage disease IX', N'glycogen storage disease characterized by deficiency of hepatic phosphorylase kinase activity', N''),
( N'Q16816779', N'stomach neoplasm', N'neoplasm listed in Medical Subject Headings (MeSH)', N''),
( N'Q16819853', N'Acquired cystic kidney disease-associated renal cell carcinoma', N'', N''),
( N'Q1682044', N'monocytosis', N'increase in the number of monocytes circulating in the blood', N''),
( N'Q16835166', N'atrophodermia vermiculata', N'Dermatological condition', N''),
( N'Q16838027', N'Bare lymphocyte syndrome 2', N'human disease', N''),
( N'Q168403', N'myopia', N'problem with distance vision', N''),
( N'Q16866974', N'Gordon syndrome', N'', N''),
( N'Q16873382', N'wooden chest', N'side effect from opioids', N''),
( N'Q16874615', N'supravalvular aortic stenosis', N'Human disease', N''),
( N'Q16877679', N'Papillary renal cell carcinomas', N'renal cell carcinoma that is characterized by the development of multiple, bilateral papillary renal tumors', N''),
( N'Q16877704', N'mycetoma', N'chronic subcutaneous infection caused by aerobic actinomycetic bacteria  or fungi', N''),
( N'Q16878290', N'Malar flush', N'medical sign', N''),
( N'Q1688105', N'Freiberg disease', N'', N''),
( N'Q1688222', N'phonagnosia', N'agnosia that is a loss of the ability to recognize familiar voices', N''),
( N'Q16882760', N'Inflammatory pseudotumor', N'', N''),
( N'Q16887028', N'multinodular goiter', N'goiter characterized by a multinodular enlargement of the thyroid gland', N''),
( N'Q16889762', N'multiple pterygium syndrome', N'Human disease', N''),
( N'Q16892594', N'radioulnar synostosis', N'Human disease', N''),
( N'Q16892735', N'neurodegeneration with brain iron accumulation', N'neurodegenerative disease characterized by progressive iron accumulation in the basal ganglia and other regions of the brain, resulting in extrapyramidal movements, such as parkinsonism and dystonia', N''),
( N'Q16893452', N'Pulmonary carcinoid tumour', N'', N''),
( N'Q16897486', N'Histoid leprosy', N'', N''),
( N'Q16905725', N'Intestinal varices', N'', N''),
( N'Q16908143', N'cerebral creatine deficiency syndrome', N'Human disease', N''),
( N'Q16908633', N'hyperprolactinemic SAHA syndrome', N'', N''),
( N'Q16909671', N'generalized epilepsy with febrile seizures plus', N'idiopathic generalized epilepsy that is characterized by febrile seizures often with accessory afebrile generalized tonic-clonic seizures with childhood onset', N''),
( N'Q1691351', N'lipomatosis', N'Human disease', N''),
( N'Q16918398', N'chromosomal deletion syndrome', N'Human disease', N''),
( N'Q16919874', N'Limb girdle syndrome', N'', N''),
( N'Q16921213', N'Syndrome Without A Name', N'', N''),
( N'Q16927422', N'inverted follicular keratosis', N'Human disease', N''),
( N'Q16928312', N'Endometrial stromal nodule', N'Human disease', N''),
( N'Q16929881', N'Neurofibromatosis type 3', N'', N''),
( N'Q16934007', N'Locked twins', N'multiple pregnancy in which fetuses are interlocked', N''),
( N'Q16934669', N'heart septal defect', N'Human disease', N''),
( N'Q16934832', N'mixed cerebral palsy', N'subtype of cerebral palsy characterized by both the tight muscle tone of spastic cerebral palsy and the writhing, involuntary muscle movements of athetoid cerebral palsy', N''),
( N'Q16935263', N'Serratia infection', N'', N''),
( N'Q1693598', N'nasopharynx carcinoma', N'common cancer originating in the nasopharynx', N''),
( N'Q16937928', N'Hereditary sclerosing poikiloderma', N'human disease', N''),
( N'Q16938550', N'Refractory anemia with ring sideroblasts', N'', N''),
( N'Q16938596', N'Trotters syndrome', N'', N''),
( N'Q16938818', N'Mental retardation and microcephaly with pontine and cerebellar hypoplasia', N'syndromic X-linked intellectual disability characterized by severe intellectual disability, microcephaly with pontine and cerebellar hypoplasia that has material basis in heterozygous mutation or deletion in the CASK gene on chromosome Xp11', N''),
( N'Q16939023', N'orthostatic proteinuria', N'Human disease', N''),
( N'Q16939433', N'Junctional nevus', N'Human disease', N''),
( N'Q16940237', N'Multifocal lymphangioendotheliomatosis', N'human disease', N''),
( N'Q16940647', N'Johnson–McMillin syndrome', N'Johnson neuroectodermal syndrome is characterised by alopecia, anosmia or hyposmia, conductive deafness with malformed ears and microtia and/or atresia of the external auditory canal, and hypogonadotropic hypogonadism', N''),
( N'Q16943887', N'Jugular vein ectasia', N'', N''),
( N'Q16944450', N'autosomal recessive distal spinal muscular atrophy 2', N'human disease', N''),
( N'Q16944551', N'Biemond syndrome', N'Brachydactyly-nystagmus-cerebellar ataxia syndrome is characterized by brachydactyly, nystagmus and cerebellar ataxia. Intellectual deficit and strabismus are also reported in some patients.', N''),
( N'Q16944985', N'chromosome 15q11-q13 duplication syndrome', N'', N''),
( N'Q16947790', N'McGillivray syndrome', N'Familial scaphocephaly syndrome, McGillivray type is a rare newly described craniosynostosis (see this term) syndrome characterized by scaphocephaly, macrocephaly, severe maxillary retrusion, and mild intellectual disability', N''),
( N'Q16956975', N'overnutrition', N'form of malnutrition in which the intake of nutrients is oversupplied', N''),
( N'Q16957524', N'urinary tract obstruction', N'Human disease', N''),
( N'Q16964509', N'Periorbital hyperpigmentation', N'', N''),
( N'Q16965166', N'inflammatory arthritis', N'', N''),
( N'Q16965307', N'Neonatal adrenoleukodystrophy', N'', N''),
( N'Q16965421', N'organ perforation', N'complete penetration of organ wall', N''),
( N'Q16966202', N'Hyperplastic arteriolosclerosis', N'', N''),
( N'Q16966324', N'Intravenous leiomyomatosis', N'Human disease', N''),
( N'Q16968886', N'mandibuloacral dysplasia', N'', N''),
( N'Q16975956', N'Acquired idiopathic generalized anhidrosis', N'', N''),
( N'Q16977270', N'Nablus mask-like facial syndrome', N'The 8q22.1 microdeletion syndrome or Nablus mask-like facial syndrome is a rare microdeletion syndrome associated with a distinct facial appearance.', N''),
( N'Q16977356', N'septic thrombophlebitis', N'', N''),
( N'Q16978490', N'Lyngstadaas syndrome', N'', N''),
( N'Q1698867', N'non-syndromic pontocerebellar hypoplasia', N'Human disease', N''),
( N'Q1699007', N'Johanson-Blizzard syndrome', N'congenital disorder of digestive system', N''),
( N'Q16992883', N'Sylvatic plague', N'infectious bacterial disease', N''),
( N'Q16993341', N'Urban plague', N'', N''),
( N'Q16994031', N'MBL deficiency', N'human disease', N''),
( N'Q16999817', N'Tight hymenal ring', N'Human disease', N''),
( N'Q16999912', N'Microgyrus', N'', N''),
( N'Q17001349', N'cervical agenesis', N'human disease', N''),
( N'Q17002910', N'ABO hemolytic disease of the newborn', N'', N''),
( N'Q17004056', N'Interstitial pregnancy', N'', N''),
( N'Q17004153', N'Pacemaker failure', N'', N''),
( N'Q170082', N'psychosis', N'abnormal condition of the mind that involves a loss of contact with reality', N''),
( N'Q17008739', N'Latent Iron Deficiency', N'', N''),
( N'Q17009830', N'Progestin-induced virilisation', N'', N''),
( N'Q170102', N'scrapie', N'disease that affects sheep and goats', N''),
( N'Q17010855', N'achondrogenesis type IB', N'achondrogenesis that has material basis in mutation in the SLC26A2 gene which results in umbilical or inguinal hernia and a prominent rounded abdomen', N''),
( N'Q17010866', N'achondrogenesis type II', N'achondrogenesis that has material basis in mutations in the COL2A1 gene which results in underdeveloped lungs, hydrops fetalis, a prominent forehead and abnormal ossification of the located in vertebral column or located in pelvis', N''),
( N'Q17012451', N'Mild androgen insensitivity syndrome', N'', N''),
( N'Q17022356', N'Hemoglobin E', N'variant form of human hemoglobin', N''),
( N'Q1702335', N'Gardners syndrome', N'congenital disorder of digestive system', N''),
( N'Q17024798', N'Langerhans cell sarcoma', N'histiocytic and dendritic cell cancer that derives from the lymph nodes, derives from the skin, derives from the liver, derives from the spleen and derives from bones', N''),
( N'Q17028415', N'hyperkinetic disorder', N'range of neurodevelopmental conditions', N''),
( N'Q17028486', N'intestinal hypomagnesemia 1', N'human disease', N''),
( N'Q1704044', N'portal vein thrombosis', N'human disease', N''),
( N'Q17042115', N'Myhre syndrome', N'', N''),
( N'Q1704531', N'pilomatrixoma', N'Human disease', N''),
( N'Q17047222', N'Myxoid chondrosarcoma', N'Human disease', N''),
( N'Q17048613', N'Hereditary CNS demyelinating disease', N'Human disease', N''),
( N'Q17067160', N'intraocular hemorrhage', N'', N''),
( N'Q17071650', N'Calcium channel blocker toxicity', N'', N''),
( N'Q17074273', N'Viral cardiomyopathy', N'', N''),
( N'Q17075324', N'eustrongylidosis', N'', N''),
( N'Q17077617', N'reading disorder', N'range of neurological conditions, developmental or acquired', N''),
( N'Q17077887', N'hemorrhagic smallpox', N'severe manifestation of smallpox caused by bleeding under the skin', N''),
( N'Q1707822', N'Pendred syndrome', N'genetic disorder', N''),
( N'Q17080095', N'22q11.2 distal deletion syndrome', N'Human disease', N''),
( N'Q17080979', N'Autoimmune optic neuropathy', N'', N''),
( N'Q17082044', N'Kowarski syndrome', N'', N''),
( N'Q17082341', N'macrodystrophia lipomatosa', N'', N''),
( N'Q17083093', N'Cenani-Lenz syndactyly syndrome', N'dysostosis characterized by syndactyly, malformation of the forearm and lower limb bones, renal hypoplasia or aplasia and that has material basis in homozygous or compound heterozygous mutation in the LRP4 gene on chromosome 11p11', N''),
( N'Q17083190', N'cerebral atherosclerosis', N'type of atherosclerosis where build-up of plaque in the blood vessels of the brain occurs', N''),
( N'Q17083598', N'Chronic sclerosing sialadenitis', N'', N''),
( N'Q17084678', N'cortisone reductase deficiency 1', N'cortisone reductase deficiency that has material basis in homozygous or compound heterozygous mutation in the H6PD gene on chromosome 1p36', N''),
( N'Q17084842', N'creatine transporter deficiency', N'Human disease', N''),
( N'Q17085142', N'cyclotropia', N'Human disease', N''),
( N'Q17091221', N'Hypoplastic right heart syndrome', N'congenital heart disease characterized by underdevelopment of the structures on the right side of the heart commonly associated with atrial septal defect', N''),
( N'Q17094243', N'selective IgG deficiency disease', N'human disease', N''),
( N'Q170990', N'arthritis', N'form of joint disorder that involves inflammation of one or more joints', N''),
( N'Q17101813', N'Intraparenchymal hemorrhage', N'intraparenchymal', N''),
( N'Q17106360', N'Pineocytoma', N'', N''),
( N'Q17112235', N'Pilon fracture', N'', N''),
( N'Q17114216', N'Neurocristopathy', N'Neural crest diseases', N''),
( N'Q1711733', N'Salter–Harris fracture', N'fracture that involves the epiphyseal plate or growth plate of a bone', N''),
( N'Q1711744', N'Merkel cell carcinoma', N'rare and highly aggressive skin cancer', N''),
( N'Q17118587', N'Minors disease', N'', N''),
( N'Q17119115', N'ethylmalonic encephalopathy', N'Human disease', N''),
( N'Q17119158', N'Eiken syndrome', N'Eiken syndrome is a rare familial skeletal dysplasia characterized by multiple epiphyseal dysplasia, with extremely retarded ossification. It has been described in 6 members of a unique consanguineous family.', N''),
( N'Q17119372', N'Haemophilus meningitis', N'bacterial meningitis that has material basis in Haemophilus influenzae infection', N''),
( N'Q17119512', N'Mast cell sarcoma', N'Human disease', N''),
( N'Q17119515', N'Mungan syndrome', N'human disease', N''),
( N'Q17120550', N'peeling skin syndrome', N'Human disease', N''),
( N'Q17120696', N'MDP syndrome', N'human disease', N''),
( N'Q17120992', N'Hyperglycerolemia', N'genetic disorder', N'')
GO