INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q7131598', N'pansteatitis', N'animal disease', N''),
( N'Q7132981', N'papillary adenocarcinoma', N'adenocarcinoma that derives from epithelial cells originating in glandular tissue, which form complex papillary structures and exhibit compressive, destructive growth that replaces the normal tissue', N''),
( N'Q7132983', N'papillary eccrine adenoma', N'Human disease', N''),
( N'Q7132990', N'Papillary urothelial neoplasm of low malignant potential', N'Human disease', N''),
( N'Q7133004', N'Papillomatosis cutis carcinoides', N'medical condition', N''),
( N'Q7133011', N'renal coloboma syndrome', N'autosomal dominant disease characterized by optic nerve coloboma and renal disease', N''),
( N'Q7134468', N'paradoxical embolism', N'embolus which is carried from the venous side of circulation to the arterial side, or vice versa', N''),
( N'Q7135955', N'parasitic pneumonia', N'infection of the lungs with parasites, commonly by parasitic worms', N''),
( N'Q7136039', N'Parastremmatic dwarfism', N'Parastremmatic dwarfism is a very rare chondrodysplasia characterized by severe dwarfism, kyphoscoliosis, stiffness of large joints and distortion of lower limbs', N''),
( N'Q7136145', N'parathyroid gland disease', N'endocrine disease', N''),
( N'Q7136155', N'Parathyroiditis', N'', N''),
( N'Q7138441', N'Parkes Weber syndrome', N'uncommon congenital vascular malformation (CVM) characterized by the venous malformations, cutaneous capillary malformations, and lymphatic malformations along with arteriovenous malformation.', N''),
( N'Q7139584', N'Paroxysmal dyskinesia', N'', N''),
( N'Q7139585', N'childhood onset GLUT1 deficiency syndrome 2', N'Paroxysmal exertion-induced dyskinesia (PED) is a form of paroxysmal dyskinesia (see this term), characterized by painless attacks of dystonia of the extremities triggered by prolonged physical activities', N''),
( N'Q7139588', N'Paroxysmal extreme pain disorder', N'Paroxysmal extreme pain disorder is a rare disorder of abnormal pain sensation', N''),
( N'Q7139591', N'Paroxysmal tonic upgaze', N'rare and distinctive neuro-ophthalmological syndrome characterized by episodes of sustained upward deviation of the eyes', N''),
( N'Q7140388', N'focal epilepsy', N'epilepsy syndrome characterised by seizures preceded by isolated disturbances of a cerebral function', N''),
( N'Q7141967', N'Pashayan syndrome', N'Blepharonasofacial syndrome is a rare otorhinolaryngological malformation syndrome characterized by a distinctive mask-like facial dysmorphism, lacrimal duct obstruction, extrapyramidal features, digital malformations and intellectual disability', N''),
( N'Q7144437', N'patellofemoral pain syndrome', N'Human disease', N''),
( N'Q7157933', N'peanut allergy', N'type of food allergy caused by peanuts', N''),
( N'Q7158463', N'Peat fire cancer', N'', N''),
( N'Q7159224', N'Pediatric ependymoma', N'Human disease', N''),
( N'Q7161793', N'Taylors syndrome', N'Human disease', N''),
( N'Q7161798', N'Pelvic floor muscle disorder', N'', N''),
( N'Q7161799', N'Pelvic floor dysfunction', N'Medical condition', N''),
( N'Q7161801', N'pelvic lipomatosis', N'Human disease', N''),
( N'Q7161811', N'pelvic neoplasm', N'tumors or cancer of the pelvic region', N''),
( N'Q7162853', N'Penicillin drug reaction', N'beta-lactam allergy triggered by penicillin', N''),
( N'Q7165022', N'pentalogy of Cantrell', N'disease', N''),
( N'Q7168173', N'perforating calcific elastosis', N'', N''),
( N'Q7168175', N'Perforating folliculitis', N'skin condition involving mainly the hairy parts of the extremities', N''),
( N'Q7168360', N'Perianal gland tumor', N'Human disease', N''),
( N'Q7168462', N'perifolliculitis', N'', N''),
( N'Q7168573', N'perineocele', N'Human disease', N''),
( N'Q7168693', N'Peripheral T-cell lymphoma', N'mature T-cell and NK-cell lymphoma includes a group of T-cell lymphomas that develop away from the thymus', N''),
( N'Q7168708', N'Peripheral ossifying fibroma', N'', N''),
( N'Q7168876', N'peritoneal mesothelioma', N'peritoneum cancer that develops from cells of the mesothelium and is located in the peritoneum', N''),
( N'Q7169165', N'Perlman syndrome', N'A syndrome characterized by polyhydramnios with neonatal macrosomia, nephromegaly, distinctive facial appearance, renal dysplasia, nephroblastomatosis, and predisposition to Wilms tumor. It shows similarities to Beckwith-Wiedemann syndrome.', N''),
( N'Q7170403', N'persistent aura without infarction', N'disease', N''),
( N'Q7170405', N'Persistent cloaca', N'', N''),
( N'Q7170410', N'persistent fetal circulation syndrome', N'Human disease', N''),
( N'Q7170411', N'persistent generalized lymphadenopathy', N'lymph node disease characterized by enlarged, non-painful lymph nodes occurring for more than three to six months for which no other reason can be found', N''),
( N'Q7170412', N'persistent hyperplastic primary vitreous', N'Human disease', N''),
( N'Q7170418', N'persistent pupillary membrane', N'Human disease', N''),
( N'Q7170425', N'Persistent tunica vasculosa lentis', N'', N''),
( N'Q7171312', N'pes anserine bursitis', N'type of inflammation on the inner side of the knee', N''),
( N'Q7180167', N'phagocyte bactericidal dysfunction', N'primary immunodeficiency disease where phagocytes have a diminished ability to fight bacterial infection', N''),
( N'Q7186555', N'phlyctenulosis', N'Human disease', N''),
( N'Q7189630', N'physical urticaria', N'urticaria induced by external physical influences', N''),
( N'Q7193408', N'pigmentation disorders', N'Human disease', N''),
( N'Q7193411', N'Pigmented purpuric dermatosis', N'human disease', N''),
( N'Q7193412', N'pigmented spindle cell nevus', N'human disease', N''),
( N'Q7193413', N'pigmented wart', N'Human disease', N''),
( N'Q7193794', N'Pilar sheath acanthoma', N'cutaneous condition most often found on the face, particularly above the upper lip in adults', N''),
( N'Q7197254', N'Pipecolic acidemia', N'a very rare autosomal recessive metabolic disorder that is caused by a peroxisomal defect', N''),
( N'Q719727', N'Fixed drug reaction', N'human disease', N''),
( N'Q7199538', N'pituitary gland disease', N'endocrine disease', N''),
( N'Q7199565', N'Pityrosporum folliculitis', N'', N''),
( N'Q72000', N'Lemierres syndrome', N'Human disease: infectious thrombophlebitis of the internal jugular vein', N''),
( N'Q720020', N'soft-tissue sarcoma', N'human disease', N''),
( N'Q7200296', N'placenta disease', N'uterine disease that is located in the placenta', N''),
( N'Q7200298', N'Placental infarction', N'Human disease', N''),
( N'Q7200299', N'Placental site nodule', N'Human disease', N''),
( N'Q7200300', N'Placental villous immaturity', N'', N''),
( N'Q7200301', N'placental site trophoblastic tumor', N'human disease', N''),
( N'Q720032', N'exanthema subitum', N'Human disease', N''),
( N'Q7201765', N'Plasma cell leukemia', N'Human disease', N''),
( N'Q7202249', N'platelet storage pool deficiency', N'Human disease', N''),
( N'Q7202556', N'Platybasia', N'platybasia is characterised by abnormal flattening of the skull base as defined as a base of skull angle over 143º.', N''),
( N'Q7202845', N'Platyspondylic lethal skeletal dysplasia, Torrance type', N'gene. Although PLSD-T is generally lethal, survival to adulthood has been reported in two families.', N''),
( N'Q7204591', N'Pleomorphic fibroma', N'Human disease', N''),
( N'Q7204592', N'pleomorphic lipoma', N'lipoma that is characterized by floret giant cells with overlapping nuclei', N''),
( N'Q7204730', N'pleuropneumonia', N'pneumonia accompanied by inflammation of the pleura and accumulation of pus in the pleural space caused by bacteria', N''),
( N'Q7204732', N'pleural disease', N'human disease, lung disease', N''),
( N'Q7204815', N'pleuropulmonary blastoma', N'pulmonary blastoma that derives from the lung or pleural cavity', N''),
( N'Q7204901', N'plexopathy', N'human disease', N''),
( N'Q7204944', N'Plica syndrome', N'Human disease', N''),
( N'Q720523', N'cervix erosion', N'ectropion', N''),
( N'Q7205365', N'Plum syndrome', N'', N''),
( N'Q7205992', N'pneumococcal pneumonia', N'human disease', N''),
( N'Q7205993', N'pneumocystosis', N'infection by Pneumocystis jirovecii', N''),
( N'Q7206010', N'Pneumosinus dilatans', N'', N''),
( N'Q7206990', N'podoconiosis', N'human disease', N''),
( N'Q721073', N'delusional disorder', N'mental disease', N''),
( N'Q7226305', N'polyembryoma', N'', N''),
( N'Q7226604', N'Polymorphous low-grade adenocarcinoma', N'', N''),
( N'Q7228858', N'Poorly differentiated thyroid cancer', N'', N''),
( N'Q7234177', N'posterior cerebral artery infarction', N'human disease', N''),
( N'Q7234207', N'posterior ischemic optic neuropathy', N'', N''),
( N'Q7234232', N'Posterior reversible encephalopathy syndrome', N'', N''),
( N'Q7234683', N'Potassium-aggravated myotonia', N'human disease', N''),
( N'Q7235099', N'potomania', N'hypo-osmolality syndrome related to massive consumption of beer', N''),
( N'Q7240236', N'premature atrial contraction', N'', N''),
( N'Q7242093', N'histoplasmosis retinitis', N'Human disease', N''),
( N'Q7243115', N'primary cutaneous amyloidosis', N'amyloidosis characterized by pruritus, skin scratching and by deposits of amyloid in the dermis', N''),
( N'Q7243132', N'Primary gonococcal dermatitis', N'', N''),
( N'Q7243137', N'primary hyperoxaluria', N'Human disease', N''),
( N'Q7243138', N'primary hypertrophic osteoarthropathy', N'human disease', N''),
( N'Q7243682', N'Primrose syndrome', N'', N''),
( N'Q7248833', N'progressive bulbar palsy', N'Human disease', N''),
( N'Q7248853', N'Progressive myoclonus epilepsy', N'Human disease', N''),
( N'Q7248854', N'Progressive osseous heteroplasia', N'gene (20q13.2-q13.3), coding for guanine nucleotide-binding proteins. POH can, however, be distinguished clinically by the deep and progressive nature of the heterotopic bone formation.', N''),
( N'Q7248868', N'Progressive rubella panencephalitis', N'human disease', N''),
( N'Q7248877', N'Progressive transformation of germinal centres', N'', N''),
( N'Q7249599', N'prolidase deficiency', N'', N''),
( N'Q7249608', N'proliferative vitreoretinopathy', N'Human disease', N''),
( N'Q7250189', N'Properdin deficiency', N'human disease', N''),
( N'Q7250337', N'propionic acidemia', N'organic acidemia that involes a nonfunctional propionyl CoA carboxylase affecting conversion of aminio acids and fats into sugar for energy', N''),
( N'Q7250686', N'Prosopamnesia', N'', N''),
( N'Q725129', N'adhesions of uterus', N'adhesions or fibrosis of endometrium of uterus', N''),
( N'Q7251459', N'Protein contact dermatitis', N'', N''),
( N'Q7252856', N'proximal renal tubular acidosis', N'', N''),
( N'Q7253115', N'Prurigo simplex', N'', N''),
( N'Q725345', N'Kaposis sarcoma', N'connective tissue cancer', N''),
( N'Q7254411', N'pseudo-Hurler polydystrophy', N'Human disease', N''),
( N'Q7254462', N'Pseudo gray platelet syndrome', N'', N''),
( N'Q7254511', N'pseudoangiomatous stromal hyperplasia', N'', N''),
( N'Q7255172', N'pseudoneurotic schizophrenia', N'mental disorder', N''),
( N'Q7255691', N'pseudovaginal perineoscrotal hypospadias', N'', N''),
( N'Q7256456', N'psychoorganic syndrome', N'disorder characterised by impairment of memory, thought disorders etc., due to diffuse psychoorganic brain damage', N''),
( N'Q7256482', N'psychosexual disorder', N'Human disease', N''),
( N'Q725845', N'histidinemia', N'histidine metabolism disease that involves a deficiency of the enzyme histidase', N''),
( N'Q7259515', N'Pulmonary-to-systemic shunt', N'', N''),
( N'Q7259524', N'pulmonary capillary hemangiomatosis', N'human disease', N''),
( N'Q7259585', N'dental pulp calcification', N'Human disease', N''),
( N'Q7261148', N'Pure hair-nail type ectodermal dysplasia', N'human disease', N''),
( N'Q7261474', N'Purple glove syndrome', N'', N''),
( N'Q7262033', N'pustulosis', N'human skin disease', N''),
( N'Q7263138', N'pyogenic liver abscess', N'areas of pus from bacterial infection in the hepatic parenchyma', N''),
( N'Q7263591', N'Pyridoxine-dependent epilepsy', N'extremely rare disorder', N''),
( N'Q7263721', N'pyrotechnic incidents', N'', N''),
( N'Q7263794', N'pyruvate carboxylase deficiency disease', N'Human disease', N''),
( N'Q7263801', N'pyruvate decarboxylase deficiency', N'carbohydrate metabolic disorder characterized by the buildup of lactic acid in the body and a variety of neurological problems and caused by a deficiency of one of the three enzymes in the pyruvate dehydrogenase complex', N''),
( N'Q7267327', N'Qazi Markouizos syndrome', N'syndrome that is characterized by hypotonia, congenital fiber type disproportion and dysharmonic skeletal maturation', N''),
( N'Q7269853', N'Quebec platelet disorder', N'Quebec platelet syndrome (QPS) is a platelet granule disorder characterized by moderate to severe bleeding after trauma, surgery or obstetric interventions, frequent ecchymoses, mucocutaneous bleeding and muscle and joint bleeds', N''),
( N'Q727096', N'congenital disorder', N'condition present at birth regardless of cause; human disease or disorder developed prior to birth', N''),
( N'Q727153', N'hiatus hernia', N'type of hernia in which abdominal organs (typically the stomach) slip through the diaphragm into the middle compartment of the chest', N''),
( N'Q727436', N'Lesch–Nyhan syndrome', N'', N''),
( N'Q7284803', N'Raine syndrome', N'Lethal osteosclerotic bone dysplasia is defined by generalized osteosclerosis with periosteal bone formation, characteristic facial dysmorphism, brain abnormalities including intracerebral calcifications, and neonatal lethal course', N''),
( N'Q7294342', N'Rapp-Hodgkin syndrome', N'autosomal dominant disease characterized by abnormal development of ectodermal tissues including the skin, hair, nails, teeth and sweat glands and anhidrotic ectodermal dysplasia with cleft lip/palate', N''),
( N'Q729735', N'chronic myeloid leukemia', N'myeloid leukemia that is characterized by over production of white blood cells', N''),
( N'Q7300315', N'Reactive neutrophilic dermatoses', N'disease', N''),
( N'Q7302398', N'Recessive dystrophic epidermolysis bullosa', N'Human disease', N''),
( N'Q730877', N'hydronephrosis', N'human disease', N''),
( N'Q7310756', N'Relationship obsessive–compulsive disorder', N'', N''),
( N'Q7312494', N'Renal medullary carcinoma', N'', N''),
( N'Q7312495', N'Renal medullary fibroma', N'', N''),
( N'Q7312498', N'kidney papillary necrosis', N'Human disease', N''),
( N'Q7313459', N'Renpenning syndrome', N'intellectual disability that is characterized by small head size (microcephaly), long narrow face, short stature, small testes, and intellectual deficit which follows X-linked inheritance and presents most often in males', N''),
( N'Q7314317', N'reproductive system disease', N'disease of anatomical entity that is located in reproductive system organs', N''),
( N'Q7315926', N'respiratory system cancer', N'organ system cancer located in the respiratory system that is characterized by uncontrolled cellular proliferation in the respiratory tract', N''),
( N'Q7316329', N'Restrictive dermopathy', N'Human disease', N''),
( N'Q7316718', N'reticular dysgenesis', N'Human disease', N''),
( N'Q7316720', N'Dowling-Degos disease', N'pigmentation disease characterized by a reticulate pattern of abnormally dark skin coloring, particularly in the bodys folds and creases', N''),
( N'Q7316721', N'reticulate acropigmentation of Kitamura', N'Human disease', N''),
( N'Q7316735', N'Reticulohistiocytoma', N'Human disease', N''),
( N'Q7316736', N'Reticulohistiocytosis', N'', N''),
( N'Q7316761', N'retinal degeneration  associated with rhodopsin mutations', N'retinitis pigmentosa that has material basis in mutation in the RHO gene on chromosome 3q22', N''),
( N'Q7316771', N'retinal vasculitis', N'human disease', N''),
( N'Q7318329', N'Revesz syndrome', N'dyskeratosis congenita that has material basis in an X-linked recessive mutation of TINF2 on chromosome 14q12', N''),
( N'Q7319683', N'Reynolds syndrome', N'Reynolds syndrome (RS) is an autoimmune disorder characterized by the association of primary biliary cirrhosis (PBC) with limited cutaneous systemic sclerosis (lcSSc) (see these terms)', N''),
( N'Q7319955', N'Rh deficiency syndrome', N'Human disease', N''),
( N'Q7320486', N'rheumatoid lung disease', N'Human disease', N''),
( N'Q7320761', N'rhizomelic chondrodysplasia punctata', N'Human disease', N''),
( N'Q7331102', N'alcohol abuse', N'substance abuse that involves the recurring use of alcoholic beverages despite negative consequences', N''),
( N'Q7333596', N'Right atrial enlargement', N'', N''),
( N'Q733493', N'Dandy-Walker syndrome', N'congenital disorder of nervous system', N''),
( N'Q733616', N'Erythema induratum', N'panniculitis on the calves. It occurs mainly in women, but it is very rare now', N''),
( N'Q734042', N'paroxysmal cold hemoglobinuria', N'', N''),
( N'Q734123', N'Asomatognosia', N'', N''),
( N'Q73518', N'marantic endocarditis', N'endocarditis that results from the deposition of small sterile vegetations on valve leaflets', N''),
( N'Q7355063', N'Rocker bottom foot', N'Isolated congenital vertical talus (CVT) is a rare pedal deformity recognizable at birth by a dislocation of the talonavicular joint, resulting in a characteristic radiographic near-vertical orientation of the talus', N''),
( N'Q735652', N'mitral valve prolapse', N'mitral valve disease where one or both of the cusps of the mitral valve bulge or collapse backward in the left atrium during systole', N''),
( N'Q7356544', N'tapeworm infection', N'helminthiasis', N''),
( N'Q736599', N'aspermia', N'complete lack of semen with ejaculation', N''),
( N'Q736633', N'Mismatch repair cancer syndrome', N'', N''),
( N'Q736715', N'chronic kidney disease', N'progressive loss in kidney function over a period of months or years', N''),
( N'Q736776', N'tennis elbow', N'condition in which the outer part of the elbow becomes sore and tender', N''),
( N'Q737712', N'Asplenia', N'Congenital disorder', N''),
( N'Q738101', N'Condyloma', N'Wikimedia disambiguation page', N''),
( N'Q738153', N'ileus', N'Human disease characterized by impairment of intestinal peristalsis; in modern language usually excludes mechanical bowel obstruction', N''),
( N'Q738170', N'small cell carcinoma', N'type of carcinoma that commonly arises within lung and sometime other body sites', N''),
( N'Q73828', N'oromandibular dystonia', N'focal dystonia that is characterized by distortions of the mouth and tongue.', N''),
( N'Q738292', N'Japanese encephalitis', N'infection of the brain caused by the Japanese encephalitis virus', N''),
( N'Q7388564', N'SAHA syndrome', N'', N''),
( N'Q7390227', N'SHORT syndrome', N'', N''),
( N'Q739221', N'astereognosia', N'agnosia that is the loss of the ability to recognize objects by touch based on its texture, size and weight', N''),
( N'Q7404457', N'Salicylate sensitivity', N'drug allergy that has allergic trigger acetylsalicylic acid', N''),
( N'Q7404867', N'Salivary duct carcinoma', N'', N''),
( N'Q7404869', N'Salivary gland–like carcinoma of the lung', N'', N''),
( N'Q7405738', N'Salpingitis isthmica nodosa', N'Human disease', N''),
( N'Q740731', N'Jarisch-Herxheimer reaction', N'reaction to endotoxin-like products released by the death of harmful microorganisms within the body during antimicrobial treatment', N''),
( N'Q741208', N'pseudotumor cerebri', N'Human disease', N''),
( N'Q741315', N'von Hippel-Lindau disease', N'a rare genetic disorder characterized by visceral cysts and benign tumors in multiple organ systems with potential for subsequent malignant change.', N''),
( N'Q741713', N'panic disorder', N'anxiety disorder characterized by unexpected and repeated episodes of intense fear accompanied by physical symptoms', N''),
( N'Q742099', N'subclavian steal syndrome', N'constellation of signs and symptoms that arise from retrograde (reversed) blood flow in the vertebral artery or the internal thoracic artery, due to a proximal stenosis (narrowing) and/or occlusion of the subclavian artery', N''),
( N'Q7423635', N'sarcosinemia', N'Sarcosinemia is a metabolic disorder characterized by an increased concentration of sarcosine in plasma and urine due to sarcosine dehydrogenase deficiency', N''),
( N'Q742500', N'methylmalonic acidemia', N'organic acidemia that involves an accumulation of methylmalonic acid in the blood', N''),
( N'Q742672', N'dyscalculia', N'neurological condition, developmental or acquired', N''),
( N'Q742762', N'diffuse idiopathic skeletal hyperostosis', N'calcinosis that is the calcification or a bony hardening of ligaments in areas where they attach to your spine', N''),
( N'Q7429841', N'Scalp–ear–nipple syndrome', N'', N''),
( N'Q7431481', N'Schinzel–Giedion syndrome', N'Schinzel-Giedion syndrome (SGS) is an ectodermal dysplasia syndrome chiefly characterized by a distinctive facial dysmorphism, hydronephrosis, severe developmental delay, typical skeletal malformations, and genital and cardiac anomalies', N''),
( N'Q7433355', N'Schöpf–Schulz–Passarge syndrome', N'SchC6pf-Schulz-Passarge syndrome (SSPS) is a rare autosomal recessive ectodermal dysplasia characterized by multiple eyelid apocrine hidrocystomas, palmoplantar keratoderma, hypotrichosis, hypodontia and nail dystrophy', N''),
( N'Q7434137', N'scleredema', N'Human disease', N''),
( N'Q7434154', N'sclerocornea', N'corneal disease in which the cornea blends with sclera, resulting in clouding of the cornea', N''),
( N'Q7434176', N'scleromyositis', N'an autoimmune disease', N''),
( N'Q743545', N'fetal erythroblastosis', N'Human disease', N''),
( N'Q7437571', N'Scott syndrome', N'inherited blood coagulation disease', N''),
( N'Q7440153', N'Seabathers eruption', N'', N''),
( N'Q7442318', N'Sebaceoma', N'', N''),
( N'Q7442319', N'sebaceous carcinoma', N'Human disease', N''),
( N'Q7442321', N'Sebaceous lymphadenoma', N'', N''),
( N'Q74426740', N'Carcinocythemia', N'', N''),
( N'Q744305', N'lordosis', N'curvature of the spine', N''),
( N'Q744387', N'Rocky Mountain spotted fever', N'human disease', N''),
( N'Q7444204', N'Secretans syndrome', N'', N''),
( N'Q744790', N'Treacher Collins syndrome', N'Human disease', N''),
( N'Q7451019', N'Sensenbrenner syndrome', N'Human disease', N''),
( N'Q7451220', N'Senter syndrome', N'', N''),
( N'Q745162', N'polyarteritis nodosa', N'Human disease', N''),
( N'Q7454942', N'Serkal syndrome', N'genetic disorder', N''),
( N'Q7455058', N'Serous carcinoma', N'', N''),
( N'Q7455060', N'serous cystadenocarcinoma', N'cystadenocarcinoma that derives from epithelial cells originating in glandular tissue forming serous lesions', N''),
( N'Q7455473', N'Sertoli cell nodule', N'', N''),
( N'Q7458487', N'sex chromosome disorder', N'human disease', N''),
( N'Q7458489', N'Sex cord tumour with annular tubules', N'', N''),
( N'Q745865', N'trichomoniasis', N'gagoparasitic protozoa infectious disease that is caused by the parasites Trichomonas vaginalis or Trichomonas tenax', N''),
( N'Q7458757', N'Sexual anorexia', N'', N''),
( N'Q746001', N'thromboangiitis obliterans', N'Human disease', N''),
( N'Q746781', N'neuroacanthocytosis', N'Neuroacanthocytosis (NA) syndromes are a group of genetic diseases characterized by the association of red blood cell acanthocytosis (deformed erythrocytes with spike-like protrusions) and progressive degeneration of the basal ganglia', N''),
( N'Q7476276', N'hemometra', N'Human disease', N''),
( N'Q7476596', N'genital herpes', N'infection by herpes simplex virus (HSV) of the genitals', N''),
( N'Q747735', N'paranoid personality disorder', N'mental disorder characterized by paranoia and a pervasive, long-standing suspiciousness and generalized mistrust of others', N''),
( N'Q748309', N'pathological gambling', N'urge to continuously gamble despite harmful negative consequences or a desire to stop', N''),
( N'Q748376', N'phakomatosis', N'Multisystem disorders that involve the ectodermal structures like central nervous system, skin and eyes.', N''),
( N'Q748442', N'Methemoglobinemia', N'Human disease', N''),
( N'Q7484623', N'tyrosinemia type II', N'tyrosinemia that has material basis in deficiency of hepatic tyrosine aminotransferase located in the liver and is characterized by keratitis, painful palmoplantar hyperkeratosis, mental retardation, and elevated serum tyrosine levels', N''),
( N'Q749159', N'asthenopia', N'Human disease', N''),
( N'Q749409', N'osteogenesis imperfecta', N'osteochondrodysplasia that has material basis in a deficiency in type-I collagen which results in brittle bones and defective connective tissue', N''),
( N'Q7501551', N'short-chain acyl-coenzyme A dehydrogenase deficiency', N'lipid metabolism disorder that is characterized by deficiency of the enzyme short chain acyl-CoA dehydrogenase that results in the inability to convert short chain fatty acids', N''),
( N'Q7506696', N'sialuria', N'lysosomal storage disease characterized by increased sialic acid in the urine', N''),
( N'Q7507600', N'Sick cell syndrome', N'', N''),
( N'Q750826', N'medium chain acyl-CoA dehydrogenase deficiency', N'lipid metabolism disorder that is characterized by a deficiency of the enzyme medium chain acyl-CoA dehydrogenase that results in the inability to convert medium chain fatty acids to energy, particularly during fasting', N''),
( N'Q751261', N'Foster-Kennedy syndrome', N'Human disease', N''),
( N'Q751631', N'pure red-cell aplasia', N'Human disease', N''),
( N'Q751641', N'hypersomnia', N'excessive sleep', N''),
( N'Q7520132', N'Simon focus', N'', N''),
( N'Q752216', N'Gilbert syndrome', N'metabolic disorder', N''),
( N'Q752298', N'Cri-Du-Chat syndrome', N'Human disease', N''),
( N'Q7524910', N'Sinonasal undifferentiated carcinoma', N'A rare, highly aggressive carcinoma that arises from the sinonasal tract. It is characterized by the presence of small to medium size malignant cells. The prognosis is poor.', N''),
( N'Q7534814', N'Skewed X-inactivation', N'Inactivation of one parents X chromosome more so than the others', N''),
( N'Q7535394', N'Skin fragility syndrome', N'Epidermolysis bullosa simplex due to plakophilin deficiency (EBS-PD) is a suprabasal subtype of epidermolysis bullosa simplex (EBS, see this term) characterized by generalized superficial erosions and less commonly blistering', N''),
( N'Q7535428', N'Skin track', N'', N''),
( N'Q753904', N'rheumatic fever', N'post-streptococcal inflammatory disease that can involve the heart, joints, skin, & brain', N''),
( N'Q754031', N'atelectasis', N'collapse or closure of a lung resulting in reduced or absent gas exchange', N''),
( N'Q7542594', N'Small-blue-round-cell tumor', N'', N''),
( N'Q754348', N'infant respiratory distress syndrome', N'Human disease effecting newborns', N''),
( N'Q7545701', N'Smith–Fineman–Myers syndrome', N'', N''),
( N'Q7546446', N'smooth tongue', N'Human disease', N''),
( N'Q7550406', N'social emotional agnosia', N'agnosia that is a loss of the ability to perceive facial expression, body language and intonation, rendering them unable to non-verbally perceive peoples emotions and limiting that aspect of social interaction', N''),
( N'Q7556879', N'solar retinopathy', N'Human disease', N''),
( N'Q7557926', N'Solid pseudopapillary tumour', N'', N''),
( N'Q7558248', N'solitary fibrous tumor', N'Human disease', N''),
( N'Q7558253', N'solitary mastocytoma', N'Human disease', N''),
( N'Q7562539', N'facial paralysis', N'common problem that involves the paralysis of any structures innervated by the facial nerve', N''),
( N'Q7562765', N'Soot tattoo', N'', N''),
( N'Q756289', N'nephroblastoma', N'rare disease', N''),
( N'Q756610', N'otosclerosis', N'otitis interna characterized by an abnormal bone growth in the middle ear', N''),
( N'Q7573981', N'accommodative spasm', N'Human disease', N''),
( N'Q7573994', N'spastic hemiplegia', N'type of spastic cerebral palsy characterized by increased muscle tone of the arm and leg on the same side of the body', N''),
( N'Q7573995', N'spastic cerebral palsy', N'Cerebral palsy characterized by high muscle tone', N''),
( N'Q7574983', N'specific developmental disorder', N'range of neurodevelopmental conditions', N''),
( N'Q7576386', N'spermatocytoma', N'Human disease', N''),
( N'Q7576389', N'spermatogenesis arrest', N'', N''),
( N'Q757676', N'Atony', N'muscle losing its strength', N''),
( N'Q7577457', N'spinal disease', N'disease involving the vertebral column', N''),
( N'Q7577467', N'Spinal muscular atrophy with lower extremity predominance', N'rare neuromuscular disorder of infants characterised by severe progressive muscle atrophy', N''),
( N'Q7577468', N'Spinal muscular atrophy with progressive myoclonic epilepsy', N'rare neurodegenerative disease whose symptoms include slowly progressive muscle wasting', N''),
( N'Q757749', N'atrial heart septal defect', N'A heart septal defect located in in the septum that separates the two atria of the heart.', N''),
( N'Q7577496', N'spindle cell carcinoma', N'squamous cell carcinoma that is usually composed of the squamous cell type and results in fusiform development of rapidly proliferating cells', N''),
( N'Q7577498', N'spindle cell lipoma', N'lipoma that is an asymptomatic, slow-growing subcutaneous tumor that has a predilection for the posterior back, neck, and shoulders of older men', N''),
( N'Q7577499', N'spindle cell rhabdomyosarcoma', N'human disease', N''),
( N'Q7577501', N'Spindle cell squamous cell carcinoma', N'Human disease', N''),
( N'Q7577703', N'spiradenoma', N'Human disease', N''),
( N'Q757838', N'keratitis', N'corneal disease that is characterized by inflammation of the cornea.', N''),
( N'Q7578540', N'splenic disease', N'human disease', N''),
( N'Q7578545', N'Splenic lymphoma with villous lymphocytes', N'', N''),
( N'Q7578590', N'splints', N'ailment of the horse or pony', N''),
( N'Q7578690', N'Split hand syndrome', N'Neurological syndrome involving wasting of part of the hand', N''),
( N'Q7578955', N'Spondylodiscitis', N'', N''),
( N'Q7578957', N'spondyloepimetaphyseal dysplasia, Pakistani type', N'spondyloepimetaphyseal dysplasia that is characterized by short stature, short and bowed lower limbs, mild brachydactyly, kyphoscoliosis, abnormal gait, enlarged knee joints, precocious osteoarthropathy, and normal intelligence', N''),
( N'Q7578959', N'Spondyloperipheral dysplasia', N'', N''),
( N'Q7578960', N'spondyloepiphyseal dysplasia congenita', N'Human disease', N''),
( N'Q7581954', N'squamous cell papilloma', N'Human disease', N''),
( N'Q7581957', N'Squamous odontogenic tumor', N'', N''),
( N'Q7604533', N'status migrainosus', N'', N''),
( N'Q7607891', N'stenosing tenosynovitis', N'narrowing or stenosis of a tendons retinacular sheath', N''),
( N'Q7611600', N'glucocorticoid-induced osteoporosis', N'Human disease', N''),
( N'Q7611608', N'steroid diabetes', N'insulin and steroid treatment', N''),
( N'Q761496', N'parametritis', N'Human disease', N''),
( N'Q7616403', N'stiff skin syndrome', N'', N''),
( N'Q7616509', N'neurofibromatosis type I', N'type of neurofibromatosis disease', N''),
( N'Q7623345', N'Streptococcal intertrigo', N'', N''),
( N'Q7623555', N'Striate palmoplantar keratoderma', N'', N''),
( N'Q762583', N'catarrh', N'inflammation of the mucous membranes in one of the airways or cavities of the body', N''),
( N'Q7630706', N'Subacute cutaneous lupus erythematosus', N'', N''),
( N'Q7630974', N'Subcorneal pustular dermatosis', N'Human disease', N''),
( N'Q7630991', N'subcutaneous fat necrosis of the newborn', N'', N''),
( N'Q7631130', N'cork-handlers disease', N'An extrinsic allergic alveolitis caused by inhalation of cork dust containing the antigens produced by the fungus Penicillium glabrum. The symptoms include dyspnea, wheezing cough, fever and asthenia.', N''),
( N'Q7632070', N'substance use disorder', N'mental disorder involving the abuse or dependence on a substance that is ingested in order to produce a high, alter ones senses, or otherwise affect functioning', N''),
( N'Q7632441', N'subvalvular aortic stenosis', N'Human disease', N''),
( N'Q7632698', N'Succinyl-CoA:3-oxoacid CoA transferase deficiency', N'Succinyl-CoA:3-ketoacid CoA transferase deficiency (SCOTD) is a defect in ketone body utilization characterized by severe, potentially fatal intermittent episodes of ketoacidosis', N''),
( N'Q763356', N'CREST syndrome', N'syndrome characterized by calcinosis, Raynauds phenomeno, esophageal dysmotility, sclerodactyly and telangiectasia', N''),
( N'Q7635034', N'orofaciodigital syndrome III', N'Human disease', N''),
( N'Q7643645', N'Superior limbic keratoconjunctivitis', N'ocular disease characterized by episodes of recurrent inflammation of the superior cornea and limbus, as well as of the superior tarsal and bulbar conjunctiva', N''),
( N'Q7644639', N'suppression amblyopia', N'Human disease', N''),
( N'Q7644763', N'supraventricular extrasystole', N'', N''),
( N'Q7645976', N'surface epithelial-stromal tumor', N'ovarian tumor that is derived_from ovarian surface epithelium', N''),
( N'Q7646086', N'Surfers myelopathy', N'spinal cord injury caused by hyperextension of the back', N''),
( N'Q7662637', N'synpolydactyly', N'syndactyly characterized by an increased number of digits; often a result of a mutation in the HOX D13 gene', N''),
( N'Q7663355', N'syringocystadenoma papilliferum', N'Human disease', N''),
( N'Q7663815', N'Systemic inflammation', N'', N''),
( N'Q7663896', N'systolic hypertension', N'elevated systolic blood pressure', N''),
( N'Q7667895', N'T-cell leukemia', N'Human disease', N''),
( N'Q7667896', N'T-cell lymphoma', N'Rare T-cell lymphoma', N''),
( N'Q766856', N'pityriasis rubra pilaris', N'Human disease', N''),
( N'Q7672692', N'T cell deficiency', N'Human disease', N''),
( N'Q767327', N'sporotrichosis', N'primary systemic mycosis that results in a systemic fungal infection, has material basis in Sporothrix schenckii in animals and humans and results in formation of red papule at the site of inoculation', N''),
( N'Q767485', N'respiratory failure', N'inadequate gas exchange by the respiratory system', N''),
( N'Q7685929', N'Targetoid hemosiderotic hemangioma', N'Human disease', N''),
( N'Q768888', N'miliaria', N'Human disease', N''),
( N'Q7688951', N'Taussig–Bing syndrome', N'hearth disease', N''),
( N'Q769595', N'meibomian cyst', N'Cyst in the eyelid caused by inflammation of a blocked oil gland', N''),
( N'Q76973', N'yaws', N'Human disease: tropical infection of the skin, bones and joints caused by the spirochete bacterium Treponema pallidum pertenue', N''),
( N'Q769741', N'adenoviral keratoconjunctivitis', N'common and highly contagious viral infection of the eye', N''),
( N'Q769815', N'food allergy', N'hypersensitivity reaction type I disease that is an abnormal response to a food, triggered by the bodys immune system', N''),
( N'Q7698379', N'Tempi syndrome', N'TEMPI syndrome is a rare multi-systemic disease characterized by the presence of Telangiectasias, Erythrocytosis with elevated erythropoietin levels, Monoclonal gammopathy, Perinephric-fluid collections, and Intrapulmonary shunting', N''),
( N'Q769988', N'Goldenhar syndrome', N'A syndrome that is characterized by incomplete development of the ear, nose, soft palate, lip, and mandible. It is associated with anomalous development of the first branchial arch and second branchial arch.', N''),
( N'Q7700555', N'orbital tenonitis', N'Human disease', N''),
( N'Q7702722', N'Terminal complement pathway deficiency', N'', N''),
( N'Q7702740', N'Terminal osseous dysplasia with pigmentary defects', N'Terminal osseous dysplasia-pigmentary defects syndrome is characterised by malformation of the hands and feet, pigmentary skin lesions on the face and scalp and digital fibromatosis', N''),
( N'Q7705854', N'testicular disease', N'Human disease', N''),
( N'Q7706537', N'tetrahydrobiopterin deficiency', N'', N''),
( N'Q7707070', N'Teunissen–Cremers syndrome', N'Stapes ankylosis with broad thumbs and toes is a very rare genetic bone disorder characterized by ankylosis of stapes, broad thumbs and halluces, conductive hearing loss and hyperopia', N''),
( N'Q770843', N'glucagonoma', N'', N''),
( N'Q771310', N'anodontia', N'human disease', N''),
( N'Q772022', N'asplenia with cardiovascular anomalies', N'rare disease', N''),
( N'Q773118', N'Andersen-Tawil syndrome', N'Human disease', N''),
( N'Q774016', N'Denys-Drash syndrome', N'Human disease', N''),
( N'Q774483', N'galactosemia', N'carbohydrate metabolic disorder that involves a defect in galactose metabolism resulting in toxic levels of galactose 1-phosphate in various tissues', N''),
( N'Q775593', N'specific language impairment', N'range of neurodevelopmental conditions', N''),
( N'Q7758678', N'night blindness', N'condition making it difficult or impossible to see in relatively low light', N''),
( N'Q775927', N'tinea corporis', N'fungal infection', N''),
( N'Q776026', N'biotinidase deficiency', N'multiple carboxylase deficiency that involves a deficiency in biotinidase', N''),
( N'Q776881', N'hereditary hemorrhagic telangiectasia', N'genetic disorder involving capillaries', N''),
( N'Q777087', N'echinococcosis', N'parasitic disease of tapeworms of the Echinococcus type', N''),
( N'Q778502', N'vaginal discharge', N'mixture of liquid, cells, and bacteria, produced in the vagina and cervix, lubricating and protecting the vagina; typically clear or white in color, with consistency varying from thin to thick, typically without a strong odor', N''),
( N'Q779203', N'CINCA syndrome', N'Chronic Infantile Neurological, Cutaneous, and Articular (CINCA) syndrome is characterised by skin rash, joint involvement, chronic meningitis with granulocytes and, in some cases, sensorineural hearing loss and ocular signs', N''),
( N'Q779250', N'Crouzon syndrome', N'Congenital disorder of the skull and face', N''),
( N'Q7799620', N'thymic carcinoma', N'A thymus cancer that derives from epithelial cells. The tumor cells in a thymic carcinoma look very different from the normal cells of the thymus, grow more quickly, and have usually spread to other parts of the body when the cancer is found.', N''),
( N'Q7799748', N'Thyroid dyshormonogenesis', N'Familial thyroid dyshormonogenesis is a type of primary congenital hypothyroidism (see this term), a permanent thyroid hormone deficiency that is present from birth, which results from inborn errors of thyroid hormone synthesis', N''),
( N'Q7801152', N'Tietz syndrome', N'monogenic disease that is characterized by congenital profound bilateral sensorineural hearing loss and generalized albino-like hypopigmentation of skin, eyes and hair that has material basis in mutation in the MITF gene on chromosome 3p13', N''),
( N'Q780629', N'panniculitis', N'Inflammation of the subcutaneous adipose tissue', N''),
( N'Q7809849', N'Titanium metallic discoloration', N'', N''),
( N'Q781618', N'cleidocranial dysplasia', N'osteochondrodysplasia that has material basis in mutations in the RUNX2 gene which results in undeveloped or absent located in clavicle along with delayed closing of fontanels in the located in skull', N''),
( N'Q78188915', N'Coffee Wilt Disease', N'Coffee three disease', N''),
( N'Q7824262', N'tooth and nail syndrome', N'Human disease', N''),
( N'Q7824266', N'tooth disease', N'disease involving the calcareous tooth', N''),
( N'Q7824277', N'tooth resorption', N'Human disease', N''),
( N'Q7824965', N'topographical agnosia', N'agnosia that is a loss of the ability to rely on visual cues to guide them directionally due to the inability to recognise objects', N''),
( N'Q782515', N'ureterocele', N'cystic dilatation of the end of a ureter as it enters into the urinary bladder', N''),
( N'Q782958', N'centronuclear myopathy', N'myopathy characterized by abnormally located  nuclei in skeletal muscle cells', N''),
( N'Q7830375', N'nutritional optic neuropathy', N'Human disease', N''),
( N'Q7830379', N'Toxic encephalopathy', N'nervous system disease that results from exposure to neurotoxicants and is characterized by an altered mental status, memory loss, and visual problems', N''),
( N'Q7830387', N'Plummers disease', N'Human disease', N''),
( N'Q7831293', N'tracheal neoplasm', N'Human disease', N''),
( N'Q7831319', N'tracheoesophageal fistula', N'congenital disorder of digestive system', N''),
( N'Q7833752', N'Transaldolase deficiency', N'', N''),
( N'Q7834208', N'transfusion hemosiderosis', N'', N''),
( N'Q7834264', N'transient bullous dermolysis of the newborn', N'Transient bullous dermolysis of the newborn is a rare subtype of dystrophic epidermolysis bullosa (DEB, see this term) characterized by generalized blistering at birth that usually regresses within the first 6 to 24 months of life', N''),
( N'Q7834274', N'Transient erythroporphyria of infancy', N'', N''),
( N'Q7834286', N'transient neonatal diabetes mellitus', N'neonatal diabetes mellitus characterized by hyperglycemia during the neonatal period that remits during infancy but recurs in later life in most patients', N''),
( N'Q7835825', N'Traumatic bone cyst', N'', N''),
( N'Q783644', N'Lynch syndrome', N'Human disease', N''),
( N'Q783903', N'contact dermatitis', N'Human disease', N''),
( N'Q7839508', N'Trevors disease', N'', N''),
( N'Q7840696', N'Tricho-hepato-enteric syndrome', N'', N''),
( N'Q7840841', N'Trichomegaly', N'human disease', N''),
( N'Q7841014', N'trichosporonosis', N'opportunistic mycosis that results in disseminated infection, has material basis in Trichosporon and results in formation of nontender erythematous nodules anywhere on the body', N''),
( N'Q7841074', N'Tricho–dento–osseous syndrome', N'congenital disorder of digestive system', N''),
( N'Q7843329', N'triple-A syndrome', N'Human disease', N''),
( N'Q7844856', N'Trochleitis', N'', N''),
( N'Q7845637', N'trophoblastic neoplasm', N'gestational or non-gestational  germ cell and embryonal cancer that derives from trophoblastic tissue', N''),
( N'Q784564', N'akinetopsia', N'agnosia that is a loss of motion perception', N''),
( N'Q7847568', N'hermaphroditism', N'Human disease', N''),
( N'Q7850839', N'tuberculoid leprosy', N'leprosy that results in one erythematous large plaque with well-defined borders that are elevated and that slope down into an atrophic center', N''),
( N'Q7850851', N'Tuberculous cellulitis', N'', N''),
( N'Q7850856', N'pericardial tuberculosis', N'extrapulmonary tuberculosis that is located in pericardium resulting in acute pericarditis, chronic pericardial effusion, cardiac tamponade or pericardial constriction', N''),
( N'Q7852683', N'Tumoral calcinosis', N'', N''),
( N'Q7853304', N'Tunnel cluster', N'', N''),
( N'Q785827', N'keratoacanthoma', N'Human disease', N''),
( N'Q7860879', N'type IV hypersensitivity', N'inflammatory response driven by T cell recognition of processed soluble or cell-associated antigens, leading to cytokine release and leukocyte activation', N''),
( N'Q7861692', N'tyrosinemia type III', N'tyrosinemia that has material basis in deficiency of 4-hydroxyphenylpyruvate dioxygenase disrupting the break down of tyrosine', N''),
( N'Q786468', N'frontal lobe disorder', N'disorder', N''),
( N'Q786844', N'autoimmune hepatitis', N'autoimmune disease of gastrointestinal tract that results in inflammation located in liver caused by the bodys immune system attacking the liver cells', N''),
( N'Q786852', N'gastrinoma', N'neuroendocrine tumor that results in an overproduction of gastric acid', N''),
( N'Q7876086', N'UV-sensitive syndrome', N'autosomal recessive disease characterized by photosensitivity and liver spots (solar lentigines)', N''),
( N'Q787751', N'glycogen storage disease V', N'Human disease', N''),
( N'Q7879206', N'Ullrich disease', N'', N''),
( N'Q7879706', N'Ulnar collateral ligament injury', N'', N''),
( N'Q7879711', N'ulnar neuropathy', N'Human disease', N''),
( N'Q7879712', N'ulnar-mammary syndrome', N'Human disease', N''),
( N'Q7883835', N'Undervirilization', N'', N''),
( N'Q7899541', N'Urachal cancer', N'Human disease', N''),
( N'Q7900262', N'Urban–Rogers–Meyer syndrome', N'', N''),
( N'Q7900355', N'Ureaplasma infection', N'', N''),
( N'Q7900422', N'ureteral cancer', N'urinary system cancer that is located in the ureter', N''),
( N'Q7900433', N'urethral syndrome', N'human disease', N''),
( N'Q7900436', N'prolapse of urethra', N'Human disease', N''),
( N'Q7900619', N'bladder neck obstruction', N'Human disease', N''),
( N'Q7900855', N'urogenital neoplasm', N'tumors or cancer of the urogenital system in either the male or the female', N''),
( N'Q7900883', N'urinary system disease', N'disease of the urinary system', N''),
( N'Q7901359', N'urticarial allergic eruption', N'human disease', N''),
( N'Q7901561', N'toxicodendron dermatitis', N'Human disease', N''),
( N'Q7902645', N'Uterine adenosarcoma', N'', N''),
( N'Q7902651', N'uterine inversion', N'Human disease', N''),
( N'Q790971', N'Bartter disease', N'Human disease', N''),
( N'Q7916836', N'Vasitis nodosa', N'', N''),
( N'Q7918687', N'vein disorder', N'vascular disease located in a vein', N''),
( N'Q7920253', N'ventilator-associated pneumonia', N'pneumonia caused by extended or improper use of a pulmonary mechanical ventilator', N''),
( N'Q7922589', N'Verruciform xanthoma', N'Human disease', N''),
( N'Q7922590', N'verruca plana', N'Human disease', N''),
( N'Q7922592', N'verrucous carcinoma', N'squamous cell carcinoma that is a diffuse, papillary, non metastasizing, well differentiated, malignant neoplasm of epidermis or oral epithelium', N''),
( N'Q7923095', N'very long chain acyl-CoA dehydrogenase deficiency', N'human disease', N''),
( N'Q7923227', N'Vesicular pemphigoid', N'', N''),
( N'Q7923229', N'vesiculobullous skin disease', N'Human disease', N''),
( N'Q7923448', N'Vestibular adenitis', N'', N''),
( N'Q7924673', N'Vibratory angioedema', N'human disease', N''),
( N'Q7925271', N'Vici syndrome', N'autosomal recessive disease characterized by callosal agenesis, cataracts, cardiomyopathy, combined immunodeficiency and hypopigmentation, with material basis in mutation in the EPG5 gene on chromosome 18q12.3.', N''),
( N'Q7931112', N'Villitis of unknown etiology', N'', N''),
( N'Q7931117', N'Villoglandular adenocarcinoma of the cervix', N'', N''),
( N'Q7931125', N'villous adenoma', N'Human disease', N''),
( N'Q7936643', N'visuospatial dysgnosia', N'inability to analyse and orient using visual representations and their spatial relationships', N''),
( N'Q7939442', N'Vohwinkel syndrome', N'human disease', N''),
( N'Q794002', N'Azoor', N'disease', N''),
( N'Q794026', N'azoospermia', N'male infertility disease characterized by the absence of any measurable level of sperm in semen', N''),
( N'Q794072', N'azotemia', N'abnormally high levels of nitrogen in the blood', N''),
( N'Q794086', N'hypokalemia', N'Human disease', N''),
( N'Q7943630', N'Vulvar childhood pemphigoid', N'', N''),
( N'Q7943634', N'Vulvar vestibulitis', N'', N''),
( N'Q794457', N'locked-in syndrome', N'nervous system disease that is characterized by complete paralysis of all voluntary muscles except for the ones that control the movements of the eyes', N''),
( N'Q795024', N'sirenomelia', N'disease', N''),
( N'Q796150', N'intertrigo', N'', N''),
( N'Q797128', N'bovine virus diarrhea', N'significant economic disease of cattle caused by two species of Pestivirus', N''),
( N'Q7974427', N'watershed stroke', N'brain ischemia in the vulnerable border zones between the tissues supplied by the anterior, posterior and middle cerebral arteries', N''),
( N'Q797668', N'babesiosis', N'malaria-like parasitic disease caused by infection with Babesia and nalga, a genus of Apicomplexa', N''),
( N'Q797708', N'Babinski–Nageotte syndrome', N'alternating brainstem syndrome', N''),
( N'Q79793', N'measles', N'viral disease affecting humans', N''),
( N'Q7982503', N'Wende–Bauckus syndrome', N'', N''),
( N'Q79928', N'acne', N'sebaceous glands disease characterized by areas of blackheads, whiteheads, pimples, greasy skin, and possibly scarring.', N''),
( N'Q7995600', N'white dot syndromes', N'eye diseases', N''),
( N'Q799615', N'osteitis fibrosa cystica', N'bone resorption disease that has material basis in hyperparathyroidism which results in hyperactivity in osteoclasts, deformity, and loss of mass located in bone', N''),
( N'Q8023321', N'Wilson–Turner syndrome', N'Human disease', N''),
( N'Q8026184', N'Winter-over syndrome', N'psychological condition related to the Antarctic winter', N''),
( N'Q8027735', N'Wisslers syndrome', N'syndrome that is characterized by four typical symptoms: polymorphous exanthemas, recurrent high fever, leucocytosis and arthralgia', N''),
( N'Q8029730', N'Wolcott-Rallison syndrome', N'Wolcott-Rallison syndrome (WRS) is a very rare genetic disease, characterized by permanent neonatal diabetes mellitus (PNDM) with multiple epiphyseal dysplasia and other clinical manifestations, including recurrent episodes of acute liver failure', N''),
( N'Q8032762', N'Woodhouse–Sakati syndrome', N'Woodhouse-Sakati syndrome is a multisystemic disorder characterized by hypogonadism, alopecia, diabetes mellitus, intellectual deficit and extrapyramidal signs with choreoathetoid movements and dystonia', N''),
( N'Q8037184', N'Worths syndrome', N'hyperostosis that has material basis in a mutation in the LRP5 gene which results in increased bone density and bony structures located in palate', N''),
( N'Q8038353', N'Wrinkly skin syndrome', N'', N''),
( N'Q8041552', N'X-linked congenital stationary night blindness', N'', N''),
( N'Q8041560', N'X-linked intellectual disability', N'syndromic intellectual characterized by an X-linked inheritance pattern', N''),
( N'Q8041561', N'X-linked recessive chondrodysplasia punctata', N'', N''),
( N'Q8041562', N'X-linked spinal muscular atrophy type 2', N'', N''),
( N'Q8041590', N'X-type histiocytosis', N'', N''),
( N'Q8042656', N'46 XX gonadal dysgenesis', N'gonadal dysgenesis that is characterized by the lack of functional ovaries to induce puberty in an otherwise 46,XX female', N''),
( N'Q8043037', N'Xanthoma diabeticorum', N'', N''),
( N'Q8043040', N'Xanthoma striatum palmare', N'', N''),
( N'Q8043043', N'Xanthomatous biliary cirrhosis', N'disease', N''),
( N'Q804521', N'bacterial vaginosis', N'vaginal infection caused by excessive growth of bacteria', N''),
( N'Q8046191', N'Y chromosome microdeletion', N'Male sterility due to chromosome Y deletion is characterized by a severe deficiency of spermatogenesis. Chromosome Y deletions are a frequent genetic cause of male infertility.', N''),
( N'Q805030', N'Balkan nephropathy', N'interstitial nephritis endemic to the regions along the Danube river, in the modern countries of Croatia, Bosnia and Herzegovina, Serbia, Romania and Bulgaria', N''),
( N'Q8052144', N'Yemenite deaf-blind hypopigmentation syndrome', N'Yemenite deaf-blind hypopigmentation syndrome is an exceedingly rare genetic disorder characterized by cutaneous pigmentation anomalies, ocular disorders and hearing loss', N''),
( N'Q8058422', N'Young-Simpson syndrome', N'Human disease', N''),
( N'Q8061303', N'Yunis-Varon syndrome', N'Human disease', N''),
( N'Q8064158', N'Zadik–Barak–Levin syndrome', N'', N''),
( N'Q8067052', N'myofibrillar myopathy 4', N'Human disease', N''),
( N'Q8072143', N'Zimmermann–Laband syndrome', N'rare disorder characterized by gingival fibromatosis, coarse facial appearance, and absence or hypoplasia of nails or terminal phalanges of hands and feet', N''),
( N'Q8072745', N'Zirconium granuloma', N'', N''),
( N'Q8074019', N'Zonular cataract and nystagmus', N'cataract that has material basis in mutation in the NHS gene on chromosome Xp22', N''),
( N'Q8075299', N'Zunich–Kaye syndrome', N'CHIME syndrome is a rare ectodermal dysplasia syndrome characterized by ocular colobomas, cardiac defects, ichthyosiform dermatosis, intellectual disability, conductive hearing loss and epilepsy', N''),
( N'Q8084905', N'autoimmune disease', N'type of human disease', N''),
( N'Q808892', N'Barretts esophagus', N'esophagus condition', N''),
( N'Q809122', N'Cervicocranial syndrome', N'syndrome that involves occipital head aches, nystagmus on head movement, tinnitus, spasms, blurred vision, corneal hyperaesthesia, and corneal ulcers', N''),
( N'Q809561', N'bartonellosis', N'primary bacterial infectious disease that is caused by the bacteria of the genus Bartonella', N''),
( N'Q809758', N'basal-cell carcinoma', N'A subtype of basal-cell carcinoma most commonly occurring on the sun-exposed areas of the head and neck', N''),
( N'Q812671', N'bacillary angiomatosis', N'human disease', N''),
( N'Q814547', N'Behr syndrome', N'', N''),
( N'Q815296', N'stress-related disorders', N'', N''),
( N'Q815753', N'filariasis', N'parasitic disease caused by a family of nematode worms', N''),
( N'Q815819', N'atrial fibrillation', N'abnormal heart rhythm characterized by rapid and irregular beating', N'')
GO