INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q386408', N'African horse sickness', N'insect-borne reovirus infection of horses, mules and donkeys in Africa and the Middle East; characterized by pulmonary edema, cardiac involvement, and edema of the head and neck', N''),
( N'Q387082', N'ataxia telangiectasia', N'A rare, neurodegenerative, autosomal recessive human disease causing severe disability', N''),
( N'Q3877344', N'Pendular nystagmus', N'A sinusoidal oscillation, which refers to the waveform of involuntary eye movements that may occur in any direction.', N''),
( N'Q388113', N'placental abruption', N'placenta disease that is characterized by separation of the placental lining from the uterus of the mother', N''),
( N'Q3882418', N'renal oncocytoma', N'tumour of the kidney made up of oncocytes, a special kind of cell', N''),
( N'Q388388', N'intestinal volvulus', N'Human disease', N''),
( N'Q3886247', N'urticaria pigmentosa', N'most common form of cutaneous mastocytosis', N''),
( N'Q388626', N'sleepwalking', N'phenomenon of combined sleep and wakefulness', N''),
( N'Q388628', N'Meckels diverticulum', N'congenital disorder of digestive system', N''),
( N'Q388646', N'dracunculiasis', N'Human helminthiasis', N''),
( N'Q388722', N'childhood disintegrative disease', N'neurodevelopmental condition', N''),
( N'Q3895159', N'Zenkers paralysis', N'', N''),
( N'Q3896379', N'paronychia', N'bacterial or fungal nail infection of the hand or foot', N''),
( N'Q389735', N'cardiovascular disease', N'class of diseases that involve the heart or blood vessels', N''),
( N'Q3899001', N'pemphigus vulgaris', N'chronic blistering skin disease', N''),
( N'Q3899003', N'Paraneoplastic pemphigus', N'Pemphigus is a group of chronic autoimmune skin diseases characterised by blisters formation on the outer layer of the skin and the mucous membranes. Three clinical forms have been characterised, of which paraneoplastic pemphigus is extremely rare.', N''),
( N'Q390211', N'atrioventricular septal defect', N'Human disease', N''),
( N'Q390217', N'Agalactia', N'Human disease', N''),
( N'Q3902759', N'white piedra', N'mycosis that is a superficial fungal infection of the hair shaft caused by Trichosporon beigelii', N''),
( N'Q390475', N'bilirubin metabolic disorder', N'inherited metabolic disorder that involves elevated levels of bilirubin resulting from disruption of bilirubin metabolism', N''),
( N'Q3907636', N'lymphocytic interstitial pneumonia', N'', N''),
( N'Q3907637', N'nonspecific interstitial pneumonia', N'Human disease', N''),
( N'Q390791', N'hepatoerythropoietic porphyria', N'Human disease', N''),
( N'Q3908490', N'hepatic porphyria', N'form of porphyria in which the enzyme deficiency occurs in the liver', N''),
( N'Q3908491', N'Erythropoietic porphyria', N'type of porphyria associated with erythropoietic cells. In erythropoietic porphyrias, the enzyme deficiency occurs in the red blood cells', N''),
( N'Q390908', N'Lucey–Driscoll syndrome', N'autosomal recessive metabolic disorder affecting enzymes involved in bilirubin metabolism', N''),
( N'Q3913024', N'lymphangiosarcoma', N'lymphatic system cancer that has material basis in endothelial cells located in lymphatic vessels', N''),
( N'Q3924862', N'intestinal pseudo-obstruction', N'Human disease', N''),
( N'Q3928626', N'radial scar', N'disease', N''),
( N'Q3931183', N'DRESS syndrome', N'drug eruption characterized by high fever, erythematous rash and inflammation of internal organs', N''),
( N'Q393477', N'trench fever', N'Human disease', N''),
( N'Q3956352', N'perforated ulcer', N'medical condition of the gastrointestinal tract wall', N''),
( N'Q395931', N'agraphia', N'disease that results in the loss of the ability to write', N''),
( N'Q396013', N'agranulocytosis', N'Human disease', N''),
( N'Q3961657', N'anismus', N'failure of the normal relaxation of pelvic floor muscles during attempted defecation', N''),
( N'Q3961676', N'Keppen–Lubinsky syndrome', N'human disease', N''),
( N'Q3961678', N'Laurence-Moon syndrome', N'rare autosomal recessive genetic disorder associated with retinitis pigmentosa, spastic paraplegia, and mental disabilities', N''),
( N'Q3961680', N'Levs disease', N'', N''),
( N'Q3961685', N'Rabson–Mendenhall syndrome', N'', N''),
( N'Q3961686', N'myoclonic cerebellar dyssynergia', N'degenerative, neurological disorder characterized by myoclonus epilepsy, intention tremor, progressive ataxia and occasionally cognitive impairment', N''),
( N'Q3961695', N'Weill-Marchesani syndrome', N'autosomal genetic disease characterized by short stature, bachycephaly and other facial abnormalities, brachydactyly, joint stiffness and distinctive ocular abnormalities', N''),
( N'Q39656409', N'Potocki-Luspski syndrome', N'A chromosomal duplication syndrome characterized by hypotonia, failure to thrive, mental retardation, pervasive developmental disorders and congenital anomalies that has material basis in duplication of a region of chromosome 17p11.2.', N''),
( N'Q3972207', N'Steatocystoma multiplex', N'disease', N''),
( N'Q3973118', N'Pulmonic stenosis', N'', N''),
( N'Q3973817', N'hereditary stomatocytosis', N'human disease', N''),
( N'Q3980374', N'pneumoconiosis due to talc', N'human disease', N''),
( N'Q3985306', N'spastic quadriplegia', N'type of spastic cerebral palsy characterized by increased muscle tone of all four extremities', N''),
( N'Q4000419', N'Clear-cell tumor', N'', N''),
( N'Q4000420', N'malignant Leydig cell tumor', N'sex cord-stromal tumour group of ovarian and testicular cancers', N''),
( N'Q4000421', N'Sertoli cell tumor', N'Human disease', N''),
( N'Q400277', N'fetal alcohol syndrome', N'severe form of fetal alcohol spectrum disorder', N''),
( N'Q4007235', N'atrophic vaginitis', N'inflammation of the vagina due to the thinning and shrinking of the tissues, as well as decreased lubrication', N''),
( N'Q40103033', N'Hemimegalencephaly', N'A rare disorder affecting development of one side of the brain', N''),
( N'Q401402', N'nephritis', N'inflammation of the kidneys', N''),
( N'Q402575', N'maple syrup urine disease', N'Human disease', N''),
( N'Q403453', N'Aicardi-Goutieres syndrome', N'a rare genetic neurodevelopmental disorder', N''),
( N'Q403463', N'Aicardi syndrome', N'syndrome that is characterized by absence or underdeveloped tissue connecting the left and right halves of the brain, infantile spasms and chorioretinal lacunae, which are defects in the light-sensitive tissue at the back of the eye', N''),
( N'Q4052543', N'dysequilibrium syndrome', N'Dysequilibrium syndrome (DES) is a non-progressive cerebellar disorder characterized by ataxia associated with an intellectual disability, delayed ambulation and cerebellar hypoplasia', N''),
( N'Q4053279', N'X-linked endothelial corneal dystrophy', N'Human disease', N''),
( N'Q4057453', N'adrenal crisis', N'medical emergency', N''),
( N'Q4057495', N'parathyroid adenoma', N'Human disease', N''),
( N'Q4057496', N'adrenal adenoma', N'endocrine organ benign neoplasm, a benign tumor of the glandular type (adenoma) in the adrenal gland', N''),
( N'Q4059313', N'acanthocheilonemiasis', N'human disease', N''),
( N'Q4062508', N'alcoholic neuropathy', N'Human disease', N''),
( N'Q4063436', N'alveolar soft part sarcoma', N'soft tissue cancer that is a slow growing tumor of an unknown origin that effects children and effects young adults', N''),
( N'Q4064296', N'Hereditary gelsolin amyloidosis', N'Human disease', N''),
( N'Q40649915', N'choristoma', N'form of heterotopia closely related benign tumors, found in abnormal locations.', N''),
( N'Q4072263', N'skin atrophy', N'Human disease', N''),
( N'Q408089', N'mercury poisoning', N'poisoning caused by mercury chemicals', N''),
( N'Q4082071', N'Protein-energy malnutrition', N'malnutrition defined as a range of pathological conditions arising from lack of dietary protein and energy', N''),
( N'Q4086828', N'binasal hemianopsia', N'', N''),
( N'Q4086956', N'bipolar ll disorder', N'bipolar disorder that is characterized by at least one hypomanic episode and at least one major depressive episode; with this disorder, depressive episodes are more frequent and more intense than manic episodes', N''),
( N'Q409030', N'hemoglobin C', N'Human disease', N''),
( N'Q4090775', N'Kummells disease', N'Human disease', N''),
( N'Q4116448', N'tracheal stenosis', N'respiratory disease', N''),
( N'Q4116663', N'musculoskeletal disorder', N'disease of anatomical entity that occurs in the muscular and/or skeletal system', N''),
( N'Q4117969', N'Immune-mediated disease', N'', N''),
( N'Q4118092', N'macroglobulinemia', N'Human disease', N''),
( N'Q4118166', N'polyostotic fibrous dysplasia', N'autosomal dominant disease that involves skin pigmentation, bone and hormonal problems along with premature puberty', N''),
( N'Q4118581', N'necatoriasis', N'Human disease', N''),
( N'Q4127183', N'congenital adrenal hyperplasia due to 11β-hydroxylase deficiency', N'', N''),
( N'Q4127184', N'congenital adrenal hyperplasia due to 17 alpha-hydroxylase deficiency', N'', N''),
( N'Q4127185', N'congenital adrenal hyperplasia due to 21-hydroxylase deficiency', N'', N''),
( N'Q4127186', N'congenital adrenal hyperplasia due to 3 beta-hydroxysteroid dehydrogenase deficiency', N'', N''),
( N'Q4127187', N'congenital stromal corneal dystrophy', N'Human disease', N''),
( N'Q4127191', N'congenital hereditary endothelial dystrophy of cornea', N'Human disease', N''),
( N'Q4134457', N'substance-related disorder', N'group of mental and behavioural disorders, including both substance dependence and substance abuse', N''),
( N'Q4138746', N'hypertensive encephalopathy', N'general brain dysfunction due to significantly high blood pressure', N''),
( N'Q4138762', N'vitamin D deficiency', N'Human disease', N''),
( N'Q4138764', N'Ariboflavinosis', N'Human disease', N''),
( N'Q4138767', N'vitamin K deficiency', N'human disease', N''),
( N'Q4138775', N'hypodermyasis', N'human disease', N''),
( N'Q4138959', N'leech infestation', N'human disease', N''),
( N'Q4139987', N'glomus tumor', N'hemangiopericytic tumor that is a mesenchymal neoplasm composed of cells that closely resemble the modified smooth muscle cells of the normal glomus body', N''),
( N'Q41411120', N'Non-progressive congenital ataxia', N'form of cerebellar ataxia which can occur with or without cerebellar hypoplasia.', N''),
( N'Q415833', N'acanthosis nigricans', N'Human disease', N''),
( N'Q4158999', N'blister beetle dermatitis', N'cutaneous condition', N''),
( N'Q4162388', N'epithelial basement membrane dystrophy', N'Human disease', N''),
( N'Q4162389', N'Thiel-Behnke corneal dystrophy', N'Human disease', N''),
( N'Q4162390', N'Reis-Bücklers corneal dystrophy', N'disease of the human eye', N''),
( N'Q4162391', N'Lisch epithelial corneal dystrophy', N'Human disease', N''),
( N'Q4162392', N'Meesmann corneal dystrophy', N'type of corneal dystrophy and a keratin disease', N''),
( N'Q4162393', N'Schnyder corneal dystrophy', N'Human disease', N''),
( N'Q4165484', N'lymphoproliferative disorders', N'primary immunodeficiency disease characterized by immune dysregulation typically after viral infection, usually associated with Epstein-Barr viral infection', N''),
( N'Q4170873', N'biliary reflux', N'Human disease', N''),
( N'Q4178686', N'gelatinous drop-like corneal dystrophy', N'Human disease', N''),
( N'Q4183962', N'posterior amorphous corneal dystrophy', N'Human disease', N''),
( N'Q4183965', N'posterior polymorphous corneal dystrophy', N'Human disease', N''),
( N'Q418418', N'ankylosis', N'Human disease', N''),
( N'Q418522', N'akinetic mutism', N'brain disease characterized by marked reduction of nearly all motor functions including facial expressions, gestures and speech output, but with some degree of alertness', N''),
( N'Q4198677', N'complications of diabetes mellitus', N'', N''),
( N'Q419897', N'Porphyria due to ALAD deficiency', N'porphyria that has symptom abdominal pain, has symptom neuropathy, has symptom autonomic instability and has symptom psychosis', N''),
( N'Q4199106', N'tick infestation', N'disease', N''),
( N'Q420804', N'acrodermatitis chronica atrophicans', N'An acrodermatitis characterized by a chronically progressive course, leading to widespread atrophy of the skin. It is a clinical manifestation of Lyme borreliosis.', N''),
( N'Q4216194', N'arterial tortuosity syndrome', N'connective tissue disease that is characterized by elongation and generalized tortuosity of the major arteries including the aorta', N''),
( N'Q4219511', N'Keratin disease', N'', N''),
( N'Q422225', N'actinic keratosis', N'Human disease', N''),
( N'Q4222298', N'corpus luteum cyst', N'human disease', N''),
( N'Q4223446', N'Hurthle cell', N'Thyroid follicles lined by deeply eosinophilic Hürthle cells are seen in Hashimoto disease', N''),
( N'Q4223496', N'tick paralysis', N'tick-borne disease that is not caused by an infectious organism', N''),
( N'Q42326498', N'XK aprosencephaly', N'congenital disorder', N''),
( N'Q42365072', N'Microlissencephaly', N'Microcephaly combined with lissencephaly', N''),
( N'Q4237691', N'Fleck corneal dystrophy', N'Human disease', N''),
( N'Q423927', N'Hypervitaminosis', N'a condition of abnormally high storage of vitamin levels, such as fat soluble vitamins', N''),
( N'Q423965', N'Vestibular schwannoma', N'Human disease', N''),
( N'Q42417296', N'infection associated with diseases', N'', N''),
( N'Q42417401', N'Congenital hypofibrinogenemia', N'Familial hypofibrinogenemia is a coagulation disorder characterized by mild bleeding symptoms following trauma or surgery due to a reduced plasma fibrinogen concentration', N''),
( N'Q424221', N'acute stress disorder', N'human disease', N''),
( N'Q424227', N'bronchiolitis', N'human disease', N''),
( N'Q424233', N'suppurative thyroiditis', N'Human disease', N''),
( N'Q424242', N'acute disseminated encephalomyelitis', N'An encephalomyelitis characterized by inflammation located in brain and located in spinal cord that damages myelin. It usually occurs after viral infection, but also following vaccination, bacterial or parasitic infection.', N''),
( N'Q424247', N'acute intermittent porphyria', N'human disease', N''),
( N'Q424258', N'acute interstitial pneumonitis', N'human disease', N''),
( N'Q424317', N'acute abdomen', N'medical term for sudden, severe abdominal pain of unclear origin', N''),
( N'Q424337', N'acute kidney injury', N'abrupt loss of kidney function that develops within 48 hours', N''),
( N'Q425811', N'hypertensive retinopathy', N'Human disease', N''),
( N'Q42593774', N'Aldred syndrome', N'', N''),
( N'Q4261984', N'barbiturate dependence', N'drug dependence that involves the continued use of barbiturates despite problems related to use of the substance', N''),
( N'Q4262866', N'lipoid congenital adrenal hyperplasia', N'', N''),
( N'Q427118', N'radial neuropathy', N'Human disease', N''),
( N'Q4271835', N'Cytomegalovirus retinitis', N'retinitis that has material basis in Cytomegalovirus', N''),
( N'Q427810', N'dysthymic disorder', N'mood disorder that involves the presence of a low mood almost daily over a span of at least two years', N''),
( N'Q4280605', N'mansonelliasis', N'A parasitic infection by nematodes transmitted by insects', N''),
( N'Q428447', N'cystoisosporiasis', N'coccidiosis that involves infection of the epithelial cells of the small intestine with Cystoisospora belli, which results in nonbloody diarrhea with crampy abdominal pain, malabsorption and weight loss', N''),
( N'Q4286595', N'megalocornea', N'corneal disease characterized by a bilaterally enlarged corneal diameter without an increase in intraocular pressure', N''),
( N'Q4289690', N'Ked itch', N'', N''),
( N'Q4293116', N'microvillus inclusion disease', N'Human disease', N''),
( N'Q4305015', N'buphthalmos', N'Human disease', N''),
( N'Q431643', N'microcephaly', N'medical condition in which the brain does not develop properly resulting in a smaller than normal head', N''),
( N'Q4316437', N'infection of the central nervous system', N'disease', N''),
( N'Q432396', N'achromatopsia', N'human illness, a type of color blindness', N''),
( N'Q432462', N'Takayasus arteritis', N'syndrome that involves inflammation of the aorta that carries blood from the heart to the rest of the body', N''),
( N'Q432814', N'Alström syndrome', N'rare genetic disorder caused by mutations in the gene ALMS1', N''),
( N'Q4330029', N'airway obstruction', N'blockage in the respiratory system', N''),
( N'Q4333327', N'oculogyric crisis', N'focal dystonia that is characterized by a prolonged involuntary upward deviation of the eyes', N''),
( N'Q4335557', N'central nervous system neoplasm', N'A neoplasm listed in Medical Subject Headings (MeSH)', N''),
( N'Q4338645', N'tracheobronchopathia osteochondroplastica', N'', N''),
( N'Q4338646', N'osteochondropathy', N'', N''),
( N'Q4340209', N'mental depression', N'state of low mood and aversion to activity, which can affect a persons thoughts, behavior, motivation, feelings, and sense of well-being', N''),
( N'Q4344969', N'perinephritis', N'human disease', N''),
( N'Q4345763', N'periodontosis', N'Human disease', N''),
( N'Q4347774', N'autoimmune polyendocrine syndrome type 1', N'autoimmune polyendocrine syndrome that is inherited in an autosomal recessive fashion, which is characterized by abnormal functioning of the immune system that causes auto-reactivity against endocrine organs', N''),
( N'Q4348144', N'Weaver syndrome', N'Human disease', N''),
( N'Q4351777', N'Hereditary persistence of fetal hemoglobin', N'', N''),
( N'Q4352832', N'urofacial syndrome', N'autosomal recessive disease that is characterized by inverted facial expressions in association with a severe and early-onset form of dysfunctional urinary voiding', N''),
( N'Q4352925', N'mal de Meleda', N'human disease', N''),
( N'Q4353825', N'Carnosinemia', N'disease', N''),
( N'Q4354267', N'Senior-Loken syndrome', N'autosomal recessive genetic disease characterized by progressive wasting of the filtering unit of the kidney (nephronophthisis), with or without medullary cystic renal disease, and progressive eye disease', N''),
( N'Q4354940', N'Jansky–Bielschowsky disease', N'autosomal recessive genetic disorder', N''),
( N'Q4357083', N'Galloway-Mowat syndrome', N'autosomal recessive disease characterized by is a rare autosomal recessive disease, characterized by microcephaly with brain anomalies including CA in some cases, intellectual disability, and early-infantile-onset nephrotic syndrome', N''),
( N'Q4357091', N'PEHO syndrome', N'PEHO (Progressive encephalopathy with Edema, Hypsarrhythmia and Optic atrophy) syndrome is a rare neurodegenerative disorder belonging to the group of infantile progressive encephalopathies', N''),
( N'Q4357119', N'animal allergy', N'', N''),
( N'Q4357287', N'acrodysostosis', N'dysostosis that results in shortening of interphalangeal joints located in hand or located in foot along with mental deficiency', N''),
( N'Q4358039', N'neuronal ceroid lipofuscinosis', N'Human disease', N''),
( N'Q4358147', N'rumination disorder', N'eating disorder that is characterized by effortless regurgitation of most meals following consumption', N''),
( N'Q4364722', N'Pediculus humanus corporis infestation', N'A lice infestation that is a cutaneous condition caused by parasitic infestation of body lice Pediculus humanus corporis, which feed on the human blood. Body lice can spread epidemic typhus, trench fever, and louse-borne relapsing fever.', N''),
( N'Q4365211', N'Cornea plana 2', N'', N''),
( N'Q4368172', N'Subacute lymphocytic thyroiditis', N'Human disease', N''),
( N'Q4368173', N'subacute thyroiditis', N'Human disease', N''),
( N'Q4373155', N'porocephaliasis', N'', N''),
( N'Q4385926', N'macular corneal dystrophy', N'corneal dystrophy that is characterized by corneal haze, severe photophobia at night ,gradual vision impairment ,bilateral loss of vision, eventually necessitating corneal transplantation resulting from progressive punctate opacities in the cornea', N''),
( N'Q4394144', N'lattice corneal dystrophy', N'Human disease', N''),
( N'Q441077', N'Blau syndrome', N'An autosomal dominant disease characterized by familial granulomatous arthritis, uveitis and skin granulomas. It has material basis in mutations in the NOD2/CARD15 genes.', N''),
( N'Q441094', N'Milk-alkali syndrome', N'Disease caused by very high levels of calcium and alkali', N''),
( N'Q4411659', N'Fibroma of tendon sheath', N'', N''),
( N'Q4412533', N'aspartylglucosaminuria', N'disease that is characterized by a decline in mental functioning, accompanied by an increase in skin, bone and joint issues', N''),
( N'Q4413030', N'wheat allergy', N'allergy involving a FOODON:00001141', N''),
( N'Q4420121', N'Dent disease', N'congenital disorder of urinary system', N''),
( N'Q4420129', N'Mauriac syndrome', N'', N''),
( N'Q4420133', N'ROHHAD', N'', N''),
( N'Q4420146', N'short rib – polydactyly syndrome', N'Human disease', N''),
( N'Q4420149', N'withdrawal symptom', N'substance-related disorder that occurs upon the abrupt discontinuation/separation or a decrease in dosage of the intake of medications, recreational drugs, and alcohol', N''),
( N'Q4421929', N'Hippocampal sclerosis', N'neuropathological condition with severe neuronal cell loss and gliosis in the hippocampus', N''),
( N'Q4422074', N'vermiphobia', N'fear of worms', N''),
( N'Q4438017', N'Hammans syndrome', N'', N''),
( N'Q4438477', N'Median nail dystrophy', N'', N''),
( N'Q443929', N'dirofilariasis', N'Human disease', N''),
( N'Q4445097', N'subepithelial mucinous corneal dystrophy', N'Human disease', N''),
( N'Q4458080', N'thyroid crisis', N'endocrine disease', N''),
( N'Q4463723', N'cavernous sinus thrombosis', N'Human disease', N''),
( N'Q447828', N'aluminosis', N'lung disease', N''),
( N'Q448310', N'seborrhoeic dermatitis', N'long-term skin disorder', N''),
( N'Q448698', N'pulmonary alveolar proteinosis', N'lung disease that is characterized by abnormal accumulation of surfactant occurs within the alveoli, interfering with gas exchange', N''),
( N'Q448747', N'alveolitis', N'lung disease', N''),
( N'Q448753', N'alveolar osteitis', N'human disease', N''),
( N'Q448768', N'alveolar echinococcosis', N'echinococcosis that is caused by the larvae of Echinococcus multilocularis affecting the liver as a slow growing, destructive tumor, with abdominal pain, biliary obstruction, and occasionally metastatic lesions into the lungs and brain', N''),
( N'Q4497100', N'Wheat warehouse itch', N'', N''),
( N'Q4503868', N'cementoma', N'odontogenic tumor of cementum', N''),
( N'Q450470', N'collagenous colitis', N'colitis characterized by a distinctive thickening of the subepithelial collagen table', N''),
( N'Q4532132', N'Hashimotos encephalopathy', N'human disease', N''),
( N'Q455085', N'granuloma annulare', N'Human disease', N''),
( N'Q4552290', N'17-beta-hydroxysteroid dehydrogenase deficiency', N'human disease', N''),
( N'Q4553565', N'Koolen de Vries syndrome', N'Human disease', N''),
( N'Q4557543', N'chromosome 18p deletion syndrome', N'human disease', N''),
( N'Q457737', N'Edwards syndrome‎', N'Human disease', N''),
( N'Q458099', N'triosephosphate isomerase deficiency', N'Genetic metabolic disorder', N''),
( N'Q458138', N'monoclonal gammopathy of uncertain significance', N'Human disease', N''),
( N'Q4596888', N'2-hydroxyglutaric aciduria', N'amino acid metabolic disorder that is an autosomal recessive neurometabolic disorder characterized by the significant elevation of urinary levels of hydroxyglutaric acid causing progressive brain damage', N''),
( N'Q4596905', N'2-methylbutyryl-CoA dehydrogenase deficiency', N'gene (located on chromosome 10q25-26) have been reported in affected patients. Treatment includes carnitine supplementation and a low-protein diet.', N''),
( N'Q4597494', N'intestinal atresia', N'congenital disorder of digestive system', N''),
( N'Q459896', N'cystic lymphangioma', N'human disease', N''),
( N'Q460167', N'Menieres disease', N'disorder of the inner ear', N''),
( N'Q460556', N'ganglioglioma', N'cell type benign neoplasm that has material basis in glial-type cells', N''),
( N'Q460591', N'decompression sickness', N'condition arising on depressurisation of the body', N''),
( N'Q460937', N'hemangioblastoma', N'tumor of the central nervous system that originates from the vascular system', N''),
( N'Q461854', N'amelogenesis imperfecta', N'dental enamel hypoplasia characterized by abnormal enamel formation', N''),
( N'Q461857', N'ameloblastoma', N'cell type benign neoplasm that has material basis in odontogenic epithelium', N''),
( N'Q4631454', N'chromosome 22q11.2 microduplication syndrome', N'Human disease', N''),
( N'Q4634172', N'3-methylcrotonyl-CoA carboxylase deficiency', N'Human disease', N''),
( N'Q4634217', N'3-hydroxy-3-methylglutaryl-CoA lyase deficiency', N'', N''),
( N'Q4636618', N'chromosome 3q29 microdeletion syndrome', N'Human disease', N''),
( N'Q4638720', N'49,XXXXY', N'The 49,XXXXY syndrome represents a chromosomal anomaly of the aneuploidic type characterized by the presence of three extra X chromosomes in males', N''),
( N'Q464067', N'fungal infectious disease', N'fungal infection of animals, including humans', N''),
( N'Q4641554', N'BH4-deficient hyperphenylalaninemia A', N'human disease', N''),
( N'Q4641571', N'6-phosphogluconate dehydrogenase deficiency', N'', N''),
( N'Q4646476', N'Kleefstra syndrome', N'Human disease', N''),
( N'Q465016', N'health effects of tobacco', N'circumstances, mechanisms, and factors of tobacco consumption on human health', N''),
( N'Q4650574', N'ACDC', N'arterial calcification due to deficiency of CD73, rare genetic disorder that causes calcium buildup in the arteries and joints of the hands and feet, and other areas below the waist', N''),
( N'Q4651855', N'AIDS-related complex', N'Human disease', N''),
( N'Q4651856', N'AIDS-related lymphoma', N'', N''),
( N'Q4652470', N'AL amyloidosis', N'', N''),
( N'Q4664694', N'hereditary spastic paraplegia 23', N'hereditary spastic paraplegia that has material basis in variation in the chromosome region 1q24-q32', N''),
( N'Q4664900', N'Abderhalden–Kaufmann–Lignac syndrome', N'rare autosomal-recessive, lysomal storage childhood disorder involving deposits of cystine crystals in various parts of the body, including the bone marrow, conjunctiva and cornea', N''),
( N'Q4665123', N'abdominal compartment syndrome', N'', N''),
( N'Q4665124', N'Abdominal musculature absent with microphthalmia and joint laxity', N'', N''),
( N'Q4667072', N'fibroma', N'Human disease', N''),
( N'Q4667534', N'leiomyoma', N'cell type benign neoplasm that is a benign tumor of smooth muscle cells', N''),
( N'Q4669630', N'Abruzzo–Erickson syndrome', N'', N''),
( N'Q4669671', N'Abscesses of the periodontium', N'', N''),
( N'Q4669696', N'Absence of gluteal muscle', N'human disease', N''),
( N'Q467056', N'hirsuties coronae glandis', N'small protuberance that may form on the ridge of the glans of the human penis', N''),
( N'Q4672538', N'accessory nerve disease', N'human disease', N''),
( N'Q4673499', N'Achard syndrome', N'syndrome that involves arachnodactyly, receding lower jaw, and joint laxity limited to the hands and feet', N''),
( N'Q4673593', N'acheiropody', N'Human disease', N''),
( N'Q4674074', N'Acid lipase disease', N'', N''),
( N'Q4674158', N'Acinar cell carcinoma of the pancreas', N'', N''),
( N'Q4674171', N'Acinic cell carcinoma of the lung', N'', N''),
( N'Q4674172', N'acinar cell carcinoma', N'carcinoma that has material basis in abnormally proliferating cells, derives from spindle cells and/or derives from giant cells', N''),
( N'Q4674254', N'Ackerman syndrome', N'', N''),
( N'Q4674430', N'Acne miliaris necrotica', N'skin condition', N''),
( N'Q4674433', N'Acne with facial edema', N'', N''),
( N'Q4674772', N'Acquired generalized lipodystrophy', N'complete generalized lipodystrophy that is charcterized by generalized disappearance of fat occurring during childhood and adolescence where normal  body fat is present at birth', N''),
( N'Q4675038', N'acral lentiginous melanoma', N'kind of lentiginous skin melanoma', N''),
( N'Q4675304', N'acrocallosal syndrome', N'syndrome that is an autosomal recessive disorder, which is characterized by corpus callosum agenesis, polydactyly, multiple dysmorphic features, motor and mental retardation', N''),
( N'Q4675757', N'acrodermatitis', N'dermatitis that selectively affects the hands and feet', N''),
( N'Q4675773', N'acrofrontofacionasal dysostosis', N'dysostosis characterized by intellectual disability, short stature, hypertelorism, broad notched nasal tip, cleft lip palate, postaxial camptobrachypolysyndactyly, fibular hypoplasia and anomalies of foot structure', N''),
( N'Q4675781', N'punctate palmoplantar keratoderma type III', N'Human disease', N''),
( N'Q4675784', N'acrokeratosis verruciformis', N'Human disease', N''),
( N'Q4676182', N'Acromicric dysplasia', N'Acromicric dysplasia is a rare bone dysplasia characterized by short stature, short hands and feet, mild facial dysmorphism, and characteristic X-ray abnormalities of the hands', N''),
( N'Q467635', N'multiple myeloma', N'A myeloid neoplasm that is located in the plasma cells in bone marrow.', N''),
( N'Q4676432', N'acropustulosis', N'Human disease', N''),
( N'Q4676885', N'actinic prurigo', N'rare sunlight-induced, pruritic, papular or nodular skin eruption', N''),
( N'Q4677911', N'Acute basophilic leukemia', N'rare acute myeloid leukemia in which the immature cells differentiate towards basophils', N''),
( N'Q4677914', N'Acute cerebellar ataxia of childhood', N'', N''),
( N'Q4677915', N'acute chest syndrome', N'human disease', N''),
( N'Q4677917', N'Acute biphenotypic leukaemia', N'uncommon type of leukemia which arises in multipotent progenitor cells which have the ability differentiating into both myeloid and lymphoid lineages', N''),
( N'Q4677921', N'Acute eosinophilic leukemia', N'', N''),
( N'Q4677929', N'acute fatty liver of pregnancy', N'', N''),
( N'Q4677933', N'Acute megakaryoblastic leukemia', N'leukemia that derives from blood-forming tissue in which megakaryocytes proliferate in the bone marrow and circulate in the blood in large numbers', N''),
( N'Q4677934', N'acute motor axonal neuropathy', N'pure motor axonal form of Guillain-Barré syndrome', N''),
( N'Q4677938', N'acute monocytic leukemia', N'Human disease', N''),
( N'Q4677939', N'Acute myeloid dendritic cell leukemia', N'', N''),
( N'Q4677943', N'acute myelomonocytic leukemia', N'An acute leukemia characterized by the proliferation of both neutrophil and monocyte precursors.  (WHO, 2001)', N''),
( N'Q4677951', N'acute retinal necrosis syndrome', N'Human disease', N''),
( N'Q4677952', N'acute urate nephropathy', N'Human disease', N''),
( N'Q4678337', N'lymph node tuberculosis', N'Extrapulmonary tuberculosis that is located in lymph node', N''),
( N'Q4681410', N'Adducted thumb syndrome', N'rare genetic disease affecting palate, thumbs, and upper limbs', N''),
( N'Q4682223', N'Adenine phosphoribosyltransferase deficiency', N'An amino acid metabolic disorder characterized by the formation 2,8-dihydroxyadenine stones and renal failure secondary to intratubular crystalline precipitation. It has an autosomal recessive inheritance pattern.', N''),
( N'Q4682248', N'Adenomyoepithelioma of the breast', N'', N''),
( N'Q4682249', N'adenomyoma', N'carcinosarcoma that has material basis in gland and muscle components', N''),
( N'Q4682317', N'adenylosuccinase lyase deficiency', N'a rare autosomal recessive metabolic disorder', N''),
( N'Q4684717', N'adrenal gland disease', N'endocrine disease', N''),
( N'Q4684749', N'adrenocortical adenoma', N'adrenal adenoma that is a benign tumor of the adrenal cortex', N''),
( N'Q4684750', N'adrenal gland hyperfunction', N'Human disease', N''),
( N'Q4685917', N'Adult blaschkitis', N'', N''),
( N'Q4686719', N'Adverse reaction to biologic agents', N'', N''),
( N'Q4690011', N'African histoplasmosis', N'Human disease', N''),
( N'Q4690019', N'African iron overload', N'hemochromatosis characterized by a predisposition to iron loading that is exacerbated by excessive intake of dietary iron, commonly related to consumption of tradition beer brewed in non-galvanized steel drums', N''),
( N'Q4690047', N'African tick-bite fever', N'spotted fever that has material basis in Rickettsia africae, which is transmitted by ticks', N''),
( N'Q4692280', N'natural killer cell leukemia', N'Human disease', N''),
( N'Q4692285', N'Aggressive periodontitis', N'periodontitis that is characterized by rapid attachment loss and bone destruction in the presence of little local factors such as dental plaque and dental calculus resulting in inflammation and a loss of periodontium', N''),
( N'Q4692572', N'aging-associated diseases', N'Diseases Developed By Aging', N''),
( N'Q469490', N'periventricular leukomalacia', N'human disease', N''),
( N'Q470427', N'refractive error', N'cause of vision problems', N''),
( N'Q470701', N'ecthyma', N'Human disease', N''),
( N'Q4710773', N'Loeffler endocarditis', N'restrictive cardiomyopathy that affects the endocardium and occurs with white blood cell proliferation, specifically of eosinophils', N''),
( N'Q4712419', N'albinism–deafness syndrome', N'', N''),
( N'Q4712685', N'Albrights hereditary osteodystrophy', N'osteochondrodysplasia that has material basis in lack of responsiveness to parathyroid hormone which results in shortening and widening of long bones of the located in hand or located in foot along with short stature, obesity, and rounded face', N''),
( N'Q4713263', N'alcohol dependence', N'human disease', N''),
( N'Q4713937', N'Aldolase A deficiency', N'', N''),
( N'Q471521', N'allergic conjunctivitis', N'chronic conjunctivitis that is an inflammation of the conjunctiva', N''),
( N'Q47166292', N'Amaurotic nystagmus', N'The nystagmus associated with blindness or the central vision defects.', N''),
( N'Q471778', N'Amino acid transport disorder', N'Human disease', N''),
( N'Q472052', N'dyskinesia of esophagus', N'human disease', N''),
( N'Q4721578', N'Alezzandrini syndrome', N'', N''),
( N'Q4723931', N'algaemia', N'condition where green algae is found in the blood', N''),
( N'Q4731121', N'Allan-Herndon-Dudley syndrome', N'congenital disorder of nervous system', N''),
( N'Q473262', N'complete androgen insensitivity syndrome', N'intersex condition that results in a phenotypic female', N''),
( N'Q4734609', N'follicular mucinosis', N'Human disease', N''),
( N'Q4734616', N'alopecia universalis', N'human disease', N''),
( N'Q4735280', N'alphavirus infections', N'Human disease', N''),
( N'Q4736375', N'Alternariosis', N'human disease', N''),
( N'Q473739', N'chorioamnionitis', N'placenta disease that is an inflammation of the fetal membranes (amnion and chorion) due to a bacterial infection', N''),
( N'Q4737942', N'Alveolar capillary dysplasia', N'rare lung disease, present at birth and treatable by lung transplants', N''),
( N'Q4737958', N'alveolar rhabdomyosarcoma', N'Human disease', N''),
( N'Q474070', N'Oropouche fever', N'Human disease', N''),
( N'Q4740761', N'Amazia', N'absence of the mammary gland', N''),
( N'Q4742183', N'amelanotic melanoma', N'Human disease', N''),
( N'Q474237', N'chromosome 18q deletion syndrome', N'human disease', N''),
( N'Q474254', N'Bannayan-Riley-Ruvalcaba syndrome', N'a rare overgrowth syndrome and hamartomatous disorder with occurrence of multiple subcutaneous lipomas, macrocephaly and hemangiomas.', N''),
( N'Q474261', N'ring chromosome', N'chromosome whose arms fused into a ring', N''),
( N'Q474994', N'Axenfeld-Rieger syndrome', N'autosomal dominant disease characterized by abnormalities of the front part of the eye, the anterior segment', N''),
( N'Q475086', N'aggressive fibromatosis', N'connective tissue benign neoplasm that occur most often in the abdomen, arms and legs', N''),
( N'Q4751018', N'Analbuminaemia', N'Congenital analbuminemia (CAA) is characterized by the absence or dramatic reduction of circulating human serum albumin (HSA)', N''),
( N'Q475260', N'Klatskins tumor', N'Human disease', N''),
( N'Q47535995', N'Alcoholic ketoacidosis', N'acute metabolic acidosis that typically occurs in people who chronically abuse alcohol and have a recent history of binge drinking, little or no food intake and persistent vomiting', N''),
( N'Q4761649', N'anemia of prematurity', N'Human disease', N''),
( N'Q4763254', N'extranodal NK/T-cell lymphoma, nasal type', N'', N''),
( N'Q4763257', N'Angioimmunoblastic T-cell lymphoma', N'peripheral T-cell lymphoma characterized by autoimmune features and poor prognosis', N''),
( N'Q4763260', N'Angiokeratoma of Mibelli', N'Human disease', N''),
( N'Q4763261', N'angioid streaks', N'Human disease', N''),
( N'Q4763273', N'angiolipoma', N'lipoma that is a painful subcutaneous nodule, having all other features of a typical lipoma', N''),
( N'Q4763278', N'skin epithelioid hemangioma', N'Human disease', N''),
( N'Q4763279', N'angioma serpiginosum', N'skin hemangioma characterized by the presence of small red dots that cluster together to form a linear or snake-like array or ring-shaped pattern located in the blood vessels of the skin', N''),
( N'Q4763280', N'Angiomatoid fibrous histiocytoma', N'type of tumor which affects children and adolescents', N''),
( N'Q476921', N'kidney failure', N'disease where the kidneys fail to adequately filter waste products from the blood grabbeb xhunfsobgt', N''),
( N'Q4769722', N'skin sarcoidosis', N'human disease', N''),
( N'Q4770152', N'Anopsia', N'', N''),
( N'Q4771330', N'anterior cerebral artery infarction', N'Human disease', N''),
( N'Q4771350', N'anterior horn cell disease', N'Human disease', N''),
( N'Q4771415', N'Anterior urethral cancer', N'Human disease', N''),
( N'Q4781026', N'appendix cancer', N'Cancer that is located in the appendix', N''),
( N'Q4783806', N'Arakawas syndrome II', N'', N''),
( N'Q478389', N'kyphosis', N'abnormal convex curvature of the spine', N''),
( N'Q478891', N'Simpson-Golabi-Behmel syndrome', N'X-linked disease characterized by pre- and postnatal overgrowth and craniofacial, skeletal, cardiac and renal abnormalities', N''),
( N'Q4795506', N'Aromatase deficiency', N'', N''),
( N'Q4795508', N'aromatase excess syndrome', N'human disease', N''),
( N'Q4797535', N'Arterial insufficiency ulcer', N'', N''),
( N'Q4797546', N'Arteriosclerosis obliterans', N'Human disease', N''),
( N'Q4797547', N'arteriolosclerosis', N'Human disease', N''),
( N'Q4797551', N'arteritic anterior ischemic optic neuropathy', N'Human disease', N''),
( N'Q4797639', N'arthritis mutilans', N'', N''),
( N'Q4797658', N'Arthrogryposis–renal dysfunction–cholestasis syndrome', N'Human disease', N''),
( N'Q4803677', N'asbestos-related disease', N'disorder of the lung and pleura caused by the inhalation of asbestos fibres', N''),
( N'Q4803881', N'Aschers syndrome', N'', N''),
( N'Q4804182', N'aseptic meningitis', N'meningitis caused by anything other than bacteria', N''),
( N'Q4807981', N'asphyxiating thoracic dysplasia', N'human disease', N''),
( N'Q4811532', N'astroblastoma', N'glial tumor derived from the astroblast, a type of cell that closely resembles spongioblastoma and astrocytes', N''),
( N'Q4812914', N'ataxic cerebral palsy', N'A cerebral palsy that is caused by damage to the cerebellum, which affects muscle coordination, particularly in the limb. Some individuals suffer from hypotonia, tremors, difficulty with visual and/or auditory processing.', N''),
( N'Q4813037', N'Ateliosis', N'historical terminology', N''),
( N'Q4813631', N'dyskinetic cerebral palsy', N'human disease', N''),
( N'Q481392', N'theileriasis', N'parasitic protozoa infectious disease that involves infection of humans and cattle caused by a genus of parasitic protozoa Theileria, which is transmitted by ixodid ticks', N''),
( N'Q4817543', N'Atrial enlargement', N'', N''),
( N'Q4817548', N'Atrichia with papular lesions', N'Human disease', N''),
( N'Q481787', N'amusia', N'agnosia that is a loss of the ability to recognize musical notes, rhythms, and intervals', N''),
( N'Q4818237', N'Attenuated familial adenomatous polyposis', N'Human disease', N''),
( N'Q4818238', N'Attenuated patella alta', N'', N''),
( N'Q4818889', N'Atypical ductal hyperplasia', N'increase of cell proliferation in the breast ducts', N''),
( N'Q4818893', N'Atypical polypoid adenomyoma', N'Human disease', N''),
( N'Q4818897', N'Atypical tuberous myxedema', N'', N''),
( N'Q4818922', N'fallopian tube cancer', N'female reproductive organ cancer that is located in fallopian tube', N''),
( N'Q4820034', N'Auditory neuropathy spectrum disorder', N'', N''),
( N'Q4820036', N'auditory neuropathy', N'hearing disorder characterized by impaired transmission of signals through the auditory nerve, resulting in mild to severe hearing loss and poor speech perception', N''),
( N'Q4821698', N'spondylocostal dysostosis', N'A dysostosis that results in abnormal development located in vertebrae or located in ribs. The bones of the spine do not develop properly, which causes them to be misshapen and abnormally joined together.', N''),
( N'Q4826340', N'autoimmune disease of cardiovascular system', N'hypersensitivity reaction type II disease that is the abnormal functioning of the immune system that causes your immune system to produce antibodies or T cells against cells and/or tissues in the cardiovascular system.', N''),
( N'Q4826344', N'Autoimmune inner ear disease', N'human disease', N''),
( N'Q4826986', N'Autosensitization dermatitis', N'Disease of the skin', N''),
( N'Q4826993', N'autosomal dominant hypophosphatemic rickets', N'rickets characterized by low levels of serum phosphate and elevated levels of ALP and phosphaturia and that has material basis in autosomal dominant inheritance', N''),
( N'Q4826996', N'autosomal recessive cerebellar ataxia', N'hereditary ataxia that has material basis in autosomal recessive inheritance', N''),
( N'Q4826997', N'Autosplenectomy', N'', N''),
( N'Q4827018', N'autotopagnosia', N'form of agnosia', N''),
( N'Q4828020', N'Avellis syndrome', N'', N''),
( N'Q4830452', N'axial osteomalacia', N'osteosclerosis that results in coarsening located in trabecular bone', N''),
( N'Q4830469', N'Axillary nerve dysfunction', N'', N''),
( N'Q4830470', N'axillary nerve palsy', N'', N''),
( N'Q4831022', N'Ayazi syndrome', N'', N''),
( N'Q4833719', N'B-cell lymphoma', N'non-Hodgkin lymphoma that has material basis in B cells', N''),
( N'Q4835645', N'BIDS syndrome', N'Human disease', N''),
( N'Q4841462', N'bagassosis', N'extrinsic allergic alveolitis that is an industrial disease characterized by cough, difficult breathing, chills, fever, and prolonged weakness caused by the inhalation of the dust of bagasse containing thermophilic actinomycetes', N''),
( N'Q4842581', N'Bahima disease', N'', N''),
( N'Q4845643', N'rhinosporidiosis', N'Human disease', N''),
( N'Q484631', N'imperforate anus', N'congenital disorder of digestive system', N''),
( N'Q484765', N'anal fistula', N'anus disease characterized by an abnormal connection between the epithelialised surface of the anal canal and the perianal skin', N''),
( N'Q484797', N'anal fissure', N'Break or tear in the skin of the anal canal', N''),
( N'Q484827', N'anus cancer', N'large intestine cancer that is located in the anus', N''),
( N'Q4850044', N'balanitis xerotica obliterans', N'Human disease', N''),
( N'Q4853488', N'Bamforth-Lazarus syndrome', N'Human disease', N''),
( N'Q4854239', N'band keratopathy', N'Human disease', N''),
( N'Q485831', N'lymphopenia', N'leukopenia that is the condition of having an abnormally low level of lymphocytes in the blood', N''),
( N'Q4860001', N'Barcoo fever', N'', N''),
( N'Q486090', N'anaplastic large-cell lymphoma', N'non-Hodgkin lymphoma involving aberrant T-cells', N''),
( N'Q486092', N'anaplastic astrocytoma', N'astrocytoma that is characterized by cells with regular, round to oval nuclei', N''),
( N'Q4862390', N'brain ischemia', N'Human disease', N''),
( N'Q486485', N'anasarca', N'medical condition characterized by widespread swelling', N''),
( N'Q4865135', N'Bart syndrome', N'human disease', N''),
( N'Q4865826', N'Bart-Pumphrey syndrome', N'Human disease', N''),
( N'Q4866181', N'basal ganglia disease', N'brain disease that is characterized by dysfunction of the basal ganglia which help start and control movement', N''),
( N'Q4866195', N'Basaloid large cell carcinoma of the lung', N'Human disease', N''),
( N'Q486680', N'transvestism', N'practice of dressing in a manner traditionally associated with the opposite sex', N''),
( N'Q4867062', N'basidiobolomycosis', N'Human disease', N''),
( N'Q4875174', N'Bazex–Dupré–Christol syndrome', N'Bazex-DuprC)-Christol syndrome is a rare genodermatosis with a predisposition to early-onset basal cell carcinomas', N''),
( N'Q4876717', N'Beare-Stevenson cutis gyrata syndrome', N'Human disease', N''),
( N'Q487837', N'coccidiosis', N'A parasitic protozoa infectious disease that occurs in the intestinal tract of animals and humans caused by Coccidia protozoa. Immunocompromised persons are at greater risk of developing the infection.', N''),
( N'Q48817400', N'vaginal melanoma', N'human disease', N''),
( N'Q488214', N'benign epilepsy with centrotemporal spikes', N'the most common epilepsy syndrome in childhood which usually subsides with age', N''),
( N'Q4887955', N'benign familial infantile epilepsy', N'infancy electroclinical syndrome that is characterized by convulsions, with onset at age 3 to 12 months', N''),
( N'Q4887956', N'benign familial neonatal epilepsy', N'Human disease', N''),
( N'Q4887962', N'benign essential hypertension', N'Human disease', N''),
( N'Q4887972', N'benign paroxysmal vertigo of childhood', N'disorder of children which presents with recurrent episodes of dizzyness', N''),
( N'Q4887975', N'multiple symmetric lipomatosis', N'A skin condition characterized by extensive symmetric fat deposits in the head, neck, and shoulder girdle area.', N''),
( N'Q4889456', N'Benjamin syndrome', N'hypochromic anemia with mental deficiency and various craniofacial and other anomalies.', N''),
( N'Q4891136', N'Berdon syndrome', N'syndrome that is characterized by marked dilatation of the bladder and microcolon and decreased intestinal peristalsis', N''),
( N'Q4892313', N'Berk–Tabatznik syndrome', N'human disease', N''),
( N'Q48969022', N'ZTTK syndrome', N'human disease', N''),
( N'Q48972084', N'Srbs anomaly', N'Congenital fusion between the first and second ribs', N''),
( N'Q4897218', N'beta-ketothiolase deficiency', N'Human disease', N''),
( N'Q48988765', N'spinal epidural hematoma', N'', N''),
( N'Q48989142', N'Kenny-Caffey syndrome', N'A genetic condition characterized by long bone sclerosis and thickening, short stature, and head and eye anomalies. Many affected individuals have hypoparathyroidism with hypocalcemia.', N''),
( N'Q48989325', N'Kosaki overgrowth syndrome', N'genetic disease', N''),
( N'Q489997', N'diabetic angiopathy', N'human disease', N''),
( N'Q4903638', N'bicipital tenosynovitis', N'Human disease', N''),
( N'Q4904691', N'Bietti crystalline corneoretinal dystrophy', N'Human disease', N''),
( N'Q4907578', N'Bilateral frontoparietal polymicrogyria', N'', N''),
( N'Q4907660', N'Bile acid malabsorption', N'human disease', N''),
( N'Q4913982', N'Binder syndrome', N'Human disease', N''),
( N'Q4915431', N'Biphasic disease', N'disease with two distinct phases', N''),
( N'Q4915474', N'bipolar I disorder', N'bipolar disorder that is characterized by at least one manic or mixed episode', N''),
( N'Q4916140', N'birdshot chorioretinopathy', N'human disease', N''),
( N'Q4919794', N'Bjornstad syndrome', N'Human disease', N''),
( N'Q492129', N'porencephaly', N'congenital disorder of nervous system characterized by cysts or cavities within the cerebral hemisphere.', N''),
( N'Q4925474', N'blastocystosis', N'medical condition caused by infection with Blastocystis', N''),
( N'Q4926151', N'blepharophyma', N'chronic swelling of eyelids', N''),
( N'Q4927306', N'Blocqs disease', N'', N''),
( N'Q4930176', N'blue toe syndrome', N'Human disease', N''),
( N'Q493103', N'paramyotonia congenita', N'human disease', N''),
( N'Q4938225', N'Bohring-Opitz', N'Bohring-Opitz Syndrome is an extremely rare genetic syndrome.This syndrome is diagnosed by genetic testing and is a mutation in the ASXL1 gene.', N''),
( N'Q493965', N'childhood amnesia', N'human disease', N''),
( N'Q494066', N'experimental autoimmune encephalomyelitis', N'', N''),
( N'Q4941552', N'bone disease', N'medical condition which affects the bone', N''),
( N'Q4943512', N'Boomerang dysplasia', N'Human disease', N''),
( N'Q4944687', N'borderline leprosy', N'leprosy that results in small numerous red irregularly shaped plaques', N''),
( N'Q494922', N'glycogen storage disease III', N'human disease', N''),
( N'Q495068', N'Todds paresis', N'', N''),
( N'Q495146', N'trichinosis', N'parasitic disease due to invasion by Trichinella spp.', N''),
( N'Q4955820', N'brain fever', N'medical condition', N''),
( N'Q4955921', N'Brainstem glioma', N'Human disease', N''),
( N'Q4956398', N'branch retinal artery occlusion', N'Human disease', N''),
( N'Q4956400', N'venous tributary occlusion of retina', N'human disease', N''),
( N'Q4958833', N'Brazilian hemorrhagic fever', N'Human disease', N''),
( N'Q4959796', N'breast disease', N'thoracic disease that is located in the breast', N''),
( N'Q496812', N'leukopenia', N'decrease in the number of white blood cells', N''),
( N'Q4973199', N'Brody myopathy', N'neuromuscular disease is characterized by difficulty relaxing muscles and muscle stiffness following exercise or other strenuous activity and is located in skeletal muscles', N''),
( N'Q4976388', N'Brown induration', N'', N''),
( N'Q4976847', N'Brown-Vialetto-Van Laere syndrome', N'Human disease', N''),
( N'Q4979092', N'Brunner Syndrome', N'amino acid metabolic disorder characterized by recessive X-linked inhetiance, impaired monoamine metabolism, impulsive aggressiveness and mild mental retardation that has material basis in mutation in the MAOA gene on chromosome location Xp11', N''),
( N'Q4979461', N'Bruns apraxia', N'gait apraxia found in patients with bilateral frontal lobe disorders', N''),
( N'Q498237', N'schizoid personality disorder', N'personality disorder causing emotional detachment and social isolation', N''),
( N'Q4982380', N'Buccal bifurcation cyst', N'', N''),
( N'Q498487', N'Camurati-Engelmann disease', N'rare disease', N''),
( N'Q498826', N'sucrose intolerance', N'Congenital sucrase-isomaltase deficiency (CSID) is a carbohydrate intolerance disorder characterised by malabsorption of oligosaccharides and disaccharides', N''),
( N'Q498916', N'apraxia', N'agnosia that is a loss of the ability to map out physical actions in order to repeat them in functional activities', N''),
( N'Q4990874', N'congenital fibrosis of the extraocular muscles', N'ocular motility disease that is characterized by the inability to move the eyes in certain directions, droopy eyelids and eyes that are fixed in an abnormal position', N''),
( N'Q499574', N'tendinitis', N'Human disease', N''),
( N'Q49970049', N'Atelosteogenesis type I', N'AO1. AOI. Atelosteogenesis type 1. Giant cell chondrodysplasia. Spondylo-humero-femoral dysplasia', N''),
( N'Q499857', N'Hibernoma', N'A rare benign slow growing adipose tissue tumor, characterized by the presence of polygonal brown fat cells with multivacuolated and/or granular cytoplasm.  The tumor is usually painless and is most often seen in young adults.', N''),
( N'Q5001316', N'Buschke–Ollendorff syndrome', N'', N''),
( N'Q500695', N'retinoblastoma', N'Retinal cell cancer', N''),
( N'Q500816', N'polycystic ovary syndrome', N'set of symptoms caused by elevated androgens in females', N''),
( N'Q5009803', N'CD25 deficiency', N'human disease', N''),
( N'Q5013186', N'CNS demyelinating autoimmune diseases', N'human disease', N''),
( N'Q501561', N'pericarditis', N'pericardium disease that is characterized by an inflammation of the pericardium and has symptom chest pain', N''),
( N'Q5016237', N'Cadang-cadang', N'disease', N''),
( N'Q501829', N'gigantism', N'Human disease', N''),
( N'Q5018774', N'calcifying odontogenic cyst', N'lesion of the jaws with features of both a cyst and a solid neoplasm', N''),
( N'Q5026799', N'Camisa disease', N'', N''),
( N'Q5031732', N'Candidal intertrigo', N'', N''),
( N'Q5032577', N'Cannabinoid hyperemesis syndrome', N'Nausea and vomiting resulting from cannabis use', N''),
( N'Q5034093', N'Cantú syndrome', N'osteochondrodysplasia characterized by congenital hypertrichosis, neonatal macrosomia, and cardiomegaly', N''),
( N'Q50349632', N'Helsmoortel-Van Der Aa syndrome', N'An autosomal dominant non-syndromic intellectual disability that has material basis in an autosomal dominant mutation of ADNP on chromosome 20q13.13.', N''),
( N'Q50349641', N'White-Sutton syndrome', N'An autosomal dominant non-syndromic intellectual disability that has material basis in an autosomal dominant mutation of POGZ on chromosome 1q21.3.', N'')
GO