INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q1001150', N'fibrillation', N'irregular movement of muscle fibers', N''),
( N'Q1004647', N'bullous pemphigoid', N'autoimmune disease of skin and connective tissue characterized by large blisters', N''),
( N'Q1016605', N'Burkitt lymphoma', N'mature B-cell neoplasm of B-cells found in the germinal center', N''),
( N'Q1017169', N'Buruli ulcer disease', N'tropical disease', N''),
( N'Q1018534', N'progressive familial intrahepatic cholestasis', N'intrahepatic cholestasis characterized by early onset of chronic unremitting cholestasis of hepatocellular origin that progresses to hepatic fibrosis, cirrhosis, and end-stage liver disease before adulthood', N''),
( N'Q1018652', N'byssinosis', N'human disease', N''),
( N'Q101896', N'gonorrhea', N'sexually transmitted infection', N''),
( N'Q101971', N'wart', N'small, rough growth resembling a cauliflower or a solid blister, often found on hands', N''),
( N'Q101991', N'inflammation', N'signs of activation of the immune system', N''),
( N'Q1019940', N'Borjeson-Forssman-Lehmann syndrome', N'genetic condition in humans', N''),
( N'Q1022718', N'CADASIL', N'autosomal dominant cerebrovascular disorder characterized by recurrent subcortical ischemic stroke and cognitive impairment', N''),
( N'Q1023604', N'CHARGE syndrome', N'syndrome that is characterized by a pattern of congenital anomalies including choanal atresia and malformations of the heart, inner ear, and retina', N''),
( N'Q1024546', N'cancer of unknown primary origin', N'disease', N''),
( N'Q1026326', N'calciphylaxis', N'Human disease', N''),
( N'Q10264745', N'biotin deficiency', N'nutritional deficiency disease that is characterized by thinning of the hair (often with loss of hair color), and red scaly rash around the eyes, nose, and mouth', N''),
( N'Q1027995', N'pyloric stenosis', N'congenital disorder of digestive system', N''),
( N'Q10282075', N'gingival fibromatosis', N'rare condition of gingival overgrowth', N''),
( N'Q10295763', N'hyperlysinemia', N'amino acid metabolic disorder that involves an abnormal increase of lysine in the blood', N''),
( N'Q10302339', N'Health effects of pesticides', N'', N''),
( N'Q1031536', N'campomelic dysplasia', N'osteochondrodysplasia that has material basis in a mutation in chromosome 17 which results in bowing in the located in tibia or located in femur', N''),
( N'Q1034620', N'capillariasis', N'disease caused by nematodes of the genus Capillaria', N''),
( N'Q1034736', N'Caplans syndrome', N'pneumoconiosis that results in humans that also have rheumatoid arthritis', N''),
( N'Q1035226', N'Caput medusae', N'appearance of distended and engorged superficial epigastric veins', N''),
( N'Q1035319', N'Henoch-Schoenlein purpura', N'Human disease', N''),
( N'Q10355322', N'Psoriatic erythroderma', N'', N''),
( N'Q1035645', N'in situ carcinoma', N'human disease', N''),
( N'Q1036696', N'hypothermia', N'condition in which core temperature drops below the required temperature for normal metabolism and body functions', N''),
( N'Q1041258', N'West syndrome', N'A severe epilepsy syndrome with triad of infantile spasms, an interictal electroencephalogram (EEG) pattern termed hypsarrhythmia, and mental retardation.', N''),
( N'Q1044007', N'Carney complex', N'autosomal dominant disease characterized by myxomas, spotty pigmentation of the skin and endocrine overactivity', N''),
( N'Q1044327', N'Caroli disease', N'bile duct disease that is characterized by abnormal dilatation of the intrahepatic bile ducts', N''),
( N'Q10469820', N'language disorder', N'range of neurodevelopmental conditions', N''),
( N'Q1047551', N'Pinealoma', N'endocrine gland located in the pineal gland located in the brain', N''),
( N'Q1047559', N'agammaglobulinemia', N'B cell deficiency that is caused by a reduction in all types of gamma globulins', N''),
( N'Q10480798', N'ectopia', N'displacement or malposition of an organ or other body part', N''),
( N'Q1048084', N'opisthorchiasis', N'Human helminthiasis', N''),
( N'Q1048101', N'rickettsialpox', N'Human disease', N''),
( N'Q1049021', N'gender dysphoria', N'distress felt by a person due to a mismatch between gender identity and sex assigned at birth', N''),
( N'Q1049655', N'paraplegia', N'impairment in motor or sensory function of the lower extremities', N''),
( N'Q1049881', N'retinoschisis', N'Human disease', N''),
( N'Q1051223', N'seasonal affective disorder', N'mental depression that involves presentation of depressive symptoms only during a specific season of the year', N''),
( N'Q1051355', N'conversion disorder', N'physical illness or symptoms caused by serious emotional stress', N''),
( N'Q1051436', N'cauda equina syndrome', N'nerve damage at the end of the spinal cord', N''),
( N'Q1052391', N'inherited  pseudoxanthoma elasticum', N'Human disease', N''),
( N'Q1052626', N'pulmonary hemosiderosis', N'human disease', N''),
( N'Q1052687', N'Charcot–Marie–Tooth disease', N'neuromuscular disease that is characterized by a slowly progressive degeneration of the muscles of the foot, lower leg, hand and forearm', N''),
( N'Q10529545', N'hyperandrogenism', N'medical condition characterized by excessive levels of androgens in the body', N''),
( N'Q1053120', N'Gitelman syndrome', N'Human disease', N''),
( N'Q1053948', N'Stevens-Johnson syndrome', N'Disease', N''),
( N'Q105434', N'hypochondriasis', N'somatoform disorder that involves an excessive preoccupation or worry about having a serious illness', N''),
( N'Q1054713', N'xerophthalmia', N'Human disease', N''),
( N'Q1054718', N'kidney disease', N'urinary system disease that is located in the kidney', N''),
( N'Q1055374', N'adenosine deaminase deficiency', N'A severe combined immunodeficiency that is caused by a defective enzyme, adenosine deaminase (ADA), necessary for the breakdown of purines. Lack of ADA causes accumulation of dATP.', N''),
( N'Q105688', N'hypoxia', N'condition in which the body or a region of the body is deprived of adequate oxygen supply at the tissue level', N''),
( N'Q1058608', N'primary sclerosing cholangitis', N'sclerosing cholangitis characterized by fibroobliterative inflammation of the biliary tract, leading to cirrhosis and portal hypertension', N''),
( N'Q1058691', N'communication disorder', N'specific developmental disorder that involves specific developmental disorders of speech and language', N''),
( N'Q10591185', N'Mycoplasma pneumonia', N'Human disease', N''),
( N'Q1059765', N'periodontal disease', N'human disease', N''),
( N'Q1060310', N'narcissistic personality disorder', N'personality disorder that involves an excessive preoccupation with issues of personal adequacy, power, prestige and vanity', N''),
( N'Q1060827', N'Kikuchi disease', N'rare disease', N''),
( N'Q1061988', N'Flail chest', N'Life-threatening medical condition that occurs when a segment of the rib cage breaks due to trauma and becomes detached from the rest of the chest wall', N''),
( N'Q1063085', N'neurogenic arthropathy', N'Human disease', N''),
( N'Q1066011', N'cowpox', N'Human disease', N''),
( N'Q1066061', N'diverticulitis', N'digestive disease caused by an inflammation of a herniating pouch (diverticulum) within the wall of the intestine, most often colon', N''),
( N'Q1066265', N'Osgood-Schlatters disease', N'osteochondrosis', N''),
( N'Q1066311', N'complex regional pain syndrome', N'human disease', N''),
( N'Q1068997', N'cheilitis', N'inflammation of the lips', N''),
( N'Q1069110', N'Cotard delusion', N'mental disease', N''),
( N'Q1069694', N'retroverted uterus', N'', N''),
( N'Q1071685', N'chiasmal syndrome', N'optic nerve disease that is characterized by lesions of the optic chiasm, manifesting as various impairments of the sufferers visual field according to the location of the lesion along the optic nerve', N''),
( N'Q1071707', N'Arnold-Chiari malformation', N'human disease', N''),
( N'Q1072290', N'sick building syndrome', N'a medical condition where people in a building suffer from symptoms of illness or feel unwell for no apparent reason', N''),
( N'Q107231', N'paralysis', N'loss of muscle function in one or more muscles', N''),
( N'Q1072420', N'primary biliary cirrhosis', N'liver cirrhosis characterized by chronic and slow progressive destruction of intrahepatic bile ducts', N''),
( N'Q1072716', N'Mongolian spot', N'benign, flat, congenital birthmark, prevalent among East, South, Southeast, North and Central Asian peoples, Indigenous Oceanians, and Amerindians', N''),
( N'Q10748814', N'megalencephaly', N'neurodevelopmental disorder characterized by abnormally large brain.', N''),
( N'Q1075470', N'expressive language disorder', N'neurodevelopmental condition', N''),
( N'Q1075909', N'strawberry gallbladder', N'Human disease', N''),
( N'Q1075923', N'cholestasis', N'Human disease', N''),
( N'Q1076053', N'chondroblastoma', N'Human disease', N''),
( N'Q1076060', N'chondrodysplasia punctata', N'Human disease', N''),
( N'Q1076078', N'chondroma', N'cell type benign neoplasm that is a cartilaginous tumor encapsulated with a lobular growing pattern', N''),
( N'Q1076086', N'chondromalacia patellae', N'Human disease', N''),
( N'Q1076087', N'chondrosarcoma', N'connective tissue cancer that has material basis in cells derived from transformed cells that produce cartilage', N''),
( N'Q1076389', N'chordoma', N'notochordal cancer that derives from cellular remnants of the notochord', N''),
( N'Q1076421', N'choreatic disease', N'movement disease characterized by brief, semi-directed, irregular movements that not repetitive or rhythmic, but appear to flow from one muscle to the next', N''),
( N'Q1076481', N'choriocarcinoma', N'Human disease', N''),
( N'Q1077139', N'tic disorder', N'range of neurodevelopmental conditions', N''),
( N'Q1077603', N'mesothelioma', N'A type of cancer that develops from the thin layer of tissue that covers many of the internal organs (known as the mesothelium)', N''),
( N'Q1077955', N'hypohidrotic ectodermal dysplasia', N'Human disease', N''),
( N'Q1079120', N'hyperlipidemia', N'abnormally elevated levels of lipids or lipoproteins in the blood', N''),
( N'Q10832211', N'megaloblastic anemia', N'macrocytic anemia that is characterized by inhibition of DNA synthesis during red blood cell production', N''),
( N'Q1084600', N'hairy tongue', N'Human disease', N''),
( N'Q10859678', N'necrotizing enterocolitis', N'human disease', N''),
( N'Q10863066', N'Piedra', N'fungal hair disease', N''),
( N'Q1087232', N'Dyslalia', N'speech disorder', N''),
( N'Q1087632', N'Idiopathic CD4+ lymphocytopenia', N'rare disease', N''),
( N'Q1087811', N'chronic wasting disease', N'animal disease', N''),
( N'Q1088030', N'chronic inflammatory demyelinating polyradiculoneuropathy', N'acquired immune-mediated inflammatory disorder of the peripheral nervous system', N''),
( N'Q1088042', N'chronic venous insufficiency', N'Human disease', N''),
( N'Q1088057', N'Chronic neutrophilic leukemia', N'chronic leukemia characterized by neutrophilic leukocytosis with no detectable Philadelphia chromosome or BCR/ABL fusion gene', N''),
( N'Q1088059', N'Chronic allograft nephropathy', N'', N''),
( N'Q1088072', N'Chronic myelomonocytic leukemia', N'chronic leukemia characterized by monocytosis, increased monocytes in the bone marrow, variable degrees of dysplasia, but an absence of immature granulocytes in the blood', N''),
( N'Q1088156', N'chronic lymphocytic leukemia', N'lymphoblastic leukemia characterized by over production of B-cells and their accumulation in bone marrow and blood', N''),
( N'Q1088163', N'pre-malignant neoplasm', N'cellular proliferation that results in abnormal growths in the body, which do not invade or destroy the surrounding tissue, but in time will transform into a cancer', N''),
( N'Q1093388', N'Minimally conscious state', N'disease', N''),
( N'Q1093815', N'hyperhomocysteinemia', N'amino acid metabolic disorder that involves an abnormally large level of homocysteine in the blood', N''),
( N'Q1095925', N'Facet syndrome', N'syndrome in which the facet joints cause painful symptoms', N''),
( N'Q1097028', N'spondylosis', N'degenerative osteoarthritis of the joints between the center of the spinal vertebrae and/or neural foramina', N''),
( N'Q1097302', N'Diplegia', N'', N''),
( N'Q1097490', N'cardiofaciocutaneous syndrome', N'Human disease', N''),
( N'Q1097957', N'intermittent claudication', N'symptom that describes muscle pain on mild exertion (ache, cramp, numbness or sense of fatigue)', N''),
( N'Q10992004', N'Hereditary cystatin C amyloid angiopathy', N'A cerebral amyloid angiopathy that has material basis in an autosomal dominant mutation of CST3 on chromosome 20p11.21.', N''),
( N'Q1101694', N'Joubert syndrome', N'Joubert syndrome (JS) is characterized by congenital malformation of the brainstem and agenesis or hypoplasia of the cerebellar vermis leading to an abnormal respiratory pattern, nystagmus, hypotonia, ataxia, and delay in achieving motor milestones', N''),
( N'Q1102300', N'clonorchiasis', N'infectious disease caused by the Chinese liver fluke, Clonorchis sinensis, and two related species', N''),
( N'Q1103561', N'Cluttons joints', N'term describing the finding of symmetrical joint swelling seen in patients with congenital syphilis', N''),
( N'Q11039483', N'IgG4-related disease', N'A systemic fibroinflammatory disease, associated with elevated serum IgG4 levels in  about 60% of cases', N''),
( N'Q1106843', N'caffeine dependence', N'central nervous system stimulant drug which occurs in nature as part of the coffee, tea, yerba mate and other plants', N''),
( N'Q1106881', N'Coffin-Lowry syndrome', N'genetic disorder that is X-linked dominant', N''),
( N'Q1106923', N'Cogan syndrome', N'a rare vasculitis of children and young adults characterized by nonsyphilitic interstitial keratitis of cornea, fever and fatigue.', N''),
( N'Q1107087', N'Cohen syndrome', N'Cohen syndrome (CS) is a rare genetic developmental disorder characterized by microcephaly, characteristic facial features, hypotonia, non-progressive intellectual deficit, myopia and retinal dystrophy, neutropenia and truncal obesity', N''),
( N'Q1110197', N'Acute myeloblastic leukemia', N'form of myeloid leukemia affecting myeloblasts', N''),
( N'Q1110590', N'hypermobility syndrome', N'disease', N''),
( N'Q1112752', N'Watson syndrome', N'', N''),
( N'Q1112977', N'syringomyelia', N'congenital disorder of nervous system', N''),
( N'Q1114480', N'finger agnosia', N'agnosia that is a loss of the ability to distinguish the fingers on the hand', N''),
( N'Q11167292', N'repressed memory', N'memory that is hidden from trauma', N''),
( N'Q1117652', N'punctate epithelial keratoconjunctivitis', N'disease of the eyes', N''),
( N'Q1120682', N'metachromatic leukodystrophy', N'human disease', N''),
( N'Q1122485', N'urethritis', N'Inflammation of the urethra', N''),
( N'Q1122668', N'tyrosinemia', N'amino acid metabolic disorder that involves impaired break down of the amino acid tyrosine', N''),
( N'Q112412', N'congenital myopathy', N'human disease', N''),
( N'Q1124606', N'ganglioneuroma', N'rare and benign tumor of the autonomic nerve fibers arising from neural crest sympathogonia', N''),
( N'Q1125121', N'advanced sleep phase syndrome', N'sleep disorder that involves an altered circadian rhythm resulting in falling asleep in early evening and awaking very early in the morning', N''),
( N'Q1125160', N'pityriasis rosea', N'type of skin rash', N''),
( N'Q1125675', N'congenital disorder of glycosylation', N'carbohydrate metabolic disorder that involves deficient or defective glycosylation of a variety of tissue proteins and/or lipids', N''),
( N'Q112670', N'mastocytosis', N'human disease', N''),
( N'Q1126831', N'tetralogy of Fallot', N'Congenital heart defect that is present at birth. Symptoms include episodes of bluish color to the skin.Embryology includes the anteriosuperior displacement of the infundibular (aorticopulmonary) septum.', N''),
( N'Q1126839', N'Horners syndrome', N'Human disease characterized by miosis (a constricted pupil), partial ptosis (a weak, droopy eyelid), apparent anhydrosis (decreased sweating), with apparent enophthalmos (inset eyeball)', N''),
( N'Q1127417', N'flying phobia', N'human disease', N''),
( N'Q1127727', N'melorheostosis', N'osteosclerosis that has material basis in a mutation of the LEMD3 gene which results in a hyperdense bony cortex', N''),
( N'Q1128440', N'toxic shock syndrome', N'condition caused by bacterial toxins', N''),
( N'Q1128595', N'pulmonary hypertension', N'hypertension characterized by an increase of blood pressure in the pulmonary artery, pulmonary vein or pulmonary capillaries', N''),
( N'Q1128996', N'dysplasia', N'abnormal development, at macroscopic or microscopical level', N''),
( N'Q1129007', N'angioedema', N'skin disease characterized by the rapid swelling of the dermis, subcutaneous tissue, mucosa and submucosal tissues', N''),
( N'Q1129046', N'alexithymia', N'agnosia that is a deficiency in understanding, processing, or describing emotions', N''),
( N'Q1129105', N'diabetic nephropathy', N'disease', N''),
( N'Q1129121', N'splenomegaly', N'abnormal increased size of the spleen', N''),
( N'Q1129338', N'granuloma', N'inflammation consisting of immune cells known as macrophages', N''),
( N'Q1129947', N'caudal regression syndrome', N'congenital disorder in humans caused by abnormal fetal development of the lower spine', N''),
( N'Q1130192', N'gastroenterocolitis', N'disease characterized by inflammation of the stomach, small intestines, and colon', N''),
( N'Q1130519', N'heart valve disease', N'disease in the valves of the heart', N''),
( N'Q11312280', N'pituitary-dependent Cushings disease', N'Human disease', N''),
( N'Q1131786', N'Cor pulmonale', N'human disease', N''),
( N'Q1132056', N'myofascial pain syndrome', N'human disease', N''),
( N'Q1132108', N'hypospadias', N'congenital disorder of urinary system', N''),
( N'Q1132120', N'trigeminal neuralgia', N'neuropathic disorder', N''),
( N'Q1132959', N'Simple partial seizure', N'seizures which affect initially only one hemisphere of the brain', N''),
( N'Q1133289', N'Cornelia de Lange syndrome', N'genetic disease', N''),
( N'Q1134891', N'pica', N'eating disorder', N''),
( N'Q1135124', N'agenesis of the corpus callosum', N'disease', N''),
( N'Q1135338', N'Bells palsy', N'facial paralysis resulting from dysfunction in the cranial nerve VII (facial nerve)', N''),
( N'Q1136492', N'Costello syndrome', N'syndrome characterized by craniofacial dysmorphology, cardiac defects, mild intellectual disability, and high birth weight followed by a failure to thrive and developmental delays', N''),
( N'Q1137321', N'onchocerciasis', N'Human helminthiasis', N''),
( N'Q1137463', N'sexual dysfunction', N'difficulty experienced by humans during any stage of normal sexual activity', N''),
( N'Q1137767', N'muscular dystrophy', N'myopathy characterized by progressive skeletal muscle weakness', N''),
( N'Q1138188', N'Cowden syndrome 1', N'inherited disorder causing tumor-like growth and increased cancer risk', N''),
( N'Q1138267', N'coxa vara', N'hip deformity in which the femoral neck leans forward resulting in a decrease in the angle between the neck and shaft', N''),
( N'Q1138580', N'Ewings sarcoma', N'bone cancer that has material basis in neural crest cells derives from undeveloped, undifferentiated neuroectoderm', N''),
( N'Q1138584', N'balanitis', N'infectious or non-infectious inflammation of the glans penis', N''),
( N'Q1138590', N'non-Hodgkin lymphoma', N'cancer of lymph in humans', N''),
( N'Q11393885', N'inverted papilloma', N'Human disease', N''),
( N'Q1140000', N'Crigler-Najjar syndrome', N'bilirubin metabolic disorder that involves a build up of bilirubin as bilirubin is not being broken down as a result of a lack or deficiency of the enzyme uridine diphosphate glycosyltransferase (UGT)', N''),
( N'Q1140516', N'critical illness polyneuropathy', N'Human disease', N''),
( N'Q1140528', N'Drusen', N'tiny yellow or white accumulations of extracellular material that build up between Bruchs membrane and the retinal pigment epithelium of the eye', N''),
( N'Q1140794', N'mitral valve stenosis', N'mitral valve disease that is characterized by the narrowing of the orifice of the mitral valve of the heart', N''),
( N'Q114085', N'rhinitis', N'irritation and inflammation of the mucous membrane inside the nose', N''),
( N'Q1141055', N'diverticulum', N'medical or biological term for an outpouching of a hollow (or a fluid-filled) structure in the body', N''),
( N'Q1141499', N'Ehlers-Danlos syndrome', N'group of genetic connective tissue disorders', N''),
( N'Q1142563', N'delayed ejaculation', N'mans inability for or persistent difficulty in achieving orgasm, despite typical sexual desire and sexual stimulation', N''),
( N'Q1142806', N'developmental disability', N'diverse group of chronic conditions that are due to mental or physical impairments that arise before adulthood, causing difficulties in certain areas of life, especially in language, mobility, learning, self-help, and independent living', N''),
( N'Q1143025', N'oral cavity cancer', N'gastrointestinal system cancer that is located in the oral cavity', N''),
( N'Q1144039', N'inguinal hernia', N'intestinal disease characterized by a protrusion of abdominal cavity contests through the inguinal canal', N''),
( N'Q1144334', N'leukorrhea', N'type of vaginal discharge', N''),
( N'Q1144406', N'oligohydramnios', N'placenta disease that is characterized by a deficiency of amniotic fluid sometimes resulting in an embryonic defect through adherence between embryo and amnion', N''),
( N'Q1144618', N'familial Mediterranean fever', N'Human disease', N''),
( N'Q1145668', N'hemolytic anemia', N'form of anemia due to hemolysis', N''),
( N'Q1145674', N'necrotizing fasciitis', N'infection that results in the death of the bodys soft tissue', N''),
( N'Q1146454', N'IgA glomerulonephritis', N'glomerulonephritis characterized by build up of IgA antibody in the glomerulus', N''),
( N'Q1147182', N'fecal incontinence', N'inability to refrain from defecation', N''),
( N'Q1147596', N'cycloplegia', N'paralysis of the ciliary muscle of the eye, resulting in a loss of accommodation', N''),
( N'Q1147908', N'pyometritis', N'uterine infection', N''),
( N'Q1148337', N'hepatocellular carcinoma', N'liver carcinoma that has material basis in undifferentiated hepatocytes', N''),
( N'Q11488367', N'ossification of the posterior longitudinal ligament', N'connective tissue disease characterized by ectopic ossification of the posterior longitudinal spinal ligament resulting in spinal cord compression, myelopathy and hyperreflexia', N''),
( N'Q1149042', N'cystinosis', N'A lysosomal storage disease characterized by the abnormal accumulation of cystine in the lysosomes. It follows an autosomal recessive inheritance pattern and has material basis in mutations in the CTNS gene, located on chromosome 17.', N''),
( N'Q1149046', N'cystinuria', N'amino acid metabolic disorder that involves the formation of cystine stones in the kidneys, ureter, and bladder', N''),
( N'Q11491562', N'acute hemorrhagic conjunctivitis', N'Human disease', N''),
( N'Q1150299', N'photosensitive epilepsy', N'epilepsy characterized by seizures triggered by visual stimuli that form patterns in space or time, such as flashing lights', N''),
( N'Q1150378', N'neurodermatitis', N'Human disease', N''),
( N'Q1151300', N'autoimmune lymphoproliferative syndrome', N'Human disease', N''),
( N'Q1151507', N'dermatitis herpetiformis', N'human disease', N''),
( N'Q11516357', N'adverse event', N'unfavourable sign, symptom, or disease associated with use of a medicinal product, whether or not related to the product', N''),
( N'Q1151801', N'Waardenburgs syndrome', N'autosomal disease characterized by varying degrees of deafness, minor defects in structures arising from the neural crest and pigmentation anomalies of the hair, the skin and/or the iris of both eyes', N''),
( N'Q1153171', N'decompression illness', N'disorders arising from ambient pressure reduction', N''),
( N'Q1153419', N'interstitial lung disease', N'group of lung diseases affecting the interstitium (the tissue and space around the air sacs of the lungs)', N''),
( N'Q1153641', N'Wolfram syndrome', N'Human disease', N''),
( N'Q1154055', N'osteochondrosis', N'ischemic bone disease that results in necrosis followed by regrowth in children and teens located in bone', N''),
( N'Q11540874', N'vertebrobasilar insufficiency', N'human disease', N''),
( N'Q11542703', N'metagonimiasis', N'A parasitic helminthiasis infectious disease that involves parasitic infection of the intestine by Metagonimus yokogawai. The symptoms are diarrhea and colicky abdominal pain. The heart and brain can also be infected.', N''),
( N'Q1154321', N'tonsillolith', N'soft aggregates of bacterial and cellular debris that form in the tonsillar crypts, the crevices of the tonsils', N''),
( N'Q1154422', N'leukocyte-adhesion deficiency syndrome', N'Human disease', N''),
( N'Q1154619', N'Werner syndrome', N'Lethal autosomal recessive disorder', N''),
( N'Q11546777', N'Paradental cyst', N'', N''),
( N'Q1154764', N'DOOR syndrome', N'', N''),
( N'Q1157761', N'dacryocystitis', N'infection of the lacrimal sac', N''),
( N'Q11590740', N'nerve sheath neoplasms', N'peripheral nervous system neoplasm that is located in the connective tissue surrounding nerves', N''),
( N'Q11606722', N'pseudosarcomatous fibromatosis', N'Human disease', N''),
( N'Q11612290', N'Shenkui', N'', N''),
( N'Q11612732', N'Hyperinsulinemic hypoglycemia', N'sporadic or inherited disorder characterized by the focal or diffuse proliferation of the cells of the islets of Langerhans in the pancreas', N''),
( N'Q1161568', N'granulomatosis with polyangiitis', N'autoimmune disease affecting blood vessels in the lungs, kidneys, and skin', N''),
( N'Q1162164', N'clubfoot', N'bone development disease', N''),
( N'Q1162694', N'keratoconjunctivitis sicca', N'condition of having dry eyes', N''),
( N'Q11627066', N'West Nile fever', N'human disease', N''),
( N'Q1164401', N'Pitt-Hopkins syndrome', N'rare genetic disorder characterized by developmental delay, epilepsy, distinctive facial features, and possible intermittent hyperventilation followed by apnea', N''),
( N'Q1164529', N'renal cell carcinoma', N'renal carcinoma that has material basis in the lining of the proximal convoluted renal tubule of the kidney', N''),
( N'Q1165179', N'Kallmann syndrome', N'A form of hypogonadotropic hypogonadism which is also accompanied by a total lack or partial loss in the sense of smell. The condition affects both males and females and causes a failure in puberty and infertility.', N''),
( N'Q11663712', N'atypical chronic myeloid leukemia', N'A myelodysplastic myeloproliferative neoplasm characterized by the principal involvement of the neutrophil series with leukocytosis and multilineage dysplasia. The neoplastic cells do not have a Philadelphia chromosome or the BCR/ABL fusion gene.', N''),
( N'Q11668606', N'Myelodysplastic–myeloproliferative diseases', N'', N''),
( N'Q11668635', N'hypermethioninemia', N'An amino acid metabolic disorder that involves an excess of the amino acid methionine, in the blood. This condition can occur when methionine is not broken down properly in the body.', N''),
( N'Q1166866', N'Darwins tubercle', N'congenital ear condition which often presents as a thickening on the helix at the junction of the upper and middle thirds', N''),
( N'Q11679861', N'ancylostomiasis', N'human disease', N''),
( N'Q11688946', N'myeloid leukemia', N'leukemia that is located in myeloid tissue', N''),
( N'Q1169972', N'Sperm Granuloma', N'', N''),
( N'Q117121', N'Wilson disease', N'multisystem disease due to abnormal accumulation of copper', N''),
( N'Q1172076', N'hepatocellular adenoma', N'Hepatocellular adenoma (HA) is a rare benign tumor of the liver', N''),
( N'Q117484', N'dandruff', N'A skin condition mainly affecting the scalp causing flaking and itchiness', N''),
( N'Q11773731', N'degenerative disc disease', N'bone deterioration disease that has material basis in gradual dehydration and tears located in intervertebral disc', N''),
( N'Q11777035', N'Neurocutaneous melanosis', N'Congenital disorder involving melanocytic tumours in the skin and brain', N''),
( N'Q1178507', N'bone inflammation disease', N'inflammation of bone', N''),
( N'Q11790313', N'intermittent hydrarthrosis', N'human disease', N''),
( N'Q11793790', N'ovarian neoplasm', N'benign, borderline, or malignant neoplasm involving the ovary', N''),
( N'Q11794042', N'New daily persistent headache', N'', N''),
( N'Q1179460', N'Fanconi syndrome', N'renal tubular transport disease of the proximal renal tubes characterized by glucosuria, phosphaturia, generalized aminoaciduria and HCO3 wasting', N''),
( N'Q11835644', N'thyroiditis', N'endocrine disease', N''),
( N'Q11838430', N'Trismus-pseudocamptodactyly syndrome', N'a genetic condition where the mouth could not be opened completely', N''),
( N'Q118418', N'antisocial personality disorder', N'Personality disorder that involves a pervasive pattern of disregard for other people', N''),
( N'Q11852863', N'Arts syndrome', N'Lethal ataxia with deafness and optic atrophy (also known as Arts syndrome) is characterized by intellectual deficit, early-onset hypotonia, ataxia, delayed motor development, hearing impairment and loss of vision due to optic atrophy', N''),
( N'Q1185316', N'Dementia pugilistica', N'neurodegenerative disease found in people who have had multiple head injuries, subtype of CTE', N''),
( N'Q1186703', N'demyelinating disease', N'type of neurological disease where the myelin sheath of neurons is damaged', N''),
( N'Q1187697', N'adult-onset Stills disease', N'rare from of inflammatory arthritis characterized by fevers, rash, and joint pain', N''),
( N'Q11883686', N'Myoclonic epilepsy', N'', N''),
( N'Q11884036', N'Polycystic lipomembranous osteodysplasia with sclerosing leukoencephalopathy', N'', N''),
( N'Q1188698', N'thought disorder', N'disorder of thought form, content or stream', N''),
( N'Q1191065', N'heat illness', N'condition caused by the failure of the human body to dissipate heat in a hot environment', N''),
( N'Q119280', N'medullary sponge kidney', N'congenital disorder of urinary system', N''),
( N'Q1193891', N'retrograde amnesia', N'loss of memory of events that in occurred before the onset of amnesiac condition', N''),
( N'Q1194496', N'scrub typhus', N'form of typhus caused by the intracellular parasite Orientia tsutsugamushi', N''),
( N'Q1194520', N'graft-versus-host disease', N'medical condition', N''),
( N'Q1194557', N'laryngitis', N'inflammation of the larynx', N''),
( N'Q1196503', N'Computer vision syndrome', N'condition resulting from focusing the eyes on a computer or other display device for protracted, uninterrupted periods of time', N''),
( N'Q119660', N'Picardy sweat', N'infectious disease', N''),
( N'Q1198391', N'intracranial aneurysm', N'cerebrovascular disorder', N''),
( N'Q1199621', N'Cat eye syndrome', N'disease', N''),
( N'Q1199732', N'xanthoma', N'deposition of yellowish cholesterol-rich material that can appear anywhere in the body in various disease states', N''),
( N'Q1200228', N'Dermal cylindroma', N'disease', N''),
( N'Q1200233', N'dermatochalasis', N'', N''),
( N'Q1200237', N'sclerosing hemangioma', N'benign skin growths', N''),
( N'Q1200239', N'dermatofibrosarcoma protuberans', N'fibrosarcoma that is located in the dermis layer of the skin', N''),
( N'Q1200267', N'dermoid cyst', N'tissue disease', N''),
( N'Q1200268', N'dermatographia', N'urticaria induced by stroking of the skin', N''),
( N'Q1200839', N'oculocerebrorenal syndrome', N'Human disease', N''),
( N'Q120136', N'arcus senilis', N'Human disease', N''),
( N'Q1201835', N'impulse control disorder', N'disease of mental health that involves a failure to resist an impulsive act or behaviour that may be harmful to self or others', N''),
( N'Q1207967', N'renal glycosuria', N'Human disease', N''),
( N'Q1208654', N'Diamond-Blackfan anemia', N'rare disease', N''),
( N'Q1209150', N'cerebral infarction', N'type of ischemic stroke resulting from a blockage in the blood vessels supplying blood to the brain', N''),
( N'Q1209744', N'uterine cancer', N'female reproductive organ cancer that is located in the uterus', N''),
( N'Q1209892', N'colorectal polyp', N'polyp that involves the colon', N''),
( N'Q121041', N'appendicitis', N'inflammation of the appendix', N''),
( N'Q121576', N'vascular malformation', N'congenital disease', N''),
( N'Q1216998', N'neoplasm', N'abnormal mass of tissue as a result of abnormal growth or division of cells', N''),
( N'Q12211073', N'Mortimers disease', N'', N''),
( N'Q122222', N'subependymal giant cell astrocytoma', N'low-grade astrocytic brain tumor (astrocytoma) that arises within the ventricles of the brain', N''),
( N'Q1223924', N'papillomatosis', N'disease', N''),
( N'Q1224295', N'Dieulafoy lesion', N'Human disease', N''),
( N'Q12244913', N'Intestinal spirochetosis', N'', N''),
( N'Q1224503', N'diffuse esophageal spasm', N'hypermotility disorder of the esophagus', N''),
( N'Q12252367', N'atherosclerosis', N'form of arteriosclerosis', N''),
( N'Q1227160', N'diphyllobothriasis', N'helminthiasis', N''),
( N'Q1228633', N'disease mongering', N'pejorative term for the practice of widening the diagnostic boundaries of illnesses and aggressively promoting their public awareness in order to expand the markets for treatment', N''),
( N'Q1229478', N'Distichia', N'human disease', N''),
( N'Q123251', N'follicular lymphoma', N'non-Hodgkin lymphoma that is characterized as an indolent non-Hodgkins lymphoma and has_material_basis_in follicle center B-cells (centrocytes and centroblasts).', N''),
( N'Q1233526', N'osteosclerosis', N'bone remodeling disease that results in abnormal elevated bone density or mass', N''),
( N'Q1234529', N'Doege–Potter syndrome', N'', N''),
( N'Q1234672', N'Dogger Bank itch', N'', N''),
( N'Q1235785', N'Stiff-Person syndrome', N'movement disease that is of unknown etiology characterized by progressive rigidity', N''),
( N'Q1236063', N'littoral cell angioma', N'disease', N''),
( N'Q1238645', N'Vogt–Koyanagi–Harada syndrome', N'multisystem disease', N''),
( N'Q12412172', N'neurohypophyseal diabetes insipidus', N'Human disease', N''),
( N'Q1242612', N'dopamine beta-hydroxylase deficiency', N'Dopamine beta-hydroxylase deficiency is an extremely rare genetic metabolic disorder characterized by autonomic dysregulation leading mainly to orthostatic hypotension', N''),
( N'Q124292', N'cholangiocarcinoma', N'bile duct adenocarcinoma that has material basis in bile duct epithelial cells.', N''),
( N'Q1243807', N'tinea cruris', N'type of fungal infection of the groin region in either sex, though more often seen in males', N''),
( N'Q124407', N'type-1 diabetes', N'form of diabetes mellitus', N''),
( N'Q124604', N'portal hypertension', N'hypertension in the hepatic portal system', N''),
( N'Q1246050', N'visual verbal agnosia', N'An agnosia that is a loss of the ability to comprehending the meaning of written words.', N''),
( N'Q12466983', N'Hypertrophic decidual vasculopathy', N'', N''),
( N'Q1248007', N'vascular occlusion', N'', N''),
( N'Q1250362', N'Nijmegen breakage syndrome', N'human disease', N''),
( N'Q1251847', N'phosphofructokinase deficiency', N'Human disease', N''),
( N'Q125466', N'coprolalia', N'Neurological disorder', N''),
( N'Q1255956', N'Dravet syndrome', N'epilepsy characterized by frequent febrile seizures and with onset before 1 year', N''),
( N'Q1257011', N'nephronophthisis', N'congenital disorder of urinary system', N''),
( N'Q1258463', N'WHIM syndrome', N'An immunodeficiency disease characterized by neutropenia, hypogammaglobulinemia, and extensive human papillomavirus (HPV) infection. It has material basis in heterozygous mutation in the CXCR4 gene on chromosome 2q22.', N''),
( N'Q1258666', N'Dresslers syndrome', N'pericarditis characterized by inflammation, occurring after injury, located in pericardium', N''),
( N'Q1258984', N'herpes simplex virus keratitis', N'keratitis of the cornea that has material basis in herpes simplex type infection', N''),
( N'Q1260186', N'hepatosplenomegaly', N'simultaneous enlargement of both the liver (hepatomegaly) and the spleen (splenomegaly)', N''),
( N'Q1262161', N'Leber hereditary optic neuropathy', N'Human disease', N''),
( N'Q1262684', N'Duane retraction syndrome', N'a rare congenital disease characterized by external gaze palsy', N''),
( N'Q1263039', N'Dubin-Johnson syndrome', N'rare, autosomal recessive, benign disorder that causes an isolated increase of conjugated bilirubin in the serum', N''),
( N'Q1264268', N'stannosis', N'medical condition caused by inhalation of tin compounds', N''),
( N'Q12656487', N'hymenolepiasis', N'Human helminthiasis', N''),
( N'Q1266395', N'duodenum cancer', N'small intestine cancer that is located in the beginning section of the small intestine', N''),
( N'Q1266401', N'Duodenal atresia', N'congenital disorder of digestive system', N''),
( N'Q1266418', N'duodenitis', N'Human disease', N''),
( N'Q1266519', N'corneal neovascularization', N'Human disease', N''),
( N'Q1266890', N'vascular disease', N'cardiovascular system disease that primarily affects the blood vessels', N''),
( N'Q126691', N'gestational diabetes', N'condition in which a woman without diabetes develops high blood sugar levels during pregnancy', N''),
( N'Q1268495', N'metrorrhagia', N'uterine bleeding between menstrual periods', N''),
( N'Q1269235', N'dyschezia', N'Difficult defecation.', N''),
( N'Q1269251', N'dysgerminoma', N'germ cell cancer that derives from cells that give rise to egg cells', N''),
( N'Q1269276', N'pompholyx', N'Human disease', N''),
( N'Q1269307', N'dysostosis', N'bone development disease that results in defective ossification of located in bone', N''),
( N'Q1269351', N'developmental coordination disorder', N'neurodevelopmental condition', N''),
( N'Q1271826', N'small intestine cancer', N'intestinal cancer that is located in the small intestine', N''),
( N'Q12735648', N'myosarcoma', N'musculoskeletal system cancer that is located in muscle', N''),
( N'Q1274018', N'Schimmelpenning syndrome', N'A neurocutaneous syndrome with anomalies of the central nervous system, ocular system, skeletal system, cardiovascular system, and genitourinary system. A triad of sebaceous nevi, seizures, and mental retardation.', N''),
( N'Q127556', N'osteochondritis tulaseca', N'ischemic bone disease that results_in necrosis located_in epiphysis.', N''),
( N'Q1275814', N'konzo', N'human disease', N''),
( N'Q127664', N'febrile seizure', N'seizure associated with a high body temperature', N''),
( N'Q1276885', N'Froelich syndrome', N'hypothalamic disease that is characterized by endocrine dysfunction of the hypothalamic gland resulting in delayed puberty, small testes, and obesity', N''),
( N'Q127724', N'cataract', N'clouding of the lens inside the eye, which leads to low vision', N''),
( N'Q1277281', N'Oroantral fistula', N'Antrumperforation', N''),
( N'Q1280852', N'echopraxia', N'catatonic behaviour, repetitive imitation of the movements of another person', N''),
( N'Q12811075', N'Nager acrofacial dysostosis', N'acrofacial dysostosis characterized by underdeveloped cheek bones, very small lower jaw, cleft palate, defects in the middle ear, absent eyelashes, and a notch in the lower eyelids called a coloboma, in children', N''),
( N'Q1282114', N'speech disorder', N'communication disorder that involves difficulty with the act of speech production.', N''),
( N'Q12822297', N'Hidradenoma', N'Human disease', N''),
( N'Q1283054', N'hypochondroplasia', N'osteochondrodysplasia that has material basis in mutation in the FGFR3 gene which affects ossification of cartilage and results in short limb dwarfism', N''),
( N'Q1283303', N'tricuspid atresia', N'tricuspid valve disease characterized by a missing or abnormally developed tricuspid heart value at birth', N''),
( N'Q128581', N'breast cancer', N'cancer that originates in the mammary gland', N''),
( N'Q1286320', N'neurilemmomatosis', N'Human disease', N''),
( N'Q1286499', N'dust mite allergy', N'', N''),
( N'Q1286848', N'Pfeiffer syndrome', N'acrocephalosyndactylia that has material basis in mutations in the FGFR1 and FGFR2 gene which results in premature fusion located in skull', N''),
( N'Q1290616', N'epidemic typhus', N'human disease', N''),
( N'Q129104', N'anthrax', N'infection caused by Bacillus anthracis bacteria', N''),
( N'Q1294912', N'endophthalmitis', N'globe disease that is characterized by inflammation of the inside of the eye', N''),
( N'Q1297985', N'brain herniation', N'disease', N''),
( N'Q13026837', N'Hand–Schüller–Christian disease', N'A multifocal, unisystem form of Langerhans-cell histiocytosis. There is involvement of multiple sites in one organ system, most frequently the bone. Patients are usually young children presenting with multiple destructive bone lesions.', N''),
( N'Q13038909', N'periodic limb movement disorder', N'sleep disorder that involves involuntary limb movement during sleep', N''),
( N'Q130555', N'Norman–Roberts syndrome', N'lissencephaly that has_material_basis_in homozygous mutation in the gene encoding reelin (RELN) on chromosome 7q22.', N''),
( N'Q1306218', N'pericardial effusion', N'pericardium disease that is characterized by an abnormal accumulation of fluid in the pericardial cavity', N''),
( N'Q1307866', N'Poikiloderma', N'human disease', N''),
( N'Q1313510', N'hypophosphatasia', N'rare, and sometimes fatal, metabolic bone disease', N''),
( N'Q1313618', N'monocytic leukemia', N'type of myeloid leukemia characterized by a dominance of monocytes in the marrow', N''),
( N'Q1317319', N'Stargardt disease', N'age related macular degeneration that is characterized by progressive vision loss usually to the point of legal blindness', N''),
( N'Q131742', N'hepatitis', N'inflammation of the liver tissue', N''),
( N'Q131749', N'anorexia nervosa', N'eating disorder characterized by refusal to maintain a healthy body weight, and an obsessive fear of gaining weight due to a distorted self image', N''),
( N'Q131755', N'bipolar disorder', N'human mental illness characterized by mood changes', N''),
( N'Q1318384', N'oligodendroglioma', N'type of glioma that are believed to originate from the oligodendrocytes of the brain or from a glial precursor cell', N''),
( N'Q1320276', N'hypovolemia', N'low blood volume', N''),
( N'Q1321884', N'congenital muscular dystrophy', N'human disease', N''),
( N'Q1323002', N'lipoid nephrosis', N'Human disease', N''),
( N'Q1323713', N'ectodermal dysplasia', N'human disease', N''),
( N'Q1324103', N'perianal hematoma', N'Human disease', N''),
( N'Q1324237', N'glossitis', N'soreness of the tongue, or more usually inflammation with depapillation of the dorsal surface of the tongue', N''),
( N'Q1324592', N'laryngospasm', N'disorder in which the adductor muscles of the vocal cords exhibit increased activity leading to laryngeal spasm', N''),
( N'Q13257137', N'Lentigo maligna', N'cellular subtype of malignant melanoma,  a pigmented lesion composed of melanocytes occurring on sun-exposed skin, usually the face and neck', N''),
( N'Q1327273', N'entropion', N'medical condition in which the eyelid (usually the lower lid) folds inward', N''),
( N'Q1327700', N'reactive arthritis', N'arthritis that is an autoimmune disease which develops due to an infection located elsewhere in the body', N''),
( N'Q1328805', N'bone neoplasm', N'tumor or cancer located in bone tissue or specific bones', N''),
( N'Q1328833', N'oppositional defiant disorder', N'human disorder involving hostility and defiance', N''),
( N'Q132971', N'dyslexia', N'neurological condition, developmental or acquired', N''),
( N'Q1330254', N'Dupuytrens contracture', N'superficial fibromatosis arising from the soft tissue of the palm', N''),
( N'Q133076', N'hernia', N'abnormal exit of tissue or an organ through the wall of the cavity in which it normally resides. Sarniao (Nerea Lopez, El Cabañal)', N''),
( N'Q133087', N'gout', N'medical condition that results in recurrent pain and swelling of joints', N''),
( N'Q1331116', N'Alport syndrome', N'monogenic disease characterized by glomerulonephritis, endstage kidney disease, and hearing loss', N''),
( N'Q1331905', N'Lewy body dementia', N'type of dementia', N''),
( N'Q1332427', N'gonadal dysgenesis', N'hypogonadism that is characterized by a progressive loss of germ cells on the developing gonads of an embryo', N''),
( N'Q1332448', N'Ellis-Van Creveld syndrome', N'Human disease', N''),
( N'Q1332565', N'Naxos disease', N'Naxos disease is a recessively inherited condition with arrhythmogenic right ventricular dysplasia/cardiomyopathy (ARVD/C) and a cutaneous phenotype, characterised by peculiar woolly hair and palmoplantar keratoderma', N''),
( N'Q1333608', N'medulloblastoma', N'infratentorial cancer located in the lower part of the brain, a type of primitive neuroectodermal tumor', N''),
( N'Q1334408', N'severe combined immunodeficiency', N'combined T cell and B cell immunodeficiency that is caused by a defect in several genes encoding for B and T lymphocytes resulting in individuals with non-functional immune systems', N''),
( N'Q1335642', N'Emery-Dreifuss muscular dystrophy', N'muscular dystrophy that chiefly affects muscles used for movement (skeletal) and heart (cardiac) muscle', N''),
( N'Q1336034', N'sitosterolemia', N'rare autosomal recessively inherited lipid metabolic disorder', N''),
( N'Q13365776', N'uremia', N'type of kidney disease, urea in the blood', N''),
( N'Q133696', N'color blindness', N'inability or decreased ability to see colour, or perceive colour differences, under normal lighting conditions', N''),
( N'Q1337441', N'Kostmann syndrome', N'group of diseases that affect myelopoiesis, causing a congenital form of neutropenia', N''),
( N'Q133772', N'dental caries', N'disease involving breakdown of teeth', N''),
( N'Q133780', N'plague', N'specific contagious and frequently fatal human disease caused by Yersinia pestis', N''),
( N'Q133823', N'migraine disorder', N'Disorder resulting in recurrent moderate-severe headaches', N''),
( N'Q1338684', N'tension headache', N'a common type of headache classified by The International Classification of Headache Disorders 3rd edition', N''),
( N'Q1339243', N'emphysema', N'abnormal presence of air or other gas within tissues', N''),
( N'Q1339466', N'empty sella syndrome', N'endocrine disease', N''),
( N'Q1339539', N'empyema', N'gathering of pus within a naturally existing anatomical cavity', N''),
( N'Q134003', N'hemophilia', N'Human genetic disease that impairs the bodys ability to make blood clots, a process needed to stop bleeding', N''),
( N'Q1340774', N'endometritis', N'inflammation of inner lining of uterus', N''),
( N'Q1342955', N'penile cancer', N'cancer of the penis', N''),
( N'Q1343590', N'Enostosis', N'', N''),
( N'Q1343593', N'enophthalmos', N'posterior displacement of the eyeball within the orbit due to changes in the volume of the orbit (bone) relative to its contents', N''),
( N'Q1343645', N'Hirschsprungs disease', N'congenital disorder of digestive system', N''),
( N'Q1343674', N'lice infestation', N'parasitic ectoparasitic infectious disease that involves infestation of lice, blood-feeding ectoparasitic insects of the order Phthiraptera', N''),
( N'Q1344812', N'epididymitis', N'medical condition characterized by inflammation of the epididymis', N''),
( N'Q1344835', N'hyperparathyroidism', N'endocrine disease', N''),
( N'Q1345113', N'toxocariasis', N'Illness of humans caused by larvae of the dog, the cat or the fox roundworm', N''),
( N'Q1345746', N'Keratitis–ichthyosis–deafness syndrome', N'human disease', N''),
( N'Q1345792', N'Goodpasture syndrome', N'hypersensitivity reaction type II disease that is characterized by glomerulonephritis located in kidney and hemorrhaging located in lung', N''),
( N'Q1346016', N'pernicious anemia', N'Human disease', N''),
( N'Q134649', N'diphtheria', N'infectious disease', N''),
( N'Q1346753', N'ependymoma', N'tumor that arises from the ependyma, a tissue of the central nervous system', N''),
( N'Q1347065', N'epiglottitis', N'inflammation of the epiglottis', N''),
( N'Q1347256', N'excessive tearing', N'overflow of tears onto the face', N''),
( N'Q1347416', N'epispadias', N'congenital disorder of urinary system', N''),
( N'Q1348374', N'tinea favosa', N'disease usually affecting the scalp, but occurring occasionally on any part of the skin, and even at times on mucous membranes', N''),
( N'Q134859', N'pertussis', N'human disease caused by the bacteria Bordetella pertussis', N''),
( N'Q1349259', N'Erdheim-Chester disease', N'rare disease', N''),
( N'Q1350035', N'erethism', N'Neurological disorder', N''),
( N'Q1350326', N'frostbite', N'medical condition where localized damage is caused to skin and other tissues due to freezing', N''),
( N'Q13512178', N'melancholia', N'DSM-IV subtype of clinical depression', N''),
( N'Q13522706', N'colic', N'form of pain', N''),
( N'Q1356194', N'Ectopia cordis', N'congenital malformation in which the heart is abnormally located either partially or totally outside of the thorax', N''),
( N'Q13566985', N'metaphyseal dysplasia', N'osteochondrodysplasia that results in thinning and the tendency to fracture located in bone', N''),
( N'Q13581332', N'familial visceral amyloidosis', N'type of amyloidosis that mostly affects the kidney', N''),
( N'Q1359898', N'cryptosporidiosis', N'Human disease', N''),
( N'Q1360044', N'syndactyly', N'synostosis that results in the fusion of two or more digits', N''),
( N'Q1361144', N'nutrition disorder', N'disease that results from excessive or inadequate intake of food and nutrients', N''),
( N'Q1361346', N'acid erosion', N'loss of tooth structure due to chemical dissolution by acids not of bacterial origin', N''),
( N'Q1361515', N'heart conduction disease', N'cardiovascular system disease that involves the hearts electrical conduction system', N''),
( N'Q13616307', N'osteochondritis', N'', N''),
( N'Q1361850', N'patulous eustachian tube', N'eustachian tube disorder with a wider eustachian tube which allows a larger bolus of bacteria-laden material from the nasopharynx during an infection to enter the middle ear, causing a more fulminant infection', N''),
( N'Q1362453', N'fibrosarcoma', N'connective tissue cancer that has material basis in fibrous connective tissue and characterized by the presence of immature proliferating fibroblasts or undifferentiated anaplastic spindle cells in a storiform pattern', N''),
( N'Q1362721', N'tuberous sclerosis', N'rare multisystem genetic disease that causes benign tumors to grow in the brain and on other vital organs', N''),
( N'Q13629899', N'detrusor sphincter dyssynergia', N'Human disease', N''),
( N'Q13632630', N'thyroid neoplasm', N'tumors or cancer of the thyroid gland', N''),
( N'Q1363508', N'monilethrix', N'Human disease', N''),
( N'Q1363662', N'Acquired perforating dermatosis', N'', N''),
( N'Q13637044', N'Hyperprolinemia', N'human disease', N''),
( N'Q1363732', N'erythema multiforme', N'skin disease that is a type of allergic reaction located in skin, which occurs in response to medications, infections, or illness', N''),
( N'Q1363738', N'erythema nodosum', N'skin disease', N''),
( N'Q1363741', N'erythroderma', N'skin disease', N''),
( N'Q13641482', N'kidney neoplasm', N'tumor or cancer of the kidney', N''),
( N'Q1364270', N'hypertrophic cardiomyopathy', N'disease in which a portion of the myocardium (heart muscle) is hypertrophic (enlarged) without any obvious cause, creating functional impairment of the heart.', N''),
( N'Q1365091', N'steatosis', N'abnormal retention of fat (lipids) within a cell or organ', N''),
( N'Q1365309', N'glioma', N'a type of tumor that starts in the brain or spine', N''),
( N'Q1365789', N'glycogen storage disease II', N'human disease', N''),
( N'Q1365937', N'space motion sickness', N'Human disease', N''),
( N'Q1367304', N'air embolism', N'vascular blockage by air bubbles', N''),
( N'Q1367782', N'gluten-related disorder', N'set of diseases caused by gluten ingestion', N''),
( N'Q1368780', N'essential thrombocytosis', N'human disease', N''),
( N'Q1368943', N'cerebral hemorrhage', N'type of intracranial hemorrhage that occurs within the brain tissue itself', N''),
( N'Q1369011', N'familial adenomatous polyposis', N'autosomal dominant disease that is has material basis in mutations in the APC gene and involves formation of numerous polyps in the epithelium of the large intestine which are initially benign and later transform into colon cancer', N''),
( N'Q1369020', N'von Economos disease', N'atypical form of encephalitis', N''),
( N'Q1374020', N'somatization disorder', N'somatoform disorder that involves persistently complaints of varied physical symptoms that have no identifiable physical origin.', N''),
( N'Q137597', N'Ancylostoma duodenale ancylostomiasis', N'disease of humans and animals caused by parasitic worms known as ankylostoids.', N''),
( N'Q1378675', N'panophthalmitis', N'Human disease', N''),
( N'Q1378921', N'euthyroid sick syndrome', N'Secondary allostasis of thyroid function in fetal life, starving and in critical illness', N''),
( N'Q1384176', N'exostosis', N'hyperostosis that involves formation of new bone on the surface of preexisting bone', N''),
( N'Q1385411', N'extrapyramidal symptoms', N'drug-induced movement disorders', N''),
( N'Q138885', N'travelers diarrhea', N'disease', N''),
( N'Q1393463', N'hypopharynx cancer', N'pharynx cancer that is located in the hypopharynx', N''),
( N'Q1393718', N'hemophilia C', N'human disease', N''),
( N'Q1393725', N'factor XIII deficiency', N'Human disease', N''),
( N'Q1395332', N'familial hypocalciuric hypercalcemia', N'hypercalcemia characterized byautosomal dominant inheritance with elevation of serum calcium levels and decreased urinary calcium excretion', N''),
( N'Q1396345', N'Farber lipogranulomatosis', N'extremely rare autosomal recessive lysosomal storage disease marked by a deficiency in the enzyme ceramidase', N''),
( N'Q1396859', N'farmers lung', N'An extrinsic allergic alveolitis which is induced by the inhalation of spores (Aspergillus sp and thermophilic actinomycetes) in dust from moldy hay or straw. It is characterized by sudden onset, fever, cough, expectoration, and breathlessness.', N''),
( N'Q1399155', N'Fazio-Londe disease', N'a very rare inherited motor neuron disease of children and young adults', N''),
( N'Q1399182', N'facioscapulohumeral muscular dystrophy', N'Muscular dystrophy that classically weakens the muscles of the face (facio), shoulder girdle (scapulo) and upper arm (humerus). Weakness usually is asymmetrical and develops in other areas of the body as well, such as the abdomen and shin.', N''),
( N'Q1399293', N'Binswangers disease', N'form of small vessel vascular dementia caused by damage to the white brain matter', N''),
( N'Q1399440', N'Fechtner syndrome', N'genetic disorder', N''),
( N'Q1401065', N'oculocutaneous albinism type 1', N'', N''),
( N'Q1402851', N'chorioretinitis', N'inflammation of the choroid', N''),
( N'Q1403045', N'multiple acyl-CoA dehydrogenase deficiency', N'Human disease', N''),
( N'Q1404470', N'Feltys syndrome', N'syndrome that results in rheumatoid arthritis, splenomegaly and neutropenia', N''),
( N'Q1406803', N'tonic–clonic seizure', N'type of generalized seizure', N''),
( N'Q1409081', N'fetal nicotine spectrum disorder', N'specific developmental disorder that is characterized by physical, behavioral and learning birth defects resulting from maternal ingestion of nicotine during pregnancy', N''),
( N'Q1409160', N'twin-to-twin transfusion syndrome', N'complication of disproportionate blood supply, resulting in high morbidity and mortality', N''),
( N'Q1410673', N'tarsal tunnel syndrome', N'compression neuropathy and painful foot condition in which the tibial nerve is compressed as it travels through the tarsal tunnel', N''),
( N'Q1410808', N'breast fibroadenoma', N'breast benign neoplasm comprised of fibrous and glandular tissues', N''),
( N'Q1410831', N'fibrodysplasia ossificans progressiva', N'extremely rare connective tissue disease', N''),
( N'Q1410851', N'fibromatosis', N'poorly defined neoplasm arising from the soft tissues', N''),
( N'Q1410864', N'fibrous dysplasia of bone', N'bone remodeling disease that results in the destruction of normal bone and replacing it with fibrous bone tissue', N''),
( N'Q1411740', N'histiocytosis', N'lymphatic system disease that is characterized by an excessive number of histiocytes', N''),
( N'Q1412657', N'petechia', N'small red or purple spot on the skin or conjunctiva', N''),
( N'Q1413860', N'siderosis', N'deposition of excess iron in body tissue', N''),
( N'Q141440', N'brain abscess', N'abscess caused by inflammation and collection of infected material in the brain', N''),
( N'Q1414480', N'paraphimosis', N'medical condition in which the foreskin of a penis becomes trapped behind the glans penis', N''),
( N'Q1414805', N'systemic disease', N'systemic disease is one that affects a number of organs and tissues, or affects the body as a whole', N''),
( N'Q1415275', N'spinal cord injury', N'injury to the spine on the back side of humans', N''),
( N'Q1415842', N'Norrie disease', N'genetic disorder that primarily affects the eye and almost always leads to blindness', N'')
GO