INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q2059267', N'tinea nigra', N'superficial fungal infection that causes dark brown to black painless patches on the palms of the hands and the soles of the feet', N''),
( N'Q2059411', N'black piedra', N'superficial mycosis that is a superficial fungal infection of the hair shaft caused by Piedraia hortae', N''),
( N'Q2060353', N'Bulbar palsy', N'', N''),
( N'Q2062483', N'rectal prolapse', N'rectal walls have prolapsed to a degree where they protrude out the anus and are visible outside the body', N''),
( N'Q2064603', N'pleomorphic adenoma', N'gastrointestinal benign neoplasm that is a located in the salivary glands', N''),
( N'Q2065747', N'apparent mineralocorticoid excess syndrome', N'Human disease', N''),
( N'Q2067052', N'Giant-cell tumor of the tendon sheath', N'Human disease', N''),
( N'Q2067267', N'Niemann–Pick disease, type C', N'autosomal recessive lipid storage disorder that is characterized by accumulation of cholesterol and sphingomyelins in cells of the viscera and the central nervous system', N''),
( N'Q2068039', N'peliosis hepatis', N'Human disease', N''),
( N'Q206866', N'diseases of affluence', N'diseases and other health conditions thought to be result of wealth', N''),
( N'Q2068896', N'drug allergy', N'human disease', N''),
( N'Q206901', N'amyotrophic lateral sclerosis', N'neurodegenerative disease characterized by progressive muscular paralysis', N''),
( N'Q2069207', N'familial dysbetalipoproteinemia', N'Human disease', N''),
( N'Q2069545', N'Kimura disease', N'Human disease', N''),
( N'Q2070695', N'macrocytic anemia', N'Human disease', N''),
( N'Q20707611', N'aphantasia', N'condition where one does not possess a functioning minds eye and cannot voluntarily visualize imagery', N''),
( N'Q2070842', N'perichondritis of auricle', N'Human disease', N''),
( N'Q207087', N'ectopic pregnancy', N'female reproductive system disease characterized by the implantation of the embryo outside the uterine cavity', N''),
( N'Q207092', N'erysipelas', N'human disease', N''),
( N'Q207133', N'Klinefelters syndrome', N'Human disease', N''),
( N'Q2072063', N'patent ductus arteriosus', N'condition wherein the ductus arteriosus fails to close after birth', N''),
( N'Q2072821', N'capillary hemangioma', N'most common variant of hemangioma, dull red, firm, dome-shaped hemangioma, usually located on the head and neck, which grows rapidly caused by proliferation of immature capillary vessels', N''),
( N'Q20736878', N'Harrison Syndrome', N'', N''),
( N'Q2074059', N'oculomotor apraxia', N'The absence or defect of controlled, voluntary, and purposeful eye movement', N''),
( N'Q2075261', N'myocardial stunning', N'state when some section of the myocardium (corresponding to area of a major coronary occlusion) shows a form of contractile abnormality', N''),
( N'Q2076733', N'El Tor', N'Human disease', N''),
( N'Q207791', N'fetishism', N'sexual arousal a person receives from an object or situation', N''),
( N'Q207855', N'amblyopia', N'Human disease', N''),
( N'Q208166', N'borderline personality disorder', N'personality disorder characterized by variability of moods and unstable relationships', N''),
( N'Q2084035', N'nail disease', N'integumentary system disease that is located in nail', N''),
( N'Q208414', N'lymphoma', N'hematologic cancer that affects lymphocytes that reside in the lymphatic system and in blood-forming organs', N''),
( N'Q2085267', N'pharyngitis', N'inflammation of the pharynx', N''),
( N'Q208562', N'Marfan syndrome', N'genetic disorder of the connective tissue', N''),
( N'Q2086442', N'B-cell prolymphocytic leukemia', N'A neoplasm of prolymphocytes affecting the blood, bone marrow, and spleen. It is characterized by prolymphocytes exceeding 55% of the lymphoid cells in the blood and profound splenomegaly.', N''),
( N'Q2087205', N'prediabetes syndrome', N'a predisease state of hyperglycemia with high risk for diabetes', N''),
( N'Q208726', N'anogenital venereal wart', N'sexually transmitted disease', N''),
( N'Q2088972', N'Phototoxicity', N'An agent that renders the skin susceptible to damage (as sunburn or blisters) upon exposure to light and especially ultraviolet light.', N''),
( N'Q2089599', N'phaeohyphomycosis', N'human disease', N''),
( N'Q2089854', N'hemosiderosis', N'iron metabolism disease that has material basis in an accumulation of hemosiderin, an iron-storage complex, resulting in iron overload', N''),
( N'Q2090167', N'plasmacytoma', N'plasma cell dyscrasia in which a plasma cell tumour grows within soft tissue or within the axial skeleton', N''),
( N'Q209049', N'chromosome 1q21.1 deletion syndrome', N'Human disease', N''),
( N'Q2090711', N'thelaziasis', N'Human disease', N''),
( N'Q2092064', N'hemophilia A', N'X-linked disease that has material basis in Factor VIII deficiency, which results in the formation of fibrin deficient clots which makes coagulation much more prolonged', N''),
( N'Q209369', N'Hodgkin lymphoma', N'lymphoma that is marked classically by the presence of Reed-Sternberg cells', N''),
( N'Q209522', N'binge-eating disorder', N'an eating disorder characterized by frequent and recurrent binge eating episodes with associated negative psychological and social problems, but without subsequent purging episodes', N''),
( N'Q2095252', N'pilocytic astrocytoma', N'astrocytoma that is characterized by cells that look like fibers when viewed under a microscope and is located in the brain', N''),
( N'Q2095567', N'Pinealoblastoma', N'pineal gland neoplasm located in the brain', N''),
( N'Q209647', N'delirium tremens', N'rapid onset of confusion caused by alcohol withdrawal; usually lasts for 2–3 days; symptoms include nightmare, agitation, global confusion, disorientation, hallucination, fever, high blood pressure, heavy sweating', N''),
( N'Q2096745', N'hereditary angioedema', N'Hereditary angioedema (HAE) is a genetic disease characterized by the occurrence of transitory and recurrent subcutaneous and/or submucosal edemas resulting in swelling and/or abdominal pain', N''),
( N'Q209733', N'chronic fatigue syndrome', N'medical condition involving extreme fatigue and a wide range of other symptoms', N''),
( N'Q2099138', N'placental insufficiency', N'placenta disease that is characterized by insufficient blood flow to the placenta during pregnancy', N''),
( N'Q2099945', N'sudden death in athletes', N'natural, unexpected death from cardiac arrest of athletes', N''),
( N'Q21014372', N'microhydranencephaly', N'severe abnormality of brain development characterized by both microcephaly and hydranencephaly', N''),
( N'Q2103933', N'REM sleep behavior disorder', N'sleep disorder that involves abnormal behavior including the acting out of violent or dramatic dreams during the sleep phase with rapid eye movement', N''),
( N'Q210427', N'cerebral palsy', N'a group of permanent movement disorders that appear in early childhood', N''),
( N'Q2105535', N'porcelain gallbladder', N'calcification of the gallbladder believed to be brought on by excessive gallstones', N''),
( N'Q2106232', N'Postanesthetic shivering', N'', N''),
( N'Q2106329', N'Post-traumatic embitterment disorder', N'proposed disorder', N''),
( N'Q21097855', N'spinocerebellar ataxia type 1', N'Spinocerebellar ataxia type 1 (SCA1) is a subtype of type I autosomal dominant cerebellar ataxia (ADCA type I; see this term) characterized by dysarthria, writing difficulties, limb ataxia, and commonly nystagmus and saccadic abnormalities', N''),
( N'Q21124512', N'hypoparathyroidism-retardation-dysmorphism syndrome', N'Human disease', N''),
( N'Q2112703', N'prolapse', N'protrusion of an organ in into a natural or artificial orifice', N''),
( N'Q2112719', N'prolymphocytic leukemia', N'Human disease', N''),
( N'Q21127479', N'Cole-Carpenter syndrome', N'osteogenesis imperfecta characterized by craniosynostosis, communicating hydrocephalus, ocular proptosis, marked postnatal growth failure, and distinctive facial appearance', N''),
( N'Q2113512', N'Proteopathy', N'disease', N''),
( N'Q21154057', N'chromosome 15q11.2 deletion syndrome', N'human disease', N''),
( N'Q2115771', N'pseudopterygium', N'Human disease', N''),
( N'Q2119633', N'pyoderma', N'any skin disease involving pus', N''),
( N'Q212021', N'kleptomania', N'impulse control disorder that involves the repeated impulse to steal for no great gain, when the perpetrator has sufficient money to pay for the item and no need for what is stolen', N''),
( N'Q2123641', N'spondyloepimetaphyseal dysplasia, Strudwick type', N'Human disease', N''),
( N'Q212961', N'pancreatic cancer', N'endocrine gland cancer located in the pancreas', N''),
( N'Q213098', N'progeria', N'genetic disorder that causes early aging', N''),
( N'Q213151', N'kwashiorkor', N'Human disease', N''),
( N'Q2131705', N'Eosinophilic pustular folliculitis of infancy', N'', N''),
( N'Q213600', N'sleep apnea', N'sleep disorder characterized by repeated cessation and commencing of breathing that disrupts sleep', N''),
( N'Q2140130', N'lateral medullary syndrome', N'neurological disorder causing a range of symptoms due to ischemia in the lateral part of the medulla oblongata in the brainstem', N''),
( N'Q2140501', N'glutaric aciduria type 1', N'Glutaryl-CoA dehydrogenase (GCDH) deficiency (GDD) is an autosomal recessive neurometabolic disorder clinically characterized by encephalopathic crises resulting in striatal injury and a severe dystonic dyskinetic movement disorder', N''),
( N'Q2140729', N'fasciolopsiasis', N'A parasitic helminthiasis infectious disease that involves parasitic infection of the intestine by Fasciolopsis buski. The symptoms include diarrhea, abdominal pain, fever, ascites, anasarca and intestinal obstruction.', N''),
( N'Q2141001', N'chilblains', N'medical condition', N''),
( N'Q2141048', N'synostosis', N'dysostosis that results in abnormal fusing of adjacent bones', N''),
( N'Q2142496', N'Silver-Russell syndrome', N'growth disorder', N''),
( N'Q2143688', N'left bundle branch hemiblock', N'cardiac conduction abnormality seen on the electrocardiogram', N''),
( N'Q2144212', N'renal-hepatic-pancreatic dysplasia', N'physical disorder characterized by pancreatic fibrosis, renal dysplasia and hepatic dysgenesis; it is usual fatal soon after birth', N''),
( N'Q2146141', N'Nasal vestibulitis', N'infection of the nasal cavity', N''),
( N'Q21503282', N'episodic ataxia', N'hereditary ataxia characterized by sporadic bouts of ataxia with or without continuous muscle movement', N''),
( N'Q2151267', N'restrictive cardiomyopathy', N'form of cardiomyopathy in which the walls are rigid,and the heart is restricted from stretching and filling with blood properly', N''),
( N'Q21515257', N'necrotizing bronchiolitis', N'medical condition', N''),
( N'Q2151786', N'substance-induced psychosis', N'a psychosis that results from the effects of exogenous toxic substances or drugs', N''),
( N'Q2155008', N'Ritscher–Schinzel syndrome', N'developmental malformation syndrome characterized by craniofacial abnormalities, congenital heart defects, and cerebellar brain malformations.', N''),
( N'Q215509', N'hospital-acquired infection', N'nosocomial Infections', N''),
( N'Q2157462', N'schizophreniform disorder', N'psychotic disorder that involves schizophrenia symptoms over time period of one month', N''),
( N'Q2160802', N'familial nephrotic syndrome', N'Human disease', N''),
( N'Q2161046', N'ainhum', N'Human disease', N''),
( N'Q2161625', N'Teratospermia', N'', N''),
( N'Q2161683', N'Erythema ab igne', N'rash of the skin usually caused by the long-term exposure to heat or infrared radiation', N''),
( N'Q216211', N'hypertrophy', N'increase in the volume of an organ or tissue due to the enlargement of its component cells', N''),
( N'Q2163245', N'congenital diaphragmatic hernia', N'diaphragm disease characterized by the lack of development of all or part of the diaphragm, which results in an abnormal opening that allows the stomach and intestines to move into the chest cavity and crowd the heart and lungs', N''),
( N'Q2165266', N'Nelson syndrome', N'hormonal disorder sometimes resulting from adrenal gland removal', N''),
( N'Q2165399', N'Sezarys disease', N'type of cutaneous lymphoma', N''),
( N'Q2165411', N'spondylitis', N'inflammation of the vertebra', N''),
( N'Q2165663', N'chronic granulomatous disease', N'diverse group of hereditary diseases in which certain cells of the immune system have difficulty forming the reactive oxygen compounds  used to kill certain ingested pathogens.', N''),
( N'Q2166371', N'seborrheic keratosis', N'non-cancerous (benign) skin tumour that originates from cells in the outer layer of the skin', N''),
( N'Q216866', N'conjoined twins', N'identical twins joined in utero', N''),
( N'Q2170663', N'Acrodynia', N'', N''),
( N'Q217519', N'bubonic plague', N'human and animal disease; plague involving the lymphatic system', N''),
( N'Q2179162', N'Miliaria crystallina', N'miliaria that is characterized by clear, superficial, noninflammed, subcorneal vesicles that easily rupture when rubbed and is located in the stratum corneum', N''),
( N'Q218712', N'Zollinger-Ellison syndrome', N'syndrome that is characterized by the development of a one or more tumors (gastrinoma) in the pancreas, duodenum, or both that secrete excessive levels of gastrin, a hormone that stimulates production of acid by the stomach', N''),
( N'Q2188219', N'tooth ankylosis', N'Human disease', N''),
( N'Q219102', N'Cushings syndrome', N'adrenal gland overactivity caused by a tumor of the pituitary gland or by medication', N''),
( N'Q219223', N'lactose intolerance', N'condition in which people have symptoms due to a decreased ability to digest lactose', N''),
( N'Q2195598', N'Transcortical motor aphasia', N'', N''),
( N'Q2195906', N'Marshall–Smith syndrome', N'syndrome that is characterized by advanced bone age, failure to thrive, respiratory problems, dysmorphic facial features, and variable mental retardation', N''),
( N'Q2199494', N'tympanosclerosis', N'condition caused by hyalinization and subsequent calcification of subepithelial connective tissue of TM and middle ear', N''),
( N'Q2200359', N'Sanfilippo syndrome', N'mucopolysaccharidosis characterized by a deficiency of the lysosomal enzyme resulting in incomplete breakdown of the heparan sulfate sugar chain', N''),
( N'Q2200977', N'Miller–Dieker lissencephaly syndrome', N'A syndrome characterized by classical lissencephaly and distinct facial features. Visible and submicroscopic deletions of 17p13.3, including the LIS1 gene, are found in almost 100% of patients.', N''),
( N'Q220188', N'post-polio syndrome', N'Human disease', N''),
( N'Q220193', N'premenstrual syndrome', N'physical and emotional symptoms that occur in the one to two weeks before a womans period.', N''),
( N'Q220322', N'agnosia', N'neurologic sensory disorder', N''),
( N'Q220551', N'diabetes insipidus', N'human disease, a condition characterized by large amounts of dilute urine and increased thirst', N''),
( N'Q220570', N'pulmonary embolism', N'blockage of the main artery of the lung or one of its branches by a substance that has travelled from elsewhere in the body', N''),
( N'Q22115476', N'CLOVES syndrome', N'CLOVE syndrome is characterized by Congenital Lipomatous Overgrowth, progressive, complex and mixed truncal Vascular malformations, and Epidermal nevi', N''),
( N'Q221159', N'schistosomiasis', N'human disease', N''),
( N'Q22132220', N'Hypotrichosis with juvenile macular dystrophy', N'A hypotrichosis that has material basis in a autosomal recessive mutation of CDH3 on chromosome 16q22.1.', N''),
( N'Q2213687', N'sacroiliitis', N'inflammation of pelvis', N''),
( N'Q221441', N'pellagra', N'Human disease', N''),
( N'Q2214419', N'Omenn syndrome', N'Human disease', N''),
( N'Q221463', N'mesenteric ischemia', N'medical condition', N''),
( N'Q221472', N'fragile X syndrome', N'congenital disorder of nervous system', N''),
( N'Q2214869', N'cerebellar hypoplasia', N'rare disorder in which the cerebellum is either missing entirely or is smaller than usual', N''),
( N'Q2215516', N'ideas of reference and delusions of reference', N'belief that certain gestures, environmental cues, innocuous events, comments and so forth are directed at oneself', N''),
( N'Q221668', N'urinary tract infection', N'human and animal infection', N''),
( N'Q222580', N'Microchimerism', N'', N''),
( N'Q223102', N'peritonitis', N'inflammation of the peritoneum, the lining of the inner wall of the abdomen', N''),
( N'Q223254', N'otitis media', N'otitis which involves inflammation of the middle ear', N''),
( N'Q223591', N'gastroesophageal reflux disease', N'disease caused by stomach acid coming up from the stomach into the esophagus', N''),
( N'Q223663', N'epidemic pleurodynia', N'Human disease', N''),
( N'Q223911', N'sarcoma', N'cell type cancer that has material basis in abnormally proliferating cells derived from embryonic mesoderm', N''),
( N'Q2241556', N'enlarged vestibular aqueduct', N'Human disease', N''),
( N'Q224513', N'precocious puberty', N'human disease', N''),
( N'Q2246688', N'pseudoporphyria', N'', N''),
( N'Q2246789', N'neuromuscular disease', N'neuropathy that affect the nerves that control the voluntary muscles', N''),
( N'Q2247373', N'Photophthalmia', N'type of photokeratitis', N''),
( N'Q2248721', N'postviral fatigue syndrome', N'', N''),
( N'Q2249526', N'cerebral hypoxia', N'deprivation of oxygen to the brain', N''),
( N'Q2251669', N'plantar wart', N'viral infectious disease that results in benign epithelial tumors located in skin of the sole or toes of the foot, has material basis in human papillomavirus (types 1, 2, 4 or 63), has symptom lesions that appear on the sole of the foot', N''),
( N'Q2254511', N'associative agnosia', N'agnosia that is a loss of the ability to recognize visual scenes or classes of objects but retain the abilty to describe them', N''),
( N'Q2259421', N'Schnitzler syndrome', N'Human disease', N''),
( N'Q225957', N'dysarthria', N'motor speech disorder', N''),
( N'Q2264130', N'trichuriasis', N'Human helminthiasis', N''),
( N'Q2267451', N'Autoimmune pancreatitis', N'autoimmune disease of endocrine system that is located in the pancreas', N''),
( N'Q2270671', N'intestinal capillariasis', N'human disease', N''),
( N'Q2271749', N'subacute bacterial endocarditis', N'Human disease', N''),
( N'Q2272470', N'Carpenter syndrome', N'acrocephalosyndactylia characterized by craniosynostosis, acrocephaly, obesity, syndactyly and polydactyly', N''),
( N'Q2273662', N'pseudohermaphroditism', N'old clinical term for an organism that is born with primary sex characteristics of one sex but develops the secondary sex characteristics', N''),
( N'Q2276095', N'androgenic alopecia', N'hair loss due to susceptibility of hair follicles to androgenic miniaturization', N''),
( N'Q2279175', N'progressive muscular atrophy', N'A rare, milder form of amyotrophic lateral sclerosis. It is characterized by a slowly progressive clinical course. Signs and symptoms include muscle weakness, atrophy, and fasciculation.', N''),
( N'Q2280106', N'branchiootorenal syndrome', N'autosomal dominant genetic disorder involving the kidneys, ears, and neck', N''),
( N'Q2280285', N'dentatorubral-pallidoluysian atrophy', N'congenital disorder of nervous system', N''),
( N'Q2280692', N'Infantile free sialic acid storage disease', N'human disease', N''),
( N'Q2282783', N'epiretinal membrane', N'disease of the eye in response to changes in the vitreous humor or more rarely, diabetes', N''),
( N'Q2288646', N'Stickler syndrome', N'Stickler syndrome is an inherited vitreoretinopathy characterized by the association of ocular signs with more or less complete forms of Pierre-Robin sequence (see this term), bone disorders, and sensorineural deafness (10% of cases)', N''),
( N'Q2290446', N'idiopathic pulmonary fibrosis', N'chronic, irreversible and ultimately fatal disease characterized by a progressive decline in lung function', N''),
( N'Q22907909', N'premature atrioventricular junctional contraction', N'', N''),
( N'Q2291130', N'hemiparesis', N'weakness of one side of the body', N''),
( N'Q2291208', N'Sjogren-Larsson syndrome', N'autosomal recessive form of ichthyosis apparent at birth', N''),
( N'Q2291593', N'scaphocephaly', N'premature fusion of the sagittal suture', N''),
( N'Q229256', N'dermatitis', N'skin disease', N''),
( N'Q2292945', N'hepatico cancer', N'thyroid carcinoma that is characterized by the small mushroom shape of the tumor which has a stem attached to the epithelial layer', N''),
( N'Q2295338', N'Smith-Magenis syndrome', N'Human disease', N''),
( N'Q22965579', N'Snyder-Robinson syndrome', N'Human disease', N''),
( N'Q22978786', N'Zechi-Ceide Syndrome', N'rare disease', N''),
( N'Q2298020', N'hereditary elliptocytosis', N'hematopoietic system disease characterized by oval or elliptical red blood cells, slight or absent hemolysis with little or no anemia; splenomegaly is often present', N''),
( N'Q2298953', N'hidradenitis', N'Human disease', N''),
( N'Q2299379', N'membranoproliferative glomerulonephritis', N'Human disease', N''),
( N'Q2300099', N'gastrointestinal system disease', N'disease involving the gastrointestinal tract', N''),
( N'Q230047', N'burning mouth syndrome', N'Human disease', N''),
( N'Q2300749', N'separation anxiety disorder', N'anxiety disorder that involves the feeling of excessive and inappropriate levels of anxiety over being separated from a person to whom the individual has a strong emotional attachment or place', N''),
( N'Q23037762', N'fish allergy', N'food allergy triggered by fish', N''),
( N'Q23037783', N'hepatoid adenocarcinoma', N'adenocarcinoma with morphologic characteristics similar to hepatocellular carcinoma, arising from an anatomic site other than the liver', N''),
( N'Q2303951', N'spinal cord disease', N'neurologic deficit related to the spinal cord', N''),
( N'Q2305174', N'alcoholic cardiomyopathy', N'disease in which the chronic long-term abuse of alcohol (i.e., ethanol) leads to heart failure', N''),
( N'Q2306782', N'hypochromic anemia', N'generic term for any type of anemia in which the red blood cells (erythrocytes) are paler than normal', N''),
( N'Q2307256', N'neuritis', N'Inflammation of a nerve or the general inflammation of the peripheral nervous system', N''),
( N'Q2309612', N'sphingolipidosis', N'class of lipid storage disorders relating to sphingolipid metabolism', N''),
( N'Q2310947', N'spinocerebellar ataxia type 13', N'Human disease', N''),
( N'Q2311755', N'splenosis', N'spontaneous transplantation of splenic tissue to unusual sites after open splenic trauma', N''),
( N'Q2312030', N'discitis', N'Human disease', N''),
( N'Q231578', N'obsessive-compulsive personality disorder', N'personal perfectionism at the cost of flexibility, openness, efficiency & effect on others', N''),
( N'Q2323502', N'variant Creutzfeldt–Jakob', N'degenerative brain disease caused by prions', N''),
( N'Q2325206', N'Eosinophilic fasciitis', N'form of fasciitis, the inflammatory diseases that affect the fascia, the connective tissues surrounding muscles, blood vessels and nerves', N''),
( N'Q2325854', N'Riley-Day syndrome', N'hereditary sensory and autonomic neuropathy type III (HSAN-III), is a disorder of the autonomic nervous system which affects the development and survival of sensory', N''),
( N'Q2329041', N'asthenozoospermia', N'', N''),
( N'Q2332125', N'staphyloma', N'', N''),
( N'Q233309', N'brain neoplasm', N'neoplasm in the brain', N''),
( N'Q2334877', N'nutmeg liver', N'Human disease', N''),
( N'Q2336873', N'Jobs syndrome', N'autosomal dominant form called Jobs syndrome or Buckley syndrome, is a heterogeneous group of immune disorders', N''),
( N'Q2338307', N'depersonalization disorder', N'dissociative disorder in which the sufferer is affected by persistent or recurrent feelings of depersonalization and/or derealization', N''),
( N'Q2339038', N'neurogenic bladder', N'Human disease', N''),
( N'Q2343082', N'stenosis', N'Abnormal narrowing of a blood vessel or other tubular organ or structure. It is also sometimes called a stricture.', N''),
( N'Q2346415', N'meningoencephalitis', N'central nervous system disease that involves encephalitis which occurs along with meningitis', N''),
( N'Q2346980', N'absence seizure', N'generalized seizure characterized by a brief loss and return of consciousness, generally not followed by a period of lethargy', N''),
( N'Q2348105', N'Coffin-Siris syndrome', N'genetic disease that is characterized by underdevelopment of the tips of fingers or toes, underdevelopment or abscense of finger or toe nails and developmental disability', N''),
( N'Q2348506', N'Aleutian disease', N'disease of mustelids caused by a highly contagious parvovirus (carnivore amdoparvovirus 1)', N''),
( N'Q2349546', N'Canavan disease', N'neurodegenerative disorder; its spectrum varies between severe forms with leukodystrophy, macrocephaly and severe developmental delay, and a very rare mild/juvenile form characterized by mild developmental delay', N''),
( N'Q2349695', N'familial lipoprotein lipase deficiency', N'familial hyperlipemia characterized by a deficiency of the enzyme lipoprotein lipase and the subsequent build up of chylomicrons and increased plasma concentration of triglycerides', N''),
( N'Q2351083', N'metabolic disease', N'disease that involving errors in metabolic processes of building or degradation of molecules', N''),
( N'Q23542366', N'Warsaw breakage syndrome', N'Human disease', N''),
( N'Q23542368', N'mitochondrial complex II deficiency', N'Human disease', N''),
( N'Q2356131', N'Unverricht-Lundborg syndrome', N'Human disease', N''),
( N'Q2357409', N'struma ovarii', N'rare form of monodermal teratoma that contains mostly thyroid tissue, which may cause hyperthyroidism', N''),
( N'Q2360849', N'strongyloidiasis', N'Human helminthiasis', N''),
( N'Q2365426', N'Acneiform eruption', N'medical condition', N''),
( N'Q2373361', N'tree nut allergy', N'Allergic reaction to tree nuts that is triggered by the immune system', N''),
( N'Q2373700', N'clostridial necrotizing enteritis', N'Human disease', N''),
( N'Q2375956', N'blind loop syndrome', N'intestinal disease characterized by a dysbalance of the bacterial flora of the small intestine, causing derangement to the normal physiological processes of digestion and absorption', N''),
( N'Q2376264', N'synucleinopathy', N'neurodegenerative disease', N''),
( N'Q2376518', N'syringoma', N'Human disease', N''),
( N'Q23807991', N'Ribosomopathy', N'', N''),
( N'Q23808025', N'auditory arrhythmia', N'inability to replicate musical or rhythmic patterns', N''),
( N'Q23808336', N'fungal sinusitis', N'Inflammation of the paranasal sinuses due to fungal infection', N''),
( N'Q2384391', N'occupational dermatitis', N'Human disease', N''),
( N'Q2385892', N'Astasis', N'', N''),
( N'Q2388598', N'Ollier disease', N'rare nonhereditary sporadic disorder', N''),
( N'Q239027', N'calcinosis', N'calcium metabolism disease that is the result of the formation of calcium deposits in any soft tissue', N''),
( N'Q2397009', N'choroideremia', N'rare, X-linked recessive form of hereditary retinal degeneration', N''),
( N'Q2397106', N'tauopathy', N'neurodegenerative disease caused by tau protein aggregates', N''),
( N'Q239848', N'dumping syndrome', N'Human disease', N''),
( N'Q24026721', N'excess skin', N'', N''),
( N'Q2403156', N'vasomotor rhinitis', N'non-allergic rhinitis', N''),
( N'Q2406697', N'Tetra-amelia', N'human disease', N''),
( N'Q2411095', N'Char syndrome', N'patent ductus arteriosus with facial dysmorphism and abnormal fifth digits', N''),
( N'Q241827', N'Upper airway resistance syndrome', N'', N''),
( N'Q2420648', N'ocular cancer', N'sensory system cancer located in the eye that is characterized by uncontrolled cellular proliferation in the eye', N''),
( N'Q2423084', N'Agrammatism', N'', N''),
( N'Q2425407', N'acute kidney tubular necrosis', N'medical condition involving the death of tubular epithelial cells that form the renal tubules of the kidneys', N''),
( N'Q243257', N'chikungunya', N'infection caused by the chikungunya virus', N''),
( N'Q2435687', N'tinea imbricata', N'tinea corporis that results in fungal infection located in skin, has material basis in Trichophyton concentricum, which is characterized by ring-like growth in overlapping circles that may have an autosomal dominant genetic predisposition', N''),
( N'Q2435699', N'tinea manuum', N'dermatophytosis that results in fungal skin infection located in hand, has material basis in Ascomycota fungi that belong to a group called dermatophytes and has symptom itching, has symptom burning, has symptom cracking, and has symptom scaling', N''),
( N'Q2438516', N'reactive airway disease', N'', N''),
( N'Q2443552', N'trypanosomiasis', N'human disease', N''),
( N'Q244438', N'prosopagnosia', N'Face blindness - the inability to recognize familiar faces', N''),
( N'Q2444886', N'retinal vascular occlusion', N'Human disease', N''),
( N'Q2449188', N'Transient epileptic amnesia', N'', N''),
( N'Q2450598', N'infective endocarditis', N'endocarditis that is characterized by inflammation of the endocardium caused by infectious agents.', N''),
( N'Q2453464', N'colitis', N'inflammation of the colon or the large intestine', N''),
( N'Q245455', N'chromosome 5q deletion syndrome', N'human disease', N''),
( N'Q2454612', N'fourth cranial nerve palsy', N'Human disease', N''),
( N'Q2455180', N'recurrent corneal erosion', N'Human disease', N''),
( N'Q245590', N'cyclothymia', N'persistent instability of mood that involves recurrent hypomanic and dysthymic episodes, but no full manic episodes or full major depressive episodes', N''),
( N'Q2456424', N'median arcuate ligament syndrome', N'Human disease', N''),
( N'Q2457358', N'medial epicondylitis', N'bone inflammation disease that results in inflammation located in epicondyle', N''),
( N'Q2458539', N'skin infection', N'skin disease caused by bacteria, fungi, parasites, or viruses', N''),
( N'Q246002', N'polycystic liver disease', N'human disease', N''),
( N'Q2460356', N'delusional misidentification syndrome', N'psychopathological syndrome', N''),
( N'Q246040', N'congenital cystic adenomatoid malformation', N'congenital disorder of respiratory system', N''),
( N'Q246068', N'cysticercosis', N'Human helminthiasis', N''),
( N'Q246070', N'cystadenoma', N'adenoma that is a cystic', N''),
( N'Q246084', N'cystitis', N'human disease', N''),
( N'Q2463884', N'cervicitis', N'inflammation of the uterine cervix', N''),
( N'Q2465347', N'thyroid adenoma', N'Human disease', N''),
( N'Q2466106', N'reticular erythematous mucinosis', N'', N''),
( N'Q2466723', N'gummatous syphilis', N'A tertiary syphilis that is characterized by granulomatous lesions, called gummas, which are characterized by a center of necrotic tissue with a rubbery texture. They form in the liver, bones, and testes but may affect any organ.', N''),
( N'Q2467739', N'Donohue syndrome', N'Human disease', N''),
( N'Q2470609', N'Wagners disease', N'Wagner disease is a rare hereditary vitreoretinopathy characterized by an anomaleous vitreous associated with myopia, cataract, chorioretinal atrophy, and peripheral tractional or rhegmatogenous retinal detachment', N''),
( N'Q247096', N'paracoccidioidomycosis', N'primary systemic mycosis that results in systemic fungal infection located in mucosa, located in lymph nodes, located in bone, located in skin or located in lungs, has material basis in Paracoccidioides brasiliensis', N''),
( N'Q247131', N'hepatorenal syndrome', N'Human disease', N''),
( N'Q2471453', N'Psychogenic disease', N'', N''),
( N'Q2475919', N'subacute sclerosing panencephalitis', N'rare insidious sequela from measles infection', N''),
( N'Q2477062', N'cardiogenic shock', N'type of circulatory shock resulting from inadequate blood flow due to the dysfunction of the ventricles of the heart', N''),
( N'Q247978', N'anisometropia', N'Human disease', N''),
( N'Q2484592', N'Becker muscular dystrophy', N'X-linked recessive inherited disorder characterized by slowly progressive muscle weakness of the legs and pelvis', N''),
( N'Q2495736', N'chronic headache', N'', N''),
( N'Q24963765', N'long-chain 3-hydroxyacyl-coenzyme A dehydrogenase deficiency', N'', N''),
( N'Q2496447', N'obstetrical hemorrhage', N'heavy bleeding in pregnancy', N''),
( N'Q24975353', N'Wiedemann-Steiner syndrome', N'hereditary disease', N''),
( N'Q24975366', N'caspase-8 deficiency', N'autoimmune lymphoproliferative syndrome that has material basis in homozygous mutation in the CASP8 gene on chromosome 2q33', N''),
( N'Q24975389', N'Tuberculous dactylitis', N'', N''),
( N'Q24975453', N'Neutrophil-specific granule deficiency', N'human disease', N''),
( N'Q24975487', N'Sickle cell-beta thalassemia', N'', N''),
( N'Q24975503', N'13q deletion syndrome', N'', N''),
( N'Q24975507', N'DOCK8 deficiency', N'', N''),
( N'Q24975508', N'Juvenile nephronophthisis', N'', N''),
( N'Q24975519', N'Warfarin resistance', N'', N''),
( N'Q24975528', N'Alpha-aminoadipic and alpha-ketoadipic aciduria', N'human disease', N''),
( N'Q24975607', N'MECP2 duplication syndrome', N'Human disease', N''),
( N'Q24975699', N'citrullinemia type I', N'', N''),
( N'Q2500124', N'lipoid proteinosis', N'rare recessive genetic disorder', N''),
( N'Q2500965', N'urogenital tuberculosis', N'extrapulmonary tuberculosis that is located in urogenital system', N''),
( N'Q2501186', N'transitional cell carcinoma', N'carcinoma that derives from transitional epithelial cells', N''),
( N'Q250354', N'Prune belly syndrome', N'congenital disorder of urinary system', N''),
( N'Q250365', N'Parry–Romberg syndrome', N'a rare disease characterized by progressive shrinkage and degeneration of the tissues beneath the skin, usually on only one side of the face (hemifacial atrophy) but occasionally extending to other parts of the body', N''),
( N'Q2504473', N'fissured tongue', N'benign condition characterized by deep grooves (fissures) in the dorsum of the tongue', N''),
( N'Q250449', N'alpha-mannosidosis', N'lysosomal storage disease that has material basis in deficiency of the alpha-D-manosidase enzyme resulting in the impairment of cell function from a build up of complex sugars derived from glycoproteins in the lysosome', N''),
( N'Q2507106', N'dental pulp necrosis', N'Human disease', N''),
( N'Q2507454', N'adrenal insufficiency', N'human disease', N''),
( N'Q25091541', N'Lymphatogenous metastasis', N'', N''),
( N'Q25091637', N'Prostatorrhea', N'', N''),
( N'Q2509220', N'blood cancer', N'tumor that affect the blood, bone marrow, lymph, and lymphatic system', N''),
( N'Q25111468', N'Retrocuspid papilla', N'', N''),
( N'Q25111656', N'Xia-Gibbs Syndrome', N'An autosomal dominant non-syndromic intellectual disability that has material basis in an autosomal dominant mutation of AHDC1 on chromosome 1p36.1-p35.3.', N''),
( N'Q2517861', N'brachial plexus lesion', N'brachial plexus neuropathy characterized by an abnormality, usually caused by disease or trauma, located in the brachial plexus', N''),
( N'Q2521341', N'pitted keratolysis', N'bacterial skin infection of the foot', N''),
( N'Q2521747', N'adamantinoma', N'bone cancer that is located in almost exclusively in the long bones', N''),
( N'Q2528129', N'paragonimiasis', N'food-borne parasitic infection caused by the lung fluke, most commonly Paragonimus westermani', N''),
( N'Q2529980', N'bird fanciers lung', N'extrinsic allergic alveolitis which is caused by inhalation of antigens from avian excreta, symptoms are abrupt onset of dyspnea, cough, malaise, and fever after exposure to antigen', N''),
( N'Q25303605', N'Hypertensive crisis', N'', N''),
( N'Q25303958', N'floppy eyelid syndrome', N'', N''),
( N'Q25324086', N'diverticular disease', N'', N''),
( N'Q25324166', N'Isolated congenital asplenia', N'Rare human disease', N''),
( N'Q25324175', N'Gomez and López-Hernández syndrome', N'', N''),
( N'Q25324223', N'Peritoneal inclusion cyst', N'', N''),
( N'Q25324230', N'pancreatic cyst', N'', N''),
( N'Q25324253', N'Congenital bilateral perisylvian syndrome', N'human disease', N''),
( N'Q25324661', N'ataxia-pancytopenia syndrome', N'human disease', N''),
( N'Q2532540', N'Birt-Hogg-Dube syndrome', N'human autosomal dominant genetic disorder that can cause susceptibility to kidney cancer, renal and pulmonary cysts', N''),
( N'Q25327023', N'Hemoglobin J', N'', N''),
( N'Q253332', N'Brill-Zinsser disease', N'epidemic typhus that is a mild form of the disease, which recurs in someone after a long period of latency due to immunosuppression, malnutrition or other illnesses', N''),
( N'Q2533616', N'Rhinophyma', N'condition causing development of a large, bulbous nose associated with granulomatous infiltration, commonly due to untreated rosacea', N''),
( N'Q25339127', N'diffuse intrinsic pontine glioma', N'brainstem tumor', N''),
( N'Q25339136', N'BENTA disease', N'human disease', N''),
( N'Q25339349', N'Familial hyperaldosteronism', N'Genetic hyperaldosteronism', N''),
( N'Q25339739', N'AntiMOG associated encephalomyelitis', N'inflammatory demyelinating disease previously considered part of the multiple sclerosis spectrum', N''),
( N'Q25344755', N'Spondylo-ocular syndrome', N'', N''),
( N'Q25379699', N'Hurler syndrome', N'genetic disorder that results in the buildup of glycosaminoglycans (AKA GAGs, or mucopolysaccharides) due to a deficiency of alpha-L iduronidase', N''),
( N'Q2544879', N'Tricuspid valve stenosis', N'valvular heart disease which results in the narrowing of the orifice of the tricuspid valve of the heart', N''),
( N'Q2544887', N'chronic atrophic rhinitis', N'rare disease of the nasal mucosa', N''),
( N'Q25451213', N'Jokela type spinal muscular atrophy', N'A neuromuscular disease', N''),
( N'Q2546232', N'Plagiocephaly', N'distortion of the skull', N''),
( N'Q2551272', N'hypereosinophilic syndrome', N'unexplained chronic eosinophila', N''),
( N'Q2553422', N'POEMS syndrome', N'rare paraneoplastic syndrome caused by a clone of aberrant plasma cells', N''),
( N'Q2555537', N'Lacunar amnesia', N'AMNESIA LACUNAR', N''),
( N'Q2555727', N'arrhythmogenic right ventricular cardiomyopathy', N'intrinsic cardiomyopathy that is characterized by hypokinetic areas involving the free wall of the right ventricle, with fibrofatty replacement of the right ventricular myocardium, with associated arrhythmias originating in the right ventricle', N''),
( N'Q2556242', N'exotropia', N'form of strabismus where the eyes are deviated outward', N''),
( N'Q2556531', N'Weissenbacher-Zweymuller syndrome', N'human disease', N''),
( N'Q2557206', N'scimitar syndrome', N'Human disease', N''),
( N'Q2558350', N'Cracked nipple', N'painful, postpartum condition in breastfeeding women', N''),
( N'Q2558586', N'angiostrongyliasis', N'parasitic helminthiasis infectious disease that involves parasitic infection of the intestine, central nervous system and eyes by Angiostrongylus cantonensis or Angiostrongylus costaricensis', N''),
( N'Q2562598', N'hemophilia B', N'An inherited blood coagulation disease that has material basis in Factor IX deficiency, which makes coagulation much more prolonged. The disease is inherited as an X-linked recessive trait.', N''),
( N'Q2563414', N'cervical incompetence', N'cervix disease that is characterized by the beginning of dilation and effacement of a pregnant womans cervix before her pregnancy has reached term', N''),
( N'Q2565270', N'hydranencephaly', N'congenital disorder of nervous system', N''),
( N'Q256806', N'esthesioneuroblastoma', N'rare cancer of the nasal cavity', N''),
( N'Q2578247', N'juvenile myelomonocytic leukemia', N'Human disease', N''),
( N'Q2580627', N'Masked depression', N'', N''),
( N'Q2581333', N'post-concussion syndrome', N'organic brain syndrome that occurs following head trauma (i.e. concussion)', N''),
( N'Q2583311', N'tabes dorsalis', N'slow degeneration (specifically, demyelination) of the neural tracts primarily in the dorsal columns (posterior columns) of the spinal cord (the portion closest to the back of the body) and dorsal roots', N''),
( N'Q2583514', N'Argentine hemorrhagic fever', N'Human disease', N''),
( N'Q258858', N'bladder exstrophy', N'congenital disorder of urinary system', N''),
( N'Q2589418', N'pasteurellosis', N'Human disease', N''),
( N'Q2590966', N'cutaneous leishmaniasis', N'leishmaniasis that involves skin infection caused by Leishmania species, resulting in one or more cutaneous lesions', N''),
( N'Q2596039', N'hepatic hemangioma', N'non-cancerous tumor of the liver', N''),
( N'Q259626', N'aspergillosis', N'infectious disease of humans, birds and other animals', N''),
( N'Q259765', N'SADDAN', N'autosomal dominant disease characterized by severe achondroplasia, developmental delay and acanthosis nigricans that has material basis in heterozygous mutation in the FGFR3 gene on chromosome 4p16', N''),
( N'Q2602467', N'cerebrotendinous xanthomatosis', N'autosomal recessive form of xanthomatosis.', N''),
( N'Q2602725', N'Jessners lymphocytic infiltration of the skin', N'Jessner lymphocytic infiltration of the skin (JLIS) is a chronic benign cutaneous disease characterized by asymptomatic non-scaly erythematous papules or plaques on the face and neck', N''),
( N'Q2603200', N'viral pneumonia', N'pneumonia described as an inflammatory illness of the lung commonly caused by viruses such as influenza virus, parainfluenza, adenovirus, rhinovirus, herpes simplex virus, respiratory syncytial virus, hantavirus, and cytomegalovirus', N''),
( N'Q2605012', N'Kearns-Sayre syndrome', N'spontaneous occuring or inherited mitochondrial myopathy with a typical onset before 20 years of age', N''),
( N'Q2606101', N'paranoid schizophrenia', N'schizophrenia that involves delusions or auditory hallucinations of persecution or being plotted against without thought disorder, disorganized behavior, or affective flattening', N''),
( N'Q260688', N'Periampullary cancer', N'', N''),
( N'Q2608695', N'movement disorders', N'clinical syndromes with either an excess of movement or a paucity of voluntary and involuntary movements', N''),
( N'Q2610084', N'sideroblastic anaemia P', N'aplastic anemia where the bone marrow produces ringed sideroblasts rather than healthy red blood cells (erythrocytes)', N''),
( N'Q261327', N'thrombosis', N'vascular disease caused by the formation of a blood clot inside a blood vessel, obstructing the flow of blood through the circulatory system', N''),
( N'Q2613277', N'Alpha-thalassemia mental retardation syndrome', N'alpha thalassemia that has material basis in mutation in the ATRX gene on Xq21', N''),
( N'Q2619091', N'angiosarcoma', N'malignant Vascular tumor that results in rapidly proliferating, extensively infiltrating anaplastic cells derives from blood vessels and derived from the lining of irregular blood-filled spaces', N''),
( N'Q2619315', N'synovial sarcoma', N'synovium cancer which develops in the synovial membrane of the joints', N''),
( N'Q2622199', N'upper respiratory tract infection', N'illness caused by an acute infection in including the nose, sinuses, pharynx, or larynx', N''),
( N'Q2625993', N'Latrodectism', N'illness caused by the bite of Latrodectus spiders (the black widow spider and related species)', N''),
( N'Q2626074', N'diffuse large B-cell lymphoma', N'cancer of B cells presenting as an aggressive tumour', N''),
( N'Q2626291', N'Postorgasmic illness syndrome', N'Human disease', N''),
( N'Q2627467', N'dissociative disorder', N'disease of mental health in which the normally well-integrated functions of memory, identity, perception, or consciousness are separated (dissociated)', N''),
( N'Q2628677', N'Marinesco-Sjogren syndrome', N'Marinesco-Sjogren syndrome (MSS) belongs to the group of autosomal recessive cerebellar ataxias. Cardinal features of MSS are cerebellar ataxia, congenital cataract, and delayed psychomotor development.', N''),
( N'Q2632078', N'Proctalgia fugax', N'variant of levator ani syndrome', N''),
( N'Q2632848', N'alternating hemiplegia of childhood', N'hemiplegia characterized by recurrent episodes of temporary weakness or complete paralysis on one or both sides of the body', N''),
( N'Q2633143', N'abnormal uterine bleeding', N'', N''),
( N'Q2633267', N'atypical pneumonia', N'type of pneumonia not caused by one of the pathogens most commonly associated with the disease', N''),
( N'Q2637111', N'gingival overgrowth', N'Human disease', N''),
( N'Q2638851', N'oligospermia', N'semen with abnormally low concentration of sperm', N''),
( N'Q264118', N'acute myeloid leukemia', N'myeloid leukemia that is characterized by the rapid growth of abnormal white blood cells that accumulate in the bone marrow and interfere with the production of normal blood cells', N''),
( N'Q26492825', N'Sengers syndrome', N'Human disease', N''),
( N'Q265420', N'blackwater fever', N'human disease', N''),
( N'Q2657784', N'atypical depressive disorder', N'depression characterized by improved mood in response to positive events', N''),
( N'Q265936', N'Kawasaki disease', N'Human disease in which blood vessels throughout the body become inflamed', N''),
( N'Q266018', N'acute coronary syndrome', N'group of symptoms attributed to obstruction of the coronary arteries', N''),
( N'Q2661443', N'endocrine system disease', N'type of disease affecting the endocrine system', N''),
( N'Q2661464', N'glucose intolerance', N'pre-diabetic state of hyperglycemia that is associated with insulin resistance and increased risk of cardiovascular pathology. IGT may precede type 2 diabetes mellitus by many years', N''),
( N'Q266421', N'autosomal recessive congenital ichthyosis', N'congenital skin disease', N''),
( N'Q2665559', N'gnathomiasis', N'Human disease', N''),
( N'Q2666433', N'MELAS syndrome', N'one of the family of mitochondrial cytopathies, which also include MERRF, and Lebers hereditary optic neuropathy', N''),
( N'Q26689941', N'CANDLE syndrome', N'autosomal recessive disorder', N''),
( N'Q2669284', N'arachnoiditis', N'Human disease', N''),
( N'Q26739327', N'anomalous trichromacy', N'human disease', N''),
( N'Q267602', N'XYY syndrome', N'genetic condition in which a male has an extra Y chromosome', N''),
( N'Q26781137', N'premature ventricular contraction', N'Human disease', N''),
( N'Q2681162', N'eye injury', N'medical condition', N''),
( N'Q268292', N'mitral valve insufficiency', N'disorder of the heart in which the mitral valve does not close properly when the heart pumps out blood', N''),
( N'Q268594', N'stupor', N'total or nearly total lack of spontaneous movements (disease)', N''),
( N'Q2686385', N'factitious disorder', N'disease of mental health where symptoms are deliberately produced, feigned or exaggerated in order to falsely demonstrate the presence of an illness', N''),
( N'Q268667', N'atopic dermatitis', N'type of inflammation of the skin', N''),
( N'Q268713', N'mantle cell lymphoma', N'B-cell lymphocytic neoplasm due to CD5 positive antigen-naive pregerminal center B-cell within the mantle zone that surrounds normal germinal center follicles', N''),
( N'Q268832', N'Accelerated phase chronic myelogenous leukemia', N'disease', N''),
( N'Q2691713', N'Miller syndrome', N'human disease', N''),
( N'Q2692054', N'chromosome 1q21.1 duplication syndrome', N'Human disease', N''),
( N'Q2694437', N'asphyxia neonatorum', N'Respiratory failure in the newborn. (Dorland, 27th ed)', N''),
( N'Q2697371', N'Ramsay Hunt syndrome', N'unrelated neurological syndromes described by  James Ramsay Hunt', N''),
( N'Q2697787', N'alopecia', N'loss of hair from the head or body', N''),
( N'Q2700304', N'Bolivian hemorrhagic fever', N'hemorrhagic fever and zoonotic infectious disease originating in Bolivia after infection by Machupo virus', N''),
( N'Q2703671', N'Haemolacria', N'physical condition that causes a person to produce tears that are partially composed of blood', N''),
( N'Q27043982', N'globoszoospermia', N'male infertility characterized by round-headed spermatozoa lacking an acrosome', N''),
( N'Q270673', N'personality disorder', N'maladaptive patterns of behavior', N''),
( N'Q2710164', N'dental abscess', N'tooth disease characterized by a localized collection of pus associated with a tooth', N''),
( N'Q2711291', N'familial hypercholesterolemia', N'familial hyperlipidemia characterized by very high levels of low-density lipoprotein (LDL) and early cardiovascular disease', N''),
( N'Q2713959', N'La Crosse encephalitis', N'Human disease', N''),
( N'Q27164432', N'amelogenesis imperfecta type 1G', N'amelogenesis imperfecta that has material basis in homozygous or compound heterozygous mutation in the FAM20A gene on chromosome 17q24', N''),
( N'Q271759', N'porphyria', N'An inherited metabolic disorder that involves certain enzymes in the heme bio-synthetic pathway resulting in the overproduction and accumulation of porphyrins.', N''),
( N'Q271993', N'hyperglycemia', N'human disease', N''),
( N'Q272002', N'foodborne illness', N'illness resulting from food that is spoiled or contaminated by pathogenic bacteria, viruses, parasites or toxins', N''),
( N'Q2720759', N'esotropia', N'Esotropia is a strabismus in which the eye turns inward toward the nose', N''),
( N'Q272436', N'allergic rhinitis', N'Human disease', N''),
( N'Q2726043', N'chromoblastomycosis', N'long-term fungal infection of the skin and subcutaneous tissue', N''),
( N'Q272741', N'adenoma', N'cell type benign neoplasm that is composed of epithelial tissue in which tumor cells form glands or glandlike structures', N''),
( N'Q2730080', N'Idiopathic Hypersomnia', N'Idiopathic hypersomnia is a sleep disorder classified in two forms: idiopathic hypersomnia with long sleep time and idiopathic hypersomnia without long sleep time', N''),
( N'Q2732398', N'autosomal dominant polycystic kidney', N'human disease', N''),
( N'Q273510', N'candidiasis', N'fungal infection due to any type of Candida', N''),
( N'Q2735907', N'cutis laxa', N'skin disease characterized by skin that is loose, hanging, wrinkled and lacking in elasticity; it can also affect connective tissue in other parts of the body, including the heart, blood vessels, joints, intestines and lungs', N''),
( N'Q2736268', N'mucoepidermoid carcinoma', N'carcinoma that is characterized by squamous cells, mucus-secreting cells, and intermediate cells.  It can occur in several anatomic sites, including parotid gland, oral cavity, paranasal sinus, skin, breast, lung, larynx, and lacrimal ducts', N''),
( N'Q2737426', N'umbilical hernia', N'intestinal disease characterized by the protrusion by part of the intestine though an opening in the abdominal muscles', N''),
( N'Q2741820', N'Omsk hemorrhagic fever', N'Human disease', N''),
( N'Q27429789', N'macular degeneration', N'retinal degeneration characterized by gradual deterioration of light-sensing cells in the tissues at the back of the eye', N''),
( N'Q2744442', N'Ross River fever', N'Human disease', N''),
( N'Q274615', N'kuru', N'Human disease', N''),
( N'Q2753372', N'Majewskis polydactyly syndrome', N'Human disease', N''),
( N'Q2753827', N'Pigment dispersion syndrome', N'eye disease characterized by slit-like depigmented areas of the iris with up to 50% of patients going on to develop gluacoma', N''),
( N'Q275385', N'variegate porphyria', N'Human disease', N''),
( N'Q2755530', N'hepatobiliary disease', N'gastrointestinal system disease that is located in the liver and/or biliary tract', N''),
( N'Q27555722', N'eosinophilic gastroenteritis', N'human disease', N''),
( N'Q2756703', N'Septo-optic dysplasia', N'autosomal genetic disease characterized by the classical triad of optic nerve hypoplasia, pituitary gland hypoplasia and midline brain defects that has material basis in mutation in the HESX1 gene on chromosome 3p14', N''),
( N'Q2757585', N'Mowat-Wilson syndrome', N'rare genetic disorder', N''),
( N'Q27698000', N'Anisomastia', N'medical condition in which there is a severe asymmetry or unequalness in the size of the breasts', N''),
( N'Q277452', N'Ebstein anomaly', N'tricuspid valve disease that is a congenital heart defect in which the septal leaflet of the tricuspid valve is displaced towards the apex of the right ventricle of the heart', N''),
( N'Q27835675', N'lamin A/C congenital muscular dystrophy', N'congenital muscular dystrophy characterized by autosomal dominant inheritance that has material basis in heterozygous mutation in the LMNA gene on chromosome 1q22', N''),
( N'Q2785159', N'Drug-induced lupus erythematosus', N'lupus erythematosus caused by chronic use of certain drugs', N''),
( N'Q2787011', N'Chronic recurrent multifocal osteomyelitis', N'osteomyelitis characterized by multiple foci of painful swelling of bones, mainly in the metaphyses of the long bones, in addition to the pelvis, the shoulder girdle and the spine', N''),
( N'Q278909', N'sulfhemoglobinemia', N'Human disease', N''),
( N'Q2791374', N'essential fructosuria', N'', N''),
( N'Q279330', N'bronchospasm', N'lower respiratory tract disease that affects the airways leading into the lungs', N''),
( N'Q280027', N'uveitis', N'human disease', N''),
( N'Q280156', N'male infertility', N'inability to father a child', N''),
( N'Q28024539', N'NGLY1-deficiency', N'Human disease', N''),
( N'Q28024726', N'Stromme syndrome', N'human disease', N''),
( N'Q28032350', N'Paroxysmal supraventricular tachycardia', N'', N''),
( N'Q28058359', N'Bilharzial cor pulmonale', N'', N''),
( N'Q2805908', N'bullous keratopathy', N'Human disease', N''),
( N'Q281115', N'Proteus syndrome', N'human disease characterized by an overgrowth of skin, bones, muscles, fatty tissues, and blood and lymphatic vessels', N''),
( N'Q28111799', N'bradyesthesia', N'', N''),
( N'Q28114395', N'Nevo syndrome', N'', N''),
( N'Q28134983', N'Distal hereditary motor neuropathy type V', N'human disease', N''),
( N'Q28136285', N'Hormone-sensitive cancer', N'a type of cancer dependent on a hormone for growth', N''),
( N'Q28136452', N'ureterovaginal fistula', N'', N''),
( N'Q28136834', N'Christmas Eye', N'', N''),
( N'Q281490', N'urinary incontinence', N'uncontrolled leakage of urine', N''),
( N'Q281928', N'social phobia', N'phobic disorder that involves social anxiety', N''),
( N'Q28208917', N'Aminoacylase 1 deficiency', N'Aminoacylase 1 deficiency (ACY1D) is an inborn error of metabolism marked by a characteristic pattern of urinary N-acetyl amino acid excretion and neurologic symptoms', N''),
( N'Q28209257', N'Hemoglobin Constant Spring', N'', N''),
( N'Q282142', N'glioblastoma', N'human disease', N''),
( N'Q2822569', N'acanthoma', N'Human disease', N''),
( N'Q2823145', N'achondrogenesis', N'human disease', N''),
( N'Q2823332', N'3-methylglutaconic aciduria type 3', N'3-methylglutaconic aciduria that has material basis in mutation in the OPA3 gene', N''),
( N'Q2823333', N'succinic semialdehyde dehydrogenase deficiency', N'gamma-amino butyric acid metabolism disorder that is characterized by a deficiency of succinic semialdehyde dehydrogenase resulting in elevated levels of gamma-hydroxybutyric acid', N''),
( N'Q2823337', N'Fumarase deficiency', N'rare disease', N''),
( N'Q2823497', N'Acropachy', N'Isolated congenital digital clubbing is a rare genodermatosis disorder characterized by enlargement of the terminal segments of fingers and toes with thickened nails without any other abnormality', N''),
( N'Q2825480', N'colorectal adenoma', N'human disease', N''),
( N'Q283108', N'Bruton-type agammaglobulinemia', N'Human disease', N''),
( N'Q2831905', N'ocular albinism', N'Human disease', N''),
( N'Q283656', N'dilated cardiomyopathy', N'disease characterized by an enlarged heart', N''),
( N'Q28405104', N'Puberty menorrhagia', N'increased menstrual flow soon after puberty', N''),
( N'Q284070', N'protein-losing enteropathy', N'Human disease', N''),
( N'Q2841213', N'factor XII deficiency', N'Human disease', N''),
( N'Q284219', N'Patau syndrome', N'Human disease', N''),
( N'Q28439851', N'Chorioangioma', N'', N''),
( N'Q28439873', N'Breus mole', N'hematoma formed in uterus in pregnancy', N''),
( N'Q2844600', N'muscular atrophy', N'human disease', N''),
( N'Q2844603', N'transthyretin amyloidosis', N'Human disease', N''),
( N'Q28448698', N'Hemochromatosis type 4', N'hemochromatosis that has material basis in heterozygous mutation in the SLC40A1 gene on chromosome 2q32', N''),
( N'Q2845432', N'ehrlichiosis', N'human disease', N''),
( N'Q28454436', N'failure of eruption of teeth', N'human disease', N''),
( N'Q28456109', N'Ischiopatellar dysplasia', N'Small patella syndrome (SPS) is a very rare benign bone dysplasia affecting skeletal structures of the lower limb and the pelvis', N''),
( N'Q2845978', N'stereotypic movement disorder', N'neurodevelopmental condition', N''),
( N'Q28503199', N'vena cava inferior agenesis', N'', N''),
( N'Q2851545', N'oophoritis', N'Human disease', N''),
( N'Q2852241', N'arrhythmogenic right ventricular dysplasia 1', N'arrhythmogenic right ventricular dysplasia that has material basis in heterozygous mutation in the TGFB3 gene on chromosome 14q24', N''),
( N'Q2852337', N'Anosodiaphoria', N'', N''),
( N'Q2855592', N'Progressive inflammatory neuropathy', N'', N''),
( N'Q2855814', N'simple-type schizophrenia', N'type of schizophrenia', N''),
( N'Q2856379', N'kyphoscoliosis', N'', N''),
( N'Q2857909', N'thiamine-responsive megaloblastic anemia syndrome', N'Thiamine-responsive megaloblastic anemia (TRMA) is characterized by a triad of megaloblastic anemia, non-type I diabetes mellitus, and sensorineural deafness', N''),
( N'Q2860302', N'kidney cortex necrosis', N'rare cause of acute kidney failure', N''),
( N'Q2868696', N'pain agnosia', N'agnosia that is a loss of the ability to perceive and process pain', N''),
( N'Q2868786', N'Charlevoix-Saguenay spastic ataxia', N'autosomal recessive spastic ataxia of Charlevoix-Saguenay (ARSACS) is a neurodegenerative disorder characterised by early-onset cerebellar ataxia with spasticity, a pyramidal syndrome and peripheral neuropathy', N''),
( N'Q2868788', N'spinocerebellar ataxia type 6', N'Human disease', N''),
( N'Q2868792', N'familial isolated deficiency of vitamin E', N'rare autosomal recessive neurodegenerative disease. Symptoms are similar to those of Friedreich ataxia', N''),
( N'Q2869820', N'Kjers optic neuropathy', N'', N''),
( N'Q2870197', N'Atelosteogenesis, type II', N'', N'')
GO