INSERT INTO dbo.Disease
([Code], [Name], [Description], [Overview])
VALUES
( N'Q17121234', N'Franceschetti–Klein syndrome', N'', N''),
( N'Q17121503', N'iridocorneal endothelial syndrome', N'', N''),
( N'Q1712213', N'normal pressure hydrocephalus', N'condition in which there is excess cerebrospinal fluid in the ventricles, and with normal or slightly elevated cerebrospinal fluid pressure', N''),
( N'Q1712331', N'Rh disease', N'problem with Rh+ fetuses in Rh- mothers', N''),
( N'Q17124192', N'Smith Martin Dodd syndrome', N'Disease', N''),
( N'Q17125068', N'Dahlberg Borer Newcomer syndrome', N'', N''),
( N'Q17125239', N'Idiopathic giant-cell myocarditis', N'human disease', N''),
( N'Q17125280', N'Lateral pontine syndrome', N'', N''),
( N'Q17125282', N'Lymphoepithelioma', N'', N''),
( N'Q17125333', N'pulmonary neuroendocrine tumor', N'neuroendocrine tumor localized to the lung', N''),
( N'Q17125601', N'iridogoniodysgenesis syndrome', N'Human disease', N''),
( N'Q17125786', N'Singleton Merten syndrome', N'', N''),
( N'Q17126040', N'Transfusion associated circulatory overload', N'', N''),
( N'Q17126319', N'Multisystem proteinopathy', N'', N''),
( N'Q17126784', N'Hodgkins lymphoma, nodular sclerosis', N'Human disease', N''),
( N'Q17128230', N'Kapur–Toriello syndrome', N'Kapur-Toriello syndrome is an extremely rare syndrome characterized by facial dysmorphism, severe intellectual deficiency, cardiac and intestinal anomalies, and growth retardation', N''),
( N'Q1713037', N'membranous glomerulonephritis', N'Human disease', N''),
( N'Q17130620', N'Injury of axillary nerve', N'', N''),
( N'Q17132235', N'hypercementosis', N'Human disease', N''),
( N'Q17133302', N'Yim–Ebbin syndrome', N'disease', N''),
( N'Q1713499', N'megaesophagus', N'abnormal dilation of the esophagus not due to obstruction', N''),
( N'Q17135821', N'Heterogeneous condition', N'', N''),
( N'Q17139523', N'retinal lattice degeneration', N'Human disease', N''),
( N'Q17141201', N'Tinea', N'Human disease', N''),
( N'Q17141310', N'mucinous tubular and spindle cell carcinoma', N'human disease', N''),
( N'Q17141312', N'Vesicointestinal fistula', N'between the bladder and the bowel', N''),
( N'Q17141594', N'Urocanic aciduria', N'', N''),
( N'Q17141939', N'Hereditary neuralgic amyotrophy', N'neuralgic disorder', N''),
( N'Q17142640', N'Light chain deposition disease', N'', N''),
( N'Q17143464', N'Pretzel syndrome', N'human disease', N''),
( N'Q17143593', N'neonatal hypoglycemia', N'occurs when the neonates blood glucose level is less than the newborns body requirements for factors such as cellular energy and metabolism', N''),
( N'Q17143640', N'permanent neonatal diabetes mellitus', N'neonatal diabetes mellitus that has material basis in homozygous mutation in the glucokinase gene (GCK), heterozygous mutation in the KCNJ11 and INS genes, or by heterozygous or homozygous mutation in the ABCC8 gene', N''),
( N'Q17144153', N'Nance-Horan syndrome', N'disorder of lens', N''),
( N'Q17144183', N'Tooth mobility', N'', N''),
( N'Q17144188', N'Ogden syndrome', N'X-linked disease resulting from a deficiency in N-terminal acetyltransferase, extreme abrupt behavior, anger issues, characterized by postnatal growth failure with severe delays and dysmorphic features in boys', N''),
( N'Q17144217', N'mitochondrial DNA depletion syndrome', N'human disease', N''),
( N'Q17144875', N'papular mucinosis', N'Human disease', N''),
( N'Q17145626', N'hypertropia', N'Human disease', N''),
( N'Q17145912', N'Autoimmune neutropenia', N'disorder common in infants and young children', N''),
( N'Q17146000', N'smouldering myeloma', N'multiple myeloma that is a slow growing type of myeloma in which abnormal plasma cells results in too much of a single type of monoclonal antibody', N''),
( N'Q17146775', N'Hypergammaglobulinemia', N'Human disease', N''),
( N'Q17147306', N'usual interstitial pneumonia', N'', N''),
( N'Q17147649', N'specific social phobia', N'experiencing anxiety only in specific social situations', N''),
( N'Q17148020', N'tangentiality', N'thought disorder, involves replying to a question in an oblique, irrelevant or tangential manner', N''),
( N'Q17148148', N'odontoonychodermal syndrome', N'syndrome characterized by craniofacial, neurologic, limb and ocular abnormalities', N''),
( N'Q17148651', N'erythema annulare centrifugum', N'', N''),
( N'Q17149181', N'glucocorticoid-remediable aldosteronism', N'Human disease', N''),
( N'Q17149251', N'Left Ventricular Thrombus', N'', N''),
( N'Q17149274', N'XMEN Disease', N'human disease', N''),
( N'Q17151226', N'Neonatal bowel obstruction', N'congenital disorder of digestive system', N''),
( N'Q17152451', N'PASLI Disease', N'human disease', N''),
( N'Q17152512', N'T-cell prolymphocytic leukemia', N'A slow-growing type of leukemia (blood cancer) in which too many lymphocytes are found in the bone marrow and/or blood. The T-cell is specified as the defective cell line.', N''),
( N'Q17152566', N'salivary gland disease', N'Human disease', N''),
( N'Q17153517', N'Galactose epimerase deficiency', N'', N''),
( N'Q17153898', N'Xanthogranulomatous inflammation', N'', N''),
( N'Q17155516', N'Mucinous cystadenocarcinoma of the lung', N'lung adenocarcinoma that is a very rare malignant mucus-producing neoplasm arising from the uncontrolled growth of transformed epithelial cells originating in lung tissue', N''),
( N'Q17155571', N'Young–Madders syndrome', N'Holoprosencephaly-postaxial polydactyly syndrome associates, in chromosomally normal neonates, holoprosencephaly, severe facial dysmorphism, postaxial polydactyly and other congenital abnormalities, suggestive of trisomy 13 (see this term)', N''),
( N'Q17155582', N'Hypernasal speech', N'', N''),
( N'Q17155680', N'herpes gladiatorum', N'medical condition', N''),
( N'Q17156861', N'coenurosis', N'Human disease', N''),
( N'Q17156923', N'Sepiapterin reductase deficiency', N'human disease', N''),
( N'Q17156972', N'Paroxysmal sympathetic hyperactivity', N'syndrome that causes episodes of increased activity of the sympathetic nervous system', N''),
( N'Q17157137', N'neuronitis', N'central nervous system disease that is characterized by neuron inflammation', N''),
( N'Q17162578', N'Macrocephaly-capillary malformation', N'', N''),
( N'Q17162726', N'soil-transmitted helminthiasis', N'class of diseases', N''),
( N'Q17163513', N'Pachygyria', N'congenital malformation of the cerebral hemisphere resulting in unusually thick convolutions of the cerebral cortex.', N''),
( N'Q17164695', N'lumbar spinal stenosis', N'medical condition of the spine', N''),
( N'Q17165269', N'Impacted wisdom', N'teeth that do not fully grow out of the gums due to being blocked by other teeth', N''),
( N'Q17165460', N'Atypical hemolytic uremic syndrome', N'complement deficiency that is characterized by mechanical hemolytic anemia, thrombocytopenia, and renal dysfunction', N''),
( N'Q1718432', N'KBG syndrome', N'syndrome that is characterized by short stature, moderate to severe degrees of mental retardation, developmental abnormalities of the limbs, bones of the spine (vertebrae), extremities, and/or underdevelopment of the bones of the skeleton', N''),
( N'Q17232521', N'vascular myelopathy', N'Human disease', N''),
( N'Q1723331', N'ophthalmoplegia', N'Human disease', N''),
( N'Q172341', N'ovarian cancer', N'female reproductive organ cancer that is located in the ovary', N''),
( N'Q1725245', N'left ventricular noncompaction', N'human disease', N''),
( N'Q1728132', N'Achenbach syndrome', N'skin condition characterized by spontaneous focal hemorrhage into the palm or the volar surface of a finger', N''),
( N'Q1729124', N'cardiomegaly', N'medical condition in which the heart is enlarged', N''),
( N'Q172941', N'peptic ulcer disease', N'ulcer of an area of the gastrointestinal tract', N''),
( N'Q17300307', N'low tension glaucoma', N'Human disease', N''),
( N'Q173022', N'bronchitis', N'type of lower respiratory disease', N''),
( N'Q17332514', N'Knobloch syndrome', N'Knobloch syndrome (KS) is defined by vitreoretinal and macular degeneration, and occipital encephalocele', N''),
( N'Q1734755', N'carcinoid tumor', N'type of neuroendocrine tumor originating in the cells of the neuroendocrine system', N''),
( N'Q1736456', N'somatostatinoma', N'Human disease', N''),
( N'Q1737261', N'cavernous hemangioma', N'human disease', N''),
( N'Q1739759', N'Keshan disease', N'congestive cardiomyopathy caused by a combination of dietary deficiency of selenium and the presence of a mutated strain of Coxsackievirus', N''),
( N'Q1741331', N'receptive aphasia', N'A type of aphasia', N''),
( N'Q1741965', N'Kindler syndrome', N'skin disease characterized by congenital blistering, skin atrophy, photosensitivity, skin fragility, and scaling', N''),
( N'Q1741995', N'King–Kopetzky syndrome', N'', N''),
( N'Q174589', N'agoraphobia', N'phobic disorder involving the specific anxiety about being in a place or situation where escape is difficult or embarrassing or where help may be unavailable.', N''),
( N'Q1746068', N'clavicle fracture', N'', N''),
( N'Q174651', N'Bálints syndrome', N'uncommon and incompletely understood triad of severe neuropsychological impairments', N''),
( N'Q1747726', N'tyrosinemia type I', N'tyrosinemia that has material basis in deficiency of the enzyme fumarylacetoacetate hydrolase resulting in an increase in fumarylacetoacetate which inhibits previous steps in tyrosine degradation leading to an accumulation of tyrosine in the body', N''),
( N'Q174857', N'scoliosis', N'spinal medical condition', N''),
( N'Q1749931', N'botryoid embryo rhabdomyosarcoma', N'Human disease', N''),
( N'Q1750104', N'Carrions disease', N'infectious disease produced by Bartonella bacilliformis infection', N''),
( N'Q1750471', N'Sly syndrome', N'mucopolysaccharidosis characterized by a deficiency of the lysosomal enzyme beta-glucuronidase resulting in the inability to degrade glucuronic acid-containing glycosaminoglycans', N''),
( N'Q1750884', N'Pancoast tumor', N'tumor of the pulmonary apex. It is a type of lung cancer defined primarily by its location situated at the top end of either the right or left lung. It typically spreads to nearby tissues such as the ribs and vertebrae', N''),
( N'Q175180', N'radiculopathy', N'Human disease', N''),
( N'Q1752571', N'myelofibrosis', N'myeloid neoplasm that is located in the bone marrow which results in bone marrow being replaced by fibrous (scar) tissue', N''),
( N'Q1752891', N'polymyalgia rheumatica', N'syndrome with pain or stiffness, usually in the neck, shoulders, upper arms, and hips, but which may occur all over the body', N''),
( N'Q1753467', N'pathologic fracture', N'bone fracture caused by weakness of the bone structure that leads to decrease mechanical resistance to normal mechanical loads', N''),
( N'Q1753520', N'rheumatoid nodule', N'variant of polyarthritis', N''),
( N'Q1753778', N'juvenile neuronal ceroid lipofuscinosis', N'extremely rare and fatal autosomal recessive neurodegenerative disorder  in humans', N''),
( N'Q17540092', N'Encephalocraniocutaneous lipomatosis', N'rare neoplastic syndrome characterized by the presence of unilateral lipomas of the cranium, face and neck, and ipsilateral cerebral malformations', N''),
( N'Q1754226', N'megacolon', N'colonic disease that is characterized by an abnormal dilation of the colon', N''),
( N'Q1754830', N'latex allergy', N'hypersensitivity reaction type I disease triggered by latex', N''),
( N'Q1755457', N'patellar tendinitis', N'Human disease', N''),
( N'Q1755487', N'neonatal jaundice', N'pigmentation disease characterized by a high level of bilirubin in the blood, causing a yellowing of the skin and other tissues of a newborn infant', N''),
( N'Q1755537', N'VACTERL association', N'syndrome that is characterized by the presence of at least three of the following: vertebral defects, anal atresia, cardiac defects, tracheo-esophageal fistula, renal anomalies, and limb abnormalities', N''),
( N'Q1755568', N'osteopetrosis', N'an extremely rare inherited disorder whereby the bones harden, becoming denser, sometimes causing bones to dissolve and break, caused by malfunctioning osteoclasts’ inability to resorb bone', N''),
( N'Q1756040', N'Pierre Robin syndrome', N'a congenital condition with micrognathia and glossoptosis', N''),
( N'Q1756640', N'ranula', N'human disease', N''),
( N'Q1756659', N'Medication overuse headache', N'', N''),
( N'Q1756898', N'Lambert-Eaton myasthenic syndrome', N'an autoimmune, presynaptic disorder of neuromuscular transmission characterized by fluctuating muscle weakness and autonomic dysfunction frequently associated with small-cell lung cancer (SCLC)', N''),
( N'Q1757359', N'neurocirculatory asthenia', N'somatoform disorder that involves heart disease symptoms without any identifiable physiological abnormatlities.', N''),
( N'Q1757427', N'pancytopenia', N'medical condition in which there is a reduction in the number of red and white blood cells, as well as platelets', N''),
( N'Q1757549', N'Onychotillomania', N'', N''),
( N'Q1757666', N'Palilalia', N'language disorder', N''),
( N'Q1757915', N'sick sinus syndrome', N'group of abnormal heart rhythms (arrhythmias) presumably caused by a malfunction of the sinus node, the hearts primary pacemaker', N''),
( N'Q175827', N'stomach disease', N'gastrointestinal system disease that is located in the stomach', N''),
( N'Q1758283', N'Lown-Ganong-Levine syndrome', N'syndrome that involves pre-excitation of the ventricles due to an accessory pathway providing an abnormal electrical communication from the atria to the ventricles', N''),
( N'Q1758393', N'inherited metabolic disorder', N'class of disease including endocrine diseases, nutritional diseases and metabolic diseases', N''),
( N'Q175854', N'phobia', N'an anxiety disorder defined by a persistent and excessive fear of an object or situation', N''),
( N'Q1758624', N'Pseudarthrosis', N'permanent failure of healing following a broken bone unless intervention (such as surgery) is performed', N''),
( N'Q1758730', N'transposition of great vessels', N'group of congenital heart defects involving an abnormal spatial arrangement of any of the great vessels: superior and/or inferior venae cavae, pulmonary artery, pulmonary veins, and aorta', N''),
( N'Q1759389', N'congenital erythropoietic porphyria', N'congenital human disease', N''),
( N'Q1759514', N'eumycotic mycetoma', N'chronic granulomatous[1] fungal disease[2] of humans, affecting mainly the limbs, and sometimes the abdominal and chest walls or the head', N''),
( N'Q1759560', N'microtia', N'congenital deformity where the pinna (external ear) is underdeveloped', N''),
( N'Q1759600', N'erythropoietic protoporphyria', N'acute porphyria characterized by a deficiency in the enzyme ferrochelatase, leading to abnormally high levels of protoporphyrin in the tissue', N''),
( N'Q1760202', N'oxyphilic adenoma', N'Human disease', N''),
( N'Q1760294', N'trigonocephaly', N'congenital condition of premature fusion of the metopic suture leading to a triangular shaped forehead.', N''),
( N'Q1760461', N'ovarian hyperstimulation syndrome', N'Human disease', N''),
( N'Q1760607', N'loiasis', N'Human disease', N''),
( N'Q1762339', N'deep vein thrombosis', N'formation of a blood clot (thrombus) in a deep vein', N''),
( N'Q17627190', N'Hemimelia', N'congenital deficiency of a long bone', N''),
( N'Q17635591', N'plasmablastic lymphoma', N'', N''),
( N'Q17639642', N'tonic tensor tympani syndrome', N'syndrome where the tensor tympani activates at lower volumes cause frequent spasm', N''),
( N'Q1764657', N'Malum perforans', N'', N''),
( N'Q1765564', N'septic shock', N'medical condition that occurs when sepsis leads to dangerously low blood pressure', N''),
( N'Q176741', N'mumps', N'Human disease caused by paramyxovirus', N''),
( N'Q1770836', N'Sotos syndrome', N'autosomal recessive disease that occurs rarely and is characterized by excessive physical growth during the first 2 to 3 years of life', N''),
( N'Q1771331', N'Cryopyrin-associated periodic syndrome', N'syndrome', N''),
( N'Q177190', N'sleep disorder', N'disease of mental health that involves disruption of sleep patterns', N''),
( N'Q177254', N'hyperopia', N'condition of the eye', N''),
( N'Q1774750', N'Klippel–Trénaunay–Weber syndrome', N'syndrome that is characterized by large cutaneous hemangiomata with hypertrophy of the related bones and soft tissues', N''),
( N'Q1774751', N'Klippel-Feil syndrome', N'physical disorder that has material basis in abnormal segmentation of the vertebra during fetal development which results in fusion located in cervical vertebra', N''),
( N'Q1776603', N'Radial dysplasia', N'Radial hemimelia is a congenital longitudinal deficiency of the radius bone of the forearm characterized by partial or total absence of the radius', N''),
( N'Q1776864', N'Acoustic shock', N'', N''),
( N'Q1777118', N'knee osteoarthritis', N'', N''),
( N'Q177755', N'astrocytoma', N'type of cancer of the brain originating in a particular kind of glial cells, star-shaped brain cells in the cerebrum called astrocytes', N''),
( N'Q177809', N'adult Refsum disease', N'Human disease', N''),
( N'Q1778287', N'Waldenströms macroglobulinemia', N'B-cell lymphocytic neoplasm characterized by an uncontrolled increase of B-cells', N''),
( N'Q177878', N'fucosidosis', N'Human disease', N''),
( N'Q177895', N'astigmatism', N'refractive error characterized by the optics of the eye to focus a point object into a sharp focused image on the retina, has_symptom blurred vision.', N''),
( N'Q1778968', N'compartment syndrome', N'condition in which increased pressure within one of the bodys compartments results in insufficient blood supply to tissue within that space', N''),
( N'Q1779119', N'sacrococcygeal teratoma', N'', N''),
( N'Q1779300', N'connective tissue disease', N'musculoskeletal system disease that affects tissues such as skin, tendons, and cartilage', N''),
( N'Q1779438', N'piblokto', N'culture-bound syndrome', N''),
( N'Q1779987', N'X-linked hypophosphatemic rickets', N'Human disease', N''),
( N'Q1780241', N'tricuspid insufficiency', N'A tricuspid valve disease that is characterized by failure of the hearts tricuspid valve to close properly during systole. As a result, with each heart beat, blood is pumped out from the right side of the heart in the opposite direction to normal.', N''),
( N'Q178059', N'paraphilia', N'experience of intense sexual arousal to atypical objects, situations, or individuals', N''),
( N'Q1781802', N'hyperekplexia', N'nervous system disease characterized by an exaggerated startle response to sudden, unexpected auditory or tactile stimuli and hypertonia', N''),
( N'Q178190', N'obsessive-compulsive disorder', N'anxiety disorder that involves unwanted and repeated thoughts, feelings, ideas, sensations (obsessions), or behaviors that make them feel driven to do something (compulsions)', N''),
( N'Q178194', N'cystic fibrosis', N'autosomal recessive disease characterized by the buildup of mucus', N''),
( N'Q1782574', N'spasmodic dystonia', N'focal dystonia that involves the muscles that control the vocal cords, resulting in strained or breathy speech', N''),
( N'Q1783300', N'Contrast-induced nephropathy', N'form of kidney damage in which there has been recent exposure to medical imaging contrast material', N''),
( N'Q1783645', N'Balo concentric sclerosis', N'demyelinating disease characterized by the fact that the demyelinated tissues form concentric layers', N''),
( N'Q1783924', N'head and neck cancer', N'organ system cancer in the head or neck region', N''),
( N'Q178436', N'constipation', N'bowel dysfunction that is characterized by infrequent or difficult evacuation of feces.', N''),
( N'Q1784755', N'levo-transposition of the great arteries', N'', N''),
( N'Q1785791', N'giant-cell tumor of bone', N'giant cell tumor and bone cancer and bone tissue neoplasm that results in the presence of multinucleated giant cells (osteoclast-like cell)', N''),
( N'Q1786496', N'acrocephalosyndactylia', N'group of diseases', N''),
( N'Q1786513', N'craniopharyngioma', N'type of brain tumor derived from pituitary gland embryonic tissue that occurs most commonly in children, but also affects adults', N''),
( N'Q1786851', N'yellow nail syndrome', N'Human disease', N''),
( N'Q1786953', N'seminoma', N'germinoma that has material basis in cells that make sperm and eggs', N''),
( N'Q1787020', N'thanatophoric dysplasia', N'osteochondrodysplasia that results in short arms and legs with excess folds of skin', N''),
( N'Q1788314', N'periodic paralysis', N'human disease', N''),
( N'Q1789076', N'Malakoplakia', N'Malakoplakia is a chronic multisystem granulomatous inflammatory disease characterized by the presence of single or multiple soft plaques on various organs of the body', N''),
( N'Q1790005', N'germ cell neoplasia in situ', N'', N''),
( N'Q1790134', N'Krukenberg tumor', N'Human disease', N''),
( N'Q1790371', N'cryoglobulinemia', N'hypersensitivity reaction type IV disease that involves large amounts of cryoglobulins in the blood, which becomes thick or gel-like in cold temperatures', N''),
( N'Q1790424', N'idiopathic interstitial pneumonia', N'pneumonia located in the lung parenchyma of unknown cause', N''),
( N'Q179399', N'infertility', N'inability of a person, animal or plant to reproduce by natural means that is no intervention of contraceptive techniques', N''),
( N'Q179630', N'syndrome', N'set of medical signs and symptoms which are correlated with each other and often clinically associated with a particular disease or disorder', N''),
( N'Q1798016', N'LEOPARD syndrome', N'rare autosomal dominant,[3] multisystem disease caused by a mutation in the protein tyrosine phosphatase, non-receptor type 11 gene (PTPN11)', N''),
( N'Q1799146', N'irritant dermatitis', N'Human disease', N''),
( N'Q179945', N'psoriasis', N'Skin disease', N''),
( N'Q179951', N'strabismus', N'Visual impairment', N''),
( N'Q180152', N'vitiligo', N'hypersensitivity reaction type II disease that cause depigmentation of patches of skin resulting from loss of function or death of melanocytes', N''),
( N'Q18020133', N'Femoral-facial syndrome', N'Femoral-facial syndrome is characterized by predominant femoral hypoplasia (bilateral or unilateral) and unusual facies', N''),
( N'Q180375', N'right bundle branch block', N'heart block in the electrical conduction system', N''),
( N'Q18054140', N'collapse', N'medical symptom, a sudden and often unannounced loss of postural tone', N''),
( N'Q180614', N'melanoma', N'malignant neoplasm originating from melanocytes', N''),
( N'Q180664', N'acute lymphocytic leukemia', N'leukemia that is characterized by over production of lymphoblasts.', N''),
( N'Q18070807', N'Morning glory disc anomaly', N'congenital deformity resulting from failure of the optic nerve to completely form in utero', N''),
( N'Q1807280', N'osteoblastoma', N'Human disease', N''),
( N'Q1807401', N'sodoku', N'Human disease', N''),
( N'Q1807522', N'vaginal cancer', N'female reproductive system cancer that is located in the vagina', N''),
( N'Q181032', N'neurosis', N'term and disease in psychology', N''),
( N'Q1811132', N'Leber congenital amaurosis', N'retinal disease that is characterized by nystagmus, sluggish or no pupillary responses, and severe vision loss or blindness', N''),
( N'Q18123741', N'infectious disease', N'disease caused by infection of pathogenic biological agents in a host organism', N''),
( N'Q181257', N'prostate cancer', N'male reproductive organ cancer', N''),
( N'Q1813737', N'macular retinal edema', N'Human disease', N''),
( N'Q181391', N'baldness', N'state where most or all of hair from the head has been lost', N''),
( N'Q1815019', N'Leigh disease', N'A mitochondrial metabolism disease characterized by progressive loss of mental and movement abilities. Symptoms usually begin between ages of three months and two years and include loss of appetite, vomiting, irritability and seizure activity.', N''),
( N'Q1815985', N'pseudobulbar palsy', N'medical condition characterized by the inability to control facial movements (such as chewing and speaking) and caused by a variety of neurological disorders', N''),
( N'Q1816041', N'peritoneal carcinoma', N'carcinoma that is located in the inside of the abdomen', N''),
( N'Q181876', N'metastasis', N'spread of a disease inside a body', N''),
( N'Q181923', N'attention deficit hyperactivity disorder', N'range of neurodevelopmental conditions', N''),
( N'Q182005', N'Holt-Oram syndrome', N'autosomal dominant disease characterized by congenital anomalies located_in heart and located_in upper limb.', N''),
( N'Q18209712', N'Autoimmune autonomic ganglionopathy', N'', N''),
( N'Q18209717', N'Autosomal dominant retinal vasculopathy with cerebral leukodystrophy', N'', N''),
( N'Q18211693', N'vaginal disease', N'Human disease', N''),
( N'Q18211695', N'vaginal hypoplasia', N'', N''),
( N'Q18211751', N'vulvar disease', N'A non-neoplastic or neoplastic disorder that affects the vulva. Representative examples include infection, Bartholin gland adenoma, and vulvar carcinoma.', N''),
( N'Q182155', N'herpes zoster', N'viral disease caused by the Varicella zoster virus', N''),
( N'Q1821559', N'leukodystrophy', N'cerebral degeneration characterized by dysfunction of the white matter of the brain', N''),
( N'Q18217139', N'RAS-associated autoimmune leukoproliferative disorder', N'Human disease', N''),
( N'Q1823656', N'Liddle syndrome', N'genetic disorder inherited in an autosomal dominant manner that is characterized by early, and frequently severe, high blood pressure', N''),
( N'Q182413', N'non-controlled substance abuse', N'abuse of chemical substances and/or abuse of any licit substances', N''),
( N'Q1826391', N'atrophic gastritis', N'Human disease', N''),
( N'Q1827028', N'Ectopia lentis', N'disorder of lens', N''),
( N'Q1827380', N'pseudogynecomastia', N'male breast tissue enlargement solely due to excess fatty tissue', N''),
( N'Q1827425', N'liposarcoma', N'lipomatous cancer that arises in fat cells in deep soft tissue retroperitoneum', N''),
( N'Q1827605', N'lipedema', N'disorder where there is enlargement of both legs due to deposits of fat under the skin', N''),
( N'Q183098', N'hepatic vein thrombosis', N'Human disease', N''),
( N'Q183134', N'sepsis', N'life-threatening organ dysfunction triggered by infection', N''),
( N'Q183344', N'sinusitis', N'inflammation of the mucous membrane that lines the sinuses resulting in symptoms', N''),
( N'Q183392', N'rickets', N'human disease', N''),
( N'Q18345704', N'pulmonary venoocclusive disease', N'Human disease', N''),
( N'Q18348812', N'head and neck squamous cell carcinoma', N'head and neck carcinoma that has material basis in squamous cells that line the moist, mucosal surfaces inside the head and neck', N''),
( N'Q18350119', N'acute flaccid myelitis', N'serious condition of the spinal cord, with symptoms such as rapid onset of arm or leg weakness and decreased reflexes', N''),
( N'Q18353735', N'epidural abscess', N'human disease', N''),
( N'Q183548', N'voyeurism', N'sexual interest in or practice of spying on people engaged in intimate behaviors', N''),
( N'Q1835481', N'Familial cold urticaria', N'primary immunodeficiency disease characterized by recurrent episodes of maculopapular skin rash triggered by exposure to cold associated with low-grade fever, general malaise, eye redness and arthralgia/myalgia', N''),
( N'Q183560', N'intellectual disability', N'generalized neurodevelopmental disorder', N''),
( N'Q18357155', N'Omental infarction', N'', N''),
( N'Q18358559', N'Ostial disease', N'', N''),
( N'Q18387306', N'Childhood cataract', N'disorder of lens', N''),
( N'Q18389302', N'polysyndactyly', N'', N''),
( N'Q18394840', N'trilateral retinoblastoma', N'retinoblastoma that refers to bilateral retinoblastoma associated with an intracranial primitive neuroectodermal tumor located in the pineal or suprasellar region', N''),
( N'Q18395602', N'Vitreous touch syndrome', N'', N''),
( N'Q184084', N'beriberi', N'Human disease', N''),
( N'Q184559', N'arteriosclerosis', N'Thickening, hardening and loss of elasticity of the walls of arteries', N''),
( N'Q184674', N'erectile dysfunction', N'', N''),
( N'Q1848471', N'inclusion body myositis', N'myositis that is characterized by slowly progressive weakness and wasting of both distal and proximal muscles, most apparent in the muscles of the arms and legs that can occur in a sporadic or hereditary forms', N''),
( N'Q185034', N'sickle-cell disease', N'type of hereditary blood disorder', N''),
( N'Q185137', N'thalassemia', N'Human disease', N''),
( N'Q18553330', N'extrapulmonary tuberculosis', N'respiratory disease', N''),
( N'Q18553335', N'Askins tumor', N'Human disease', N''),
( N'Q18553391', N'Birk-Barel syndrome', N'Human disease', N''),
( N'Q18553398', N'Bowen-Conradi syndrome', N'Human disease', N''),
( N'Q18553444', N'nicotine dependence', N'state of dependence upon nicotine', N''),
( N'Q18553445', N'mature T-cell and NK-cell lymphoma', N'non-Hodgkin lymphoma that has material basis in mature T lymphocytes and natural killer cells', N''),
( N'Q18553449', N'marginal zone B-cell lymphoma', N'B-cell lymphoma that is characterized by initial formation in the marginal zones of lymph tissue', N''),
( N'Q18553480', N'achalasia microcephaly syndrome', N'Human disease', N''),
( N'Q18553563', N'tonsil squamous cell carcinoma', N'tonsil cancer that has material basis in squamous cells', N''),
( N'Q18553662', N'central nervous system primitive neuroectodermal neoplasm', N'Human disease', N''),
( N'Q18553749', N'craniometaphyseal dysplasia', N'osteosclerosis that has material basis in mutations in the ANKH gene which results in progressive thickening located in skull and abnormally shaped ends of long bones in the limbs', N''),
( N'Q18553752', N'acromesomelic dysplasia', N'osteochondrodysplasia that has material basis in mesomelia and acromelia, which results in short limb Dwarfism', N''),
( N'Q18553786', N'acute hydrops keratoconus', N'Human disease', N''),
( N'Q18553951', N'Eastern equine encephalitis', N'horse disease', N''),
( N'Q18554095', N'autonomic neuropathy', N'human disease', N''),
( N'Q18554748', N'corneal ectasia', N'Human disease', N''),
( N'Q18554801', N'multiple intestinal atresia', N'Human disease', N''),
( N'Q18554819', N'blepharophimosis, ptosis, and epicanthus inversus syndrome', N'Human disease', N''),
( N'Q18554858', N'breast papillomatosis', N'Human disease', N''),
( N'Q18554890', N'conjunctival squamous cell carcinoma', N'conjunctival cancer characterized by abnormal growth of dysplastic squamous epithelial cells on the surface of the eye that arises from the conjunctiva that has infiltrated beyond the confines of the epithelial basement membrane', N''),
( N'Q18555032', N'factor VII deficiency', N'Human disease', N''),
( N'Q18555036', N'factor X deficiency', N'Human disease', N''),
( N'Q18556143', N'Bartholins gland carcinoma', N'vulva carcinoma that has material basis in abnormally proliferating cells derives from epithelial cells and is located in Bartholins gland', N''),
( N'Q18556242', N'clear cell carcinoma', N'carcinoma (i.e. not a sarcoma) showing clear cells', N''),
( N'Q18556340', N'renal clear cell carcinoma', N'renal cell carcinoma that has material basis in cells that appear very pale or clear when examined under microscope', N''),
( N'Q18556440', N'intraneural perineurioma', N'Human disease', N''),
( N'Q18556792', N'eccrine acrospiroma', N'Human disease', N''),
( N'Q18556800', N'biliary papillomatosis', N'biliary tract neoplasm characterized by multiple papillary tumors in the intrahepatic and/or extrahepatic biliary tree', N''),
( N'Q18557126', N'ovarian mucinous neoplasm', N'Human disease', N''),
( N'Q18558107', N'urethral diverticulum', N'Human disease', N''),
( N'Q18559423', N'Flammer syndrome', N'Syndrome of vascular dysregulation', N''),
( N'Q1856914', N'nocardiosis', N'infectious disease affecting either the lungs (pulmonary nocardiosis) or the whole body (systemic nocardiosis)', N''),
( N'Q18589160', N'Lateral meningocele syndrome', N'human disease', N''),
( N'Q18589315', N'Cataract-microcornea syndrome', N'Cataract-microcornea syndrome is characterized by the association of congenital cataract and microcornea without any other systemic anomaly or dysmorphism', N''),
( N'Q1859754', N'apperceptive agnosia', N'agnosia that is a loss of the ability to distinguish visual shapes', N''),
( N'Q185986', N'Factor V Leiden', N'variant causing increased blood clotting', N''),
( N'Q18604563', N'Upshaw Schulman Syndrome', N'', N''),
( N'Q1860507', N'myotonic dystrophy', N'long term genetic disorder that affects muscle function', N''),
( N'Q18616565', N'Barber-Say syndrome', N'Barber Say syndrome (BSS) is a rare ectodermal dysplasia with neonatal onset characterized by congenital generalized hypertrichosis, atrophic skin, ectropion and macrostomia', N''),
( N'Q1862031', N'pinguecula', N'common type of conjunctival degeneration in the eye', N''),
( N'Q18621601', N'intoxication', N'pathological condition caused by exposure, ingestion, injection or inhalation of a toxic substance', N''),
( N'Q186235', N'myocarditis', N'extrinsic cardiomyopathy that is characterized as an inflammation of the heart muscle', N''),
( N'Q1862805', N'leukocoria', N'abnormal white reflection from the retina of the eye', N''),
( N'Q1862972', N'pterygium', N'winglike triangular membrane occurring in the neck, eyes, knees, elbows, ankles or digits', N''),
( N'Q186470', N'tonsillitis', N'inflammation of the tonsils', N''),
( N'Q186676', N'stuttering', N'neurodevelopmental condition', N''),
( N'Q1869874', N'insomnia', N'inability to sleep peacefully', N''),
( N'Q1869923', N'immunodeficiency-centromeric instability-facial anomalies syndrome 1', N'human disease', N''),
( N'Q1870975', N'fasciitis', N'Inflammation process in fascia', N''),
( N'Q187255', N'rheumatoid arthritis', N'An arthritis that is an autoimmune disease which attacks healthy cells and tissue located in joint.', N''),
( N'Q187440', N'urticaria', N'skin disease characterized by skin rash notable for pale red, raised and itchy bumps, located in the upper dermis', N''),
( N'Q187542', N'Li-Fraumeni syndrome', N'autosomal dominant disease characterized by increased risk of developing several types of cancer, including breast cancer, osteosarcomata and soft tissue sarcomata', N''),
( N'Q1876206', N'Pelizaeus-Merzbacher disease', N'hypomyelinating leukodystrophy characterized by impaired myelin formation, nystagmus, spastic quadriplegia, ataxia, and developmental delay that has material basis in mutation in the PLP1 gene on chromosome Xq22', N''),
( N'Q187656', N'relapsing polychondritis', N'Human disease', N''),
( N'Q1877388', N'Kienbocks disease', N'Kienbock disease is a rare bone disorder of unknown etiology characterized clinically by osteonecrosis of the carpal lunate, eventually leading to collapse of the lunate bone impacting wrist function', N''),
( N'Q1877474', N'solitary pulmonary nodule', N'human disease', N''),
( N'Q1877483', N'Congenital pulmonary venous return anomaly', N'TAPVC', N''),
( N'Q1877550', N'lung abscess', N'lung disease characterized by microbial infection which causes a type of liquefactive necrosis of the pulmonary tissue and formation of cavities containing necrotic debris or fluid', N''),
( N'Q187842', N'autoimmune thyroiditis', N'autoimmune disease of endocrine system that involves inflammation located in thyroid gland caused by the immune system reacting against its own tissues', N''),
( N'Q1878682', N'toxic epidermal necrolysis', N'Severe skin reaction', N''),
( N'Q1878741', N'lymphocele', N'Human disease', N''),
( N'Q1878759', N'lymphangioleiomyomatosis', N'human disease', N''),
( N'Q1878776', N'lymphocytic choriomeningitis', N'rodent-borne viral infectious disease that presents as aseptic meningitis, encephalitis or meningoencephalitis', N''),
( N'Q1881388', N'MERRF syndrome', N'mitochondrial disease', N''),
( N'Q188151', N'ischemia', N'restriction in blood supply to tissues, causing a shortage of oxygen and glucose', N''),
( N'Q188297', N'lupus erythematosus', N'human disease', N''),
( N'Q1883190', N'Madarosis', N'', N''),
( N'Q188605', N'pulmonary emphysema', N'Human disease', N''),
( N'Q188611', N'hypomania', N'mood state characterized by persistent and pervasive elevated or irritable mood', N''),
( N'Q188638', N'mood disorder', N'(psychology) Any of various disorders characterised by disturbance in an individuals mood', N''),
( N'Q1887877', N'tinea barbae', N'fungal infection of the hair', N''),
( N'Q188874', N'colorectal cancer', N'cancer of the colon or rectum', N''),
( N'Q1891209', N'mycosis fungoides', N'Human disease', N''),
( N'Q18912826', N'anterior cruciate ligament injury', N'ligament injury near the knee', N''),
( N'Q189167', N'Zellweger syndrome', N'congenital disorder of nervous system', N''),
( N'Q1892153', N'WAGR syndrome', N'rare genetic syndrome in which affected children are predisposed to develop Wilms tumour', N''),
( N'Q18928105', N'Kartagener syndrome', N'primary ciliary dyskinesia that is characterized by sinusitis, bronchiectasis and situs inversus with dextrocardia resulting from dysfunction of the cilia during embryologic development', N''),
( N'Q18928476', N'fusariosis', N'Human disease', N''),
( N'Q189331', N'heart arrhythmia', N'group of conditions in which the heartbeat is irregular, too fast, or too slow', N''),
( N'Q189389', N'aneurysm', N'bulge in the wall of a blood vessel', N''),
( N'Q189470', N'fistula', N'abnormal connection between two epithelialized surfaces, often organs', N''),
( N'Q189561', N'narcolepsy', N'Human sleep disorder that involves an excessive urge to sleep and other neurological features', N''),
( N'Q189580', N'acromegaly', N'Human disease / micro cephaly opposite', N''),
( N'Q189588', N'stomach cancer', N'gastrointestinal system cancer that is located in the stomach', N''),
( N'Q18966185', N'spondyloepimetaphyseal dysplasia', N'osteochondrodysplasia that results in abnormalities of bone growth located in vertebral column, located in epiphysis, located in metaphysis', N''),
( N'Q18967342', N'endemic African Kaposis sarcoma', N'Kaposis sarcoma that is located in black Africans', N''),
( N'Q18967592', N'tetanus neonatorum', N'Human disease', N''),
( N'Q18975788', N'spindle cell sarcoma', N'A sarcoma that results in cells that are spindle-shaped. They are usually resistant to radiation therapy.', N''),
( N'Q1898104', N'myeloproliferative disorders', N'hematopoietic disorders that derive from the blood-forming stem cells of the bone marrow', N''),
( N'Q1898141', N'rhabdomyosarcoma', N'skeletal muscle cancer that arise from skeletal muscle progenitors', N''),
( N'Q18987129', N'primary pigmented nodular adrenocortical disease', N'adrenal cortex disease characterized by small to normal sized adrenal glands containing multiple small cortical pigmented nodules', N''),
( N'Q189956', N'aphthous stomatitis', N'stomatitis characterized by the repeated formation of benign and non-contagious mouth ulcers', N''),
( N'Q19000410', N'adenosquamous cell lung carcinoma', N'Human disease', N''),
( N'Q19000660', N'hereditary breast ovarian cancer', N'autosomal dominant disease characterized by the higher than normal tendency to develop breast and ovarian cancers in genetically related families', N''),
( N'Q19001412', N'villonodular synovitis', N'Human disease', N''),
( N'Q1901516', N'retrognathism', N'a physical misalignment of the jaw bones', N''),
( N'Q190370', N'central pontine myelinolysis', N'demyelination disease that is characterized by severe damage to the myelin sheath of the pons nerve cells and has symptom acute paralysis, has symptom dysphagia, and has symptom dysarthria', N''),
( N'Q190564', N'Huntington disease', N'rare neurodegenerative disorder of the central nervous system characterized by unwanted choreatic movements, behavioral and psychiatric disturbances and dementia', N''),
( N'Q190805', N'heart disease', N'cardiovascular system disease that involves the heart', N''),
( N'Q1908194', N'vulvar cancer', N'primary or metastatic malignant neoplasm involving the vulva', N''),
( N'Q190831', N'central retinal vein occlusion', N'Human disease', N''),
( N'Q1909343', N'dermatophytosis', N'fungal infection of the skin', N''),
( N'Q1914356', N'May–Hegglin anomaly', N'', N''),
( N'Q191557', N'central nervous system vasculitis', N'Human disease', N''),
( N'Q191562', N'cerebral amyloid angiopathy', N'amyloidosis where amyloid protein progressively deposits in cerebral blood vessel walls with subsequent degenerative vascular changes that usually result in spontaneous cerebral hemorrhage, ischemic lesions and progressive dementia', N''),
( N'Q1915681', N'Meckel syndrome', N'a rare, lethal, ciliopathic, genetic disorder with malformations of the urinary system, of central nervous system, hepatic developmental defects, and pulmonary hypoplasia.', N''),
( N'Q191570', N'Cerebral arteriovenous malformation', N'arteriovenous malformation that is located in the brain', N''),
( N'Q1916182', N'middle cerebral artery infarction', N'human disease', N''),
( N'Q1916694', N'medullary cystic kidney disease', N'inherited form of cystic kidney disease leading to fibrosis and impaired renal function that is caused by mutations in the UMOD gene, which encodes uromodulin/Tamm-Horsfall mucoprotein', N''),
( N'Q191672', N'cercarial dermatitis', N'human disease', N''),
( N'Q191779', N'Tourette syndrome', N'neurodevelopmental condition', N''),
( N'Q1918881', N'meconium aspiration syndrome', N'Human disease', N''),
( N'Q1919462', N'Milkers nodule', N'Human disease', N''),
( N'Q1919487', N'Melkersson-Rosenthal syndrome', N'rare neurological disorder characterized by recurring facial paralysis, swelling of the face and lips (usually the upper lip - cheilitis granulomatosis) and the development of folds and furrows in the tongue (fissured tongue)', N''),
( N'Q1920586', N'meningeal carcinomatosis', N'disorder in cancer patients in which the disease spreads to the membranes surrounding the brain and spinal cord', N''),
( N'Q192100', N'filarial elephantiasis', N'human disease caused by parasitic worms', N''),
( N'Q192102', N'skin cancer', N'class of skin illnesses, tumor or cancer of the skin', N''),
( N'Q1923955', N'pyomyositis', N'Human disease', N''),
( N'Q192579', N'jet lag', N'physiological condition caused by travel across time zones', N''),
( N'Q1926345', N'22q13 deletion syndrome', N'human disease', N''),
( N'Q19275831', N'choking', N'mechanical obstruction of the flow of air from the environment into the lungs', N''),
( N'Q1928978', N'viral infectious disease', N'Human, animal or plant disease resulting from a viral infection', N''),
( N'Q193003', N'hydrocephalus', N'disorder characterized by an abnormal increase of cerebrospinal fluid in the ventricles of the brain', N''),
( N'Q193211', N'cyst', N'closed sac growth on the body', N''),
( N'Q193216', N'trachoma', N'Human disease', N''),
( N'Q1934052', N'microsporidiosis', N'opportunistic mycosis that results in systemic fungal infection in immunocompromised people, has material basis in Microsporidia phylum members', N''),
( N'Q1934069', N'Microscopic polyangiitis', N'microscopic polyangiitis (MPA) is an inflammatory, necrotizing, systemic vasculitis that affects predominantly small vessels (i.e. small arteries, arterioles, capillaries, venules) in multiple organs.', N''),
( N'Q1934449', N'Milium', N'Light-coloured spots under the skin', N''),
( N'Q1934513', N'seborrheic infantile dermatitis', N'Human disease', N''),
( N'Q1935832', N'neurofibromatosis type II', N'type of neurofibromatosis disease', N''),
( N'Q1936838', N'diseases of poverty', N'', N''),
( N'Q1938763', N'fecal vomiting', N'medical condition', N''),
( N'Q193894', N'sarcoidosis', N'Disease characterized by the growth of collections of inflammatory cells (granulomas) in multiple organs', N''),
( N'Q1939330', N'Conns syndrome', N'adrenal adenoma characterized by over production of aldosterone', N''),
( N'Q194041', N'phenylketonuria', N'amino acid metabolic disorder that is characterized by a mutation in the gene for the hepatic enzyme phenylalanine hydroxylase (PAH), rendering it nonfunctional', N''),
( N'Q194101', N'dwarfism', N'condition affecting a person or animal short in stature, caused by slow or delayed growth', N''),
( N'Q1941101', N'myoma', N'Human disease', N''),
( N'Q194520', N'atrophy', N'partial or complete wasting away of a part of the body', N''),
( N'Q1947272', N'Baastrups syndrome', N'orthopedic and radiographic disorder that often occurs in elderly humans', N''),
( N'Q1947298', N'glycogen storage disease VI', N'Glycogen storage disease', N''),
( N'Q1947302', N'Castlemans disease', N'lymphoproliferative syndrome characterized by one or more enlarged lymph nodes containing cells with hyaline-vascular, plasmacytic, or mixed appearance microscopically', N''),
( N'Q1947304', N'Cushings disease', N'a disease related to the anterior pituitary', N''),
( N'Q1947307', N'basal ganglia calcification', N'a rare, genetic neurological disorder characterized by abnormal deposits of calcium in areas of the brain that control movement', N''),
( N'Q1948740', N'Mortons neuroma', N'benign neuroma of an intermetatarsal plantar nerve', N''),
( N'Q1951267', N'moyamoya disease', N'A cerebral arterial disease characterized by constriction of certain arteries at the base of the brain. Blood flow is blocked by the constriction and also by blood clots.', N''),
( N'Q1952032', N'mucolipidosis', N'human disease', N''),
( N'Q1952336', N'multiminicore myopathy', N'Multi-minicore Disease (MmD) is a hereditary neuromuscular disorder characterized by multiple cores on muscle biopsy and clinical features of a congenital myopathy', N''),
( N'Q1952467', N'hereditary multiple exostoses', N'exostosis that has material basis in a mutation on the genes EXT1, EXT2 and EXT3 which results in multiple bony spurs throughout a childs growth', N''),
( N'Q1955377', N'Fukuyama congenital muscular dystrophy', N'Human disease', N''),
( N'Q19563983', N'Pachyosteosclerosis', N'', N''),
( N'Q1956557', N'Myeloma cast nephropathy', N'', N''),
( N'Q1956662', N'Adenosine Monophosphate Deaminase Deficiency type 1', N'', N''),
( N'Q1956669', N'Orofacial myological disorders', N'', N''),
( N'Q1956682', N'myoglobinuria', N'myopathy that is characterized by an increased urinary excretion of myoglobin', N''),
( N'Q1956696', N'congenital fiber-type disproportion', N'Human disease', N''),
( N'Q1958249', N'Chronic Thromboembolic Pulmonary Hypertension', N'', N''),
( N'Q1958739', N'persistent Müllerian duct syndrome', N'pseudohermaphroditism characterized by the persistence of Mullerian duct derivatives in a phenotypically and karyotypically male', N''),
( N'Q19596346', N'cervical spinal stenosis', N'', N''),
( N'Q19597369', N'gram-negative bacterial infection', N'Infections caused by bacteria that show up as pink (negative) when treated by the gram-staining method', N''),
( N'Q19597605', N'Irvine', N'', N''),
( N'Q1963423', N'Naegeli–Franceschetti–Jadassohn syndrome', N'Naegeli-Franceschetti-Jadassohn (NFJ) syndrome is a rare ectodermal dysplasia that affects the skin, sweat glands, nails, and teeth', N''),
( N'Q1963588', N'hematopoietic system diseases', N'disorder which primarily affects the blood', N''),
( N'Q1965082', N'pentosuria', N'an inborn error of metabolism characterized by the excretion of 1 to 4 g of the pentose L-xylulose in the urine per day', N''),
( N'Q196788', N'cervical intraepithelial neoplasia', N'disease', N''),
( N'Q1968751', N'Volkmanns contracture', N'permanent flexion contracture of the hand at the wrist, resulting in a claw-like deformity of the hand and fingers', N''),
( N'Q1970052', N'Shwachman-Diamond syndrome', N'syndrome characterized by exocrine pancreatic insufficiency, bone marrow failure and skeletal abnormalities', N''),
( N'Q1970295', N'Oligomenorrhea', N'type of menstrual disorder', N''),
( N'Q1975850', N'parotitis', N'parotid disease characterized by the inflammation of one or both parotid glands', N''),
( N'Q19772377', N'non-celiac gluten sensitivity', N'gluten-related disorder', N''),
( N'Q1978084', N'nerve compression syndrome', N'Human disease', N''),
( N'Q1981276', N'neuroendocrine tumor', N'endocrine gland cancer that has material basis in neuroendocrine cells', N''),
( N'Q1981315', N'geographic tongue', N'atrophic glossitis that is characterized as an inflammatory condition of the mucous membrane of the tongue, usually on the dorsal surface', N''),
( N'Q1981337', N'Postoperative residual curarization', N'', N''),
( N'Q1981345', N'neuroma', N'nervous system benign neoplasm that is characterized as a nerve tissue tumor', N''),
( N'Q1983841', N'viral hepatitis', N'hepatitis that involves viral infection causing inflammation of the liver', N''),
( N'Q19843148', N'Methaemalbuminaemia', N'', N''),
( N'Q1985123', N'Nonossifying fibroma', N'', N''),
( N'Q1987592', N'Pudendal nerve entrapment', N'Pudendal neuralgia (PN) is a chronic neuropathic pain, aggravated by sitting and for which no organic cause can be found by imaging studies. It is often associated with pelvic dysfunction.', N''),
( N'Q1992236', N'enterobiasis', N'Human worm infection', N''),
( N'Q1995327', N'Kennedy disease', N'Kennedys disease, also known as bulbospinal muscular atrophy (BSMA), is a rare X-linked recessive motor neuron disease characterized by proximal and bulbar muscle wasting', N''),
( N'Q1996053', N'chronic pancreatitis', N'Human disease', N''),
( N'Q199615', N'encephalitis', N'brain disease that is characterized as an acute inflammation of the brain with flu-like symptoms', N''),
( N'Q1996246', N'hereditary lymphedema', N'lymphedema commonly located in legs, caused by congenital abnormalities in the lymphatic system', N''),
( N'Q19972185', N'tubo-ovarian abscess', N'one of the late complications of pelvic inflammatory disease', N''),
( N'Q199804', N'chronic obstructive pulmonary disease', N'type of obstructive lung disease characterized by long-term poor airflow', N''),
( N'Q2000072', N'spondylolysis', N'bone structure disease that involves a defect located in lumbar vertebral column.', N''),
( N'Q2002586', N'sialadenitis', N'inflammation of a salivary gland', N''),
( N'Q2003151', N'livedo reticularis', N'common skin finding consisting of a mottled reticulated vascular pattern that appears as a lace-like purplish discoloration of the skin', N''),
( N'Q200741', N'teratoma', N'germ cell and embryonal cancer that is an encapsulated tumor with tissue or organ components resembling normal derivatives of all three germ layers', N''),
( N'Q200745', N'pseudohypoaldosteronism', N'Human disease', N''),
( N'Q200779', N'genetic disease', N'disease that has material basis in genetic variations in the human genome', N''),
( N'Q200781', N'pleural empyema', N'empyema (an accumulation of pus) in the pleural cavity that can develop when bacteria invade the pleural space, usually in the context of a pneumonia', N''),
( N'Q200985', N'Hartnup disease', N'Human disease', N''),
( N'Q201180', N'varicose veins', N'vein disease that is characterized by swollen, twisted veins visible just under the surface of the skin', N''),
( N'Q2012569', N'adenomyosis', N'extension of endometrial tissue into the myometrium', N''),
( N'Q2012642', N'cryptogenic organizing pneumonia', N'Inflammation of the bronchioles (bronchiolitis) and surrounding tissue in the lungs', N''),
( N'Q201299', N'hairy cell leukemia', N'chronic lymphocytic leukemia that is characterized by over production of B cells (lymphocytes) by the bone marrow where the B cells appear hairy under a microscope', N''),
( N'Q2013137', N'obstructive uropathy', N'', N''),
( N'Q2015728', N'specific phobia', N'phobic disorder that is characterized by an unreasonable or irrational fear related to exposure to specific objects or situations', N''),
( N'Q2017218', N'Duane-radial ray syndrome', N'autosomal dominant disease characterized by upper limb anomalies, ocular anomalies, and, in some cases, renal anomalies and that has material basis in heterozygous mutation in the SALL4 gene on chromosome 20q13', N''),
( N'Q2017741', N'oculocutaneous albinism', N'autosomal recessive disease characterized by abnormal pigmentation of the skin, hair and eyes', N''),
( N'Q2017756', N'ocular albinism type 1', N'', N''),
( N'Q2019823', N'Potters syndrome', N'congenital disorder of urinary system', N''),
( N'Q2019832', N'glycoproteinosis', N'endocrine disease', N''),
( N'Q201989', N'Lyme disease', N'infectious disease caused by Borrelia bacteria, spread by ticks', N''),
( N'Q202173', N'hordeolum', N'Infection of an oil gland in the eyelid', N''),
( N'Q202387', N'post-traumatic stress disorder', N'mental disorder that developed after experiencing or witnessing a terrifying or life-threatening event', N''),
( N'Q2025687', N'iron overload', N'human disease', N''),
( N'Q2026857', N'chronic progressive external ophthalmoplegia', N'human disease', N''),
( N'Q2027515', N'hypoparathyroidism-deafness-renal disease syndrome', N'characterized by autosomal dominant inheritance of hypoparathyroidism, sensorineural deafness and progressive renal failure that has material basis in chromosome deletion that results in haploinsufficiency of the GATA3 gene on chromosome 10p14', N''),
( N'Q202758', N'hypoglycemia', N'human disease', N''),
( N'Q2027937', N'choledochal cyst', N'congenital disorder of digestive system', N''),
( N'Q2028015', N'Alpers disease', N'cerebral degeneration that results in progressive degeneration of grey matter in the cerebrum and has symptom convulsions', N''),
( N'Q2028074', N'tungiasis', N'human disease', N''),
( N'Q2028354', N'biliary dyskinesia', N'gallbladder disease characterized by altered tonus of the sphincter of Oddi, disturbance in the coordination of contraction of the biliary ducts, and/or reduction in the speed of emptying of the biliary tree', N''),
( N'Q202837', N'cardiac arrest', N'sudden stop in effective blood flow due to the failure of the heart to contract effectively', N''),
( N'Q202849', N'Turner syndrome', N'human disease', N''),
( N'Q2029906', N'Paraproctitis', N'', N''),
( N'Q203031', N'ciliopathy', N'genetic disease associated with mutations encoding defective proteins, which result in either abnormal function formation or function of cilia', N''),
( N'Q2030989', N'heart cancer', N'cardiovascular cancer located in the heart', N''),
( N'Q203133', N'African trypanosomiasis', N'parasitic disease', N''),
( N'Q2031424', N'oropharynx cancer', N'pharynx cancer that is located in the  oropharynx', N''),
( N'Q2031871', N'vibration white finger', N'industrial injury', N''),
( N'Q2032041', N'unstable angina', N'type of angina pectoris that is irregular. It is also classified as a type of acute coronary syndrome', N''),
( N'Q2033138', N'angiokeratoma', N'benign cutaneous lesion of capillaries, resulting in small marks of red to blue color and characterized by hyperkeratosis', N''),
( N'Q2033532', N'Van der Woude syndrome', N'syndrome characterized by the combination of lower lip pits, cleft lip with or without cleft palate and cleft palate alone', N''),
( N'Q2033861', N'carnitine palmitoyltransferase II deficiency', N'lipid metabolism disorder characterized by an enzymatic defect that prevents long-chain fatty acids from being transported into the mitochondria', N''),
( N'Q2035032', N'osteochondroma', N'the most common benign tumors of the bones', N''),
( N'Q2035074', N'Pagets disease of bone', N'bone formation disease that has material basis in hyperactive osteoclast which results in abnormal osteoblast bone formation located in skull, located in pelvis, located in vertebral column, located in set of limbs', N''),
( N'Q2035109', N'nail-patella syndrome', N'Human disease', N''),
( N'Q203601', N'pneumothorax', N'Abnormal collection of air in the pleural space that causes an uncoupling of the lung from the chest wall', N''),
( N'Q203696', N'internuclear ophthalmoplegia', N'Human disease', N''),
( N'Q2037487', N'sympathetic ophthalmia', N'Human disease', N''),
( N'Q2038371', N'labyrinthitis', N'otitis interna which involves inflammation of the labyrinths', N''),
( N'Q2039267', N'aspirin-induced asthma', N'human disease', N''),
( N'Q2040895', N'canine influenza', N'influenza occurring in canine animals', N''),
( N'Q204176', N'Ritters disease', N'Human disease', N''),
( N'Q2042205', N'Residual ovary syndrome', N'', N''),
( N'Q2044034', N'Periodic fever, aphthous stomatitis, pharyngitis and adenitis', N'PFAPA (Periodic fever - aphthous stomatitis- pharyngitis - adenopathy) syndrome is an auto inflammatory syndrome characterized by recurrent febrile episodes associated with aphthous stomatitis, pharyngitis and cervical adenitis', N''),
( N'Q2044949', N'corneal dystrophy', N'human disease', N''),
( N'Q2045954', N'Haff disease', N'', N''),
( N'Q2046113', N'visceral leishmaniasis', N'Human disease', N''),
( N'Q2046550', N'diabetic neuropathy', N'nerve damaging disorders associated with diabetes mellitus', N''),
( N'Q2046811', N'simultanagnosia', N'agnosia that is a loss of the ability to recgonize a whole image or scene while retaining the ability to recognize objects or details in their visual field one at a time', N''),
( N'Q2050791', N'Papillon-Lefevre disease', N'Human disease', N''),
( N'Q2051832', N'parapsoriasis', N'Human disease', N''),
( N'Q2051919', N'Extravasation', N'', N''),
( N'Q205214', N'Guillain–Barré Syndrome', N'autoimmune disease that causes the immune system to attack part of the peripheral nervous system', N''),
( N'Q2054837', N'misophonia', N'neurologic disorder leading to extremely negative reactions and feelings related to certain sounds', N''),
( N'Q2056680', N'Patella bipartita', N'', N''),
( N'Q2057356', N'eosinophilic esophagitis', N'esophagitis characterized by inflammation involving eosinophils located in esophagus', N''),
( N'Q205764', N'endometriosis', N'disease of the female reproductive system', N''),
( N'Q2058941', N'microscopic colitis', N'colitis that can only be diagnosed by the examination of colon tissue under a microscope', N'')
GO